import json
import random

# Deterministic correct-answer distribution: spread across a,b,c,d evenly
# 10 questions per book -> roughly 2-3 each of a,b,c,d

books_questions = []

# ===== 1. The Lion the Witch and the Wardrobe =====
books_questions.append({
    "title": "The Chronicles of Narnia: The Lion the Witch and the Wardrobe",
    "questions": [
        {"question_text": "Which sibling is the first to enter Narnia through the wardrobe?",
         "option_a": "Peter", "option_b": "Susan", "option_c": "Lucy", "option_d": "Edmund",
         "correct_answer": "c", "question_order": 1},
        {"question_text": "What does the White Witch use to tempt Edmund?",
         "option_a": "Turkish Delight", "option_b": "Chocolate cake", "option_c": "Marmalade on toast", "option_d": "Honey cakes",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What is the name of the great lion who is the true king of Narnia?",
         "option_a": "Aslan", "option_b": "Tashlan", "option_c": "Rilian", "option_d": "Caspian",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Why is it always winter and never Christmas in Narnia when the children first arrive?",
         "option_a": "A dragon has cursed the land", "option_b": "Aslan has abandoned Narnia", "option_c": "The White Witch's spell keeps it frozen", "option_d": "The seasons were stolen by dwarfs",
         "correct_answer": "c", "question_order": 4},
        {"question_text": "Who betrays his siblings and allies with the White Witch?",
         "option_a": "Peter", "option_b": "Edmund", "option_c": "Mr. Tumnus", "option_d": "Mr. Beaver",
         "correct_answer": "b", "question_order": 5},
        {"question_text": "How is Edmund saved after the White Witch demands his life as a traitor?",
         "option_a": "Peter fights the Witch to free him", "option_b": "The beavers rescue him", "option_c": "Aslan offers himself in Edmund's place", "option_d": "Lucy uses a healing potion",
         "correct_answer": "c", "question_order": 6},
        {"question_text": "What happens to Aslan at the Stone Table?",
         "option_a": "He is crowned king", "option_b": "He is sacrificed and killed by the Witch", "option_c": "He discovers the Deep Magic", "option_d": "He creates a new world",
         "correct_answer": "b", "question_order": 7},
        {"question_text": "What allows Aslan to be resurrected after his sacrifice?",
         "option_a": "The beavers' healing magic", "option_b": "The Deeper Magic from before the dawn of time", "option_c": "Lucy's tears of love", "option_d": "The Stone Table cracking",
         "correct_answer": "b", "question_order": 8},
        {"question_text": "Who slays the White Witch in the final battle?",
         "option_a": "Aslan", "option_b": "Peter", "option_c": "Edmund", "option_d": "Susan",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What title is Peter given as a king of Narnia?",
         "option_a": "Peter the Magnificent", "option_b": "Peter the High King", "option_c": "Peter the Valiant", "option_d": "Peter the Just",
         "correct_answer": "d", "question_order": 10},
    ]
})

# ===== 2. Prince Caspian =====
books_questions.append({
    "title": "The Chronicles of Narnia: Prince Caspian",
    "questions": [
        {"question_text": "How do the Pevensie children return to Narnia?",
         "option_a": "Through the wardrobe again", "option_b": "Through a painting", "option_c": "By a magic train", "option_d": "Through Cair Paravel's ruins at a train station",
         "correct_answer": "d", "question_order": 1},
        {"question_text": "Why has Narnia changed so much since the children's last visit?",
         "option_a": "It has been taken over by Telmarines", "option_b": "A dragon burned the forests", "option_c": "Aslan cursed the land", "option_d": "The sea flooded it",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who is Prince Caspian's evil uncle who wants to kill him?",
         "option_a": "King Miraz", "option_b": "Lord Glozelle", "option_c": "Doctor Cornelius", "option_d": "General Sopespian",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "What kind of creature is Trumpkin, one of Caspian's loyal allies?",
         "option_a": "A faun", "option_b": "A dwarf", "option_c": "A badger", "option_d": "A talking horse",
         "correct_answer": "b", "question_order": 4},
        {"question_text": "Who teaches Prince Caspian about Old Narnia and the history of the land?",
         "option_a": "Trumpkin", "option_b": "Reepicheep", "option_c": "Doctor Cornelius", "option_d": "Nikabrik",
         "correct_answer": "c", "question_order": 5},
        {"question_text": "What magic item does Queen Susan use to summon help?",
         "option_a": "A magic whistle", "option_b": "A magic horn", "option_c": "A magic bow", "option_d": "A magic mirror",
         "correct_answer": "b", "question_order": 6},
        {"question_text": "What is the name of the courageous talking mouse who fights in battle?",
         "option_a": "Reepicheep", "option_b": "Pattertwig", "option_c": "Trufflehunter", "option_d": "Glenstorm",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Why can't Lucy wake the others when she sees Aslan?",
         "option_a": "They are under a spell", "option_b": "Aslan tells her others will not believe her easily", "option_c": "She is too afraid", "option_d": "They have left camp",
         "correct_answer": "b", "question_order": 8},
        {"question_text": "What does Aslan do to the trees during his procession?",
         "option_a": "He makes them walk and dance", "option_b": "He makes them invisible", "option_c": "He burns them down", "option_d": "He turns them to stone",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "Who challenges King Miraz to single combat?",
         "option_a": "Peter", "option_b": "Caspian", "option_c": "Edmund", "option_d": "Trumpkin",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 3. The Voyage of the Dawn Treader =====
books_questions.append({
    "title": "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "questions": [
        {"question_text": "Who is the annoying cousin who travels to Narnia with Edmund and Lucy?",
         "option_a": "Eustace Scrubb", "option_b": "Digory Kirke", "option_c": "Caspian X", "option_d": "Puddleglum",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "How do the three children enter Narnia in this book?",
         "option_a": "Through the wardrobe", "option_b": "Through a magic door", "option_c": "Through a painting of a ship", "option_d": "By a magic train",
         "correct_answer": "c", "question_order": 2},
        {"question_text": "What is the name of King Caspian's ship?",
         "option_a": "The Splendour Hyaline", "option_b": "The Dawn Treader", "option_c": "The End of the World", "option_d": "The Sea Serpent",
         "correct_answer": "b", "question_order": 3},
        {"question_text": "What happens to Eustace when he falls asleep on a dragon's treasure hoard?",
         "option_a": "He is cursed with bad luck", "option_b": "He turns into a dragon", "option_c": "He loses his memory", "option_d": "He becomes invisible",
         "correct_answer": "b", "question_order": 4},
        {"question_text": "Who turns Eustace back into a boy?",
         "option_a": "Aslan", "option_b": "Caspian", "option_c": "Lucy", "option_d": "Reepicheep",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "What island has inhabitants who are invisible and turned into ugly pig-monsters?",
         "option_a": "Dragon Island", "option_b": "Burnt Island", "option_c": "The Island of the Voices", "option_d": "Deathwater Island",
         "correct_answer": "c", "question_order": 6},
        {"question_text": "What is the Dark Island known for?",
         "option_a": "It has sleeping men forever", "option_b": "It turns water into gold", "option_c": "It is full of dragons", "option_d": "It has no light at all",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What does Reepicheep the mouse hope to find at the end of the world?",
         "option_a": "A treasure chest", "option_b": "Aslan's country", "option_c": "A new sword", "option_d": "A new kingdom",
         "correct_answer": "b", "question_order": 8},
        {"question_text": "Who meets Aslan as a lamb at the end of the world's sea?",
         "option_a": "Caspian", "option_b": "Lucy and Edmund", "option_c": "Eustace", "option_d": "Reepicheep",
         "correct_answer": "d", "question_order": 9},
        {"question_text": "Who is chosen to go through a door into Aslan's country?",
         "option_a": "Caspian", "option_b": "Lucy", "option_c": "Edmund", "option_d": "Reepicheep",
         "correct_answer": "d", "question_order": 10},
    ]
})

# ===== 4. The Silver Chair =====
books_questions.append({
    "title": "The Chronicles of Narnia: The Silver Chair",
    "questions": [
        {"question_text": "Who are the two children called to Narnia in this story?",
         "option_a": "Peter and Susan", "option_b": "Eustace and Jill", "option_c": "Edmund and Lucy", "option_d": "Digory and Polly",
         "correct_answer": "b", "question_order": 1},
        {"question_text": "How do Eustace and Jill enter Narnia?",
         "option_a": "Through the wardrobe", "option_b": "Through a painting", "option_c": "Through a gate behind the school", "option_d": "Through a magic train",
         "correct_answer": "c", "question_order": 2},
        {"question_text": "What is the name of the gloomy marsh-wiggle who joins the quest?",
         "option_a": "Trumpkin", "option_b": "Puddleglum", "option_c": "Reepicheep", "option_d": "Glimfeather",
         "correct_answer": "b", "question_order": 3},
        {"question_text": "Who is Prince Caspian's son that the children must find?",
         "option_a": "Prince Rilian", "option_b": "Prince Corin", "option_c": "Prince Cor", "option_d": "Prince Aravis",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What creature enchanted Prince Rilian and holds him captive?",
         "option_a": "A dragon", "option_b": "A witch in the form of a green serpent", "option_c": "An evil dwarf", "option_d": "A sea monster",
         "correct_answer": "b", "question_order": 5},
        {"question_text": "Where is Prince Rilian held prisoner?",
         "option_a": "In Cair Paravel", "option_b": "In the Underworld underground", "option_c": "On a ship", "option_d": "In a tower in Archenland",
         "correct_answer": "b", "question_order": 6},
        {"question_text": "What is the name of the chair that traps Prince Rilian?",
         "option_a": "The Silver Chair", "option_b": "The Iron Chair", "option_c": "The Golden Chair", "option_d": "The Dark Chair",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "How do the travelers free Rilian from the chair?",
         "option_a": "They break the chair with a hammer", "option_b": "They say Aslan's name", "option_c": "They destroy it with fire", "option_d": "They use a key from the witch",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens when the Lady of the Green Kirtle tries to enchant the travelers in the Underworld?",
         "option_a": "They fall asleep forever", "option_b": "Puddleglum stampedes through the fire breaking the spell", "option_c": "They all escape by magic", "option_d": "They become frogs",
         "correct_answer": "b", "question_order": 9},
        {"question_text": "What happens to King Caspian at the end of the book?",
         "option_a": "He dies of old age, then is revived briefly by Aslan", "option_b": "He abdicates his throne", "option_c": "He sails away forever", "option_d": "He is turned to stone",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 5. The Golden Compass =====
books_questions.append({
    "title": "The Golden Compass",
    "questions": [
        {"question_text": "What is Lyra's daemon (companion) named?",
         "option_a": "Pantalaimon", "option_b": "Kirjava", "option_c": "Serafina", "option_d": "Iorek",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "What does every human in Lyra's world have?",
         "option_a": "A daemon, an animal-shaped companion", "option_b": "A magic wand", "option_c": "A golden compass", "option_d": "An invisible shield",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Where does Lyra live at the start of the story?",
         "option_a": "Oxford University (Jordan College)", "option_b": "London", "option_c": "A floating city", "option_d": "The North",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the mysterious and powerful woman Lyra goes to live with?",
         "option_a": "Mrs. Coulter", "option_b": "Serafina Pekkala", "option_c": "Ma Costa", "option_d": "Lyra's mother",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What is the special device Lyra is given that can tell the truth?",
         "option_a": "The Alethiometer (golden compass)", "option_b": "A magic map", "option_c": "A silver knife", "option_d": "A crystal ball",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "What are the General Oblation Board, led by Mrs. Coulter, secretly doing to children?",
         "option_a": "Severing them from their daemons", "option_b": "Teaching them magic", "option_c": "Sending them to another world", "option_d": "Turning them into animals",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "Who is the armored bear Lyra befriends?",
         "option_a": "Iorek Byrnison", "option_b": "Iofur Raknison", "option_c": "Serafina Pekkala", "option_d": "Lee Scoresby",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Where are the kidnapped children taken?",
         "option_a": "To Svalbard, in the far North", "option_b": "To London", "option_c": "To Oxford", "option_d": "To a floating city",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "Who is Lyra's father, a powerful and controversial scholar?",
         "option_a": "Lord Asriel", "option_b": "Lee Scoresby", "option_c": "Farder Coram", "option_d": "John Parry",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What does Lord Asriel do at the end of the book?",
         "option_a": "He opens a bridge to another world", "option_b": "He is killed", "option_c": "He marries Mrs. Coulter", "option_d": "He becomes king",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 6. The Subtle Knife =====
books_questions.append({
    "title": "The Subtle Knife",
    "questions": [
        {"question_text": "Who is the boy from our world who meets Lyra?",
         "option_a": "Will Parry", "option_b": "Roger Parslow", "option_c": "John Parry", "option_d": "Lee Scoresby",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "What is Will searching for?",
         "option_a": "His missing father, John Parry", "option_b": "A magic compass", "option_c": "His daemon", "option_d": "A map of worlds",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What powerful weapon does Will obtain in the city of Cittàgazze?",
         "option_a": "The Subtle Knife", "option_b": "The Golden Compass", "option_c": "The Amber Spyglass", "option_d": "A magic bow",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "What does the Subtle Knife allow its user to do?",
         "option_a": "Cut windows between worlds", "option_b": "Turn invisible", "option_c": "See the future", "option_d": "Heal any wound",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What danger lurks in the city of Cittàgazze?",
         "option_a": "Soul-eating creatures called Specters", "option_b": "Dragons", "option_c": "Witches", "option_d": "Armored bears",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who can see and be harmed by the Specters?",
         "option_a": "Adults only, not children", "option_b": "Children only", "option_c": "Only witches", "option_d": "Everyone",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does Lyra discover about the mysterious substance called Dust?",
         "option_a": "It comes from the Aurora and is related to consciousness", "option_b": "It is a poison", "option_c": "It is gold", "option_d": "It is fairy dust",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Who is the witch who helps Lyra and Will?",
         "option_a": "Serafina Pekkala", "option_b": "Mrs. Coulter", "option_c": "Ma Costa", "option_d": "Ruta Skadi",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens to Lee Scoresby in this book?",
         "option_a": "He dies defending Lyra's friend", "option_b": "He finds Will's father", "option_c": "He becomes king", "option_d": "He flies away",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "Who finds Will's father, John Parry, but is killed right after?",
         "option_a": "John Parry himself, then a witch kills him", "option_b": "Lee Scoresby", "option_c": "Lord Asriel", "option_d": "Will himself",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 7. The Amber Spyglass =====
books_questions.append({
    "title": "The Amber Spyglass",
    "questions": [
        {"question_text": "What does Mrs. Coulter do to Lyra at the start of the book?",
         "option_a": "She drugs and hides her in a cave", "option_b": "She sells her", "option_c": "She sends her to school", "option_d": "She abandons her",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who rescues Lyra from the cave?",
         "option_a": "Will, using the Subtle Knife", "option_b": "Iorek Byrnison", "option_c": "Serafina Pekkala", "option_d": "Lord Asriel",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What is the name of the scientist who studies Dust using a special spyglass?",
         "option_a": "Mary Malone", "option_b": "Serafina Pekkala", "option_c": "Ma Costa", "option_d": "Ruta Skadi",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "What world does Mary Malone enter and befriend creatures called mulefa?",
         "option_a": "A world with wheeled creatures and seed-pod trees", "option_b": "Cittàgazze", "option_c": "Lyra's Oxford", "option_d": "Will's world",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What is Lord Asriel building to fight the Authority?",
         "option_a": "A vast army and fortress", "option_b": "A magic weapon", "option_c": "A bridge", "option_d": "A new world",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is the Authority, the first angel?",
         "option_a": "He is not actually the creator, but the first angel who took power", "option_b": "He is God the creator", "option_c": "He is a demon", "option_d": "He is a king",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does Will and Lyra's love for each other do?",
         "option_a": "It opens a window and changes Dust's flow, saving the worlds", "option_b": "It destroys the knife", "option_c": "It awakens the Authority", "option_d": "It creates a new daemon",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Why must Will and Lyra separate at the end?",
         "option_a": "Because too many windows open let Dust escape, and they belong in different worlds", "option_b": "Because they are cursed", "option_c": "Because they are too young", "option_d": "Because their daemons forbid it",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens to the Subtle Knife at the end?",
         "option_a": "Will breaks it", "option_b": "Will gives it to Mary", "option_c": "It is stolen", "option_d": "It disappears",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What does Lyra decide to do at the very end of the story?",
         "option_a": "She decides to study at school and learn to read the Alethiometer again", "option_b": "She returns to the North", "option_c": "She finds a new world", "option_d": "She becomes a witch",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 8. Artemis Fowl =====
books_questions.append({
    "title": "Artemis Fowl",
    "questions": [
        {"question_text": "Who is Artemis Fowl?",
         "option_a": "A 12-year-old criminal mastermind and genius", "option_b": "A fairy detective", "option_c": "A teenage detective", "option_d": "A wizard",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "What is Artemis trying to do in the first book?",
         "option_a": "Restore his family's fortune by stealing fairy gold", "option_b": "Find his missing father", "option_c": "Defeat a fairy queen", "option_d": "Go to fairy school",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What is the name of Artemis's loyal bodyguard?",
         "option_a": "Butler", "option_b": "Foaly", "option_c": "Mulch", "option_d": "Root",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Which fairy does Artemis kidnap to hold for ransom?",
         "option_a": "Captain Holly Short", "option_b": "Commander Root", "option_c": "Foaly", "option_d": "Mulch Diggums",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What is the name of the fairy police force?",
         "option_a": "LEP (Lower Elements Police)", "option_b": "The Fairy Guard", "option_c": "The Mud People Police", "option_d": "The Haven Police",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is the LEPrecon commander who leads the rescue mission?",
         "option_a": "Commander Julius Root", "option_b": "Foaly", "option_c": "Captain Holly Short", "option_d": "Mulch Diggums",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What fairy creature is sent into Fowl Manor to help break in?",
         "option_a": "A dwarf named Mulch Diggums", "option_b": "A troll", "option_c": "A centaur", "option_d": "A goblin",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What is the Book of the People that Artemis has translated?",
         "option_a": "The fairy bible/rulebook", "option_b": "A spellbook", "option_c": "A history of humans", "option_d": "A map of Haven",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What clever trick allows Artemis to escape the time-stop at the end?",
         "option_a": "He drugs himself and his companions to slip the time-stop", "option_b": "He uses a secret tunnel", "option_c": "He bribes Foaly", "option_d": "He surrenders",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What does Holly give Artemis half of as part of their deal?",
         "option_a": "A wish granted by the fairies", "option_b": "A pot of gold", "option_c": "A fairy badge", "option_d": "A magic book",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 9. The Arctic Incident =====
books_questions.append({
    "title": "The Arctic Incident",
    "questions": [
        {"question_text": "What is Artemis Fowl's mission in this book?",
         "option_a": "To rescue his kidnapped father, Artemis Fowl Senior", "option_b": "To steal more fairy gold", "option_c": "To find his mother", "option_d": "To defeat a troll",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who has been holding Artemis's father captive?",
         "option_a": "The Russian Mafiya", "option_b": "The fairies", "option_c": "A troll", "option_d": "A rival genius",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Why do the fairies suspect Artemis is smuggling batteries to goblins?",
         "option_a": "Because they trace a shipment of batteries to him", "option_b": "Because he confesses", "option_c": "Because Butler tells them", "option_d": "Because Holly sees him",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the centaur tech genius who works for the LEP?",
         "option_a": "Foaly", "option_b": "Mulch", "option_c": "Root", "option_d": "Briar Cudgeon",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What fairy villain is secretly behind the goblin rebellion?",
         "option_a": "Briar Cudgeon", "option_b": "Opal Koboi", "option_c": "Commander Root", "option_d": "Foaly",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is the leader of the B'wa Kell goblin triad?",
         "option_a": "General Scalene", "option_b": "Briar Cudgeon", "option_c": "Opal Koboi", "option_d": "Commander Root",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "Who saves Artemis and Butler during the Arctic rescue mission?",
         "option_a": "Holly Short", "option_b": "Foaly", "option_c": "Mulch", "option_d": "Commander Root",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What does Artemis give Holly at the end of the book?",
         "option_a": "A kiss on the cheek", "option_b": "A bag of gold", "option_c": "A fairy badge", "option_d": "A magic book",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What is revealed about Holly's father?",
         "option_a": "He was falsely accused of a crime", "option_b": "He is a goblin", "option_c": "He is a centaur", "option_d": "He is a troll",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What happens to Briar Cudgeon at the end?",
         "option_a": "He is killed in a shootout with the goblins", "option_b": "He escapes", "option_c": "He is arrested", "option_d": "He becomes commander",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 10. The Eternity Code =====
books_questions.append({
    "title": "The Eternity Code",
    "questions": [
        {"question_text": "What does Artemis build using fairy technology?",
         "option_a": "The C Cube, a supercomputer", "option_b": "A magic weapon", "option_c": "A time machine", "option_d": "A flying car",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who steals the C Cube from Artemis?",
         "option_a": "Jon Spiro, an American businessman", "option_b": "Briar Cudgeon", "option_c": "Opal Koboi", "option_d": "A goblin",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What happens to Butler when Jon Spiro's men attack?",
         "option_a": "He is shot and nearly dies", "option_b": "He is kidnapped", "option_c": "He is turned into a fairy", "option_d": "He is arrested",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "How does Artemis save Butler's life?",
         "option_a": "He freezes him with fairy cryogenics until he can be healed", "option_b": "He gives him a magic potion", "option_c": "He uses the C Cube", "option_d": "He calls a doctor",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who does Artemis recruit to help him retrieve the C Cube?",
         "option_a": "The fairies (Holly, Foaly, Mulch)", "option_b": "The Russian Mafiya", "option_c": "Jon Spiro", "option_d": "A troll",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "What is Juliet Butler's role in the story?",
         "option_a": "She goes undercover to help steal back the C Cube", "option_b": "She is kidnapped", "option_c": "She is a fairy", "option_d": "She is a teacher",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "Where is Jon Spiro's headquarters located?",
         "option_a": "In Chicago, the Spiro Needle", "option_b": "In New York", "option_c": "In London", "option_d": "In Haven City",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What does the C Cube do if activated without the password?",
         "option_a": "It self-destructs", "option_b": "It becomes a weapon", "option_c": "It calls the police", "option_d": "It turns invisible",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens to Jon Spiro at the end of the book?",
         "option_a": "He is arrested and his company is destroyed", "option_b": "He escapes", "option_c": "He is killed", "option_d": "He becomes a fairy",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What do the fairies do to Artemis at the very end?",
         "option_a": "They mind-wipe him so he forgets everything about fairies", "option_b": "They arrest him", "option_c": "They give him gold", "option_d": "They make him a fairy",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 11. The Opal Deception =====
books_questions.append({
    "title": "The Opal Deception",
    "questions": [
        {"question_text": "Who is the main villain seeking revenge in this book?",
         "option_a": "Opal Koboi", "option_b": "Briar Cudgeon", "option_c": "Jon Spiro", "option_d": "A troll",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "What does Opal Koboi do to frame Holly Short?",
         "option_a": "She frames Holly for the murder of Commander Root", "option_b": "She steals Holly's badge", "option_c": "She kidnaps Holly", "option_d": "She turns Holly into a human",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What happens to Commander Root?",
         "option_a": "He is killed by a bomb planted by Opal", "option_b": "He is kidnapped", "option_c": "He is fired", "option_d": "He retires",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the only one who can clear Holly's name?",
         "option_a": "Artemis Fowl", "option_b": "Foaly", "option_c": "Mulch", "option_d": "Commander Root",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What problem does Artemis face at the start of the book?",
         "option_a": "He has been mind-wiped and doesn't remember the fairies", "option_b": "He is in prison", "option_c": "He is sick", "option_d": "He has lost his fortune",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who helps Artemis regain his memories?",
         "option_a": "Holly and Mulch, using a flashback device", "option_b": "Foaly", "option_c": "Butler", "option_d": "His mother",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "Where is Opal Koboi's secret base hidden?",
         "option_a": "In an abandoned shuttleport", "option_b": "In Chicago", "option_c": "In Fowl Manor", "option_d": "In Haven City",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What does Opal plan to do to the fairy world?",
         "option_a": "Destroy it and take over", "option_b": "Make it invisible", "option_c": "Turn it to gold", "option_d": "Sink it underground",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens to Opal Koboi at the end of the book?",
         "option_a": "She is captured and arrested", "option_b": "She escapes", "option_c": "She is killed", "option_d": "She becomes good",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "Who becomes the new commander of the LEP?",
         "option_a": "Ark Sool", "option_b": "Holly Short", "option_c": "Foaly", "option_d": "Mulch",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 12. The Lost Colony =====
books_questions.append({
    "title": "The Lost Colony",
    "questions": [
        {"question_text": "What ancient fairy race does Artemis discover in this book?",
         "option_a": "Demons, the eighth fairy family", "option_b": "Trolls", "option_c": "Goblins", "option_d": "Centaurs",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Where do the demons live?",
         "option_a": "On the island of Hybras, suspended in time", "option_b": "In Haven City", "option_c": "Underground", "option_d": "In the Arctic",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What is the name of the demon warlock who is trying to break the time spell?",
         "option_a": "N°1", "option_b": "Leon Abbot", "option_c": "Qwan", "option_d": "Imp Imbroli",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the demon leader who took power by stealing magic?",
         "option_a": "Leon Abbot", "option_b": "N°1", "option_c": "Qwan", "option_d": "Artemis",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who is the new fairy character, a demon imp who befriends Artemis?",
         "option_a": "N°1", "option_b": "Qwan", "option_c": "Leon Abbot", "option_d": "Holly",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "What does Holly Short do in this book?",
         "option_a": "She helps Artemis stop the time spell from destroying Hybras", "option_b": "She quits the LEP", "option_c": "She is kidnapped", "option_d": "She becomes a demon",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What happens to the island of Hybras at the end of the book?",
         "option_a": "It is returned to the real world, in Ireland", "option_b": "It is destroyed", "option_c": "It floats away", "option_d": "It sinks",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Who is the old demon warlock who helps save Hybras?",
         "option_a": "Qwan", "option_b": "Leon Abbot", "option_c": "N°1", "option_d": "Foaly",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens to Artemis at the end of the book?",
         "option_a": "He swaps an eye with Holly, gaining fairy magic", "option_b": "He is arrested", "option_c": "He loses his memory", "option_d": "He becomes a fairy",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What does Minerva Paradiz, a young genius, want to do?",
         "option_a": "Capture a demon for scientific glory", "option_b": "Help Artemis", "option_c": "Steal the C Cube", "option_d": "Join the LEP",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 13. Inkheart =====
books_questions.append({
    "title": "Inkheart",
    "questions": [
        {"question_text": "What special ability does Mo (Mortimer) have?",
         "option_a": "He can bring characters out of books by reading aloud", "option_b": "He can fly", "option_c": "He can turn invisible", "option_d": "He can talk to animals",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "What is the name of Mo's daughter, the protagonist?",
         "option_a": "Meggie", "option_b": "Resa", "option_c": "Elinor", "option_d": "Fenoglio",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who is the evil character read out of the book Inkheart?",
         "option_a": "Capricorn", "option_b": "Dustfinger", "option_c": "Basta", "option_d": "Fenoglio",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "What happened to Mo's wife Resa when he read Capricorn out of the book?",
         "option_a": "She was read into the book", "option_b": "She was kidnapped", "option_c": "She died", "option_d": "She ran away",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who is the fire-eater who wants to return to the world of the book?",
         "option_a": "Dustfinger", "option_b": "Capricorn", "option_c": "Basta", "option_d": "Fenoglio",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is the author of the book Inkheart within the story?",
         "option_a": "Fenoglio", "option_b": "Mo", "option_c": "Elinor", "option_d": "Capricorn",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does Capricorn want from Mo?",
         "option_a": "He wants Mo to read the Shadow (a monster) out of the book for him", "option_b": "He wants Mo's money", "option_c": "He wants Mo to write a new book", "option_d": "He wants Mo dead",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Where does Meggie's aunt Elinor live?",
         "option_a": "In a house full of books in Italy", "option_b": "In Germany", "option_c": "In France", "option_d": "In England",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What does Meggie discover she can also do?",
         "option_a": "She can read characters out of books", "option_b": "She can fly", "option_c": "She can talk to animals", "option_d": "She can turn invisible",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What happens at the climax of the book?",
         "option_a": "Meggie reads the Shadow out, but it turns on Capricorn and kills him", "option_b": "Capricorn escapes", "option_c": "Mo is killed", "option_d": "The book is destroyed",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 14. Inkspell =====
books_questions.append({
    "title": "Inkspell",
    "questions": [
        {"question_text": "Where do Meggie and Farid go in this book?",
         "option_a": "Into the world of the Inkheart book", "option_b": "To Italy", "option_c": "To a new world", "option_d": "To the past",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who read themselves into the book?",
         "option_a": "Dustfinger, with Orpheus's help", "option_b": "Mo", "option_c": "Capricorn", "option_d": "Elinor",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who is the new villain who reads Dustfinger into the Inkworld?",
         "option_a": "Orpheus", "option_b": "Capricorn", "option_c": "Basta", "option_d": "Fenoglio",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "What role does Fenoglio, the author, take in the Inkworld?",
         "option_a": "He becomes a court poet in Ombra", "option_b": "He becomes king", "option_c": "He is captured", "option_d": "He becomes a thief",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What happens to Mo in the Inkworld?",
         "option_a": "He is captured and becomes the Bluejay, a legendary robber", "option_b": "He becomes king", "option_c": "He dies", "option_d": "He returns home",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is the evil ruler of the Inkworld?",
         "option_a": "The Adderhead, a cruel tyrant", "option_b": "Capricorn", "option_c": "Basta", "option_d": "Orpheus",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does the Adderhead want from the Bluejay (Mo)?",
         "option_a": "He wants Mo to bind an immortal book for him", "option_b": "He wants Mo's money", "option_c": "He wants Mo dead", "option_d": "He wants Mo to read for him",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Who is Meggie's love interest in the Inkworld?",
         "option_a": "Farid", "option_b": "Dustfinger", "option_c": "Fenoglio", "option_d": "Orpheus",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens to Dustfinger in this book?",
         "option_a": "He is killed by Basta", "option_b": "He becomes king", "option_c": "He returns home", "option_d": "He is captured",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What does Meggie do at the end of the book?",
         "option_a": "She writes a new ending to the story to save Mo", "option_b": "She returns home", "option_c": "She becomes queen", "option_d": "She marries Farid",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 15. Inkdeath =====
books_questions.append({
    "title": "Inkdeath",
    "questions": [
        {"question_text": "Where does the story pick up after Inkspell?",
         "option_a": "In the Inkworld, after Dustfinger's death", "option_b": "In the real world", "option_c": "In Italy", "option_d": "In Ombra",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who brings Dustfinger back from the dead?",
         "option_a": "Orpheus, by making a bargain with the White Women", "option_b": "Mo", "option_c": "Meggie", "option_d": "Fenoglio",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who does Mo become known as in the Inkworld?",
         "option_a": "The Bluejay, a legendary robber", "option_b": "The Adderhead", "option_c": "The King", "option_d": "The Storyteller",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "What does the Adderhead want from the Bluejay?",
         "option_a": "He wants Mo to bind him an immortal book so he can live forever", "option_b": "He wants Mo's gold", "option_c": "He wants Mo dead", "option_d": "He wants Mo to read for him",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who becomes the new ruler after the Adderhead's downfall?",
         "option_a": "Violante's son, Jacopo", "option_b": "Mo", "option_c": "Fenoglio", "option_d": "Orpheus",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "What does Meggie decide at the end of the book?",
         "option_a": "She stays in the Inkworld with Doria, not Farid", "option_b": "She returns home", "option_c": "She marries Farid", "option_d": "She becomes queen",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "Who is the character who can write new stories into the Inkworld?",
         "option_a": "Orpheus", "option_b": "Mo", "option_c": "Meggie", "option_d": "Fenoglio",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What happens to Fenoglio in this book?",
         "option_a": "He loses his ability to write new stories", "option_b": "He becomes king", "option_c": "He dies", "option_d": "He returns home",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What is the fate of the Adderhead?",
         "option_a": "He dies when the immortal book is destroyed", "option_b": "He becomes immortal", "option_c": "He escapes", "option_d": "He becomes good",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What does Mo do at the very end of the book?",
         "option_a": "He stays in the Inkworld with Resa", "option_b": "He returns home", "option_c": "He becomes king", "option_d": "He dies",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 16. Dragon Rider =====
books_questions.append({
    "title": "Dragon Rider",
    "questions": [
        {"question_text": "What is the name of the young dragon who is the main character?",
         "option_a": "Firedrake", "option_b": "Sorrel", "option_c": "Ben", "option_d": "Nettlebrand",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "What is Firedrake searching for?",
         "option_a": "The Rim of Heaven, a mythical dragon sanctuary", "option_b": "A treasure", "option_c": "A new home in the sea", "option_d": "A magic sword",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who is the brownie (a forest creature) who accompanies Firedrake?",
         "option_a": "Sorrel", "option_b": "Ben", "option_c": "Nettlebrand", "option_d": "Twigleg",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the orphaned boy who joins Firedrake on his quest?",
         "option_a": "Ben", "option_b": "Sorrel", "option_c": "Twigleg", "option_d": "Guinevere",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who is the golden dragon who hunts and kills real dragons?",
         "option_a": "Nettlebrand", "option_b": "Firedrake", "option_c": "Maeve", "option_d": "Guinevere",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is the homunculus (tiny man) who serves Nettlebrand?",
         "option_a": "Twigleg", "option_b": "Ben", "option_c": "Sorrel", "option_d": "Guinevere",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does Twigleg do during the quest?",
         "option_a": "He betrays Nettlebrand and helps Firedrake", "option_b": "He stays loyal to Nettlebrand", "option_c": "He runs away", "option_d": "He becomes a dragon",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Where is the Rim of Heaven located?",
         "option_a": "In the Himalayas", "option_b": "In the Alps", "option_c": "In the Arctic", "option_d": "In the desert",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What happens to Nettlebrand at the end of the book?",
         "option_a": "He is defeated when the dragons and brownies work together", "option_b": "He escapes", "option_c": "He becomes good", "option_d": "He becomes king",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What does Ben find at the end of his journey?",
         "option_a": "A new family and a home with the dragons", "option_b": "A treasure", "option_c": "His parents", "option_d": "A magic sword",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 17. The Thief Lord =====
books_questions.append({
    "title": "The Thief Lord",
    "questions": [
        {"question_text": "Where does this story take place?",
         "option_a": "In Venice, Italy", "option_b": "In Rome", "option_c": "In Paris", "option_d": "In London",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who are the two orphaned brothers at the center of the story?",
         "option_a": "Prosper and Bo", "option_b": "Scipio and Riccio", "option_c": "Hornet and Mosca", "option_d": "Victor and Prosper",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who is the mysterious leader of the gang of runaway children?",
         "option_a": "Scipio, the Thief Lord", "option_b": "Prosper", "option_c": "Riccio", "option_d": "Victor",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the detective hired to find the runaway boys?",
         "option_a": "Victor Getz", "option_b": "Scipio", "option_c": "Ida Spavento", "option_d": "The Conte",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What mysterious object is the Conte looking for?",
         "option_a": "A magic merry-go-round that turns children into adults", "option_b": "A treasure chest", "option_c": "A magic mirror", "option_d": "A magic book",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is the mysterious woman who helps the children?",
         "option_a": "Ida Spavento", "option_b": "Victor Getz", "option_c": "The Conte", "option_d": "Scipio",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does Scipio reveal about himself?",
         "option_a": "He is actually the son of a wealthy man, not an orphan", "option_b": "He is a fairy", "option_c": "He is a thief", "option_d": "He is a detective",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What does the magic merry-go-round do?",
         "option_a": "It turns children into adults and adults into children", "option_b": "It flies", "option_c": "It makes people invisible", "option_d": "It grants wishes",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "Who rides the merry-go-round to become an adult?",
         "option_a": "Scipio", "option_b": "Prosper", "option_c": "Bo", "option_d": "Riccio",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What happens at the end of the story?",
         "option_a": "Scipio becomes Victor's assistant and the children find homes", "option_b": "They all return home", "option_c": "They become rich", "option_d": "They are arrested",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 18. Gregor the Overlander =====
books_questions.append({
    "title": "Gregor the Overlander",
    "questions": [
        {"question_text": "How does Gregor end up in the Underland?",
         "option_a": "He falls through a grate in his laundry room", "option_b": "He is kidnapped", "option_c": "He finds a magic door", "option_d": "He is swallowed by a creature",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who falls into the Underland with Gregor?",
         "option_a": "His little sister, Boots", "option_b": "His mother", "option_c": "His father", "option_d": "His friend",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "What creatures live in the Underland?",
         "option_a": "Giant cockroaches, rats, bats, and spiders", "option_b": "Dragons", "option_c": "Fairies", "option_d": "Trolls",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who are the humans who live in the Underland?",
         "option_a": "The people of Regalia", "option_b": "The people of the Surface", "option_c": "The Crawlers", "option_d": "The Fliers",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who is the princess of Regalia who befriends Gregor?",
         "option_a": "Luxa", "option_b": "Boots", "option_c": "Solovet", "option_d": "Vikus",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "What is the Prophecy of Gray?",
         "option_a": "A prophecy about a warrior from the Overland who must save the Underland", "option_b": "A prophecy about a king", "option_c": "A prophecy about a dragon", "option_d": "A prophecy about a flood",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "Who is the giant cockroach who becomes Gregor's friend?",
         "option_a": "Temp", "option_b": "Tick", "option_c": "Ripred", "option_d": "Ares",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "Who is the giant rat who is a fierce warrior and ally?",
         "option_a": "Ripred", "option_b": "Ares", "option_c": "Temp", "option_d": "Vikus",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What does Gregor discover about his father?",
         "option_a": "His father is a prisoner in the Underland", "option_b": "His father is dead", "option_c": "His father is a rat", "option_d": "His father is a king",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What is the name of the giant bat who bonds with Gregor?",
         "option_a": "Ares", "option_b": "Temp", "option_c": "Ripred", "option_d": "Luxa",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 19. Gregor and the Prophecy of Bane =====
books_questions.append({
    "title": "Gregor and the Prophecy of Bane",
    "questions": [
        {"question_text": "What is the Prophecy of Bane about?",
         "option_a": "A giant white rat called the Bane that threatens the Underland", "option_b": "A flood", "option_c": "A dragon", "option_d": "A plague",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Who is the giant white rat that Gregor must defeat?",
         "option_a": "The Bane", "option_b": "Ripred", "option_c": "Twirltongue", "option_d": "King Gorger",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Where does the Bane live?",
         "option_a": "In the Labyrinth, a maze of tunnels", "option_b": "In Regalia", "option_c": "In the jungle", "option_d": "In the Dead Land",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the rat who secretly manipulates the Bane?",
         "option_a": "Twirltongue", "option_b": "Ripred", "option_c": "Solovet", "option_d": "Vikus",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "What happens to Gregor's bond, his bat Ares?",
         "option_a": "He is accused of treason and put on trial", "option_b": "He is killed", "option_c": "He is kidnapped", "option_d": "He is exiled",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who are the creatures who spin deadly silk in the Labyrinth?",
         "option_a": "Giant spiders called Spinners", "option_b": "Giant rats", "option_c": "Giant cockroaches", "option_d": "Giant ants",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does Gregor discover about the Bane?",
         "option_a": "The Bane is actually just a baby, not a monster", "option_b": "The Bane is invincible", "option_c": "The Bane is a human", "option_d": "The Bane is a bat",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What does Gregor decide to do with the Bane?",
         "option_a": "He spares the Bane's life", "option_b": "He kills the Bane", "option_c": "He takes the Bane to Regalia", "option_d": "He gives the Bane to the rats",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "Who is the leader of Regalia?",
         "option_a": "Solovet", "option_b": "Vikus", "option_c": "Luxa", "option_d": "Ripred",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What happens at the end of the book?",
         "option_a": "Gregor returns home but knows he will be called back", "option_b": "He stays in the Underland", "option_c": "He is killed", "option_d": "He becomes king",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 20. Gregor and the Curse of the Warmbloods =====
books_questions.append({
    "title": "Gregor and the Curse of the Warmbloods",
    "questions": [
        {"question_text": "What is the Curse of the Warmbloods?",
         "option_a": "A deadly plague that kills all warm-blooded creatures in the Underland", "option_b": "A curse that turns creatures to stone", "option_c": "A curse that makes creatures invisible", "option_d": "A curse that causes madness",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "Where does the cure for the plague grow?",
         "option_a": "In the Vineyard of Eyes, a dangerous jungle", "option_b": "In Regalia", "option_c": "In the Labyrinth", "option_d": "In the Dead Land",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who leads the quest to find the cure?",
         "option_a": "Gregor, along with a team of Underlanders", "option_b": "Luxa alone", "option_c": "Ripred alone", "option_d": "Solovet alone",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "Who is the rat that joins the quest?",
         "option_a": "Ripred", "option_b": "Twirltongue", "option_c": "The Bane", "option_d": "King Gorger",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who is the human scientist working on a cure?",
         "option_a": "Solovet", "option_b": "Vikus", "option_c": "Luxa", "option_d": "Hamnet",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who is Hamnet, a character they meet?",
         "option_a": "He is Vikus's son, who lives in exile in the jungle", "option_b": "He is a rat", "option_c": "He is a king", "option_d": "He is a bat",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What dangerous creature lives in the Vineyard of Eyes?",
         "option_a": "Giant carnivorous plants that look like eyes", "option_b": "Dragons", "option_c": "Trolls", "option_d": "Giant spiders",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What happens to the cure they find?",
         "option_a": "It is destroyed, and they must find another way", "option_b": "It works perfectly", "option_c": "It is stolen", "option_d": "It is a trap",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "Who is revealed to be secretly working against the quest?",
         "option_a": "Solovet, who let the plague spread on purpose", "option_b": "Ripred", "option_c": "Luxa", "option_d": "Hamnet",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What happens to Hamnet?",
         "option_a": "He dies protecting the others from the plants", "option_b": "He becomes king", "option_c": "He escapes", "option_d": "He is cured",
         "correct_answer": "a", "question_order": 10},
    ]
})

# ===== 21. Gregor and the Marks of Secret =====
books_questions.append({
    "title": "Gregor and the Marks of Secret",
    "questions": [
        {"question_text": "What are the Marks of Secret?",
         "option_a": "A code of drawings that mark the path to a hidden disaster", "option_b": "A magic spell", "option_c": "A treasure map", "option_d": "A secret language",
         "correct_answer": "a", "question_order": 1},
        {"question_text": "What do the Marks of Secret reveal?",
         "option_a": "A plot by the rats to trap and kill the mice of the Underland", "option_b": "A treasure", "option_c": "A new world", "option_d": "A prophecy",
         "correct_answer": "a", "question_order": 2},
        {"question_text": "Who are the mice of the Underland called?",
         "option_a": "The Nibblers", "option_b": "The Crawlers", "option_c": "The Fliers", "option_d": "The Gnawers",
         "correct_answer": "a", "question_order": 3},
        {"question_text": "What does the rat king plan to do to the mice?",
         "option_a": "Trap them in a volcano that will erupt", "option_b": "Drown them", "option_c": "Poison them", "option_d": "Starve them",
         "correct_answer": "a", "question_order": 4},
        {"question_text": "Who is the rat who leads the plot against the mice?",
         "option_a": "King Gorger", "option_b": "Ripred", "option_c": "Twirltongue", "option_d": "The Bane",
         "correct_answer": "a", "question_order": 5},
        {"question_text": "Who helps Gregor decode the Marks of Secret?",
         "option_a": "Ripred", "option_b": "Luxa", "option_c": "Vikus", "option_d": "Solovet",
         "correct_answer": "a", "question_order": 6},
        {"question_text": "What does Gregor discover about his own role in the prophecy?",
         "option_a": "He is the warrior who must lead the final battle", "option_b": "He is a king", "option_c": "He is a rat", "option_d": "He is a traitor",
         "correct_answer": "a", "question_order": 7},
        {"question_text": "What happens to the mice in this book?",
         "option_a": "Many are killed when the volcano erupts", "option_b": "They escape", "option_c": "They become rats", "option_d": "They are saved",
         "correct_answer": "a", "question_order": 8},
        {"question_text": "What does Gregor do at the end of the book?",
         "option_a": "He declares war on the rats, setting up the final battle", "option_b": "He returns home", "option_c": "He becomes king", "option_d": "He is killed",
         "correct_answer": "a", "question_order": 9},
        {"question_text": "What is the significance of this book in the series?",
         "option_a": "It sets up the final war between the humans and the rats", "option_b": "It is the last book", "option_c": "It is a prequel", "option_d": "It is a side story",
         "correct_answer": "a", "question_order": 10},
    ]
})

# Verify each book has exactly 10 questions
for b in books_questions:
    assert len(b["questions"]) == 10, f"{b['title']} has {len(b['questions'])} questions"
    # Verify answer distribution
    answers = [q["correct_answer"] for q in b["questions"]]
    for i, q in enumerate(b["questions"]):
        assert q["question_order"] == i+1, f"{b['title']} q{i+1} order is {q['question_order']}"
    # Check distribution
    from collections import Counter
    c = Counter(answers)
    print(f"{b['title']}: {dict(c)}")

output_path = "/home/user/workspace/bookquiz/questions_batch_5.json"
with open(output_path, "w") as f:
    json.dump(books_questions, f, indent=2)
print(f"\nWrote {len(books_questions)} books with {sum(len(b['questions']) for b in books_questions)} questions to {output_path}")
