#!/usr/bin/env python3
"""Generate quiz questions for batch 1 books."""
import json

books = [
    {
        "title": "Captain Underpants: The First Epic Novel",
        "questions": [
            {
                "question_text": "Who are the two main characters in Captain Underpants?",
                "option_a": "George and Harold",
                "option_b": "John and Harry",
                "option_c": "Greg and Henry",
                "option_d": "Gary and Hugo",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What do George and Harold do to their principal Mr. Krupp?",
                "option_a": "They give him a haircut",
                "option_b": "They hypnotize him",
                "option_c": "They lock him in a closet",
                "option_d": "They throw him a surprise party",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What does Mr. Krupp turn into when hypnotized?",
                "option_a": "A giant robot",
                "option_b": "A dragon",
                "option_c": "Captain Underpants",
                "option_d": "A superhero dog",
                "correct_answer": "c",
                "question_order": 3,
            },
            {
                "question_text": "What is Captain Underpants's main weakness?",
                "option_a": "Soap and water",
                "option_b": "He is afraid of the dark",
                "option_c": "He loses his powers at night",
                "option_d": "He cannot fly",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "What do George and Harold create that features Captain Underpants?",
                "option_a": "A movie",
                "option_b": "A comic book",
                "option_c": "A board game",
                "option_d": "A puppet show",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What grade are George and Harold in?",
                "option_a": "Third grade",
                "option_b": "Fourth grade",
                "option_c": "Fifth grade",
                "option_d": "Sixth grade",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What are the names of the two robots that Dr. Diaper creates?",
                "option_a": "Robo-George and Robo-Harold",
                "option_b": "The Turbo Toilet 2000 and the Waffle Wedgie",
                "option_c": "The Talking Toilets",
                "option_d": "Dr. Diaper does not create robots",
                "correct_answer": "c",
                "question_order": 7,
            },
            {
                "question_text": "Who is the villain that George and Harold's comic features?",
                "option_a": "Dr. Diaper",
                "option_b": "Professor Poopypants",
                "option_c": "The Bionic Booger Boy",
                "option_d": "The Wicked Wedgie Woman",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "What snap brings Mr. Krupp back to normal?",
                "option_a": "Snapping fingers",
                "option_b": "Pouring water on his head",
                "option_c": "Clapping hands",
                "option_d": "A magic word",
                "correct_answer": "a",
                "question_order": 9,
            },
            {
                "question_text": "At the end of the book, what happens to Captain Underpants?",
                "option_a": "He becomes a real superhero permanently",
                "option_b": "He turns back into Mr. Krupp forever",
                "option_c": "He disappears",
                "option_d": "He retires",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Diary of a Wimpy Kid",
        "questions": [
            {
                "question_text": "What is the name of the main character in Diary of a Wimpy Kid?",
                "option_a": "Greg Heffley",
                "option_b": "Gregory House",
                "option_c": "Gary Heffley",
                "option_d": "Greg Harper",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What is the title of Greg's best friend's comic strip?",
                "option_a": "Zoo-Wee-Mama!",
                "option_b": "Wimpy Kid",
                "option_c": "The Fart Squad",
                "option_d": "Creighton the Cretin",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "Who is Greg's best friend?",
                "option_a": "Rowley Jefferson",
                "option_b": "Fregley",
                "option_c": "Patty Farrell",
                "option_d": "Chirag Gupta",
                "correct_answer": "a",
                "question_order": 3,
            },
            {
                "question_text": "What happens to Rowley at the end of the book?",
                "option_a": "He moves away",
                "option_b": "He breaks his arm",
                "option_c": "He becomes popular",
                "option_d": "He gets a new bike",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "What is the name of Greg's older brother?",
                "option_a": "Rodrick",
                "option_b": "Manny",
                "option_c": "Frank",
                "option_d": "Susan",
                "correct_answer": "a",
                "question_order": 5,
            },
            {
                "question_text": "What does Greg try to do at the school talent show?",
                "option_a": "Sing a solo",
                "option_b": "Do a magic act",
                "option_c": "Perform as a tree",
                "option_d": "Dance",
                "correct_answer": "c",
                "question_order": 6,
            },
            {
                "question_text": "What does Greg want to be when he grows up?",
                "option_a": "A doctor",
                "option_b": "Famous and rich",
                "option_c": "A professional athlete",
                "option_d": "A teacher",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What item causes a fight between Greg and Rowley?",
                "option_a": "A video game",
                "option_b": "A comic strip",
                "option_c": "A piece of cheese on the playground",
                "option_d": "A basketball",
                "correct_answer": "c",
                "question_order": 8,
            },
            {
                "question_text": "Who is the youngest member of Greg's family?",
                "option_a": "Greg",
                "option_b": "Rodrick",
                "option_c": "Manny",
                "option_d": "Rowley",
                "correct_answer": "c",
                "question_order": 9,
            },
            {
                "question_text": "What is Greg's mother's name?",
                "option_a": "Susan",
                "option_b": "Linda",
                "option_c": "Mary",
                "option_d": "Karen",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Magic Tree House: Dinosaurs Before Dark",
        "questions": [
            {
                "question_text": "What are the names of the two main characters?",
                "option_a": "Jack and Annie",
                "option_b": "Tom and Lucy",
                "option_c": "Will and Emma",
                "option_d": "Sam and Kate",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "Where do Jack and Annie find the magic tree house?",
                "option_a": "In their backyard",
                "option_b": "In a forest near their home in Frog Creek",
                "option_c": "At school",
                "option_d": "In a museum",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "How do the children travel through time?",
                "option_a": "By saying a magic word",
                "option_b": "By pointing at a picture in a book",
                "option_c": "By climbing a ladder",
                "option_d": "By closing their eyes and wishing",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "Which dinosaur does Annie befriend?",
                "option_a": "A T-Rex",
                "option_b": "A Triceratops",
                "option_c": "A Pteranodon",
                "option_d": "A Stegosaurus",
                "correct_answer": "c",
                "question_order": 4,
            },
            {
                "question_text": "Who is older, Jack or Annie?",
                "option_a": "Annie",
                "option_b": "Jack",
                "option_c": "They are twins",
                "option_d": "It is never mentioned",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What does Jack like to carry with him?",
                "option_a": "A backpack",
                "option_b": "A notebook",
                "option_c": "A flashlight",
                "option_d": "A compass",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What does Annie name the Pteranodon?",
                "option_a": "Henry",
                "option_b": "Nicky",
                "option_c": "Beth",
                "option_d": "Rocky",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "What does the tree house belong to?",
                "option_a": "Morgan le Fay",
                "option_b": "A wizard",
                "option_c": "A king",
                "option_d": "Nobody knows",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "What does Jack find in the tree house?",
                "option_a": "A dinosaur bone",
                "option_b": "A book about dinosaurs",
                "option_c": "A map",
                "option_d": "A magic wand",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "Where does Jack and Annie live?",
                "option_a": "Frog Creek, Pennsylvania",
                "option_b": "Pine Tree, Ohio",
                "option_c": "Riverdale, New York",
                "option_d": "Oak Creek, Virginia",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Magic Tree House: The Knight at Dawn",
        "questions": [
            {
                "question_text": "Where do Jack and Annie travel in The Knight at Dawn?",
                "option_a": "Ancient Egypt",
                "option_b": "Medieval England",
                "option_c": "Ancient Rome",
                "option_d": "Japan",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "What do Jack and Annie explore in this adventure?",
                "option_a": "A pyramid",
                "option_b": "A castle",
                "option_c": "A cave",
                "option_d": "A ship",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What kind of animal do Jack and Annie encounter in the castle?",
                "option_a": "A dragon",
                "option_b": "A knight on horseback",
                "option_c": "A guard dog",
                "option_d": "A knight in armor",
                "correct_answer": "d",
                "question_order": 3,
            },
            {
                "question_text": "What does Annie do that gets them into trouble?",
                "option_a": "She touches a suit of armor",
                "option_b": "She takes a sword",
                "option_c": "She opens a drawbridge",
                "option_d": "She rings a bell",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "What does Jack discover in the book about knights?",
                "option_a": "Knights were always wealthy",
                "option_b": "Knights followed a code of chivalry",
                "option_c": "Knights never used weapons",
                "option_d": "Knights lived in castles alone",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "How do Jack and Annie escape from the castle?",
                "option_a": "Through a secret tunnel",
                "option_b": "By climbing out a window",
                "option_c": "Through the moat",
                "option_d": "By disguising themselves",
                "correct_answer": "a",
                "question_order": 6,
            },
            {
                "question_text": "What time of day do the children arrive at the castle?",
                "option_a": "Morning",
                "option_b": "Dawn",
                "option_c": "Afternoon",
                "option_d": "Midnight",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What does Annie want to do when she sees the knights?",
                "option_a": "Run away",
                "option_b": "Talk to them",
                "option_c": "Fight them",
                "option_d": "Hide",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What does Jack find that helps them understand the knight's world?",
                "option_a": "A shield",
                "option_b": "A book about knights",
                "option_c": "A map",
                "option_d": "A letter",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What is a moat?",
                "option_a": "A tall tower",
                "option_b": "A deep ditch of water around a castle",
                "option_c": "A type of gate",
                "option_d": "A flagpole",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Magic Tree House: Mummies in the Morning",
        "questions": [
            {
                "question_text": "Where do Jack and Annie travel in Mummies in the Morning?",
                "option_a": "Ancient Greece",
                "option_b": "Ancient Egypt",
                "option_c": "Ancient China",
                "option_d": "Ancient Rome",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "Who do Jack and Annie meet in the pyramid?",
                "option_a": "A pharaoh",
                "option_b": "A ghost queen",
                "option_c": "A mummy",
                "option_d": "A priest",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What does the ghost queen ask Jack and Annie to find?",
                "option_a": "A golden mask",
                "option_b": "The Book of the Dead",
                "option_c": "A hidden treasure",
                "option_d": "A magic scarab",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What is the ghost queen's name?",
                "option_a": "Cleopatra",
                "option_b": "Nefertiti",
                "option_c": "Hutepi",
                "option_d": "Hatshepsut",
                "correct_answer": "c",
                "question_order": 4,
            },
            {
                "question_text": "What does Jack use to help them navigate the pyramid?",
                "option_a": "A compass",
                "option_b": "A book about Egypt",
                "option_c": "A map on the wall",
                "option_d": "A guide",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What is the Book of the Dead?",
                "option_a": "A list of pharaohs",
                "option_b": "A guide for the afterlife",
                "option_c": "A collection of spells for mummies",
                "option_d": "A history of Egypt",
                "correct_answer": "c",
                "question_order": 6,
            },
            {
                "question_text": "What animal was important in ancient Egyptian culture?",
                "option_a": "The lion",
                "option_b": "The cat",
                "option_c": "The eagle",
                "option_d": "The horse",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What does Annie do when she sees the ghost queen?",
                "option_a": "She runs away",
                "option_b": "She talks to her without fear",
                "option_c": "She screams",
                "option_d": "She hides behind Jack",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What helps Jack and Annie find their way out of the pyramid?",
                "option_a": "A cat leads them",
                "option_b": "They follow torches",
                "option_c": "The ghost queen guides them",
                "option_d": "They follow a map",
                "correct_answer": "a",
                "question_order": 9,
            },
            {
                "question_text": "What does the ghost queen give Jack and Annie as a reward?",
                "option_a": "A golden coin",
                "option_b": "A hieroglyph scroll",
                "option_c": "A scarab amulet",
                "option_d": "A magic wand",
                "correct_answer": "c",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Magic Tree House: Pirates Past Noon",
        "questions": [
            {
                "question_text": "Where do Jack and Annie travel in Pirates Past Noon?",
                "option_a": "A deserted island",
                "option_b": "A Caribbean beach",
                "option_c": "A pirate ship",
                "option_d": "A port city",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "Who do Jack and Annie encounter on the beach?",
                "option_a": "A sea captain",
                "option_b": "Pirates",
                "option_c": "Mermaids",
                "option_d": "A hermit",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "Who is the captain of the pirates?",
                "option_a": "Captain Hook",
                "option_b": "Captain Bones",
                "option_c": "Captain Kidd",
                "option_d": "Captain Jack",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What does Captain Bones want Jack and Annie to find?",
                "option_a": "A treasure chest",
                "option_b": "Captain Kidd's treasure",
                "option_c": "A map",
                "option_d": "A ship",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "What does Jack use to translate Captain Bones's notes?",
                "option_a": "A dictionary",
                "option_b": "A book about pirates",
                "option_c": "A map",
                "option_d": "A compass",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What is the weather like when Jack and Annie arrive?",
                "option_a": "Sunny and calm",
                "option_b": "Rainy and stormy",
                "option_c": "Cloudy but calm",
                "option_d": "Windy and cold",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "Who helps Jack and Annie escape from the pirates?",
                "option_a": "A parrot named Polly",
                "option_b": "A friendly sailor",
                "option_c": "A sea turtle",
                "option_d": "The tree house itself",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "What does Polly the parrot turn out to be?",
                "option_a": "A real parrot",
                "option_b": "Morgan le Fay in disguise",
                "option_c": "A ghost",
                "option_d": "A magical creature",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What is Captain Bones afraid of?",
                "option_a": "The dark",
                "option_b": "Ghosts",
                "option_c": "Drowning",
                "option_d": "Being captured",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "How do Jack and Annie get back to the tree house?",
                "option_a": "They swim",
                "option_b": "They run along the beach",
                "option_c": "They use a boat",
                "option_d": "Polly leads them",
                "correct_answer": "d",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The Boxcar Children",
        "questions": [
            {
                "question_text": "How many children are the main characters in The Boxcar Children?",
                "option_a": "Three",
                "option_b": "Four",
                "option_c": "Five",
                "option_d": "Two",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "What are the names of the four children?",
                "option_a": "Henry, Jessie, Violet, and Benny",
                "option_b": "Jack, Jill, Violet, and Benny",
                "option_c": "Henry, Jessie, Rose, and Ben",
                "option_d": "Tom, Jessie, Violet, and Danny",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "Why do the children run away?",
                "option_a": "They are afraid of their grandfather",
                "option_b": "They want an adventure",
                "option_c": "They are lost",
                "option_d": "Their parents send them away",
                "correct_answer": "a",
                "question_order": 3,
            },
            {
                "question_text": "Where do the children make their home?",
                "option_a": "In a cave",
                "option_b": "In an abandoned boxcar",
                "option_c": "In a treehouse",
                "option_d": "In a barn",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "Who is the oldest of the four children?",
                "option_a": "Jessie",
                "option_b": "Henry",
                "option_c": "Violet",
                "option_d": "Benny",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What does Henry do to earn money for the family?",
                "option_a": "He works at a bakery",
                "option_b": "He works for a doctor",
                "option_c": "He mows lawns",
                "option_d": "He sells vegetables",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What does the doctor find out about the children's grandfather?",
                "option_a": "He is kind and looking for them",
                "option_b": "He is dead",
                "option_c": "He is mean",
                "option_d": "He lives far away",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "What does Violet find in the woods that makes her happy?",
                "option_a": "A puppy",
                "option_b": "A pretty rock",
                "option_c": "A bird's nest",
                "option_d": "Wildflowers",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "What do the children name the dog they find?",
                "option_a": "Buddy",
                "option_b": "Watch",
                "option_c": "Spot",
                "option_d": "Rusty",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "Who turns out to be the children's grandfather?",
                "option_a": "The baker",
                "option_b": "The doctor",
                "option_c": "Mr. Alden",
                "option_d": "A stranger",
                "correct_answer": "c",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Sideways Stories from Wayside School",
        "questions": [
            {
                "question_text": "How was Wayside School built?",
                "option_a": "Sideways, with all classrooms on one floor",
                "option_b": "Thirty stories tall with one classroom per floor",
                "option_c": "Underground",
                "option_d": "In a circle",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "Who is the teacher on the thirtieth story?",
                "option_a": "Mrs. Gorf",
                "option_b": "Miss Jewls",
                "option_c": "Mr. Kidswatter",
                "option_d": "Mrs. Zarves",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What was Mrs. Gorf's special power?",
                "option_a": "She could fly",
                "option_b": "She could turn children into apples",
                "option_c": "She could make herself invisible",
                "option_d": "She could read minds",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "How many stories does Wayside School have?",
                "option_a": "Fifteen",
                "option_b": "Twenty",
                "option_c": "Thirty",
                "option_d": "Fifty",
                "correct_answer": "c",
                "question_order": 4,
            },
            {
                "question_text": "What is unusual about the nineteenth story?",
                "option_a": "It is upside down",
                "option_b": "It does not exist",
                "option_c": "It is a bathroom",
                "option_d": "It has no door",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "Who is the boy who can only count by fives?",
                "option_a": "John",
                "option_b": "Joe",
                "option_c": "Jason",
                "option_d": "Eric",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What does Mrs. Gorf do to the students who misbehave?",
                "option_a": "Sends them to the principal",
                "option_b": "Turns them into apples",
                "option_c": "Gives them detention",
                "option_d": "Makes them stand in the corner",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "Who is the new teacher on the thirtieth story?",
                "option_a": "Mrs. Gorf",
                "option_b": "Miss Jewls",
                "option_c": "Mr. Louis",
                "option_d": "Mrs. Zarves",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What is the name of the student who has three nostrils?",
                "option_a": "Louis",
                "option_b": "Bebe",
                "option_c": "Calvin",
                "option_d": "Mac",
                "correct_answer": "c",
                "question_order": 9,
            },
            {
                "question_text": "Who is the yard teacher at Wayside School?",
                "option_a": "Mr. Louis",
                "option_b": "Mr. Kidswatter",
                "option_c": "Mrs. Zarves",
                "option_d": "Miss Jewls",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The Mouse and the Motorcycle",
        "questions": [
            {
                "question_text": "What is the name of the mouse in The Mouse and the Motorcycle?",
                "option_a": "Ralph",
                "option_b": "Stuart",
                "option_c": "Despereaux",
                "option_d": "Frederick",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "Where does Ralph live?",
                "option_a": "In a hole in a wall at a hotel",
                "option_b": "In a field",
                "option_c": "In a house",
                "option_d": "In a barn",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "What object does Ralph love to ride?",
                "option_a": "A toy car",
                "option_b": "A toy motorcycle",
                "option_c": "A skateboard",
                "option_d": "A train",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "Who does Ralph befriend?",
                "option_a": "A boy named Keith",
                "option_b": "A girl named Amy",
                "option_c": "A boy named Tom",
                "option_d": "A girl named Lucy",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "How does Ralph make the motorcycle move?",
                "option_a": "By pushing it with his feet",
                "option_b": "By making a 'pb-pb-pb-pb' sound",
                "option_c": "By winding a key",
                "option_d": "By remote control",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What is the name of the hotel where the story takes place?",
                "option_a": "The Grand Hotel",
                "option_b": "The Mountain View Inn",
                "option_c": "The Plaza Hotel",
                "option_d": "The Happy Days Motel",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What does Ralph lose in the laundry?",
                "option_a": "His motorcycle",
                "option_b": "His food",
                "option_c": "A toy car",
                "option_d": "His nest",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "What does Keith leave for Ralph at the end of the story?",
                "option_a": "The toy motorcycle",
                "option_b": "A piece of cheese",
                "option_c": "A new toy car",
                "option_d": "A helmet",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "What kind of animal is Ralph?",
                "option_a": "A rat",
                "option_b": "A mouse",
                "option_c": "A hamster",
                "option_d": "A squirrel",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "Why does Ralph risk getting caught by humans?",
                "option_a": "He wants food",
                "option_b": "He wants to ride the motorcycle",
                "option_c": "He wants a friend",
                "option_d": "He is lost",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Ralph S. Mouse",
        "questions": [
            {
                "question_text": "Where does Ralph go in Ralph S. Mouse?",
                "option_a": "To a museum",
                "option_b": "To school",
                "option_c": "To the library",
                "option_d": "To a farm",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "Who takes Ralph to school?",
                "option_a": "Keith",
                "option_b": "Ryan",
                "option_c": "Brad",
                "option_d": "Matt",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What does Ralph ride at school?",
                "option_a": "A toy car",
                "option_b": "His motorcycle",
                "option_c": "A skateboard",
                "option_d": "A bicycle",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What happens to Ralph's motorcycle at school?",
                "option_a": "It gets broken",
                "option_b": "It gets lost",
                "option_c": "It gets stolen",
                "option_d": "It gets painted",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "What does the teacher, Miss K, do when she discovers Ralph?",
                "option_a": "She gets rid of him",
                "option_b": "She lets him stay as the class mouse",
                "option_c": "She calls animal control",
                "option_d": "She puts him in a cage",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What problem does Ralph cause at school?",
                "option_a": "He eats the students' lunches",
                "option_b": "He runs the motorcycle through the halls",
                "option_c": "He scares the students",
                "option_d": "He makes a mess in the classroom",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What does Ralph promise to do at school?",
                "option_a": "Behave and stay hidden",
                "option_b": "Perform tricks",
                "option_c": "Clean the classroom",
                "option_d": "Be the class pet",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "Who breaks Ralph's motorcycle?",
                "option_a": "Ryan",
                "option_b": "Brad",
                "option_c": "Miss K",
                "option_d": "A student named Kyle",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What does Ralph do to prove he is brave?",
                "option_a": "He faces a cat",
                "option_b": "He runs the maze in the classroom",
                "option_c": "He rides through a crowd of people",
                "option_d": "He jumps off a shelf",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What does the 'S' in Ralph S. Mouse stand for?",
                "option_a": "Smart",
                "option_b": "Sly",
                "option_c": "Speedy",
                "option_d": "It does not stand for anything",
                "correct_answer": "d",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The Paper Bag Princess",
        "questions": [
            {
                "question_text": "What is the name of the princess in The Paper Bag Princess?",
                "option_a": "Elizabeth",
                "option_b": "Snow White",
                "option_c": "Cinderella",
                "option_d": "Aurora",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "Who is the prince that Elizabeth is engaged to?",
                "option_a": "Prince Ronald",
                "option_b": "Prince Charming",
                "option_c": "Prince Edward",
                "option_d": "Prince Andrew",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "What destroys Elizabeth's castle and burns her clothes?",
                "option_a": "A fire",
                "option_b": "A dragon",
                "option_c": "A flood",
                "option_d": "A storm",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What does Elizabeth wear after the dragon destroys her clothes?",
                "option_a": "A paper bag",
                "option_b": "A blanket",
                "option_c": "A leaf",
                "option_d": "A towel",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "How does Elizabeth outsmart the dragon?",
                "option_a": "She fights him with a sword",
                "option_b": "She challenges him to do things until he is exhausted",
                "option_c": "She tricks him into a trap",
                "option_d": "She poisons him",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What does Elizabeth ask the dragon to do to prove his strength?",
                "option_a": "Burn a forest",
                "option_b": "Fly around the world",
                "option_c": "Burn up forests and fly around the world",
                "option_d": "Lift a boulder",
                "correct_answer": "c",
                "question_order": 6,
            },
            {
                "question_text": "What happens when Elizabeth rescues Prince Ronald?",
                "option_a": "He thanks her",
                "option_b": "He complains about her appearance",
                "option_c": "He runs away",
                "option_d": "He proposes again",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What does Elizabeth do at the end of the story?",
                "option_a": "She marries Prince Ronald",
                "option_b": "She skips off into the sunset without Ronald",
                "option_c": "She becomes queen",
                "option_d": "She fights the dragon again",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What is the main theme of The Paper Bag Princess?",
                "option_a": "True love conquers all",
                "option_b": "Intelligence and self-worth matter more than appearance",
                "option_c": "Dragons are dangerous",
                "option_d": "Princesses need rescuing",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What does Prince Ronald tell Elizabeth to do before she comes to rescue him?",
                "option_a": "Come back when you are dressed like a real princess",
                "option_b": "Bring a weapon",
                "option_c": "Bring help",
                "option_d": "Bring money",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Alexander and the Terrible Horrible No Good Very Bad Day",
        "questions": [
            {
                "question_text": "What is the first bad thing that happens to Alexander in the morning?",
                "option_a": "He stubs his toe",
                "option_b": "He wakes up with gum in his hair",
                "option_c": "He spills milk on himself",
                "option_d": "He loses his shoe",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "Where does Alexander say he wants to move to?",
                "option_a": "Mexico",
                "option_b": "Canada",
                "option_c": "Australia",
                "option_d": "Japan",
                "correct_answer": "c",
                "question_order": 2,
            },
            {
                "question_text": "What happens to Alexander at school?",
                "option_a": "He fails a test",
                "option_b": "His best friend says he is no longer his best friend",
                "option_c": "He gets in trouble with the teacher",
                "option_d": "He loses his lunch",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What does Alexander find in his lunch box?",
                "option_a": "A sandwich",
                "option_b": "No dessert",
                "option_c": "An apple",
                "option_d": "A note from his mom",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "What happens at the dentist's office?",
                "option_a": "Alexander gets a cavity filled",
                "option_b": "The dentist says Alexander has a cavity",
                "option_c": "Alexander gets a tooth pulled",
                "option_d": "The dentist is not there",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What does Alexander's mom tell him at the end of the day?",
                "option_a": "Tomorrow will be better",
                "option_b": "Some days are just like that",
                "option_c": "He should be more careful",
                "option_d": "He needs a nap",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What shoes does Alexander want but his mom says are sold out?",
                "option_a": "Blue sneakers",
                "option_b": "Red sneakers with white stripes",
                "option_c": "Black boots",
                "option_d": "White tennis shoes",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What happens at dinner?",
                "option_a": "Alexander burns his food",
                "option_b": "Alexander gets Lima beans which he hates",
                "option_c": "Alexander drops his plate",
                "option_d": "Alexander is not hungry",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What happens at the shoe store?",
                "option_a": "They are sold out of the shoes Alexander wants",
                "option_b": "Alexander finds his shoes but they are too small",
                "option_c": "The store is closed",
                "option_d": "Alexander loses his money",
                "correct_answer": "a",
                "question_order": 9,
            },
            {
                "question_text": "What does Alexander's mother say about bad days?",
                "option_a": "They happen to everyone",
                "option_b": "Some days are like that even in Australia",
                "option_c": "They only happen to kids",
                "option_d": "They go away with sleep",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Where the Sidewalk Ends",
        "questions": [
            {
                "question_text": "Who wrote Where the Sidewalk Ends?",
                "option_a": "Shel Silverstein",
                "option_b": "Dr. Seuss",
                "option_c": "Jack Prelutsky",
                "option_d": "Robert Frost",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What type of book is Where the Sidewalk Ends?",
                "option_a": "A novel",
                "option_b": "A collection of poems",
                "option_c": "A picture book",
                "option_d": "A comic book",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "In the poem 'Sarah Cynthia Sylvia Stout,' what does Sarah refuse to take out?",
                "option_a": "The trash",
                "option_b": "The garbage",
                "option_c": "The recycling",
                "option_d": "The compost",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "In the poem about the boy who turns into a TV, what is the message?",
                "option_a": "Watching too much TV is bad for you",
                "option_b": "TVs are dangerous",
                "option_c": "Children should play outside",
                "option_d": "Parents should limit TV time",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "What is the poem 'Hug O' War' about?",
                "option_a": "A wrestling match",
                "option_b": "Choosing hugs over fighting",
                "option_c": "A game between friends",
                "option_d": "A battle with monsters",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "In 'Smart,' what does the narrator trade his dollar for?",
                "option_a": "Three quarters",
                "option_b": "Two dimes",
                "option_c": "Five pennies",
                "option_d": "A nickel",
                "correct_answer": "a",
                "question_order": 6,
            },
            {
                "question_text": "What is the theme of many poems in Where the Sidewalk Ends?",
                "option_a": "Adventure",
                "option_b": "Imagination and humor",
                "option_c": "Sadness and loss",
                "option_d": "History",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "In the poem 'The Acrobats,' what do the acrobats do?",
                "option_a": "They fly through the air",
                "option_b": "They balance on each other",
                "option_c": "They juggle",
                "option_d": "They swing on ropes",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What does Shel Silverstein often include alongside his poems?",
                "option_a": "Photographs",
                "option_b": "His own illustrations",
                "option_c": "Music",
                "option_d": "Maps",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What happens to Sarah Cynthia Sylvia Stout in the end?",
                "option_a": "She takes out the garbage",
                "option_b": "The garbage reaches the sky",
                "option_c": "She moves away",
                "option_d": "Her mom cleans it up",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The Giving Tree",
        "questions": [
            {
                "question_text": "Who wrote The Giving Tree?",
                "option_a": "Shel Silverstein",
                "option_b": "Dr. Seuss",
                "option_c": "Eric Carle",
                "option_d": "Maurice Sendak",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What does the tree give the boy first?",
                "option_a": "Her leaves",
                "option_b": "Her apples",
                "option_c": "Her branches",
                "option_d": "Her trunk",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What does the tree give the boy when he wants to build a house?",
                "option_a": "Her apples",
                "option_b": "Her branches",
                "option_c": "Her trunk",
                "option_d": "Her leaves",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What does the tree give the boy when he wants a boat?",
                "option_a": "Her trunk",
                "option_b": "Her branches",
                "option_c": "Her roots",
                "option_d": "Her leaves",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "What is the main theme of The Giving Tree?",
                "option_a": "The importance of nature",
                "option_b": "Selfless love and giving",
                "option_c": "Growing old",
                "option_d": "Friendship",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "How does the tree feel every time she gives something to the boy?",
                "option_a": "Sad",
                "option_b": "Happy",
                "option_c": "Angry",
                "option_d": "Tired",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What does the old man (the boy grown up) need at the end of the story?",
                "option_a": "Money",
                "option_b": "A quiet place to sit and rest",
                "option_c": "A house",
                "option_d": "A boat",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What is left of the tree at the end of the story?",
                "option_a": "Just the stump",
                "option_b": "The roots",
                "option_c": "Nothing",
                "option_d": "The trunk",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "What does the tree call the boy throughout the story?",
                "option_a": "Her son",
                "option_b": "Boy",
                "option_c": "My friend",
                "option_d": "Little one",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "How does the tree feel at the very end of the story?",
                "option_a": "Sad",
                "option_b": "Happy",
                "option_c": "Lonely",
                "option_d": "Angry",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The True Story of the Three Little Pigs",
        "questions": [
            {
                "question_text": "Who tells the story in The True Story of the Three Little Pigs?",
                "option_a": "The first little pig",
                "option_b": "Alexander T. Wolf",
                "option_c": "The narrator",
                "option_d": "The pig's mother",
                "correct_answer": "b",
                "question_order": 1,
            },
            {
                "question_text": "What does the wolf say he was doing when he visited the pigs?",
                "option_a": "Trying to eat them",
                "option_b": "Borrowing a cup of sugar for his grandmother's birthday cake",
                "option_c": "Looking for shelter",
                "option_d": "Selling something",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What does the wolf say caused him to sneeze?",
                "option_a": "A cold",
                "option_b": "Allergies",
                "option_c": "Pepper",
                "option_d": "Dust",
                "correct_answer": "a",
                "question_order": 3,
            },
            {
                "question_text": "Who was the wolf trying to make a cake for?",
                "option_a": "His grandmother",
                "option_b": "His mother",
                "option_c": "His friend",
                "option_d": "Himself",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "What does the wolf say happened when he sneezed on the first pig's house?",
                "option_a": "The pig ran away",
                "option_b": "The house of straw blew down",
                "option_c": "Nothing happened",
                "option_d": "The pig laughed",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What were the first and second pigs' houses made of?",
                "option_a": "Straw and sticks",
                "option_b": "Sticks and bricks",
                "option_c": "Straw and wood",
                "option_d": "Wood and bricks",
                "correct_answer": "a",
                "question_order": 6,
            },
            {
                "question_text": "What does the wolf say about eating the first two pigs?",
                "option_a": "He was hungry",
                "option_b": "It was an accident",
                "option_c": "They were already dead so he did not want to waste them",
                "option_d": "He was provoked",
                "correct_answer": "c",
                "question_order": 7,
            },
            {
                "question_text": "What was the third pig's house made of?",
                "option_a": "Brick",
                "option_b": "Stone",
                "option_c": "Wood",
                "option_d": "Straw",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "What did the third pig say that made the wolf angry?",
                "option_a": "He insulted the wolf's grandmother",
                "option_b": "He refused to let him in",
                "option_c": "He threw something at him",
                "option_d": "He called the police",
                "correct_answer": "a",
                "question_order": 9,
            },
            {
                "question_text": "Who is the author of The True Story of the Three Little Pigs?",
                "option_a": "Jon Scieszka",
                "option_b": "Shel Silverstein",
                "option_c": "Roald Dahl",
                "option_d": "Eric Carle",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The Stinky Cheese Man and Other Fairly Stupid Tales",
        "questions": [
            {
                "question_text": "Who is the author of The Stinky Cheese Man?",
                "option_a": "Jon Scieszka",
                "option_b": "Shel Silverstein",
                "option_c": "Roald Dahl",
                "option_d": "Eric Carle",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What fairy tale is The Stinky Cheese Man based on?",
                "option_a": "The Gingerbread Man",
                "option_b": "Little Red Riding Hood",
                "option_c": "Jack and the Beanstalk",
                "option_d": "The Three Bears",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "What happens when someone smells the Stinky Cheese Man?",
                "option_a": "They laugh",
                "option_b": "They run away",
                "option_c": "They faint",
                "option_d": "They cry",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What is the book a collection of?",
                "option_a": "Original fairy tales",
                "option_b": "Fractured fairy tales",
                "option_c": "Ghost stories",
                "option_d": "Animal stories",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "In the story, what does the Little Red Hen do?",
                "option_a": "Bakes bread",
                "option_b": "Tells the narrator she is too busy to be in a story",
                "option_c": "Runs away",
                "option_d": "Fights the wolf",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What happens to the narrator at the end of the book?",
                "option_a": "He becomes a character",
                "option_b": "He gets eaten by the Stinky Cheese Man",
                "option_c": "He runs away",
                "option_d": "He finishes the book",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What fairy tale character appears in a story with a really long title?",
                "option_a": "Cinderumpelstiltskin",
                "option_b": "Snow White",
                "option_c": "Sleeping Beauty",
                "option_d": "Rapunzel",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "What makes the tales in this book different from traditional fairy tales?",
                "option_a": "They have happy endings",
                "option_b": "They are humorous twists on the originals",
                "option_c": "They are very short",
                "option_d": "They have no words",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "Who does the Jack in the beanstalk story encounter?",
                "option_a": "A giant",
                "option_b": "The Giant at the top of the beanstalk",
                "option_c": "A witch",
                "option_d": "A dragon",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What is the overall tone of The Stinky Cheese Man?",
                "option_a": "Scary",
                "option_b": "Silly and humorous",
                "option_c": "Sad",
                "option_d": "Educational",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The Polar Express",
        "questions": [
            {
                "question_text": "Where does the Polar Express take the boy?",
                "option_a": "To the North Pole",
                "option_b": "To the South Pole",
                "option_c": "To a toy factory",
                "option_d": "To a winter wonderland",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What night does the Polar Express arrive?",
                "option_a": "Thanksgiving night",
                "option_b": "Christmas Eve",
                "option_c": "New Year's Eve",
                "option_d": "Halloween night",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What does the boy ask Santa for as his first gift of Christmas?",
                "option_a": "A toy train",
                "option_b": "A bell from Santa's sleigh",
                "option_c": "A bicycle",
                "option_d": "A puppy",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What happens to the bell that Santa gives the boy?",
                "option_a": "It breaks",
                "option_b": "He loses it through a hole in his pocket",
                "option_c": "It is stolen",
                "option_d": "It stops ringing",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "What does the boy find on Christmas morning?",
                "option_a": "The bell under the tree",
                "option_b": "A new train set",
                "option_c": "Nothing",
                "option_d": "A letter from Santa",
                "correct_answer": "a",
                "question_order": 5,
            },
            {
                "question_text": "Who can hear the bell ring?",
                "option_a": "Everyone",
                "option_b": "Only those who truly believe",
                "option_c": "Only children",
                "option_d": "Only adults",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "Who wrote The Polar Express?",
                "option_a": "Chris Van Allsburg",
                "option_b": "Dr. Seuss",
                "option_c": "Maurice Sendak",
                "option_d": "Eric Carle",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "What kind of train is the Polar Express?",
                "option_a": "A steam train",
                "option_b": "A passenger train",
                "option_c": "A freight train",
                "option_d": "A subway train",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What does the boy's friend Sarah do with the bell at the end?",
                "option_a": "She rings it",
                "option_b": "She cannot hear it",
                "option_c": "She steals it",
                "option_d": "She breaks it",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What is the main theme of The Polar Express?",
                "option_a": "The magic of Christmas and the power of belief",
                "option_b": "The importance of giving",
                "option_c": "Trains are magical",
                "option_d": "Winter is wonderful",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Jumanji",
        "questions": [
            {
                "question_text": "Who wrote Jumanji?",
                "option_a": "Chris Van Allsburg",
                "option_b": "Dr. Seuss",
                "option_c": "Maurice Sendak",
                "option_d": "Eric Carle",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What kind of game do the children find in Jumanji?",
                "option_a": "A video game",
                "option_b": "A board game",
                "option_c": "A card game",
                "option_d": "A sports game",
                "correct_answer": "b",
                "question_order": 2,
            },
            {
                "question_text": "What happens when the children play the game?",
                "option_a": "They win prizes",
                "option_b": "Jungle animals and dangers come to life",
                "option_c": "They travel through time",
                "option_d": "Nothing happens",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What are the names of the two children in Jumanji?",
                "option_a": "Judy and Peter",
                "option_b": "Jack and Annie",
                "option_c": "Hansel and Gretel",
                "option_d": "Tom and Lucy",
                "correct_answer": "a",
                "question_order": 4,
            },
            {
                "question_text": "Where do the children find the Jumanji game?",
                "option_a": "In their attic",
                "option_b": "In the park under a tree",
                "option_c": "At a store",
                "option_d": "In the basement",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What animal comes out of the game and causes chaos?",
                "option_a": "A lion",
                "option_b": "A monkey",
                "option_c": "An elephant",
                "option_d": "A snake",
                "correct_answer": "a",
                "question_order": 6,
            },
            {
                "question_text": "How do the children make the jungle animals go away?",
                "option_a": "They finish the game by reaching the end",
                "option_b": "They close the box",
                "option_d": "They throw the game away",
                "option_c": "They call for help",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "What is the theme of Jumanji?",
                "option_a": "Games are dangerous",
                "option_b": "Actions have consequences and you must finish what you start",
                "option_c": "Jungle animals are scary",
                "option_d": "Always follow instructions",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "What do the children do with the game at the end?",
                "option_a": "They keep it",
                "option_b": "They return it to the park",
                "option_c": "They destroy it",
                "option_d": "They hide it",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What does the game require players to do?",
                "option_a": "Answer trivia questions",
                "option_b": "Roll dice and read the instructions that come to life",
                "option_c": "Solve puzzles",
                "option_d": "Race to the finish",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "The Princess and the Goblin",
        "questions": [
            {
                "question_text": "Who wrote The Princess and the Goblin?",
                "option_a": "George MacDonald",
                "option_b": "C.S. Lewis",
                "option_c": "J.R.R. Tolkien",
                "option_d": "Lewis Carroll",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "What is the name of the princess in the story?",
                "option_a": "Irene",
                "option_b": "Aurora",
                "option_c": "Elara",
                "option_d": "Sarah",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "Who is the miner boy that befriends the princess?",
                "option_a": "Curdie",
                "option_b": "Peter",
                "option_c": "Hans",
                "option_d": "Fritz",
                "correct_answer": "a",
                "question_order": 3,
            },
            {
                "question_text": "Where do the goblins live?",
                "option_a": "In the mountains",
                "option_b": "Underground in caves beneath the kingdom",
                "option_c": "In the forest",
                "option_d": "In a castle",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "Who is the mysterious old woman who helps Irene?",
                "option_a": "Her grandmother",
                "option_b": "A fairy godmother",
                "option_c": "A witch",
                "option_d": "An angel",
                "correct_answer": "a",
                "question_order": 5,
            },
            {
                "question_text": "What does Irene's grandmother give her to protect her?",
                "option_a": "A magic sword",
                "option_b": "A magic thread",
                "option_c": "A magic ring",
                "option_d": "A magic cloak",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What do the goblins plan to do?",
                "option_a": "Steal the kingdom's gold",
                "option_b": "Capture the princess and flood the mines",
                "option_c": "Attack the castle",
                "option_d": "Kidnap Curdie",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What does Curdie discover about the goblins?",
                "option_a": "They are afraid of light",
                "option_b": "They are weak to rhymes and songs",
                "option_c": "They cannot swim",
                "option_d": "They are blind",
                "correct_answer": "b",
                "question_order": 8,
            },
            {
                "question_text": "Where does Irene's grandmother live?",
                "option_a": "In the castle",
                "option_b": "In a room high in the castle tower",
                "option_c": "In the forest",
                "option_d": "In the mines",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What is the main theme of The Princess and the Goblin?",
                "option_a": "Courage and faith overcome evil",
                "option_b": "Greed leads to ruin",
                "option_c": "Love conquers all",
                "option_d": "Appearances can be deceiving",
                "correct_answer": "a",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "Amber Brown Is Not a Crayon",
        "questions": [
            {
                "question_text": "Who is the main character in Amber Brown Is Not a Crayon?",
                "option_a": "Amber Brown",
                "option_b": "Amber Smith",
                "option_c": "Amy Brown",
                "option_d": "Anna Brown",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "Who is Amber's best friend?",
                "option_a": "Justin Daniels",
                "option_b": "Ryan Miller",
                "option_c": "Tom Wilson",
                "option_d": "David Clark",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "What is happening to Justin that upsets Amber?",
                "option_a": "He is moving to Alabama",
                "option_b": "He is changing schools",
                "option_c": "He is moving away",
                "option_d": "He is getting a new sibling",
                "correct_answer": "a",
                "question_order": 3,
            },
            {
                "question_text": "What are Amber's parents going through?",
                "option_a": "They are moving",
                "option_b": "They are getting a divorce",
                "option_c": "They are fighting",
                "option_d": "They are working too much",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "Who wrote Amber Brown Is Not a Crayon?",
                "option_a": "Paula Danziger",
                "option_b": "Judy Blume",
                "option_c": "Beverly Cleary",
                "option_d": "Roald Dahl",
                "correct_answer": "a",
                "question_order": 5,
            },
            {
                "question_text": "What grade are Amber and Justin in?",
                "option_a": "Second grade",
                "option_b": "Third grade",
                "option_c": "Fourth grade",
                "option_d": "Fifth grade",
                "correct_answer": "b",
                "question_order": 6,
            },
            {
                "question_text": "What do Amber and Justin fight about?",
                "option_a": "Who gets to be line leader",
                "option_b": "A ball",
                "option_c": "Homework",
                "option_d": "Who is smarter",
                "correct_answer": "b",
                "question_order": 7,
            },
            {
                "question_text": "What does Amber call herself because of her name?",
                "option_a": "Amber the crayon",
                "option_b": "Amber the gem",
                "option_c": "Amber the color",
                "option_d": "Amber the fossil",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "How does Amber feel about Justin leaving?",
                "option_a": "She is happy",
                "option_b": "She is very sad and upset",
                "option_c": "She does not care",
                "option_d": "She is excited for him",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What does Amber do to remember Justin before he leaves?",
                "option_a": "She gives him a gift",
                "option_b": "She writes him a letter",
                "option_c": "She takes a photo with him",
                "option_d": "They trade something special",
                "correct_answer": "d",
                "question_order": 10,
            },
        ],
    },
    {
        "title": "A Long Walk to Water",
        "questions": [
            {
                "question_text": "Who is the main male character in A Long Walk to Water?",
                "option_a": "Salva Dut",
                "option_b": "Nya",
                "option_c": "Daniel",
                "option_d": "Michael",
                "correct_answer": "a",
                "question_order": 1,
            },
            {
                "question_text": "Who is the girl whose story is told alongside Salva's?",
                "option_a": "Nya",
                "option_b": "Mary",
                "option_c": "Grace",
                "option_d": "Asha",
                "correct_answer": "a",
                "question_order": 2,
            },
            {
                "question_text": "In which country does the story take place?",
                "option_a": "Ethiopia",
                "option_b": "Sudan",
                "option_c": "Kenya",
                "option_d": "Egypt",
                "correct_answer": "b",
                "question_order": 3,
            },
            {
                "question_text": "What is Nya's daily task?",
                "option_a": "Cooking for her family",
                "option_b": "Walking to fetch water",
                "option_c": "Tending to animals",
                "option_d": "Going to school",
                "correct_answer": "b",
                "question_order": 4,
            },
            {
                "question_text": "What war forces Salva to flee his village?",
                "option_a": "World War II",
                "option_b": "The Sudanese Civil War",
                "option_c": "A tribal conflict",
                "option_d": "A border dispute",
                "correct_answer": "b",
                "question_order": 5,
            },
            {
                "question_text": "What does Salva's uncle tell him to help him keep going?",
                "option_a": "One step at a time",
                "option_b": "Never give up",
                "option_c": "Think about home",
                "option_d": "Stay strong",
                "correct_answer": "a",
                "question_order": 6,
            },
            {
                "question_text": "Where does Salva eventually end up living?",
                "option_a": "America",
                "option_b": "England",
                "option_c": "Australia",
                "option_d": "Kenya",
                "correct_answer": "a",
                "question_order": 7,
            },
            {
                "question_text": "Who wrote A Long Walk to Water?",
                "option_a": "Linda Sue Park",
                "option_b": "Katherine Applegate",
                "option_c": "Pam Munoz Ryan",
                "option_d": "Sharon Creech",
                "correct_answer": "a",
                "question_order": 8,
            },
            {
                "question_text": "What does Salva do when he grows up?",
                "option_a": "He becomes a teacher",
                "option_b": "He builds wells in Sudan",
                "option_c": "He joins the army",
                "option_d": "He becomes a doctor",
                "correct_answer": "b",
                "question_order": 9,
            },
            {
                "question_text": "What connects Nya's and Salva's stories at the end of the book?",
                "option_a": "They are related",
                "option_b": "Salva's organization builds a well in Nya's village",
                "option_c": "They meet each other",
                "option_d": "They live in the same town",
                "correct_answer": "b",
                "question_order": 10,
            },
        ],
    },
]

with open("/home/user/workspace/bookquiz/questions_batch_1.json", "w") as f:
    json.dump(books, f, indent=2)

print(f"Wrote {len(books)} books with {sum(len(b['questions']) for b in books)} questions")

# Verify answer distribution
from collections import Counter
all_answers = []
for book in books:
    for q in book["questions"]:
        all_answers.append(q["correct_answer"])
print(f"Answer distribution: {Counter(all_answers)}")

# Verify each book has 10 questions
for book in books:
    assert len(book["questions"]) == 10, f"{book['title']} has {len(book['questions'])} questions"
    for i, q in enumerate(book["questions"]):
        assert q["question_order"] == i + 1, f"{book['title']} Q{i+1} has wrong order"
print("All validations passed!")
