import {test} from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {BoardQuestGame} from '../server/boardQuestEngine';
import {registerBoardQuestRoutes} from '../server/boardQuest';
import {BANK,BOARD_LAST_SPACE,TIMING,moveLandingAt,rpsWinner,cueStage,type Player,type Hand} from '../shared/boardQuest';
const human=(id:number):Player=>({id,name:'Reader '+id,characterId:'robin-hood',team:'blue',space:0,strikes:0,shield:0,power:0,out:false,bot:false});
function game(){const g=new BoardQuestGame('123456',human(10),'K-2',()=>0);g.add(human(20));g.start(10,1000);for(const p of g.view.players.filter(p=>!p.bot))g.tutorialFinish(p.id,g.view.tutorialId,'skipped',1000);g.tick(25000);for(const p of g.view.players)g.openingChoose(p.id,'rock',25001);g.tick(25001+TIMING.openingResultHold);return g;}
function roll(g:BoardQuestGame,from:number,raw:number=1){g.view.players[0].space=from;(g as any).random=()=> (raw-1)/6+.001;g.answer(10,g.view.question!.id,1,2000);return g.view.cue!;}
test('server owns rolls, blocks spectators, duplicate answers, and premature replay',()=>{const g=game();assert.throws(()=>g.answer(20,g.view.question!.id,1,2000));assert.throws(()=>g.start(10,2000));const c=roll(g,0,6);assert.equal(c.raw,6);assert.equal(c.steps,6);assert.throws(()=>g.answer(10,1,1,2001));assert.equal(cueStage(c,c.startAt),'roll');assert.equal(cueStage(c,c.startAt+TIMING.roll),'reveal');assert.equal(cueStage(c,moveLandingAt(c)),'landing');});
test('all clients get the same cue and timestamp; rewards apply once after landing',()=>{const g=game();const c=roll(g,6);const when=moveLandingAt(c)+TIMING.landing;g.tick(when-1);assert.equal(g.view.scores.blue,0);const a=g.snapshot(when),b=g.snapshot(when);assert.deepEqual(a,b);assert.equal(a.scores.blue,50);g.tick(when+100);assert.equal(g.view.scores.blue,50);assert.equal(g.view.players[0].space,7);});
test('steal transfers only available points and shields block strikes',()=>{const g=game();g.view.scores.gold=12;const c=roll(g,1);g.tick(moveLandingAt(c)+TIMING.landing);assert.deepEqual(g.view.scores,{blue:12,gold:0});const h=game();h.view.players[0].shield=1;h.answer(10,h.view.question!.id,0,2000);assert.equal(h.view.players[0].strikes,0);assert.equal(h.view.players[0].shield,0);assert.equal(h.view.cue?.blocked,true);});
test('power bonus is distinct from six-sided die and movement caps at finish',()=>{const g=game();g.view.players[0].power=1;const c=roll(g,BOARD_LAST_SPACE-2,6);assert.equal(c.raw,6);assert.equal(c.bonus,2);assert.equal(c.steps,8);assert.equal(c.to,BOARD_LAST_SPACE);assert.equal(g.view.players[0].power,0);g.tick(moveLandingAt(c)+TIMING.landing+TIMING.reward);assert.equal(g.view.phase,'finished');assert.equal(g.view.winner,g.view.teamNames.blue);g.start(10,30000);assert.equal(g.view.phase,'tutorial');assert.equal(g.view.players[0].space,0);assert.deepEqual(g.view.scores,{blue:0,gold:0});});
test('RPS is private until simultaneous reveal; duplicate choice cannot change a hand',()=>{const g=game(),c=roll(g,4),when=moveLandingAt(c)+TIMING.landing;g.tick(when);assert.equal(g.view.phase,'rps');assert.equal(g.view.cue?.rival,20);g.choose(10,'rock',c.id,when+1);assert.equal((g.snapshot(when+2) as any).choices,undefined);assert.equal(g.snapshot(when+2).cue?.hands,undefined);g.choose(10,'paper',c.id,when+3);g.choose(20,'scissors',c.id,when+4);const cue=g.view.cue!;assert.equal(cue.kind,'duel');assert.equal(g.snapshot(cue.startAt+TIMING.countdown-1).cue?.hands,undefined);const revealed=g.snapshot(cue.startAt+TIMING.countdown);assert.deepEqual(revealed.cue?.hands,['rock','scissors']);assert.equal(revealed.cue?.duelWinner,10);assert.equal(revealed.players[1].strikes,1);g.tick(cue.startAt+TIMING.countdown+1);assert.equal(g.view.players[1].strikes,1);});
test('RPS timeout resolves absent players and ties do not add strikes',()=>{const g=game(),c=roll(g,4);g.tick(moveLandingAt(c)+TIMING.landing);g.tick(g.view.rpsDeadline);assert.equal(g.view.cue?.kind,'duel');const cue=g.view.cue!;g.tick(cue.startAt+TIMING.countdown);assert.equal(g.view.cue?.duelWinner,null);assert.equal(g.view.players.reduce((a,p)=>a+p.strikes,0),0);});
test('all RPS pairings follow the real rules',()=>{const hands:Hand[]=['rock','paper','scissors'];for(const a of hands)for(const b of hands){const winner=rpsWinner(a,b);if(a===b)assert.equal(winner,null);else assert.equal(winner===0?rpsWinner(b,a):winner,1);}});
test('join/reconnect preserve roster; full or running room rejects new members',()=>{const g=game();g.add(human(10));assert.equal(g.view.players.length,6);assert.throws(()=>g.add(human(30)));const fresh=new BoardQuestGame('444444',human(10),'K-2');for(let id=11;id<16;id++)fresh.add(human(id));assert.throws(()=>fresh.add(human(16)));});
test('shared HTTP room enforces membership and turn ownership across two clients',async(t)=>{let clock=Date.now();t.mock.method(Date,'now',()=>clock);const app=express();app.use(express.json());registerBoardQuestRoutes(app,(req:any,res,next)=>{const id=Number(req.headers['x-test-user']);if(!id)return res.status(401).end();req.user={id,role:'student',displayName:'Reader '+id};next();});const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));try{const base=`http://127.0.0.1:${(server.address() as any).port}/api/board-quest/rooms`;const call=async(path:string,id:number,body?:any)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'x-test-user':String(id),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};const created=await call('',10,{level:'K-2'}),code=created.data.code;assert.equal((await call('/'+code,20)).status,409);await call('/'+code+'/join',20,{});await call('/'+code+'/action',10,{type:'settings',fillCpu:false});assert.equal((await call('/'+code+'/action',20,{type:'start'})).status,409);const start=await call('/'+code+'/action',10,{type:'start'});assert.equal(start.data.phase,'tutorial');await call('/'+code+'/action',10,{type:'tutorial-ready',tutorialId:start.data.tutorialId,result:'skipped'});assert.equal((await call('/'+code,20)).data.phase,'tutorial');await call('/'+code+'/action',20,{type:'tutorial-ready',tutorialId:start.data.tutorialId,result:'finished'});clock+=25000;await call('/'+code,10);await call('/'+code+'/action',10,{type:'opening-hand',hand:'rock'});await call('/'+code+'/action',20,{type:'opening-hand',hand:'rock'});clock+=TIMING.openingCountdown;await call('/'+code,10);clock+=TIMING.openingResultHold;const started=(await call('/'+code,10)).data;const turnId=started.players[started.turn].id;assert.ok(started.question);const q=started.question;assert.equal(q.correct,undefined);const right=BANK['K-2'].find(x=>x.q===q.q)!.correct;const answer=await call('/'+code+'/action',turnId,{type:'answer',questionId:q.id,choice:right});const viewer=await call('/'+code,20);assert.deepEqual(answer.data.cue,viewer.data.cue);assert.equal((await call('/'+code+'/action',turnId===10?20:10,{type:'answer',questionId:q.id,choice:right})).status,409);}finally{server.close();server.closeAllConnections();}});
test('every numbered dice face settles toward the viewing camera',async()=>{const {dieOrientation,DIE_VALUES,DIE_NORMALS}=await import('../client/src/components/board-quest/BoardScene');const THREE=await import('three');for(let value=1;value<=6;value++){const normal=new THREE.Vector3(...DIE_NORMALS[DIE_VALUES.indexOf(value)]).applyQuaternion(dieOrientation(value));assert.ok(normal.distanceTo(new THREE.Vector3(0,.4,1).normalize())<.00001);}});
