import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,Dices,Shield,Trophy,Zap} from "lucide-react";
import * as THREE from "three";
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader.js";
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls.js";
import {getAvatarCharacter} from "@/lib/avatarCharacters";

type Level="K-2"|"3-5"|"6-8"|"9-12"; type Team="blue"|"gold";
type P={name:string;characterId:string;team:Team;space:number;strikes:number;shield:number;power:number;out:boolean}; type Q={q:string;a:string[];correct:number};
const BANK:Record<Level,Q[]>={"K-2":[{q:"What is 4 + 3?",a:["6","7","8","9"],correct:1},{q:"Which word rhymes with cat?",a:["dog","hat","sun","red"],correct:1},{q:"What is 10 - 2?",a:["6","7","8","9"],correct:2}],"3-5":[{q:"What is 8 × 6?",a:["42","46","48","54"],correct:2},{q:"Which is a synonym for happy?",a:["Glad","Angry","Tiny","Slow"],correct:0},{q:"What is 3/4 of 20?",a:["10","12","15","18"],correct:2}],"6-8":[{q:"Solve: 3x + 5 = 20",a:["3","5","7","15"],correct:1},{q:"What is 25% of 80?",a:["10","20","25","40"],correct:1},{q:"Which word is an adjective?",a:["Run","Quickly","Bright","Under"],correct:2}],"9-12":[{q:"Solve x² - 9 = 0. Positive solution?",a:["1","3","6","9"],correct:1},{q:"What is the slope between (0,2) and (4,10)?",a:["1","2","4","8"],correct:1},{q:"Which is a metaphor?",a:["Cold as ice","Time is a thief","He ran quickly","The dog barked"],correct:1}]};
const EVENTS=["points","safe","steal","shield","power","rps","bonus"] as const;
const fresh=():P[]=>[{name:"You",characterId:"robin-hood",team:"blue",space:0,strikes:0,shield:0,power:0,out:false},{name:"Robin",characterId:"robin-hood",team:"gold",space:0,strikes:0,shield:0,power:0,out:false},{name:"Alice",characterId:"alice",team:"blue",space:0,strikes:0,shield:0,power:0,out:false},{name:"Arthur",characterId:"king-arthur",team:"gold",space:0,strikes:0,shield:0,power:0,out:false},{name:"Sherlock",characterId:"sherlock-holmes",team:"blue",space:0,strikes:0,shield:0,power:0,out:false},{name:"Hercules",characterId:"hercules",team:"gold",space:0,strikes:0,shield:0,power:0,out:false}];
function pos(i:number){const row=Math.floor(i/7),c=i%7,col=row%2?6-c:c;return new THREE.Vector3((col-3)*5,1,(row-1.5)*6)}
function tag(text:string,bg:string){const c=document.createElement("canvas");c.width=512;c.height=128;const x=c.getContext("2d")!;x.fillStyle=bg;x.beginPath();x.roundRect(8,8,496,112,28);x.fill();x.fillStyle="#fff";x.font="800 38px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText(text,256,64);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(3.6,.9,1);return s}
export default function BoardGameWorld(){
 const timers=useRef<Set<number>>(new Set());
 const later=(fn:()=>void,ms:number)=>{const id=window.setTimeout(()=>{timers.current.delete(id);fn()},ms);timers.current.add(id);return id};
 const clearTimers=()=>{timers.current.forEach(id=>{clearTimeout(id);clearInterval(id)});timers.current.clear()};
 useEffect(()=>()=>clearTimers(),[]);
 const [round,setRound]=useState(0),[renderError,setRenderError]=useState(false);
 const dieRef=useRef<THREE.Mesh|null>(null);
 const mount=useRef<HTMLDivElement>(null),roots=useRef<THREE.Group[]>([]),mixers=useRef<THREE.AnimationMixer[]>([]),moveTargets=useRef<(THREE.Vector3|null)[]>([]); const [level,setLevel]=useState<Level|null>(null),[players,setPlayers]=useState<P[]>(fresh),[started,setStarted]=useState(false),[turn,setTurn]=useState(0),[blue,setBlue]=useState(0),[gold,setGold]=useState(0),[question,setQuestion]=useState<Q|null>(null),[dice,setDice]=useState<number|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("Choose a learning level to begin."),[winner,setWinner]=useState<string|null>(null); const current=players[turn];
 const leave=()=>window.location.replace("/#/worlds"); const start=()=>{clearTimers();setRound(v=>v+1);setBusy(false);setRenderError(false);setPlayers(fresh());setBlue(0);setGold(0);setTurn(0);setWinner(null);setDice(null);setQuestion(null);setMessage("Your turn — answer a question to unlock the dice!");setStarted(true)};
 useEffect(()=>{if(!started||!mount.current)return;const host=mount.current,scene=new THREE.Scene();scene.background=new THREE.Color(0x07162b);scene.fog=new THREE.Fog(0x07162b,45,95);const camera=new THREE.PerspectiveCamera(52,host.clientWidth/host.clientHeight,.1,150);camera.position.set(0,30,35);let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true})}catch{setRenderError(true);return}let disposed=false;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute("aria-label","3D Board Quest world — drag to rotate, pinch or scroll to zoom");host.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);controls.minDistance=15;controls.maxDistance=55;controls.maxPolarAngle=Math.PI*.48;scene.add(new THREE.HemisphereLight(0xbfe8ff,0x1b3b2b,2.8));const sun=new THREE.DirectionalLight(0xffe7b0,4);sun.position.set(-20,35,20);sun.castShadow=true;scene.add(sun);
 const base=new THREE.Mesh(new THREE.CylinderGeometry(27,30,2.5,48),new THREE.MeshStandardMaterial({color:0x174c3a,roughness:.85}));base.position.y=-1.7;base.receiveShadow=true;scene.add(base);const water=new THREE.Mesh(new THREE.CircleGeometry(70,64),new THREE.MeshStandardMaterial({color:0x087aa5,roughness:.25,metalness:.1}));water.rotation.x=-Math.PI/2;water.position.y=-3;scene.add(water);
 const colors=[0x22c55e,0x64748b,0xef4444,0x3b82f6,0xa855f7,0xf97316,0xfacc15];for(let i=0;i<28;i++){const p=pos(i),e=i%EVENTS.length;const tile=new THREE.Mesh(new THREE.BoxGeometry(4.35,.7,5.1),new THREE.MeshStandardMaterial({color:colors[e],roughness:.48,metalness:.08,emissive:colors[e],emissiveIntensity:.12}));tile.position.copy(p);tile.castShadow=true;tile.receiveShadow=true;scene.add(tile);const n=tag(String(i+1),"#0f172a");n.position.set(p.x,1.55,p.z);n.scale.set(1.25,.31,1);scene.add(n)}
 const finish=tag("🏆 FINISH","#6d28d9");const fp=pos(27);finish.position.set(fp.x,5,fp.z);finish.scale.set(4.5,1.1,1);scene.add(finish);
 for(let i=0;i<18;i++){const a=i/18*Math.PI*2,x=Math.cos(a)*25,z=Math.sin(a)*25;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.22,.34,2.2,7),new THREE.MeshStandardMaterial({color:0x704323}));trunk.position.set(x,0,z);scene.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.4,3.3,8),new THREE.MeshStandardMaterial({color:0x23804c}));crown.position.set(x,2.4,z);scene.add(crown)}
 const die=new THREE.Mesh(new THREE.BoxGeometry(2.4,2.4,2.4),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.28,metalness:.1}));die.position.set(0,5,0);die.castShadow=true;scene.add(die);die.userData.spin=0;dieRef.current=die;
 roots.current=[];mixers.current=[];moveTargets.current=[];const loader=new GLTFLoader();players.forEach((p,i)=>{const root=new THREE.Group();const pp=pos(0);root.position.set(pp.x+(i%3-1)*.75,1.3,pp.z+(Math.floor(i/3)-.5)*.8);scene.add(root);roots.current[i]=root;moveTargets.current[i]=null;const name=tag(p.name,p.team==="blue"?"#075985":"#a16207");name.position.y=3.5;name.scale.set(2.5,.62,1);root.add(name);loader.load(getAvatarCharacter(p.characterId).modelPath,g=>{if(disposed)return;const model=g.scene,b=new THREE.Box3().setFromObject(model),size=b.getSize(new THREE.Vector3());model.scale.setScalar(2.7/Math.max(.01,size.y));model.updateMatrixWorld();const bb=new THREE.Box3().setFromObject(model);model.position.y=-bb.min.y;model.traverse(o=>{if((o as THREE.Mesh).isMesh)(o as THREE.Mesh).castShadow=true});root.add(model);if(g.animations.length){const m=new THREE.AnimationMixer(model);mixers.current.push(m);root.userData.mixer=m;root.userData.clips=g.animations;const idle=g.animations.find(a=>/idle/i.test(a.name))||g.animations[0];root.userData.action=m.clipAction(idle);root.userData.action.play()}})});
 let raf=0;const clock=new THREE.Clock();const animate=()=>{const dt=Math.min(.04,clock.getDelta());controls.update();roots.current.forEach((root,i)=>{const target=moveTargets.current[i];if(target){const d=target.clone().sub(root.position);d.y=0;if(d.length()>.12){root.rotation.y=Math.atan2(d.x,d.z);root.position.addScaledVector(d.normalize(),dt*7);const clips=root.userData.clips as THREE.AnimationClip[]|undefined,m=root.userData.mixer as THREE.AnimationMixer|undefined;if(clips&&m&&!root.userData.walking){root.userData.action?.fadeOut(.15);const walk=clips.find(a=>/walk|run/i.test(a.name));if(walk){root.userData.action=m.clipAction(walk).reset().fadeIn(.15).play();root.userData.walking=true}}}else{root.position.x=target.x;root.position.z=target.z;moveTargets.current[i]=null;if(root.userData.walking){const idle=root.userData.clips?.find((a:THREE.AnimationClip)=>/idle/i.test(a.name));if(idle&&root.userData.mixer){root.userData.action?.fadeOut(.15);root.userData.action=root.userData.mixer.clipAction(idle).reset().fadeIn(.15).play()}}root.userData.walking=false}}});mixers.current.forEach(m=>m.update(dt));if(die.userData.spin>0){die.rotation.x+=dt*8;die.rotation.y+=dt*10;die.userData.spin-=dt}renderer.render(scene,camera);raf=requestAnimationFrame(animate)};animate();const resize=()=>{camera.aspect=host.clientWidth/Math.max(1,host.clientHeight);camera.fov=camera.aspect<1?75:52;camera.position.set(0,camera.aspect<1?40:30,camera.aspect<1?45:35);camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};resize();window.addEventListener("resize",resize);return()=>{disposed=true;cancelAnimationFrame(raf);window.removeEventListener("resize",resize);controls.dispose();mixers.current.forEach(m=>m.stopAllAction());scene.traverse(o=>{const mesh=o as THREE.Mesh;mesh.geometry?.dispose();const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];materials.forEach(material=>{if(!material)return;Object.values(material).forEach(value=>{if(value instanceof THREE.Texture)value.dispose()});material.dispose()})});renderer.dispose();host.replaceChildren()}},[started,round]);
 useEffect(()=>{if(!started)return;players.forEach((p,i)=>{const root=roots.current[i];if(root){root.visible=!p.out;const t=pos(p.space);moveTargets.current[i]=new THREE.Vector3(t.x+(i%3-1)*.6,root.position.y,t.z+(Math.floor(i/3)-.5)*.65)}})},[players,started]);
 const next=(ps:P[])=>{const alive=ps.filter(p=>!p.out);if(!alive.some(p=>p.team==="blue")||!alive.some(p=>p.team==="gold")){setWinner(alive.length?(alive[0].team==="blue"?"BLUE":"GOLD")+" TEAM":"NEITHER TEAM");setBusy(false);setQuestion(null);return}let n=(turn+1)%ps.length;for(let i=0;i<ps.length&&ps[n].out;i++)n=(n+1)%ps.length;setTurn(n);setDice(null);setQuestion(null);setBusy(false);setMessage(ps[n].name+"'s turn — answer to roll!")};
 const event=(ps:P[],idx:number)=>{const p=ps[idx],e=EVENTS[p.space%EVENTS.length];if(e==="points"){p.team==="blue"?setBlue(v=>v+50):setGold(v=>v+50);setMessage("🎉 +50 team points!")}else if(e==="steal"){if(p.team==="blue"){setBlue(v=>v+30);setGold(v=>Math.max(0,v-30))}else{setGold(v=>v+30);setBlue(v=>Math.max(0,v-30))}setMessage("⚡ Stole 30 points!")}else if(e==="shield"){p.shield++;setMessage("🛡️ Strike shield collected!")}else if(e==="power"){p.power++;setMessage("⚡ Power-up: +2 next roll!")}else if(e==="bonus"){p.team==="blue"?setBlue(v=>v+100):setGold(v=>v+100);setMessage("⭐ Jackpot +100!")}else if(e==="rps"){const rival=ps.find(x=>x.team!==p.team&&!x.out);if(rival){if(Math.random()>.5){rival.strikes++;if(rival.strikes>=3)rival.out=true;setMessage("✊ RPS win — opponent gets a strike!")}else{p.strikes++;if(p.strikes>=3)p.out=true;setMessage("✋ RPS loss — strike!")}}}else setMessage("😌 Safe space.");setPlayers([...ps]);if(p.space>=27){setWinner((p.team==="blue"?"BLUE":"GOLD")+" TEAM");setBusy(false);return}later(()=>next(ps),1200)};
 const ask=()=>{if(!level||busy||winner)return;const b=BANK[level];setQuestion(b[Math.floor(Math.random()*b.length)]);setMessage("Get it right to roll!")};
 const answer=(choice:number)=>{if(!question||busy)return;setBusy(true);setQuestion(null);const ps=players.map(p=>({...p})),p=ps[turn];if(choice!==question.correct){if(p.shield){p.shield--;setMessage("🛡️ Shield blocked the strike!")}else{p.strikes++;setMessage(`❌ Strike ${p.strikes} of 3`);if(p.strikes>=3){p.out=true;setMessage(`❌ ${p.name} is out!`)}}setPlayers(ps);later(()=>next(ps),1100);return}const raw=1+Math.floor(Math.random()*6),roll=Math.min(8,raw+(p.power?2:0));p.power=0;setDice(roll);setMessage(`🎲 ${p.name} rolled ${roll}!`);if(dieRef.current)dieRef.current.userData.spin=1;let step=0;const timer=window.setInterval(()=>{step++;p.space=Math.min(27,p.space+1);setPlayers([...ps]);if(step>=roll||p.space>=27){clearInterval(timer);timers.current.delete(timer);later(()=>event(ps,turn),650)}},520);timers.current.add(timer)};
 useEffect(()=>{if(!started||winner||busy||turn===0)return;
   const id=later(()=>{if(question){answer(Math.random()<.7?question.correct:(question.correct+1)%question.a.length)}else{ask()}},question?1000:700);
   return()=>{clearTimeout(id);timers.current.delete(id)};
 },[started,turn,question,busy,winner,round]);
 const counts=useMemo(()=>({b:players.filter(p=>p.team==="blue"&&!p.out).length,g:players.filter(p=>p.team==="gold"&&!p.out).length}),[players]);
 if(!started)return <main className="min-h-[100dvh] bg-gradient-to-b from-sky-950 via-indigo-950 to-violet-950 text-white flex items-center justify-center p-5"><button onClick={leave} className="fixed left-4 top-4 z-50 rounded-xl bg-black/50 px-4 py-3 font-black"><ArrowLeft className="inline h-5"/> Worlds</button><section className="max-w-3xl w-full text-center"><div className="text-7xl">🎲</div><h1 className="text-4xl sm:text-6xl font-black">A.R.I.S.E. BOARD QUEST 3D</h1><p className="mt-3 text-cyan-100">Your avatar IS your game piece.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-7">{(["K-2","3-5","6-8","9-12"] as Level[]).map(l=><button key={l} onClick={()=>setLevel(l)} className={`rounded-2xl border-2 p-5 text-xl font-black ${level===l?"border-white bg-cyan-500":"border-white/20 bg-white/10"}`}>{l}</button>)}</div><button disabled={!level} onClick={start} className="mt-7 rounded-2xl bg-amber-300 px-10 py-5 text-2xl font-black text-slate-950 disabled:opacity-40">ENTER BOARD WORLD</button></section></main>;
 return <main className="fixed inset-0 z-[20000] bg-slate-950 text-white overflow-hidden">{renderError&&<div role="alert" className="absolute inset-0 z-50 flex flex-col items-center justify-center gap-4 bg-slate-950 p-6 text-center"><p>The 3D world could not start. Reload the page to try again.</p><button onClick={()=>window.location.reload()} className="rounded-xl bg-cyan-400 px-5 py-3 text-slate-950">Reload game</button><button onClick={leave}>Back to Worlds</button></div>}<div ref={mount} className="absolute inset-x-0 top-16 bottom-[240px] sm:bottom-[230px]"/><button onClick={leave} className="absolute left-3 top-3 z-50 rounded-xl bg-black/70 px-4 py-3 font-black"><ArrowLeft className="inline h-5"/> Worlds</button><div className="absolute top-3 right-3 z-40 flex gap-2"><span className="rounded-xl bg-blue-700/95 px-3 py-2 font-black">🔵 {blue} · {counts.b}</span><span className="rounded-xl bg-amber-400 px-3 py-2 font-black text-slate-950">🟡 {gold} · {counts.g}</span></div><section className="absolute bottom-3 left-1/2 z-50 w-[min(94vw,620px)] -translate-x-1/2 rounded-3xl border border-white/20 bg-slate-950/95 p-4 text-center shadow-2xl"><p className="mb-2 text-sm text-cyan-100">Drag to look around · Pinch or scroll to zoom</p><div className="font-black">{current?.name} · {current?.team.toUpperCase()} TEAM</div><div className="text-sm mb-2">Strikes {"❌".repeat(current?.strikes||0)||"0"} · <Shield className="inline h-4"/> {current?.shield||0} · <Zap className="inline h-4"/> {current?.power||0}</div><div className="mb-3 font-bold">{message}</div>{!question&&!winner&&!busy&&turn===0&&<button onClick={ask} className="rounded-xl bg-cyan-400 px-7 py-3 font-black text-slate-950"><Dices className="mr-2 inline"/>GET QUESTION</button>}{question&&<><div className="mb-3 text-xl font-black">{question.q}</div><div className="grid grid-cols-2 gap-2">{question.a.map((a,i)=><button key={a} disabled={turn!==0||busy} onClick={()=>answer(i)} className="rounded-xl bg-white/10 p-3 font-bold active:bg-cyan-600">{a}</button>)}</div></>}{dice&&<div className="text-4xl">🎲 {dice}</div>}{winner&&<div><Trophy className="mx-auto h-10 w-10 text-amber-300"/><div className="text-2xl font-black">{winner} WINS!</div><button onClick={start} className="mt-3 rounded-xl bg-amber-300 px-6 py-3 font-black text-slate-950">PLAY AGAIN</button></div>}</section></main>
}
