import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, ChevronDown, ChevronUp, Play, Volume2, VolumeX } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { loadParentControls } from "@/lib/parentControls";

type Video={id:string;title:string;channel:string;topic:string};
const DEFAULTS:Video[]=[
 {id:"jwoWBrT-FyU",title:"The Count Counts to Zero",channel:"Sesame Street",topic:"Numbers"},
 {id:"w0VQIJVnoxU",title:"Daniel's Feeling Songs",channel:"PBS KIDS",topic:"Feelings"},
 {id:"-k5R0haCa6o",title:"The Ancient Animal Crossing",channel:"SciShow Kids",topic:"Animals & Earth"},
];
const storageKey=(id?:number|string)=>`arise-tv-parent-videos-${id||"default"}`;
const usageKey=(id?:number|string)=>`arise-tv-usage-${id||"default"}-${new Date().toISOString().slice(0,10)}`;
function extractId(value:string){const v=value.trim();const m=v.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/|embed\/))([A-Za-z0-9_-]{11})/);return m?.[1]||( /^[A-Za-z0-9_-]{11}$/.test(v)?v:"");}
function loadVideos(id?:number|string):Video[]{try{const saved=JSON.parse(localStorage.getItem(storageKey(id))||"null");return Array.isArray(saved)&&saved.length?saved:DEFAULTS;}catch{return DEFAULTS;}}
function saveVideos(id:number|string|undefined,v:Video[]){localStorage.setItem(storageKey(id),JSON.stringify(v));}
export default function EyeGazeTV(){
 const {user}=useAuth();const [,navigate]=useLocation();const [videos,setVideos]=useState<Video[]>(()=>loadVideos(user?.id));const [index,setIndex]=useState(0);const [muted,setMuted]=useState(false);const [url,setUrl]=useState("");const [title,setTitle]=useState("");const [manage,setManage]=useState(false);const [minutes,setMinutes]=useState(0);const startRef=useRef(Date.now());const controls=useMemo(()=>loadParentControls(user?.id),[user?.id]);
 useEffect(()=>{setVideos(loadVideos(user?.id));try{setMinutes(Number(localStorage.getItem(usageKey(user?.id))||0));}catch{}},[user?.id]);
 useEffect(()=>{const timer=window.setInterval(()=>{const delta=(Date.now()-startRef.current)/60000;startRef.current=Date.now();setMinutes(m=>{const next=m+delta;try{localStorage.setItem(usageKey(user?.id),String(next));}catch{}return next;});},15000);return()=>window.clearInterval(timer);},[user?.id]);
 const limited=controls.enabled&&controls.tvDailyMinutes>0&&minutes>=controls.tvDailyMinutes;
 const current=videos[index%Math.max(1,videos.length)];
 const move=(d:number)=>{if(!videos.length)return;setIndex(i=>(i+d+videos.length)%videos.length);};
 const add=()=>{const id=extractId(url);if(!id)return;const next=[...videos,{id,title:title.trim()||"Learning video",channel:"Parent approved",topic:"Learning"}];setVideos(next);saveVideos(user?.id,next);setUrl("");setTitle("");};
 const remove=(i:number)=>{const next=videos.filter((_,x)=>x!==i);setVideos(next);saveVideos(user?.id,next);setIndex(0);};
 if(limited)return <main className="fixed inset-0 z-[120] bg-slate-950 text-white grid place-items-center p-6"><div className="max-w-lg text-center"><div className="text-8xl">🌙</div><h1 className="text-4xl font-black mt-4">TV time is finished for today</h1><p className="text-white/70 font-bold mt-2">A grown-up set today's A.R.I.S.E. TV limit.</p><button onClick={()=>navigate("/eye-gaze-home")} className="mt-6 min-h-14 rounded-2xl bg-white text-slate-950 px-6 font-black">Back Home</button></div></main>;
 return <main className="fixed inset-0 z-[120] h-[100dvh] bg-black text-white overflow-hidden">
  <header className="absolute z-50 top-0 inset-x-0 p-3 flex items-center gap-2 bg-gradient-to-b from-black/80 to-transparent pointer-events-none"><button onClick={()=>navigate("/eye-gaze-home")} className="pointer-events-auto min-h-11 rounded-full bg-black/60 border border-white/20 px-4 font-black flex items-center gap-2"><ArrowLeft className="w-5 h-5"/> Home</button><div className="flex-1 text-center font-black">A.R.I.S.E. TV</div><button onClick={()=>setMuted(v=>!v)} className="pointer-events-auto w-11 h-11 rounded-full bg-black/60 border border-white/20 grid place-items-center">{muted?<VolumeX/>:<Volume2/>}</button></header>
  {!current?<div className="h-full grid place-items-center text-center p-6"><div><div className="text-8xl">📺</div><h1 className="text-3xl font-black">No videos yet</h1><p className="text-white/60 font-bold">A grown-up can add approved YouTube videos.</p><button onClick={()=>setManage(true)} className="mt-5 rounded-2xl bg-white text-black px-5 py-3 font-black">Parent: add videos</button></div></div>:<section className="h-full w-full snap-y snap-mandatory overflow-y-auto overscroll-none" onScroll={e=>{const h=e.currentTarget.clientHeight;const next=Math.round(e.currentTarget.scrollTop/h);if(next!==index&&next>=0&&next<videos.length)setIndex(next);}}>{videos.map((video,i)=><article key={`${video.id}-${i}`} className="relative h-[100dvh] snap-start snap-always bg-black grid place-items-center"><iframe title={video.title} className="absolute inset-0 w-full h-full" src={`https://www.youtube-nocookie.com/embed/${video.id}?autoplay=${i===index?1:0}&mute=${muted?1:0}&controls=1&playsinline=1&rel=0&modestbranding=1`} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/><div className="absolute z-20 left-4 right-20 bottom-8 pointer-events-none drop-shadow-lg"><span className="inline-block rounded-full bg-cyan-300 text-slate-950 px-3 py-1 text-xs font-black">✓ GROWN-UP APPROVED</span><h2 className="text-xl sm:text-3xl font-black mt-2">{video.title}</h2><p className="font-bold text-white/80">{video.channel}</p></div><div className="absolute z-30 right-3 bottom-8 flex flex-col gap-3"><button onClick={()=>move(-1)} className="w-14 h-14 rounded-full bg-black/65 border border-white/20 grid place-items-center"><ChevronUp/></button><button onClick={()=>move(1)} className="w-14 h-14 rounded-full bg-black/65 border border-white/20 grid place-items-center"><ChevronDown/></button></div></article>)}</section>}
  <button onClick={()=>setManage(true)} className="absolute z-50 top-16 right-3 rounded-full bg-black/65 border border-white/20 px-3 py-2 text-xs font-black">👨‍👩‍👧 Parent</button>
  {manage&&<div className="absolute inset-0 z-[80] bg-slate-950/98 overflow-y-auto p-4 sm:p-7"><div className="max-w-2xl mx-auto"><div className="flex justify-between items-center"><div><p className="text-xs font-black text-cyan-300 uppercase tracking-widest">Parent video controls</p><h1 className="text-3xl font-black">Choose the whole feed</h1></div><button onClick={()=>setManage(false)} className="rounded-2xl bg-white text-black px-4 py-3 font-black">Done</button></div><div className="mt-5 rounded-3xl bg-white text-slate-950 p-5"><label className="font-black">YouTube link or video ID<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste YouTube link" className="mt-2 w-full min-h-14 rounded-xl border-2 p-3"/></label><label className="font-black block mt-3">Kid-friendly title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What should the child see?" className="mt-2 w-full min-h-14 rounded-xl border-2 p-3"/></label><button onClick={add} disabled={!extractId(url)} className="mt-3 w-full min-h-14 rounded-xl bg-violet-700 text-white font-black disabled:opacity-40">+ Add approved video</button></div><div className="space-y-2 mt-4">{videos.map((v,i)=><div key={`${v.id}-${i}`} className="rounded-2xl bg-white text-slate-950 p-3 flex items-center gap-3"><img src={`https://i.ytimg.com/vi/${v.id}/mqdefault.jpg`} className="w-24 aspect-video rounded-xl object-cover" alt=""/><strong className="flex-1">{v.title}</strong><button onClick={()=>remove(i)} className="rounded-xl bg-rose-100 text-rose-800 px-3 py-2 font-black">Remove</button></div>)}</div></div></div>}
 </main>;
}
