import { useEffect,useMemo,useRef,useState } from "react";
import { useLocation } from "wouter";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { ArrowLeft, Camera, Home, Lock, Paintbrush, RotateCcw, ShoppingBag, Unlock, X } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { API_BASE } from "@/lib/queryClient";
import { getAvatarCharacter } from "@/lib/avatarCharacters";
import { createPet, openPetCare } from "@/lib/pets";
import MobileJoystick from "@/components/MobileJoystick";

type CatalogItem={id:string;type:string;name:string;price:number;rarity:string};
type HomeMeta={ownerId:number;displayName:string;homeId:string;propertyId:string;lot:number;x:number;z:number;unlocked:boolean};
type State={selectedCharacter:string;equipped:Record<string,string>;purchased:string[];furniture:string[]};
type Payload={economy?:{wallet:number};state:State;catalog?:CatalogItem[];home:HomeMeta;isOwner:boolean};

const ROOM_NAMES=[
  {name:"Living Room",test:(x:number,z:number)=>x<0&&z>3},
  {name:"Kitchen",test:(x:number,z:number)=>x>=0&&z>3},
  {name:"Game Room",test:(x:number,z:number)=>x<-5&&z<=3&&z>=-3},
  {name:"Bathroom",test:(x:number,z:number)=>x>5&&z<=3&&z>=-3},
  {name:"Reading Room",test:(x:number,z:number)=>x<0&&z<-3},
  {name:"Bedroom",test:(x:number,z:number)=>x>=0&&z<-3},
];

function mat(color:number,roughness=.78,metalness=0){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
function box(scene:THREE.Scene,size:[number,number,number],pos:[number,number,number],color:number,roughness=.78){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat(color,roughness));m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
function plane(scene:THREE.Scene,size:[number,number],pos:[number,number,number],color:number){const m=new THREE.Mesh(new THREE.PlaneGeometry(...size),mat(color,.9));m.position.set(...pos);m.rotation.x=-Math.PI/2;m.receiveShadow=true;scene.add(m);return m;}
function rug(scene:THREE.Scene,x:number,z:number,w:number,d:number,color:number){return plane(scene,[w,d],[x,.015,z],color);}
function couch(scene:THREE.Scene,x:number,z:number,color:number,rot=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;scene.add(g);const add=(s:[number,number,number],p:[number,number,number])=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...s),mat(color,.88));m.position.set(...p);m.castShadow=true;g.add(m);};add([5,.7,1.8],[0,.42,0]);add([5,1.3,.35],[0,1.05,.72]);add([.45,1,1.8],[-2.3,.62,0]);add([.45,1,1.8],[2.3,.62,0]);}
function table(scene:THREE.Scene,x:number,z:number,w=3,d=1.5,color=0x7c4a24){box(scene,[w,.2,d],[x,.72,z],color);for(const dx of [-w*.4,w*.4])for(const dz of [-d*.34,d*.34])box(scene,[.14,1.25,.14],[x+dx,.32,z+dz],color);}
function plant(scene:THREE.Scene,x:number,z:number){box(scene,[.8,.65,.8],[x,.33,z],0x9a3412);for(let i=0;i<6;i++){const leaf=box(scene,[.16,1.35,.16],[x+(i-2.5)*.12,1.25,z],0x16a34a);leaf.rotation.z=(i-2.5)*.16;}}
function lamp(scene:THREE.Scene,x:number,z:number){box(scene,[.14,2.4,.14],[x,1.2,z],0x334155);const shade=new THREE.Mesh(new THREE.ConeGeometry(.7,.85,20,1,true),new THREE.MeshStandardMaterial({color:0xfef3c7,side:THREE.DoubleSide}));shade.position.set(x,2.55,z);scene.add(shade);const light=new THREE.PointLight(0xffe3aa,1.7,8);light.position.set(x,2.5,z);scene.add(light);}
function bookshelf(scene:THREE.Scene,x:number,z:number,rot=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;scene.add(g);const wood=mat(0x6b3f20,.85);const add=(s:[number,number,number],p:[number,number,number])=>{const m=new THREE.Mesh(new THREE.BoxGeometry(...s),wood);m.position.set(...p);m.castShadow=true;g.add(m);};add([5,3,.35],[0,1.5,0]);for(let i=0;i<4;i++)add([4.7,.12,.55],[0,.5+i*.72,.2]);const colors=[0x2563eb,0xdc2626,0x16a34a,0xca8a04,0x7c3aed,0xdb2777];for(let shelf=0;shelf<3;shelf++)for(let i=0;i<8;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.32,.48,.22),mat(colors[(i+shelf)%colors.length],.7));b.position.set(-1.85+i*.52,.8+shelf*.72,.5);g.add(b);}}
function bed(scene:THREE.Scene,x:number,z:number,accent:number){box(scene,[5.4,.55,6.2],[x,.42,z],0x334155);box(scene,[5.1,.48,5.7],[x,.86,z-.05],0xf8fafc);box(scene,[5.5,2.2,.35],[x,1.35,z-2.9],accent);box(scene,[2,.3,1.05],[x-1.25,1.18,z-2.15],0xe2e8f0);box(scene,[2,.3,1.05],[x+1.25,1.18,z-2.15],0xe2e8f0);}
function tv(scene:THREE.Scene,x:number,z:number,rot=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;scene.add(g);const frame=new THREE.Mesh(new THREE.BoxGeometry(4.2,2.45,.2),mat(0x080d18,.25,.35));frame.position.y=2.25;g.add(frame);const screen=new THREE.Mesh(new THREE.PlaneGeometry(3.85,2.1),new THREE.MeshStandardMaterial({color:0x2563eb,emissive:0x172554,emissiveIntensity:.8}));screen.position.set(0,2.25,.11);g.add(screen);}
function kitchen(scene:THREE.Scene,accent:number){box(scene,[6.4,1.1,1.2],[8.8,.55,8.6],0x78350f);box(scene,[6.6,.18,1.4],[8.8,1.12,8.6],0xf8fafc);box(scene,[2,3.5,1.4],[13.7,1.75,8.3],0x94a3b8);box(scene,[3.2,1,1.35],[8.5,.52,5.2],accent);box(scene,[3.35,.12,1.5],[8.5,1.05,5.2],0x111827);}
function gameRoom(scene:THREE.Scene,accent:number){rug(scene,-10,0,7,5,0x312e81);tv(scene,-14,0,Math.PI/2);couch(scene,-8.4,0,accent,Math.PI/2);box(scene,[2.4,1.2,1.2],[-11,.6,2],0x111827);box(scene,[2.1,.95,.12],[-11,1.3,1.38],0x22d3ee,.35);}
function bathroom(scene:THREE.Scene,accent:number){rug(scene,10,0,6,5,0xdbeafe);box(scene,[3,.9,1.2],[11.5,.48,2],0xf8fafc);box(scene,[2.4,2.5,.15],[11.5,2,1.34],0x93c5fd,.2);const tub=new THREE.Mesh(new THREE.BoxGeometry(4.4,1.2,2.2),mat(0xe0f2fe,.35));tub.position.set(8.7,.62,-1);scene.add(tub);box(scene,[.15,1.4,.15],[10.2,1.5,-1],accent);}
function wallSegment(scene:THREE.Scene,size:[number,number,number],pos:[number,number,number],color:number){const m=box(scene,size,pos,color,.9);m.castShadow=false;return m;}
function blocked(x:number,z:number){if(x<-15.5||x>15.5||z<-10.4||z>10.4)return true;const furniture=[[-14,-10.8,-1.6,1.6],[-11.8,-5.5,-2.2,2.2],[5.6,11.4,-8.9,-2.8],[5.3,12,4.2,6.2],[12.5,15.2,7,10],[7,11.3,-2.4,.3]];return furniture.some(([x1,x2,z1,z2])=>x>x1&&x<x2&&z>z1&&z<z2);}

export default function HomeInterior(){
  const {token,user}=useAuth();const [,navigate]=useLocation();
  const ownerParam=Number(new URLSearchParams(window.location.search).get("owner")||user?.id||0);const ownerId=Number.isFinite(ownerParam)&&ownerParam>0?ownerParam:Number(user?.id||0);
  const mountRef=useRef<HTMLDivElement>(null),rootRef=useRef<THREE.Group|null>(null),petRef=useRef<THREE.Object3D|null>(null),cameraRef=useRef<THREE.PerspectiveCamera|null>(null),controlsRef=useRef<OrbitControls|null>(null),keysRef=useRef(new Set<string>()),targetRef=useRef(new THREE.Vector3(0,0,8.5));
  const [payload,setPayload]=useState<Payload|null>(null),[notice,setNotice]=useState("Opening home…"),[room,setRoom]=useState("Foyer"),[decorate,setDecorate]=useState(false),[busy,setBusy]=useState(""),[cameraPreset,setCameraPreset]=useState<"follow"|"wide"|"top">("follow");
  const headers=useMemo(()=>({Authorization:"Bearer "+token,"Content-Type":"application/json"}),[token]);

  const load=async()=>{if(!token||!ownerId)return;try{const homeResponse=await fetch(API_BASE+"/api/homes/"+ownerId,{headers,cache:"no-store"});const homeData=await homeResponse.json();if(!homeResponse.ok)throw Error(homeData.message||"Could not enter this home.");if(homeData.isOwner){const worldResponse=await fetch(API_BASE+"/api/avatar-world",{headers,cache:"no-store"});const world=await worldResponse.json();if(!worldResponse.ok)throw Error(world.message||"Could not load your home.");setPayload({...homeData,economy:world.economy,catalog:world.catalog,state:world.state});}else setPayload(homeData);setNotice(homeData.isOwner?"Welcome home.":"You are visiting "+homeData.home.displayName+". You can explore, but only the owner can change things.");}catch(error:any){setNotice(error.message||"Could not enter this home.");setPayload(null);}};
  useEffect(()=>{void load();},[token,ownerId]);

  const customize=async(body:any)=>{if(!payload?.isOwner||busy)return;setBusy("save");try{const r=await fetch(API_BASE+"/api/avatar-world/customize",{method:"POST",headers,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.message||"Could not update your home.");setPayload(p=>p?{...p,state:d.state,economy:d.economy,catalog:d.catalog}:p);setNotice("Home updated.");}catch(error:any){setNotice(error.message||"Could not update your home.");}finally{setBusy("");}};
  const toggleDoor=async()=>{if(!payload?.isOwner||busy)return;setBusy("door");try{const r=await fetch(API_BASE+"/api/homes/door",{method:"POST",headers,body:JSON.stringify({unlocked:!payload.home.unlocked})});const d=await r.json();if(!r.ok)throw Error(d.message||"Could not change the door.");setPayload(p=>p?{...p,home:d.home}:p);setNotice(d.home.unlocked?"Front door unlocked. Other readers can visit.":"Front door locked. Only you can enter.");}catch(error:any){setNotice(error.message||"Could not change the door.");}finally{setBusy("");}};

  const applyCamera=(preset:"follow"|"wide"|"top")=>{setCameraPreset(preset);const root=rootRef.current,camera=cameraRef.current,controls=controlsRef.current;if(!root||!camera||!controls)return;const p=root.position;if(preset==="follow")camera.position.set(p.x,p.y+4.8,p.z+8);else if(preset==="wide")camera.position.set(p.x+10,p.y+9,p.z+12);else camera.position.set(p.x+.1,p.y+16,p.z+.1);controls.target.set(p.x,1.4,p.z);controls.update();};

  useEffect(()=>{
    const mount=mountRef.current;if(!mount||!payload)return;let disposed=false,raf=0,lastRoom="";
    const homeId=payload.home.homeId,dark=homeId==="home-loft",studio=homeId==="home-studio",modern=homeId==="home-modern";
    const wall=dark?0x292734:studio?0x304257:modern?0xf2f0ea:0xf8fafc,floorColor=dark?0x45414d:studio?0x566779:modern?0xd8d2c8:0xd2c9bb,accent=dark?0xa855f7:studio?0x14b8a6:modern?0x0284c7:0x2563eb;
    const scene=new THREE.Scene();scene.background=new THREE.Color(dark?0x111827:studio?0x183047:0xbfe4ff);scene.fog=new THREE.Fog(scene.background.getHex(),35,65);
    const camera=new THREE.PerspectiveCamera(56,1,.1,90);camera.position.set(0,5.2,16.5);cameraRef.current=camera;
    const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;mount.innerHTML="";mount.appendChild(renderer.domElement);
    const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=15;controls.minPolarAngle=.42;controls.maxPolarAngle=1.38;controls.target.set(0,1.4,8.5);controlsRef.current=controls;
    scene.add(new THREE.HemisphereLight(0xffffff,0x475569,2.7));const sun=new THREE.DirectionalLight(0xffefd1,3.1);sun.position.set(-12,18,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
    const floor=plane(scene,[32,22],[0,0,0],floorColor);floor.userData.ground=true;
    // Exterior shell uses a wide front doorway and lower cutaway walls so the camera never feels trapped.
    wallSegment(scene,[32,4.3,.3],[0,2.15,-11],wall);wallSegment(scene,[.3,4.3,22],[-16,2.15,0],wall);wallSegment(scene,[.3,4.3,22],[16,2.15,0],wall);wallSegment(scene,[13.5,4.3,.3],[-9.25,2.15,11],wall);wallSegment(scene,[13.5,4.3,.3],[9.25,2.15,11],wall);wallSegment(scene,[5,.35,.3],[0,4.05,11],wall);
    // Partial dividers create six recognizable rooms without boxing the camera in.
    wallSegment(scene,[11.5,3.6,.22],[-10.2,1.8,3],wall);wallSegment(scene,[11.5,3.6,.22],[10.2,1.8,3],wall);wallSegment(scene,[11.5,3.6,.22],[-10.2,1.8,-3],wall);wallSegment(scene,[11.5,3.6,.22],[10.2,1.8,-3],wall);wallSegment(scene,[.22,3.6,5.4],[0,1.8,7.8],wall);wallSegment(scene,[.22,3.6,5.4],[0,1.8,-7.8],wall);
    rug(scene,-8.5,7,7,5,dark?0x581c87:0x1d4ed8);rug(scene,-8.5,-7,7,5,0x0f766e);rug(scene,8.5,-7,7,5,dark?0x7c2d12:0x64748b);
    couch(scene,-8.5,8,0x475569);table(scene,-8.5,5.2);tv(scene,-8.5,3.45);plant(scene,-14,9);lamp(scene,-3.3,9);kitchen(scene,accent);plant(scene,4,9);
    bookshelf(scene,-8.5,-10.2);couch(scene,-8.5,-6,0x0f766e,Math.PI);table(scene,-8.5,-4.2);lamp(scene,-14,-4.5);bed(scene,8.5,-7.3,accent);table(scene,13,-4.5,2.5,1.3);lamp(scene,13.5,-5.2);gameRoom(scene,accent);bathroom(scene,accent);
    if(payload.state.furniture.includes("furniture-books"))bookshelf(scene,-14,-7,Math.PI/2);if(payload.state.furniture.includes("furniture-sofa"))couch(scene,7.5,7,0x7c3aed,Math.PI);if(payload.state.furniture.includes("furniture-desk")){table(scene,3,-7,4,1.8,0x713f12);box(scene,[3.2,1.6,.12],[3,2,-7.9],0x111827);}if(payload.state.furniture.includes("furniture-neon")){const light=new THREE.PointLight(0x22d3ee,3,10);light.position.set(-8,3.5,-9.5);scene.add(light);}
    const loader=new GLTFLoader(),avatar=new THREE.Group();avatar.position.set(0,0,8.5);scene.add(avatar);rootRef.current=avatar;targetRef.current.copy(avatar.position);
    loader.load(getAvatarCharacter(payload.state.selectedCharacter||"robin-hood").modelPath,gltf=>{if(disposed)return;const model=gltf.scene,b=new THREE.Box3().setFromObject(model),s=b.getSize(new THREE.Vector3());model.scale.setScalar(2.5/Math.max(.01,s.y));model.updateMatrixWorld(true);const n=new THREE.Box3().setFromObject(model);model.position.y=-n.min.y;model.traverse(o=>{if((o as THREE.Mesh).isMesh){(o as THREE.Mesh).castShadow=true;(o as THREE.Mesh).receiveShadow=true;}});avatar.add(model);if(gltf.animations.length){const mixer=new THREE.AnimationMixer(model),idle=gltf.animations.find(a=>/idle/i.test(a.name))||gltf.animations[0],walk=gltf.animations.find(a=>/walk|run/i.test(a.name));const idleAction=mixer.clipAction(idle);idleAction.play();avatar.userData.mixer=mixer;avatar.userData.idleAction=idleAction;if(walk)avatar.userData.walkAction=mixer.clipAction(walk);}});
    const pet=createPet(payload.state.equipped.pet,loader,.9);if(pet){pet.position.set(.9,0,9);scene.add(pet);petRef.current=pet;}
    const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down:{x:number;y:number}|null=null;const pd=(e:PointerEvent)=>down={x:e.clientX,y:e.clientY};const pu=(e:PointerEvent)=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>9){down=null;return;}down=null;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const petObj=petRef.current;if(payload.isOwner&&petObj&&ray.intersectObject(petObj,true).length){openPetCare();return;}const hit=ray.intersectObject(floor)[0];if(hit&&!blocked(hit.point.x,hit.point.z))targetRef.current.set(hit.point.x,0,hit.point.z);};const kd=(e:KeyboardEvent)=>keysRef.current.add(e.key.toLowerCase()),ku=(e:KeyboardEvent)=>keysRef.current.delete(e.key.toLowerCase());renderer.domElement.addEventListener("pointerdown",pd);renderer.domElement.addEventListener("pointerup",pu);window.addEventListener("keydown",kd);window.addEventListener("keyup",ku);
    const resize=()=>{camera.aspect=mount.clientWidth/Math.max(1,mount.clientHeight);camera.updateProjectionMatrix();renderer.setSize(mount.clientWidth,mount.clientHeight);};resize();window.addEventListener("resize",resize);const clock=new THREE.Clock();
    const loop=()=>{if(disposed)return;const dt=Math.min(.05,clock.getDelta()),root=rootRef.current;if(root){let side=0,forwardInput=0,k=keysRef.current;if(k.has("w")||k.has("arrowup"))forwardInput+=1;if(k.has("s")||k.has("arrowdown"))forwardInput-=1;if(k.has("d")||k.has("arrowright"))side+=1;if(k.has("a")||k.has("arrowleft"))side-=1;if(side||forwardInput){const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0)).normalize().multiplyScalar(-1);const step=forward.multiplyScalar(forwardInput).add(right.multiplyScalar(side)).normalize().multiplyScalar(4.7*dt);const nx=root.position.x+step.x,nz=root.position.z+step.z;if(!blocked(nx,nz))targetRef.current.set(nx,0,nz);}const delta=targetRef.current.clone().sub(root.position);delta.y=0;const moving=delta.length()>.08;if(moving){const before=root.position.clone();const step=Math.min(delta.length(),4.5*dt);delta.normalize();root.position.addScaledVector(delta,step);root.rotation.y=Math.atan2(delta.x,delta.z);const moved=root.position.clone().sub(before);if(cameraPreset!=="top")camera.position.add(moved);controls.target.add(moved);}const mixer=root.userData.mixer as THREE.AnimationMixer|undefined;mixer?.update(dt);const walk=root.userData.walkAction as THREE.AnimationAction|undefined,idle=root.userData.idleAction as THREE.AnimationAction|undefined;if(walk){if(moving&&!walk.isRunning()){idle?.fadeOut(.15);walk.reset().fadeIn(.15).play();}else if(!moving&&walk.isRunning()){walk.fadeOut(.15);idle?.reset().fadeIn(.15).play();}}const petObj=petRef.current;if(petObj){const behind=new THREE.Vector3(-Math.sin(root.rotation.y)*1.1,0,-Math.cos(root.rotation.y)*1.1).add(root.position);petObj.position.lerp(behind,Math.min(1,dt*3.5));petObj.rotation.y=THREE.MathUtils.lerp(petObj.rotation.y,root.rotation.y,Math.min(1,dt*4));}const current=ROOM_NAMES.find(r=>r.test(root.position.x,root.position.z))?.name||"Foyer";if(current!==lastRoom){lastRoom=current;setRoom(current);}}
      controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(loop);};loop();
    return()=>{disposed=true;cancelAnimationFrame(raf);window.removeEventListener("resize",resize);window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku);renderer.domElement.removeEventListener("pointerdown",pd);renderer.domElement.removeEventListener("pointerup",pu);controls.dispose();renderer.dispose();mount.innerHTML="";rootRef.current=null;petRef.current=null;};
  },[payload?.home.propertyId,payload?.home.homeId,payload?.state.selectedCharacter,payload?.state.equipped.pet,payload?.state.furniture.join("|"),cameraPreset]);

  const move=(key:"w"|"a"|"s"|"d",on:boolean)=>{if(on)keysRef.current.add(key);else keysRef.current.delete(key);};const reset=()=>{const r=rootRef.current;if(r){r.position.set(0,0,8.5);targetRef.current.copy(r.position);applyCamera("follow");setNotice("Back at the front door.");}};const ownedHomes=(payload?.catalog||[]).filter(x=>x.type==="home"&&payload?.state.purchased.includes(x.id));const ownedFurniture=(payload?.catalog||[]).filter(x=>x.type==="furniture"&&payload?.state.purchased.includes(x.id));

  if(!payload)return <main className="relative grid h-[100dvh] place-items-center bg-slate-950 p-5 text-center text-white"><div><Home className="mx-auto h-12 w-12 text-cyan-300"/><h1 className="mt-3 text-2xl font-black">{notice}</h1><div className="mt-5 flex flex-wrap justify-center gap-2"><button onClick={()=>navigate("/neighborhood")} className="rounded-xl bg-white/10 px-5 py-3 font-black">Back to The Block</button>{notice.toLowerCase().includes("buy")&&<button onClick={()=>navigate("/avatar-world")} className="flex items-center gap-2 rounded-xl bg-amber-300 px-5 py-3 font-black text-slate-950"><ShoppingBag className="h-4 w-4"/> Buy a home</button>}</div></div></main>;

  return <main className="club-world-root relative h-[100dvh] overflow-hidden bg-slate-950 text-white"><div ref={mountRef} className="absolute inset-0 touch-none"/><header className="pointer-events-none absolute inset-x-0 top-0 z-30 flex items-center gap-2 bg-gradient-to-b from-slate-950/95 via-slate-950/70 to-transparent p-2.5 sm:p-4"><button onClick={()=>navigate("/neighborhood")} className="pointer-events-auto flex min-h-11 items-center gap-2 rounded-2xl border border-white/10 bg-slate-950/88 px-3 font-black shadow-xl"><ArrowLeft className="h-4 w-4"/><span className="hidden sm:inline">The Block</span></button><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.22em] text-cyan-300">{payload.isOwner?"My Home":"Visiting"}</p><h1 className="truncate text-base font-black sm:text-xl">{payload.isOwner?room:payload.home.displayName+" · "+room}</h1></div>{payload.isOwner&&<button onClick={()=>void toggleDoor()} disabled={!!busy} className={"pointer-events-auto flex min-h-11 items-center gap-2 rounded-2xl px-3 text-xs font-black shadow-xl "+(payload.home.unlocked?"bg-emerald-400 text-slate-950":"bg-amber-300 text-slate-950")}>{payload.home.unlocked?<Unlock className="h-4 w-4"/>:<Lock className="h-4 w-4"/>}<span className="hidden sm:inline">{payload.home.unlocked?"Door open":"Door locked"}</span></button>}{payload.isOwner&&<button onClick={()=>setDecorate(true)} className="pointer-events-auto flex min-h-11 items-center gap-2 rounded-2xl bg-fuchsia-600/90 px-3 text-xs font-black shadow-xl"><Paintbrush className="h-4 w-4"/><span className="hidden sm:inline">Decorate</span></button>}<button onClick={reset} className="pointer-events-auto grid h-11 w-11 place-items-center rounded-2xl bg-slate-950/88 shadow-xl"><RotateCcw className="h-4 w-4"/></button></header>
    <div className="absolute right-3 top-20 z-30 flex gap-1 rounded-2xl border border-white/10 bg-slate-950/80 p-1.5 backdrop-blur"><Camera className="m-2 h-4 w-4 text-cyan-300"/>{(["follow","wide","top"] as const).map(p=><button key={p} onClick={()=>applyCamera(p)} className={"min-h-9 rounded-xl px-2 text-[10px] font-black uppercase "+(cameraPreset===p?"bg-cyan-300 text-slate-950":"bg-white/10")}>{p}</button>)}</div>
    <div className="pointer-events-none absolute left-1/2 top-[74px] z-20 max-w-[54vw] -translate-x-1/2 truncate rounded-full bg-slate-950/72 px-3 py-1 text-[10px] font-black text-white/85 backdrop-blur sm:top-24">{payload.isOwner?(payload.home.unlocked?"Door unlocked · visitors may enter":"Door locked · private home"):"View only · owner controls this home"}</div>
    <MobileJoystick onMove={move} className="bottom-24 left-4" label="Home movement controls"/><div className="pointer-events-none absolute bottom-5 left-1/2 z-20 max-w-[68vw] -translate-x-1/2 rounded-xl bg-slate-950/76 px-3 py-2 text-center text-[10px] font-bold text-white/85 backdrop-blur sm:text-xs">{notice}</div>
    {decorate&&payload.isOwner&&<div className="fixed inset-0 z-[100] flex items-end bg-black/70 p-2 backdrop-blur-sm sm:items-center sm:justify-center" onClick={()=>setDecorate(false)}><section className="max-h-[78dvh] w-full overflow-y-auto rounded-t-[2rem] border border-white/10 bg-slate-950 p-4 shadow-2xl sm:max-w-xl sm:rounded-[2rem]" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3"><div className="flex-1"><p className="text-xs font-black uppercase tracking-widest text-cyan-300">My Property</p><h2 className="text-2xl font-black">Decorate Home</h2></div><button onClick={()=>setDecorate(false)} className="grid h-11 w-11 place-items-center rounded-xl bg-white/10"><X/></button></div><p className="mt-2 text-sm font-bold text-white/55">Only you can change your house. Visitors can only explore when your door is unlocked.</p><h3 className="mt-5 font-black">House style</h3><div className="mt-2 grid grid-cols-2 gap-2">{ownedHomes.map(home=><button key={home.id} disabled={!!busy} onClick={()=>void customize({action:"equip",slot:"home",itemId:home.id})} className={"min-h-16 rounded-xl border p-3 text-left font-black "+(payload.state.equipped.home===home.id?"border-cyan-200 bg-cyan-300 text-slate-950":"border-white/10 bg-white/5")}><span className="block">{home.name}</span><span className="text-[10px] uppercase opacity-60">{home.rarity}</span></button>)}</div><h3 className="mt-5 font-black">Furniture</h3><div className="mt-2 grid grid-cols-2 gap-2">{ownedFurniture.length?ownedFurniture.map(item=>{const active=payload.state.furniture.includes(item.id);return <button key={item.id} disabled={!!busy} onClick={()=>void customize({action:"furniture",itemIds:active?payload.state.furniture.filter(id=>id!==item.id):[...payload.state.furniture,item.id]})} className={"min-h-16 rounded-xl border p-3 text-left font-black "+(active?"border-emerald-200 bg-emerald-300 text-slate-950":"border-white/10 bg-white/5")}><span className="block">{item.name}</span><span className="text-[10px] uppercase opacity-60">{active?"Placed":"Tap to place"}</span></button>}):<p className="col-span-2 rounded-xl bg-white/5 p-3 text-sm font-bold text-white/60">Unlock furniture in the Avatar World Shop.</p>}</div><button onClick={()=>navigate("/avatar-world")} className="mt-5 min-h-12 w-full rounded-xl bg-amber-300 font-black text-slate-950">Open Avatar World Shop</button></section></div>}
  </main>;
}
