import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "wouter";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { ArrowLeft, Crosshair, Shield, Zap, Trophy, Map, Footprints } from "lucide-react";
import { API_BASE } from "@/lib/queryClient";
import { useAuth } from "@/context/AuthContext";
import { getAvatarCharacter } from "@/lib/avatarCharacters";

type SelfInfo={userId:number;displayName:string;characterId:string};
type Fighter={name:string;characterId:string;root:THREE.Group;hp:number;shield:number;alive:boolean;respawn:number;cooldown:number;target:THREE.Vector3;strafe:number};
const ROSTER=[{name:"Robin",characterId:"robin-hood"},{name:"Arthur",characterId:"king-arthur"},{name:"Alice",characterId:"alice"},{name:"Sherlock",characterId:"sherlock-holmes"},{name:"Frank",characterId:"frankenstein"},{name:"Hercules",characterId:"hercules"}];
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));

function terrainY(x:number,z:number){return Math.sin(x*.055)*1.25+Math.cos(z*.047)*1.05+Math.sin((x+z)*.025)*.7;}
function tag(text:string,bg="#0f172a",fg="#fff"){
 const c=document.createElement("canvas");c.width=512;c.height=112;const x=c.getContext("2d")!;x.fillStyle=bg;x.beginPath();x.roundRect(8,8,496,96,28);x.fill();x.fillStyle=fg;x.font="800 34px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText(text,256,56);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(4.2,.92,1);return s;
}
function building(scene:THREE.Scene,x:number,z:number,w:number,d:number,h:number,color:number){
 const g=new THREE.Group();g.position.set(x,terrainY(x,z),z);scene.add(g);const body=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.72}));body.position.y=h/2;body.castShadow=true;body.receiveShadow=true;g.add(body);const roof=new THREE.Mesh(new THREE.BoxGeometry(w+.5,.35,d+.5),new THREE.MeshStandardMaterial({color:0x263247,metalness:.25}));roof.position.y=h+.18;g.add(roof);for(let i=-1;i<=1;i+=2){const win=new THREE.Mesh(new THREE.PlaneGeometry(Math.max(1,w*.22),1.1),new THREE.MeshBasicMaterial({color:0x8be9fd}));win.position.set(i*w*.25,h*.58,d/2+.011);g.add(win);}return g;
}
function tree(scene:THREE.Scene,x:number,z:number,s=1){const y=terrainY(x,z);const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.25*s,.38*s,2.8*s,7),new THREE.MeshStandardMaterial({color:0x6b4423}));trunk.position.set(x,y+1.4*s,z);scene.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.6*s,4*s,8),new THREE.MeshStandardMaterial({color:0x26734d,roughness:.9}));crown.position.set(x,y+4*s,z);crown.castShadow=true;scene.add(crown);}

export default function LaserRoyale(){
 const {token}=useAuth();const [,navigate]=useLocation();const mount=useRef<HTMLDivElement>(null);const player=useRef<THREE.Group|null>(null);const camera=useRef<THREE.PerspectiveCamera|null>(null);const keys=useRef(new Set<string>());const fighters=useRef<Fighter[]>([]);const energyRef=useRef(100);const scoreRef=useRef(0);const [self,setSelf]=useState<SelfInfo|null>(null);const [hp,setHp]=useState(100);const [shield,setShield]=useState(50);const [energy,setEnergy]=useState(100);const [score,setScore]=useState(0);const [alive,setAlive]=useState(7);const [time,setTime]=useState(240);const [zone,setZone]=useState(78);const [notice,setNotice]=useState("DROP IN · EXPLORE · TAG · SURVIVE");const [sprint,setSprint]=useState(false);const headers=useMemo(()=>({Authorization:"Bearer "+token}),[token]);
 useEffect(()=>{if(!token)return;fetch(API_BASE+"/api/club-arise/bootstrap",{headers,cache:"no-store"}).then(r=>r.json()).then(d=>setSelf(d.self)).catch(()=>setSelf({userId:0,displayName:"Reader",characterId:"robin-hood"}));},[token]);
 useEffect(()=>{energyRef.current=energy},[energy]);
 useEffect(()=>{
  if(!self||!mount.current)return;const host=mount.current;let dead=false;const scene=new THREE.Scene();scene.background=new THREE.Color(0x77b9e8);scene.fog=new THREE.FogExp2(0x8bc6e8,.0065);
  const cam=new THREE.PerspectiveCamera(60,host.clientWidth/Math.max(1,host.clientHeight),.1,260);camera.current=cam;const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xdff4ff,0x36552d,2.5));const sun=new THREE.DirectionalLight(0xfff4dc,3.6);sun.position.set(-40,70,35);sun.castShadow=true;scene.add(sun);
  const geo=new THREE.PlaneGeometry(190,190,64,64);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position as THREE.BufferAttribute;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,terrainY(x,z));}geo.computeVertexNormals();const land=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x4d965c,roughness:.96}));land.receiveShadow=true;land.userData.land=true;scene.add(land);
  const water=new THREE.Mesh(new THREE.CircleGeometry(125,96),new THREE.MeshStandardMaterial({color:0x3197c7,transparent:true,opacity:.86,roughness:.25,metalness:.08}));water.rotation.x=-Math.PI/2;water.position.y=-3.3;scene.add(water);
  const roadMat=new THREE.MeshStandardMaterial({color:0x374151,roughness:.88});for(const rot of [0,Math.PI/2]){const road=new THREE.Mesh(new THREE.PlaneGeometry(9,150),roadMat);road.rotation.x=-Math.PI/2;road.rotation.z=rot;road.position.y=.18;scene.add(road);}
  const towns=[[-32,-28],[30,-24],[-27,31],[31,29],[0,0]];towns.forEach(([x,z],n)=>{for(let i=0;i<5;i++){const a=i*Math.PI*2/5,r=n===4?12:9;const bx=x+Math.cos(a)*r,bz=z+Math.sin(a)*r;building(scene,bx,bz,6+(i%2)*2,6,4+(i%3)*1.5,[0xd97706,0x2563eb,0x7c3aed,0xdc2626,0x0891b2][(i+n)%5]);}});
  for(let i=0;i<72;i++){const a=Math.random()*Math.PI*2,r=22+Math.random()*68;tree(scene,Math.cos(a)*r,Math.sin(a)*r,.7+Math.random()*.55);}
  const hill=new THREE.Mesh(new THREE.ConeGeometry(13,18,16),new THREE.MeshStandardMaterial({color:0x567c4c,roughness:1}));hill.position.set(-57,7,-52);scene.add(hill);const tower=building(scene,-57,-52,6,6,18,0x475569);tower.add(tag("SKY TOWER","#1e293b","#67e8f9"));tower.children[tower.children.length-1].position.set(0,21,0);
  const zoneRing=new THREE.Mesh(new THREE.TorusGeometry(78,.38,12,160),new THREE.MeshBasicMaterial({color:0x7dd3fc,transparent:true,opacity:.9}));zoneRing.rotation.x=Math.PI/2;zoneRing.position.y=.4;scene.add(zoneRing);
  const loader=new GLTFLoader();const addAvatar=(id:string,name:string,x:number,z:number,you=false)=>{const root=new THREE.Group();root.position.set(x,terrainY(x,z),z);scene.add(root);const label=tag(name,you?"#075985":"#111827",you?"#cffafe":"#fff");label.position.set(0,3.2,0);root.add(label);loader.load(getAvatarCharacter(id).modelPath,g=>{if(dead)return;const model=g.scene;const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());model.scale.setScalar(2.55/Math.max(.01,size.y));model.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(model);model.position.y=-b.min.y;model.traverse(o=>{if((o as THREE.Mesh).isMesh)(o as THREE.Mesh).castShadow=true});root.add(model);if(g.animations.length){const mixer=new THREE.AnimationMixer(model);const idle=g.animations.find(a=>/idle/i.test(a.name))||g.animations[0];mixer.clipAction(idle).play();root.userData.mixer=mixer;}});return root};
  const p=addAvatar(self.characterId,self.displayName||"You",0,62,true);player.current=p;cam.position.set(0,7,72);cam.lookAt(p.position.clone().add(new THREE.Vector3(0,1.5,0)));
  fighters.current=ROSTER.map((b,i)=>{const a=i*Math.PI*2/ROSTER.length,r=42+Math.random()*18;const root=addAvatar(b.characterId,b.name,Math.cos(a)*r,Math.sin(a)*r);return{...b,root,hp:100,shield:50,alive:true,respawn:0,cooldown:1+Math.random(),target:new THREE.Vector3(),strafe:Math.random()>.5?1:-1}});
  const pickups:THREE.Mesh[]=[];for(let i=0;i<18;i++){const a=Math.random()*Math.PI*2,r=12+Math.random()*60;const type=i%3;const m=new THREE.Mesh(type===0?new THREE.OctahedronGeometry(.65):new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:type===0?0x60a5fa:type===1?0xfacc15:0x4ade80,emissive:type===0?0x2563eb:type===1?0xf59e0b:0x16a34a,emissiveIntensity:2}));m.position.set(Math.cos(a)*r,2,Math.sin(a)*r);m.userData.type=type;scene.add(m);pickups.push(m);}
  const beams=new THREE.Group();scene.add(beams);const beam=(a:THREE.Vector3,b:THREE.Vector3,color:number)=>{const d=b.clone().sub(a),g=new THREE.CylinderGeometry(.055,.055,d.length(),7),m=new THREE.MeshBasicMaterial({color});const x=new THREE.Mesh(g,m);x.position.copy(a).add(b).multiplyScalar(.5);x.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.clone().normalize());beams.add(x);setTimeout(()=>{beams.remove(x);g.dispose();m.dispose()},100)};
  const damagePlayer=(d:number)=>{setShield(s=>{const used=Math.min(s,d),left=d-used;if(left)setHp(h=>{const nh=h-left;if(nh<=0){setNotice("TAGGED OUT! Respawning…");setTimeout(()=>{p.position.set(0,terrainY(0,62),62);setHp(100);setShield(50)},1800);return 0}return nh});return s-used})};
  const shoot=()=>{if(energyRef.current<12)return;energyRef.current-=12;setEnergy(energyRef.current);const origin=p.position.clone().add(new THREE.Vector3(0,1.55,0));const dir=new THREE.Vector3(0,0,-1).applyQuaternion(cam.quaternion).normalize();let best:Fighter|null=null,bd=999;for(const f of fighters.current){if(!f.alive)continue;const v=f.root.position.clone().sub(origin),dist=v.length();if(dist<45&&dir.angleTo(v.normalize())<.16&&dist<bd){best=f;bd=dist}}const end=best?best.root.position.clone().add(new THREE.Vector3(0,1.4,0)):origin.clone().add(dir.multiplyScalar(48));beam(origin,end,0x22d3ee);if(best){let d=36;if(best.shield){const u=Math.min(best.shield,d);best.shield-=u;d-=u}best.hp-=d;if(best.hp<=0){best.alive=false;best.root.visible=false;best.respawn=performance.now()+5000;scoreRef.current+=2;setScore(scoreRef.current);setNotice("⚡ TAGGED "+best.name+" · +2");setAlive(1+fighters.current.filter(x=>x.alive).length)}else setNotice("HIT · "+best.name)}};p.userData.shoot=shoot;
  const down=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.code==="Space"){e.preventDefault();shoot()}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());window.addEventListener("keydown",down);window.addEventListener("keyup",up);
  let drag=false,lastX=0,lastY=0,yaw=0,pitch=-.18;const pd=(e:PointerEvent)=>{drag=true;lastX=e.clientX;lastY=e.clientY};const pm=(e:PointerEvent)=>{if(!drag)return;yaw-=(e.clientX-lastX)*.006;pitch=clamp(pitch-(e.clientY-lastY)*.004,-.65,.3);lastX=e.clientX;lastY=e.clientY};const pu=()=>drag=false;renderer.domElement.addEventListener("pointerdown",pd);renderer.domElement.addEventListener("pointermove",pm);window.addEventListener("pointerup",pu);
  const clock=new THREE.Clock();let raf=0,lastSec=performance.now(),round=240,zr=78;
  const loop=()=>{if(dead)return;const dt=Math.min(.035,clock.getDelta()),now=performance.now();(p.userData.mixer as THREE.AnimationMixer|undefined)?.update(dt);let mx=0,mz=0;if(keys.current.has("w")||keys.current.has("arrowup"))mz-=1;if(keys.current.has("s")||keys.current.has("arrowdown"))mz+=1;if(keys.current.has("a")||keys.current.has("arrowleft"))mx-=1;if(keys.current.has("d")||keys.current.has("arrowright"))mx+=1;const running=keys.current.has("shift")||sprint;if(mx||mz){const ang=yaw,forward=new THREE.Vector3(-Math.sin(ang),0,-Math.cos(ang)),right=new THREE.Vector3(Math.cos(ang),0,-Math.sin(ang)),move=forward.multiplyScalar(-mz).add(right.multiplyScalar(mx)).normalize();p.position.addScaledVector(move,(running?11:7)*dt);p.rotation.y=Math.atan2(move.x,move.z)+Math.PI;}const pr=Math.hypot(p.position.x,p.position.z);if(pr>88){p.position.x*=88/pr;p.position.z*=88/pr}p.position.y=terrainY(p.position.x,p.position.z);
   const look=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch));const desired=p.position.clone().add(new THREE.Vector3(-look.x*9,5-look.y*5,-look.z*9));cam.position.lerp(desired,.16);cam.lookAt(p.position.clone().add(new THREE.Vector3(0,1.6,0)).add(look.multiplyScalar(7)));
   pickups.forEach(m=>{m.rotation.y+=dt*2;m.position.y=terrainY(m.position.x,m.position.z)+1.4+Math.sin(now*.003+m.position.x)*.2;if(m.visible&&m.position.distanceTo(p.position)<2){m.visible=false;if(m.userData.type===0)setShield(v=>Math.min(100,v+50));if(m.userData.type===1){energyRef.current=100;setEnergy(100)}if(m.userData.type===2)setHp(v=>Math.min(100,v+45));setNotice("POWER-UP COLLECTED");setTimeout(()=>m.visible=true,10000)}});
   for(const f of fighters.current){(f.root.userData.mixer as THREE.AnimationMixer|undefined)?.update(dt);if(!f.alive){if(now>f.respawn){f.alive=true;f.root.visible=true;f.hp=100;f.shield=50;const a=Math.random()*Math.PI*2,r=35+Math.random()*30;f.root.position.set(Math.cos(a)*r,0,Math.sin(a)*r);setAlive(1+fighters.current.filter(x=>x.alive).length)}continue}const to=p.position.clone().sub(f.root.position),dist=to.length();if(dist<32){const forward=to.clone().normalize(),side=new THREE.Vector3(-forward.z,0,forward.x).multiplyScalar(f.strafe);const move=dist>15?forward:side;f.root.position.addScaledVector(move,4.4*dt);f.root.rotation.y=Math.atan2(move.x,move.z)+Math.PI;f.cooldown-=dt;if(f.cooldown<=0&&dist<28){f.cooldown=.9+Math.random()*1.2;beam(f.root.position.clone().add(new THREE.Vector3(0,1.5,0)),p.position.clone().add(new THREE.Vector3(0,1.4,0)),0xff4fa3);if(Math.random()<.55)damagePlayer(20)}}else if(Math.random()<.008){const a=Math.random()*Math.PI*2,r=Math.random()*Math.max(15,zr-4);f.target.set(Math.cos(a)*r,0,Math.sin(a)*r)}if(dist>=32){const d=f.target.clone().sub(f.root.position);if(d.length()>.8){d.normalize();f.root.position.addScaledVector(d,3.5*dt);f.root.rotation.y=Math.atan2(d.x,d.z)+Math.PI}}f.root.position.y=terrainY(f.root.position.x,f.root.position.z)}
   if(now-lastSec>1000){lastSec=now;round=Math.max(0,round-1);setTime(round);zr=Math.max(22,78-(240-round)*.24);setZone(Math.round(zr));zoneRing.scale.setScalar(zr/78);setEnergy(v=>{const n=Math.min(100,v+9);energyRef.current=n;return n});if(Math.hypot(p.position.x,p.position.z)>zr)damagePlayer(5);if(round===0){round=240;zr=78;setNotice("NEW ROUND · ZONE RESET")}}
   renderer.render(scene,cam);raf=requestAnimationFrame(loop)};loop();
  const resize=()=>{cam.aspect=host.clientWidth/Math.max(1,host.clientHeight);cam.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};window.addEventListener("resize",resize);return()=>{dead=true;cancelAnimationFrame(raf);window.removeEventListener("resize",resize);window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);window.removeEventListener("pointerup",pu);renderer.dispose();if(host.contains(renderer.domElement))host.removeChild(renderer.domElement)};
 },[self?.characterId,sprint]);
 const fire=()=>{const p=player.current as any;p?.userData?.shoot?.()};
 return <main className="relative h-[100dvh] overflow-hidden bg-sky-900 text-white"><div ref={mount} className="absolute inset-0 touch-none"/>
  <header className="pointer-events-none absolute inset-x-0 top-0 z-30 flex items-center gap-2 bg-gradient-to-b from-black/75 to-transparent p-2 sm:p-4"><button onClick={()=>navigate("/worlds")} className="pointer-events-auto flex min-h-11 items-center gap-2 rounded-xl bg-black/65 px-3 font-black backdrop-blur"><ArrowLeft className="h-4 w-4"/> Worlds</button><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.22em] text-cyan-200">A.R.I.S.E. BATTLE ISLAND</p><h1 className="text-lg font-black">⚡ Laser Royale</h1></div><div className="rounded-xl bg-black/65 px-3 py-2 text-xs font-black"><Trophy className="mr-1 inline h-4 w-4 text-amber-300"/>{score}</div></header>
  <div className="absolute left-3 top-20 z-30 w-40 rounded-2xl bg-black/60 p-3 text-xs font-black backdrop-blur"><div className="mb-1 flex justify-between"><span>❤️ HEALTH</span><span>{hp}</span></div><div className="h-2 rounded bg-white/15"><div className="h-full rounded bg-emerald-400" style={{width:hp+"%"}}/></div><div className="mb-1 mt-2 flex justify-between"><span><Shield className="mr-1 inline h-3 w-3"/>SHIELD</span><span>{shield}</span></div><div className="h-2 rounded bg-white/15"><div className="h-full rounded bg-blue-400" style={{width:shield+"%"}}/></div></div>
  <div className="absolute right-3 top-20 z-30 rounded-2xl bg-black/60 p-3 text-right text-[11px] font-black backdrop-blur"><div><Footprints className="mr-1 inline h-3 w-3"/>{alive} ACTIVE</div><div><Map className="mr-1 inline h-3 w-3"/>ZONE {zone}m</div><div>{Math.floor(time/60)}:{String(time%60).padStart(2,"0")}</div></div>
  <div className="pointer-events-none absolute left-1/2 top-20 z-20 max-w-[48vw] -translate-x-1/2 rounded-full bg-black/50 px-3 py-1 text-center text-[10px] font-black backdrop-blur">{notice}</div>
  <div className="absolute bottom-5 left-4 z-40 flex gap-2"><button onPointerDown={()=>setSprint(true)} onPointerUp={()=>setSprint(false)} className="grid h-16 w-16 place-items-center rounded-full border-2 border-white/30 bg-black/55 text-xs font-black backdrop-blur">SPRINT</button></div>
  <div className="absolute bottom-5 right-4 z-40 flex items-end gap-2"><div className="rounded-xl bg-black/55 px-3 py-2 text-[10px] font-black backdrop-blur"><Zap className="mr-1 inline h-3 w-3 text-amber-300"/>{energy}</div><button onClick={fire} disabled={energy<12} className="grid h-20 w-20 place-items-center rounded-full border-4 border-cyan-100/80 bg-cyan-400 text-slate-950 shadow-[0_0_35px_rgba(34,211,238,.6)] disabled:opacity-40"><Crosshair className="h-9 w-9"/></button></div>
  <div className="pointer-events-none absolute bottom-3 left-1/2 z-20 hidden -translate-x-1/2 rounded-xl bg-black/50 px-3 py-2 text-[10px] font-bold backdrop-blur sm:block">WASD move · Shift sprint · drag to aim/look · Space fires laser · loot power-ups · stay inside the storm ring</div>
 </main>;
}
