import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { ArrowLeft, Crosshair, Gamepad2, Loader2, LogOut, Play, RotateCcw, Shield, Users } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { API_BASE } from "@/lib/queryClient";
import { useLocation } from "wouter";

type Team="cyan"|"magenta";
type Player={id:number;name:string;team:Team;x:number;z:number;rot:number;moving:boolean;sprinting:boolean;tags:number;downs:number;respawnAt:number;bot:boolean};
type Room={code:string;hostId:number;phase:"lobby"|"playing"|"finished";players:Player[];scores:Record<Team,number>;serverNow:number;timeLeft:number;winner:Team|null};
type Lobby={code:string;hostName:string;players:number};
type MobileInput={forward:boolean;back:boolean;left:boolean;right:boolean;sprint:boolean};

function makeCharacter(team:Team,name:string){
 const root=new THREE.Group();
 const color=team==="cyan"?0x22d3ee:0xec4899;
 const dark=new THREE.MeshStandardMaterial({color:0x111827,roughness:.55,metalness:.25});
 const suit=new THREE.MeshStandardMaterial({color,roughness:.58,metalness:.18});
 const skin=new THREE.MeshStandardMaterial({color:0x9b6648,roughness:.9});
 const white=new THREE.MeshStandardMaterial({color:0xf8fafc,roughness:.35,metalness:.15});
 const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.78,6,12),suit);body.position.y=1.55;body.castShadow=true;root.add(body);
 const head=new THREE.Mesh(new THREE.SphereGeometry(.4,18,14),skin);head.position.y=2.63;head.castShadow=true;root.add(head);
 const mask=new THREE.Mesh(new THREE.BoxGeometry(.62,.24,.09),white);mask.position.set(0,2.67,.37);mask.castShadow=true;root.add(mask);
 const visor=new THREE.Mesh(new THREE.BoxGeometry(.5,.11,.04),new THREE.MeshStandardMaterial({color:0x0b1727,metalness:.75,roughness:.15,emissive:color,emissiveIntensity:.2}));visor.position.set(0,2.7,.42);root.add(visor);
 const armL=new THREE.Group(),armR=new THREE.Group(),legL=new THREE.Group(),legR=new THREE.Group();
 for(const [group,x] of [[armL,-.55],[armR,.55]] as const){group.position.set(x,1.98,0);const limb=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.58,5,9),dark);limb.position.y=-.34;limb.castShadow=true;group.add(limb);root.add(group);}
 for(const [group,x] of [[legL,-.22],[legR,.22]] as const){group.position.set(x,1.1,0);const limb=new THREE.Mesh(new THREE.CapsuleGeometry(.15,.72,5,9),dark);limb.position.y=-.42;limb.castShadow=true;group.add(limb);root.add(group);}
 const marker=new THREE.Group();marker.position.set(.3,1.92,.48);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.08,.08,.85,10),dark);barrel.rotation.x=Math.PI/2;barrel.position.z=.38;marker.add(barrel);const hopper=new THREE.Mesh(new THREE.SphereGeometry(.18,12,8),suit);hopper.position.set(0,.19,.12);marker.add(hopper);root.add(marker);
 const tagCanvas=document.createElement("canvas");tagCanvas.width=512;tagCanvas.height=100;const ctx=tagCanvas.getContext("2d")!;ctx.fillStyle="rgba(4,10,20,.82)";ctx.beginPath();ctx.roundRect(4,4,504,92,24);ctx.fill();ctx.fillStyle="#fff";ctx.font="800 38px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(name.slice(0,20),256,50);const tex=new THREE.CanvasTexture(tagCanvas);tex.colorSpace=THREE.SRGBColorSpace;const label=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}));label.scale.set(2.8,.55,1);label.position.y=3.35;root.add(label);
 root.userData={armL,armR,legL,legR,body,step:0};
 return root;
}

function PaintballScene({room,myId,onMove,onShoot,mobile}:{room:Room;myId:number;onMove:(x:number,z:number,rot:number,moving:boolean,sprinting:boolean)=>void;onShoot:(rot:number)=>void;mobile:MobileInput}){
 const host=useRef<HTMLDivElement>(null);
 const roomRef=useRef(room);roomRef.current=room;
 const mobileRef=useRef(mobile);mobileRef.current=mobile;
 const shootRef=useRef(onShoot);shootRef.current=onShoot;
 const moveRef=useRef(onMove);moveRef.current=onMove;
 useEffect(()=>{
  const mount=host.current;if(!mount)return;
  let renderer:THREE.WebGLRenderer|undefined,raf=0,lastSend=0;
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x7dd3fc);scene.fog=new THREE.FogExp2(0x9adcf1,.012);
  const camera=new THREE.PerspectiveCamera(62,1,.1,140);
  try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance",failIfMajorPerformanceCaveat:false});}catch{return;}
  const phone=matchMedia("(max-width: 820px)").matches;renderer.setPixelRatio(Math.min(devicePixelRatio,phone?1.15:1.55));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=!phone;renderer.shadowMap.type=THREE.PCFSoftShadowMap;mount.replaceChildren(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xe8fbff,0x24412c,2.1));const sun=new THREE.DirectionalLight(0xfff4dd,3.8);sun.position.set(18,32,12);sun.castShadow=!phone;scene.add(sun);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(74,74),new THREE.MeshStandardMaterial({color:0x5aa367,roughness:.96}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
  const arena=new THREE.Group();scene.add(arena);
  const obstacle=(x:number,z:number,w:number,h:number,d:number,c:number,rot=0)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.08}));mesh.position.set(x,h/2,z);mesh.rotation.y=rot;mesh.castShadow=true;mesh.receiveShadow=true;arena.add(mesh);return mesh;};
  obstacle(0,0,4,2.2,13,0x334155,.22);obstacle(-12,-9,8,3.2,2,0x155e75,-.38);obstacle(13,9,8,3.2,2,0x9d174d,.38);obstacle(-13,11,5,2.5,5,0x1e293b,.2);obstacle(13,-11,5,2.5,5,0x1e293b,-.2);
  for(const x of [-21,-7,7,21])for(const z of [-18,18])obstacle(x,z,3.5,2.3,1.3,(x+z)%2?0x0891b2:0xdb2777,(x/20)*.25);
  const tower=(x:number,z:number,color:number)=>{const base=new THREE.Mesh(new THREE.CylinderGeometry(3,3,5.2,16),new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.12}));base.position.set(x,2.6,z);base.castShadow=true;arena.add(base);const rail=new THREE.Mesh(new THREE.TorusGeometry(2.5,.08,8,32),new THREE.MeshStandardMaterial({color:0xf8fafc,metalness:.5,roughness:.3}));rail.position.set(x,5.2,z);rail.rotation.x=Math.PI/2;arena.add(rail)};tower(-22,0,0x0e7490);tower(22,0,0xbe185d);
  for(let i=0;i<22;i++){const a=i/22*Math.PI*2,r=31+(i%3);const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.28,.38,3.7,8),new THREE.MeshStandardMaterial({color:0x6b4423}));trunk.position.set(Math.cos(a)*r,1.85,Math.sin(a)*r);arena.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.8,4.6,9),new THREE.MeshStandardMaterial({color:i%2?0x166534:0x15803d}));crown.position.set(trunk.position.x,5.2,trunk.position.z);arena.add(crown);}
  const splashMat=[0x22d3ee,0xec4899,0xfacc15,0x8b5cf6];
  for(let i=0;i<40;i++){const s=new THREE.Mesh(new THREE.CircleGeometry(.18+(i%4)*.06,10),new THREE.MeshBasicMaterial({color:splashMat[i%4],transparent:true,opacity:.45,depthWrite:false}));s.rotation.x=-Math.PI/2;s.position.set(-26+(i*13)%52,.012,-26+(i*17)%52);scene.add(s);}
  const playerGroups=new Map<number,THREE.Group>();
  const particles:{mesh:THREE.Mesh;vel:THREE.Vector3;life:number}[]=[];
  const keys=new Set<string>();let yaw=0,localX=0,localZ=0,initialized=false;
  const ensurePlayers=()=>{for(const p of roomRef.current.players){if(!playerGroups.has(p.id)){const g=makeCharacter(p.team,p.name);scene.add(g);playerGroups.set(p.id,g);}}for(const [id,g] of playerGroups){if(!roomRef.current.players.some(p=>p.id===id)){scene.remove(g);playerGroups.delete(id);}}};
  ensurePlayers();
  const resize=()=>{if(!renderer)return;const w=mount.clientWidth,h=mount.clientHeight;camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();addEventListener("resize",resize);
  const down=(e:KeyboardEvent)=>keys.add(e.key.toLowerCase()),up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());addEventListener("keydown",down);addEventListener("keyup",up);
  const mouse=(e:MouseEvent)=>{if(document.pointerLockElement===renderer?.domElement)yaw-=e.movementX*.0023};addEventListener("mousemove",mouse);
  const pointerDown=(e:PointerEvent)=>{if(e.button===0&&document.pointerLockElement===renderer?.domElement){shootRef.current(yaw);for(let i=0;i<14;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.055,6,5),new THREE.MeshBasicMaterial({color:splashMat[i%4]}));const dir=new THREE.Vector3(Math.sin(yaw),.05+Math.random()*.04,Math.cos(yaw));m.position.set(localX,.95,localZ);scene.add(m);particles.push({mesh:m,vel:dir.multiplyScalar(12+Math.random()*3),life:.65});}}else if(e.button===0&&!phone)renderer?.domElement.requestPointerLock?.();};renderer.domElement.addEventListener("pointerdown",pointerDown);
  const clock=new THREE.Clock();
  const animate=()=>{if(!renderer)return;const dt=Math.min(clock.getDelta(),.04),now=performance.now();ensurePlayers();const state=roomRef.current;const me=state.players.find(p=>p.id===myId);
   if(me){if(!initialized){localX=me.x;localZ=me.z;yaw=me.rot;initialized=true;}if(me.respawnAt){localX=me.x;localZ=me.z;}
    const m=mobileRef.current;const f=(keys.has("w")||keys.has("arrowup")||m.forward?1:0)-(keys.has("s")||keys.has("arrowdown")||m.back?1:0);const r=(keys.has("d")||keys.has("arrowright")||m.right?1:0)-(keys.has("a")||keys.has("arrowleft")||m.left?1:0);const sprint=keys.has("shift")||m.sprint;const mag=Math.hypot(f,r);const moving=mag>.01&&!me.respawnAt;
    if(moving){const speed=(sprint?8.7:6.2)*dt;const nf=f/mag,nr=r/mag;localX+= (Math.sin(yaw)*nf+Math.cos(yaw)*nr)*speed;localZ+=(Math.cos(yaw)*nf-Math.sin(yaw)*nr)*speed;localX=Math.max(-27,Math.min(27,localX));localZ=Math.max(-27,Math.min(27,localZ));}
    if(phone&&Math.abs(r)>.1)yaw-=r*dt*1.55;
    if(now-lastSend>110){lastSend=now;moveRef.current(localX,localZ,yaw,moving,sprint);}
    for(const p of state.players){const g=playerGroups.get(p.id);if(!g)continue;const targetX=p.id===myId?localX:p.x,targetZ=p.id===myId?localZ:p.z;g.position.x+=(targetX-g.position.x)*Math.min(1,dt*11);g.position.z+=(targetZ-g.position.z)*Math.min(1,dt*11);g.rotation.y=p.id===myId?yaw:p.rot;g.visible=!p.respawnAt;const d=g.userData as any;const walk=(p.id===myId?moving:p.moving);if(walk){d.step+=dt*(p.sprinting?12:8);const swing=Math.sin(d.step)*.72;d.armL.rotation.x=swing;d.armR.rotation.x=-swing;d.legL.rotation.x=-swing;d.legR.rotation.x=swing;d.body.position.y=1.55+Math.abs(Math.sin(d.step*2))*.06;}else{d.armL.rotation.x*=.82;d.armR.rotation.x*=.82;d.legL.rotation.x*=.82;d.legR.rotation.x*=.82;d.body.position.y+=(1.55-d.body.position.y)*.18;}}
    const camDist=phone?8.7:7.3,camHeight=phone?4.8:4.1;const tx=localX-Math.sin(yaw)*camDist,tz=localZ-Math.cos(yaw)*camDist;camera.position.x+=(tx-camera.position.x)*Math.min(1,dt*8);camera.position.z+=(tz-camera.position.z)*Math.min(1,dt*8);camera.position.y+=(camHeight-camera.position.y)*Math.min(1,dt*6);camera.lookAt(localX,1.65,localZ);
   }
   for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.vel.y-=3.5*dt;p.mesh.position.addScaledVector(p.vel,dt);if(p.life<=0){scene.remove(p.mesh);p.mesh.geometry.dispose();(p.mesh.material as THREE.Material).dispose();particles.splice(i,1);}}
   renderer.render(scene,camera);raf=requestAnimationFrame(animate);
  };animate();
  return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("mousemove",mouse);renderer?.domElement.removeEventListener("pointerdown",pointerDown);try{document.exitPointerLock?.()}catch{};scene.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose?.();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(mat=>{if("map" in mat)(mat as THREE.MeshBasicMaterial).map?.dispose?.();mat.dispose();});});renderer?.dispose();mount.replaceChildren();};
 },[]);
 return <div ref={host} className="absolute inset-0"/>;
}

export default function PaintballArena(){
 const {user,token}=useAuth();const [,navigate]=useLocation();
 const [room,setRoom]=useState<Room|null>(null),[lobbies,setLobbies]=useState<Lobby[]>([]),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [mobile,setMobile]=useState<MobileInput>({forward:false,back:false,left:false,right:false,sprint:false});
 const myId=Number(user?.id),me=room?.players.find(p=>p.id===myId),host=room?.hostId===myId;
 const roomRef=useRef(room);roomRef.current=room;
 const action=async(body:any)=>{const r=roomRef.current;if(!r||!token)return;try{const res=await fetch(API_BASE+"/api/paintball/rooms/"+r.code+"/action",{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await res.json();if(res.ok)setRoom(data);else setError(data.message||"Action failed.");}catch{}};
 const enter=async(kind:"queue"|"create"|"practice"|"join")=>{if(!token||busy)return;setBusy(true);setError("");try{const path=kind==="queue"?"/api/paintball/queue":kind==="join"?"/api/paintball/rooms/"+code+"/join":"/api/paintball/rooms";const res=await fetch(API_BASE+path,{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify(kind==="practice"?{practice:true}:{publicLobby:kind==="create"})});const data=await res.json();if(res.ok)setRoom(data);else setError(data.message||"Could not enter Paintball Arena.");}catch{setError("Could not reach Paintball Arena.")}finally{setBusy(false)}};
 useEffect(()=>{if(room||!token)return;let stop=false;const load=async()=>{try{const r=await fetch(API_BASE+"/api/paintball/lobbies",{headers:{Authorization:"Bearer "+token}});if(r.ok&&!stop)setLobbies(await r.json())}catch{}};load();const t=setInterval(load,3000);return()=>{stop=true;clearInterval(t)}},[!!room,token]);
 useEffect(()=>{if(!room?.code||!token)return;let stop=false;const poll=async()=>{try{const r=await fetch(API_BASE+"/api/paintball/rooms/"+room.code,{headers:{Authorization:"Bearer "+token},cache:"no-store"});const data=await r.json();if(r.ok&&!stop)setRoom(data);else if(!stop&&r.status===409){setRoom(null);setError(data.message||"Room ended.");}}catch{}if(!stop)setTimeout(poll,180)};const t=setTimeout(poll,180);return()=>{stop=true;clearTimeout(t)}},[room?.code,token]);
 const leave=()=>{if(room&&token)void fetch(API_BASE+"/api/paintball/rooms/"+room.code+"/leave",{method:"POST",headers:{Authorization:"Bearer "+token},keepalive:true});setRoom(null);navigate("/worlds")};
 const setPress=(key:keyof MobileInput,value:boolean)=>setMobile(m=>({...m,[key]:value}));
 const time=room?Math.ceil(room.timeLeft/1000):0;

 if(!room)return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_20%_10%,#164e63,transparent_28%),radial-gradient(circle_at_85%_8%,#831843,transparent_27%),linear-gradient(#050816,#10182c)] p-4 text-white sm:p-8">
  <button onClick={()=>navigate("/worlds")} className="rounded-xl border border-white/10 bg-black/30 px-4 py-3 font-black"><ArrowLeft className="mr-2 inline h-5 w-5"/> Worlds</button>
  <section className="mx-auto mt-5 max-w-6xl overflow-hidden rounded-[2.5rem] border border-white/10 bg-slate-950/70 shadow-[0_40px_100px_rgba(0,0,0,.55)] backdrop-blur-xl">
   <div className="relative min-h-[360px] overflow-hidden bg-[linear-gradient(120deg,rgba(34,211,238,.16),transparent_46%),linear-gradient(240deg,rgba(236,72,153,.17),transparent_48%),#080d18] p-7 sm:p-12">
    <div className="absolute inset-0 opacity-25 [background-image:radial-gradient(circle_at_30%_30%,#22d3ee_0_3px,transparent_4px),radial-gradient(circle_at_70%_50%,#ec4899_0_4px,transparent_5px)] [background-size:55px_55px,71px_71px]"/>
    <div className="relative max-w-3xl"><p className="text-xs font-black uppercase tracking-[.3em] text-cyan-300">A.R.I.S.E. competitive world</p><h1 className="mt-3 text-5xl font-black tracking-[-.05em] sm:text-8xl">PRISM<br/><span className="text-cyan-300">PAINTBALL</span></h1><p className="mt-5 max-w-2xl text-base font-bold leading-7 text-slate-300 sm:text-xl">Fast third-person team paintball with real multiplayer rooms, animated runners, towers, cover, respawns, live scores, and a bright outdoor arena.</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-black"><span className="rounded-full bg-cyan-400/15 px-3 py-2 text-cyan-200">REAL MULTIPLAYER</span><span className="rounded-full bg-pink-400/15 px-3 py-2 text-pink-200">NO GORE</span><span className="rounded-full bg-white/10 px-3 py-2">WASD + TOUCH</span><span className="rounded-full bg-white/10 px-3 py-2">5 MINUTE MATCHES</span></div></div>
   </div>
   <div className="grid gap-4 p-5 sm:p-8 md:grid-cols-[1.1fr_.9fr]"><div><button disabled={busy} onClick={()=>enter("queue")} className="min-h-16 w-full rounded-2xl bg-cyan-300 text-xl font-black text-slate-950 shadow-lg"><Users className="mr-2 inline"/> Join multiplayer match</button><div className="mt-3 grid gap-2">{lobbies.slice(0,5).map(l=><button key={l.code} onClick={()=>{setCode(l.code);setTimeout(()=>enter("join"),0)}} className="flex min-h-14 items-center justify-between rounded-xl border border-white/10 bg-white/5 px-4 text-left"><span><b>{l.hostName}'s arena</b><small className="block text-slate-500">{l.players}/8 players</small></span><span className="font-black text-cyan-300">JOIN</span></button>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><button disabled={busy} onClick={()=>enter("practice")} className="min-h-12 w-full rounded-xl bg-violet-500 font-black">Practice vs computer squad</button><button disabled={busy} onClick={()=>enter("create")} className="mt-2 min-h-12 w-full rounded-xl border border-white/15 bg-white/5 font-black">Create open room</button><div className="mt-3 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="6-digit room" className="min-h-12 min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-900 px-3"/><button disabled={busy||code.length!==6} onClick={()=>enter("join")} className="rounded-xl bg-amber-300 px-4 font-black text-slate-950">Join</button></div></div></div>
   {error&&<p className="mx-5 mb-5 rounded-xl bg-red-500/10 p-3 font-bold text-red-200 sm:mx-8">{error}</p>}
  </section>
 </main>;

 if(room.phase==="lobby")return <main className="min-h-screen bg-[#050816] p-4 text-white sm:p-8"><button onClick={leave} className="rounded-xl bg-white/5 px-4 py-3 font-black"><ArrowLeft className="mr-2 inline h-4 w-4"/> Worlds</button><section className="mx-auto mt-5 max-w-5xl rounded-[2.2rem] border border-white/10 bg-slate-950/80 p-5 shadow-2xl sm:p-8"><p className="text-xs font-black uppercase tracking-[.25em] text-cyan-300">Paintball room {room.code}</p><h1 className="mt-2 text-4xl font-black">Choose your team</h1><div className="mt-6 grid gap-4 md:grid-cols-2">{(["cyan","magenta"] as Team[]).map(team=><div key={team} className={"rounded-2xl border p-4 "+(team==="cyan"?"border-cyan-300/25 bg-cyan-400/5":"border-pink-300/25 bg-pink-400/5")}><h2 className="text-2xl font-black uppercase">{team} squad</h2>{room.players.filter(p=>p.team===team).map(p=><div key={p.id} className="mt-2 flex items-center justify-between rounded-xl bg-black/25 px-3 py-3"><span><b>{p.name}{p.id===myId?" · YOU":""}</b><small className="block text-slate-500">{p.bot?"Computer player":p.id===room.hostId?"Host":"Player"}</small></span></div>)}</div>)}</div><div className="mt-5 flex flex-wrap gap-2">{me&&<button onClick={()=>action({type:"switch-team"})} className="min-h-12 rounded-xl border border-white/15 bg-white/5 px-4 font-black">Switch team</button>}{host&&<button onClick={()=>action({type:"add-bots",count:6})} className="min-h-12 rounded-xl border border-white/15 bg-white/5 px-4 font-black">Fill with computer players</button>}{host?<button disabled={room.players.length<2} onClick={()=>action({type:"start"})} className="min-h-12 flex-1 rounded-xl bg-cyan-300 px-5 font-black text-slate-950"><Play className="mr-2 inline h-4 w-4"/> Start match</button>:<p className="py-3 font-black text-slate-400">Waiting for host…</p>}</div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-red-200">{error}</p>}</section></main>;

 return <main className="relative h-[100dvh] overflow-hidden bg-slate-950 text-white">
  <PaintballScene room={room} myId={myId} mobile={mobile} onMove={(x,z,rot,moving,sprinting)=>void action({type:"move",x,z,rot,moving,sprinting})} onShoot={rot=>void action({type:"shoot",rot})}/>
  <header className="pointer-events-none absolute inset-x-0 top-0 z-30 flex items-start gap-2 p-3 sm:p-4"><button onClick={leave} className="pointer-events-auto rounded-xl border border-white/10 bg-black/65 px-3 py-2 font-black backdrop-blur"><LogOut className="mr-1 inline h-4 w-4"/> Exit</button><div className="mx-auto flex items-center gap-2 rounded-2xl border border-white/10 bg-black/65 px-4 py-2 shadow-xl backdrop-blur"><div className="text-center"><small className="block text-[9px] font-black uppercase text-cyan-300">CYAN</small><b className="text-2xl">{room.scores.cyan}</b></div><div className="px-3 text-center"><small className="block text-[9px] font-black uppercase text-slate-400">TIME</small><b className="text-2xl">{Math.floor(time/60)}:{String(time%60).padStart(2,"0")}</b></div><div className="text-center"><small className="block text-[9px] font-black uppercase text-pink-300">MAGENTA</small><b className="text-2xl">{room.scores.magenta}</b></div></div><div className="rounded-xl border border-white/10 bg-black/65 px-3 py-2 text-right backdrop-blur"><b className="block">{me?.name}</b><small className="font-bold text-slate-400">{me?.tags||0} tags · {me?.downs||0} tagged</small></div></header>
  <div className="pointer-events-none absolute left-1/2 top-1/2 z-20 -translate-x-1/2 -translate-y-1/2"><Crosshair className="h-9 w-9 text-white drop-shadow-[0_2px_6px_rgba(0,0,0,.8)]"/></div>
  <div className="absolute bottom-4 left-4 z-30 hidden rounded-xl border border-white/10 bg-black/55 px-3 py-2 text-xs font-black backdrop-blur md:block">WASD move · Shift sprint · Mouse aim · Click fire</div>
  <div className="absolute bottom-4 left-4 z-30 grid grid-cols-3 gap-2 md:hidden"><span/><button onPointerDown={()=>setPress("forward",true)} onPointerUp={()=>setPress("forward",false)} onPointerCancel={()=>setPress("forward",false)} className="h-14 w-14 rounded-2xl bg-black/65 font-black backdrop-blur">▲</button><span/><button onPointerDown={()=>setPress("left",true)} onPointerUp={()=>setPress("left",false)} onPointerCancel={()=>setPress("left",false)} className="h-14 w-14 rounded-2xl bg-black/65 font-black backdrop-blur">◀</button><button onPointerDown={()=>setPress("back",true)} onPointerUp={()=>setPress("back",false)} onPointerCancel={()=>setPress("back",false)} className="h-14 w-14 rounded-2xl bg-black/65 font-black backdrop-blur">▼</button><button onPointerDown={()=>setPress("right",true)} onPointerUp={()=>setPress("right",false)} onPointerCancel={()=>setPress("right",false)} className="h-14 w-14 rounded-2xl bg-black/65 font-black backdrop-blur">▶</button></div>
  <div className="absolute bottom-5 right-4 z-30 flex gap-2 md:hidden"><button onPointerDown={()=>setPress("sprint",true)} onPointerUp={()=>setPress("sprint",false)} className="h-16 w-16 rounded-full border-2 border-white/20 bg-amber-400/85 text-xs font-black text-slate-950 shadow-xl">RUN</button><button onClick={()=>action({type:"shoot",rot:me?.rot||0})} className="h-20 w-20 rounded-full border-4 border-white bg-pink-500 font-black shadow-2xl">FIRE</button></div>
  {me?.respawnAt? <div className="absolute inset-0 z-40 grid place-items-center bg-black/45 backdrop-blur-sm"><div className="rounded-[2rem] border border-white/15 bg-slate-950/90 px-8 py-6 text-center shadow-2xl"><Shield className="mx-auto h-12 w-12 text-cyan-300"/><h2 className="mt-2 text-3xl font-black">Paint tagged!</h2><p className="mt-1 font-bold text-slate-400">Respawning at your team base…</p></div></div>:null}
  {room.phase==="finished"&&<div className="absolute inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur"><div className="max-w-lg rounded-[2.2rem] border border-white/15 bg-slate-950/95 p-8 text-center shadow-2xl"><h2 className="text-5xl font-black">{room.winner?room.winner.toUpperCase()+" WINS!":"DRAW!"}</h2><p className="mt-3 text-xl font-bold text-slate-300">{room.scores.cyan} – {room.scores.magenta}</p>{host?<button onClick={()=>action({type:"restart"})} className="mt-5 min-h-14 w-full rounded-xl bg-cyan-300 font-black text-slate-950"><RotateCcw className="mr-2 inline"/> Play again</button>:<p className="mt-4 font-bold text-slate-400">Waiting for host…</p>}</div></div>}
 </main>;
}
