import { useEffect,useRef,useState } from "react";
import * as THREE from "three";
import { ArrowLeft, Flag, RotateCcw, Sparkles, Trophy } from "lucide-react";
import { useLocation } from "wouter";

type Touch={left:boolean;right:boolean;jump:boolean};

function hero(){
 const root=new THREE.Group();const suit=new THREE.MeshStandardMaterial({color:0x5b5df5,roughness:.6});const dark=new THREE.MeshStandardMaterial({color:0x172033,roughness:.7});const skin=new THREE.MeshStandardMaterial({color:0xa96f50,roughness:.9});
 const body=new THREE.Mesh(new THREE.CapsuleGeometry(.35,.7,6,10),suit);body.position.y=1.4;root.add(body);
 const head=new THREE.Mesh(new THREE.SphereGeometry(.34,16,12),skin);head.position.y=2.35;root.add(head);
 const scarf=new THREE.Mesh(new THREE.TorusGeometry(.39,.07,8,18,Math.PI*1.6),new THREE.MeshStandardMaterial({color:0xfbbf24,roughness:.5}));scarf.position.y=1.94;scarf.rotation.x=Math.PI/2;root.add(scarf);
 const armL=new THREE.Group(),armR=new THREE.Group(),legL=new THREE.Group(),legR=new THREE.Group();
 for(const [g,x] of [[armL,-.46],[armR,.46]] as const){g.position.set(x,1.72,0);const m=new THREE.Mesh(new THREE.CapsuleGeometry(.1,.5,5,8),dark);m.position.y=-.28;g.add(m);root.add(g)}
 for(const [g,x] of [[legL,-.2],[legR,.2]] as const){g.position.set(x,1.03,0);const m=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.58,5,8),dark);m.position.y=-.34;g.add(m);root.add(g)}
 root.userData={body,armL,armR,legL,legR,step:0};return root;
}

export default function SkyboundSprint(){
 const [,navigate]=useLocation();const mount=useRef<HTMLDivElement>(null);const [status,setStatus]=useState<"play"|"win">("play"),[gems,setGems]=useState(0),[checkpoint,setCheckpoint]=useState(0),[touch,setTouch]=useState<Touch>({left:false,right:false,jump:false}),[reset,setReset]=useState(0);const touchRef=useRef(touch);touchRef.current=touch;
 useEffect(()=>{const host=mount.current;if(!host)return;let renderer:THREE.WebGLRenderer|undefined,raf=0;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance",failIfMajorPerformanceCaveat:false})}catch{return}const phone=matchMedia("(max-width:820px)").matches;renderer.setPixelRatio(Math.min(devicePixelRatio,phone?1.15:1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=!phone;host.replaceChildren(renderer.domElement);
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x92dcff);scene.fog=new THREE.Fog(0xc7efff,45,115);const camera=new THREE.PerspectiveCamera(55,1,.1,180);scene.add(new THREE.HemisphereLight(0xffffff,0x39496a,2.3));const sun=new THREE.DirectionalLight(0xfff1c5,4);sun.position.set(-15,30,15);sun.castShadow=!phone;scene.add(sun);
  const cloudMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:1,transparent:true,opacity:.9});for(let i=0;i<22;i++){const g=new THREE.Group();for(let j=0;j<4;j++){const c=new THREE.Mesh(new THREE.SphereGeometry(1.5+(j%2)*.7,12,8),cloudMat);c.position.set(j*1.6,Math.sin(j)*.3,0);g.add(c)}g.position.set(-10+i*10,10+(i%4)*2,-12-(i%3)*5);scene.add(g)}
  const sea=new THREE.Mesh(new THREE.PlaneGeometry(240,70),new THREE.MeshStandardMaterial({color:0x1ba6c9,roughness:.3,metalness:.05,transparent:true,opacity:.92}));sea.rotation.x=-Math.PI/2;sea.position.set(85,-5,-3);scene.add(sea);
  type P={x:number;y:number;w:number;h:number;moving?:boolean;baseY?:number};const platforms:P[]=[{x:0,y:0,w:12,h:2},{x:15,y:2,w:8,h:2},{x:27,y:4,w:7,h:2},{x:38,y:1,w:9,h:2},{x:51,y:5,w:8,h:2},{x:64,y:8,w:8,h:2,moving:true,baseY:8},{x:78,y:4,w:10,h:2},{x:93,y:7,w:7,h:2},{x:106,y:10,w:8,h:2,moving:true,baseY:10},{x:120,y:6,w:10,h:2},{x:137,y:9,w:8,h:2},{x:151,y:12,w:8,h:2},{x:166,y:8,w:16,h:2}];
  const platMeshes:THREE.Mesh[]=[];for(const p of platforms){const m=new THREE.Mesh(new THREE.BoxGeometry(p.w,p.h,8),new THREE.MeshStandardMaterial({color:0x5abf7a,roughness:.78}));m.position.set(p.x,p.y-p.h/2,0);m.castShadow=true;m.receiveShadow=true;scene.add(m);platMeshes.push(m);const rock=new THREE.Mesh(new THREE.ConeGeometry(p.w*.43,Math.max(3,p.w*.6),6),new THREE.MeshStandardMaterial({color:0x536273,roughness:.9}));rock.position.set(p.x,p.y-p.h-Math.max(3,p.w*.3),0);rock.rotation.y=Math.PI/6;scene.add(rock)}
  const gemPositions=[8,18,29,41,54,66,80,95,108,123,139,153,169].map((x,i)=>({x,y:platforms[Math.min(i,platforms.length-1)].y+2.2,got:false}));const gemMeshes=gemPositions.map((g,i)=>{const m=new THREE.Mesh(new THREE.OctahedronGeometry(.55,0),new THREE.MeshStandardMaterial({color:i%2?0xf472b6:0x67e8f9,emissive:i%2?0x831843:0x155e75,emissiveIntensity:.9,metalness:.25,roughness:.2}));m.position.set(g.x,g.y,0);scene.add(m);return m});
  const botData=[{x:35,y:3,min:33,max:43,dir:1},{x:87,y:6,min:83,max:96,dir:-1},{x:133,y:11,min:130,max:143,dir:1}];const bots=botData.map(b=>{const g=new THREE.Group();const body=new THREE.Mesh(new THREE.SphereGeometry(.6,14,10),new THREE.MeshStandardMaterial({color:0xff7a59,metalness:.25,roughness:.5}));g.add(body);for(const x of [-.23,.23]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.08,8,6),new THREE.MeshBasicMaterial({color:0xffffff}));eye.position.set(x,.12,.55);g.add(eye)}g.position.set(b.x,b.y,0);scene.add(g);return g});
  const goal=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(1.5,.16,12,36),new THREE.MeshStandardMaterial({color:0xfbbf24,emissive:0xf59e0b,emissiveIntensity:1.1,metalness:.45,roughness:.2}));ring.rotation.y=Math.PI/2;goal.add(ring);const core=new THREE.Mesh(new THREE.CircleGeometry(1.25,32),new THREE.MeshBasicMaterial({color:0x8b5cf6,transparent:true,opacity:.36,side:THREE.DoubleSide}));core.rotation.y=Math.PI/2;goal.add(core);goal.position.set(172,11,0);scene.add(goal);
  const player=hero();scene.add(player);let x=0,y=2.2,vx=0,vy=0,onGround=false,cpX=0,cpY=2.2,gemCount=0;const keys=new Set<string>(),clock=new THREE.Clock();let jumpLatch=false;
  const kd=(e:KeyboardEvent)=>{keys.add(e.key.toLowerCase());if(e.code==="Space")e.preventDefault()},ku=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());addEventListener("keydown",kd);addEventListener("keyup",ku);
  const respawn=()=>{x=cpX;y=cpY;vx=0;vy=0};
  const resize=()=>{if(!renderer)return;const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();addEventListener("resize",resize);
  const animate=()=>{if(!renderer)return;const dt=Math.min(clock.getDelta(),.035),t=clock.elapsedTime;platforms.forEach((p,i)=>{if(p.moving){p.y=(p.baseY||0)+Math.sin(t*1.2+i)*2;platMeshes[i].position.y=p.y-p.h/2}});
   const T=touchRef.current,left=keys.has("a")||keys.has("arrowleft")||T.left,right=keys.has("d")||keys.has("arrowright")||T.right,jump=keys.has(" ")||keys.has("w")||keys.has("arrowup")||T.jump;const dir=(right?1:0)-(left?1:0);vx+=(dir*14-vx)*Math.min(1,dt*8);if(Math.abs(dir)<.1)vx*=Math.pow(.001,dt);if(jump&&onGround&&!jumpLatch){vy=11.5;onGround=false}jumpLatch=jump;vy-=25*dt;x+=vx*dt;y+=vy*dt;
   onGround=false;for(const p of platforms){if(x>p.x-p.w/2+.2&&x<p.x+p.w/2-.2&&y<=p.y+1.15&&y-vy*dt>=p.y-.2&&vy<=0){y=p.y+1.15;vy=0;onGround=true;}}
   if(y<-7)respawn();for(let i=0;i<botData.length;i++){const b=botData[i];b.x+=b.dir*dt*2.4;if(b.x>b.max||b.x<b.min)b.dir*=-1;bots[i].position.x=b.x;bots[i].rotation.y=b.dir>0?Math.PI/2:-Math.PI/2;if(Math.hypot(x-b.x,y-b.y)<1.15)respawn();}
   gemPositions.forEach((g,i)=>{gemMeshes[i].rotation.y+=dt*2.2;gemMeshes[i].position.y=g.y+Math.sin(t*3+i)*.22;if(!g.got&&Math.hypot(x-g.x,y-g.y)<1.3){g.got=true;gemMeshes[i].visible=false;gemCount++;setGems(gemCount)}});if(x>74&&cpX<74){cpX=78;cpY=7;setCheckpoint(1)}if(x>126&&cpX<126){cpX=130;cpY=10;setCheckpoint(2)}if(x>168&&Math.abs(y-11)<4){setStatus("win");}
   player.position.set(x,y-1.15,0);player.rotation.y=dir<0?-Math.PI/2:dir>0?Math.PI/2:player.rotation.y;const d=player.userData as any;if(Math.abs(vx)>1&&onGround){d.step+=dt*10;const s=Math.sin(d.step)*.75;d.armL.rotation.x=s;d.armR.rotation.x=-s;d.legL.rotation.x=-s;d.legR.rotation.x=s;d.body.position.y=1.4+Math.abs(Math.sin(d.step*2))*.05}else{d.armL.rotation.x*=.82;d.armR.rotation.x*=.82;d.legL.rotation.x*=.82;d.legR.rotation.x*=.82}
   const targetCamX=x+phone?0:0;camera.position.x+=(x+5-camera.position.x)*Math.min(1,dt*4.5);camera.position.y+=(Math.max(6,y+4)-camera.position.y)*Math.min(1,dt*4);camera.position.z+=(phone?15:13-camera.position.z)*Math.min(1,dt*4);camera.lookAt(x+2,y+.8,0);goal.rotation.z+=dt*.6;renderer.render(scene,camera);raf=requestAnimationFrame(animate)};animate();
  return()=>{cancelAnimationFrame(raf);removeEventListener("keydown",kd);removeEventListener("keyup",ku);removeEventListener("resize",resize);scene.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose?.();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(v=>v.dispose())});renderer?.dispose();host.replaceChildren()};
 },[reset]);
 const press=(k:keyof Touch,v:boolean)=>setTouch(t=>({...t,[k]:v}));
 return <main className="relative h-[100dvh] overflow-hidden bg-sky-300 text-white"><div ref={mount} className="absolute inset-0"/><header className="pointer-events-none absolute inset-x-0 top-0 z-30 flex items-start gap-2 p-3"><button onClick={()=>navigate("/worlds")} className="pointer-events-auto rounded-xl bg-slate-950/70 px-3 py-2 font-black backdrop-blur"><ArrowLeft className="mr-1 inline h-4 w-4"/> Worlds</button><div className="mx-auto rounded-2xl bg-slate-950/65 px-5 py-2 text-center shadow-xl backdrop-blur"><small className="block text-[9px] font-black uppercase tracking-[.2em] text-cyan-300">Skybound Sprint</small><b className="text-xl"><Sparkles className="mr-1 inline h-4 w-4 text-amber-300"/> {gems}/13 crystals · Checkpoint {checkpoint+1}/3</b></div><button onClick={()=>{setGems(0);setCheckpoint(0);setStatus("play");setReset(n=>n+1)}} className="pointer-events-auto grid h-11 w-11 place-items-center rounded-xl bg-slate-950/70 backdrop-blur"><RotateCcw/></button></header><div className="absolute bottom-4 left-4 z-30 hidden rounded-xl bg-slate-950/65 px-3 py-2 text-xs font-black backdrop-blur md:block">A / D run · SPACE jump · Reach the golden portal</div><div className="absolute bottom-4 left-4 z-30 flex gap-2 md:hidden"><button onPointerDown={()=>press("left",true)} onPointerUp={()=>press("left",false)} onPointerCancel={()=>press("left",false)} className="h-16 w-16 rounded-full bg-slate-950/65 text-2xl font-black backdrop-blur">◀</button><button onPointerDown={()=>press("right",true)} onPointerUp={()=>press("right",false)} onPointerCancel={()=>press("right",false)} className="h-16 w-16 rounded-full bg-slate-950/65 text-2xl font-black backdrop-blur">▶</button></div><button onPointerDown={()=>press("jump",true)} onPointerUp={()=>press("jump",false)} onPointerCancel={()=>press("jump",false)} className="absolute bottom-4 right-4 z-30 h-20 w-20 rounded-full border-4 border-white bg-violet-500 text-sm font-black shadow-2xl md:hidden">JUMP</button>{status==="win"&&<div className="absolute inset-0 z-50 grid place-items-center bg-slate-950/70 p-4 backdrop-blur"><div className="max-w-lg rounded-[2rem] border border-white/15 bg-slate-950/95 p-8 text-center shadow-2xl"><Trophy className="mx-auto h-14 w-14 text-amber-300"/><h2 className="mt-2 text-5xl font-black">ISLAND CLEARED!</h2><p className="mt-3 text-lg font-bold text-slate-300">You reached the portal with {gems} crystals.</p><button onClick={()=>{setGems(0);setCheckpoint(0);setStatus("play");setReset(n=>n+1)}} className="mt-5 min-h-14 w-full rounded-xl bg-violet-500 font-black">Play again</button></div></div>}</main>;
}
