import { useEffect, useRef, useState } from "react";
import { ArrowLeft, CheckCircle2, Maximize2, MonitorPlay, Radio, RefreshCw } from "lucide-react";
import { useLocation } from "wouter";
import { useAuth } from "@/context/AuthContext";
import { API_BASE } from "@/lib/queryClient";

type SceneLabel={name:string;x:number;y:number};
type Scene={id:string;bookTitle:string;author?:string;chapterStart:number;chapterEnd:number;imageUrl?:string|null;characterLabels?:SceneLabel[]};
type LiveQuestion={id:string;prompt:string;options:string[]};
type LivePayload={id:string;code:string;teacherName:string;status:"live"|"ended";updatedAt:string;viewerCount:number;scene:Scene|null;currentQuestion?:LiveQuestion|null;myAnswer?:{choice:string;submittedAt:string}|null};

function getTokenFromCookie():string|null{try{for(const cookie of document.cookie.split(";")){const value=cookie.trim();if(!value.startsWith("arise_session="))continue;const data=JSON.parse(atob(value.substring("arise_session=".length)));return data.token||null;}}catch{}return null;}
function codeFromHash(){try{return String(new URLSearchParams(window.location.hash.split("?")[1]||"").get("code")||"").trim().toUpperCase().slice(0,6);}catch{return "";}}
function SceneVisual({scene}:{scene:Scene}){return <div className="relative inline-block max-h-full max-w-full">{scene.imageUrl&&<img key={scene.id} src={scene.imageUrl} alt={scene.bookTitle+" live classroom Scene"} className="block max-h-full max-w-full object-contain"/>}{(scene.characterLabels||[]).map((label,i)=><div key={label.name+i} className="pointer-events-none absolute z-10 -translate-x-1/2 -translate-y-full" style={{left:label.x+"%",top:label.y+"%"}}><div className="rounded-full border-2 border-white bg-black/85 px-3 py-1 text-xs font-black text-white shadow-xl sm:text-sm">{label.name}</div><div className="mx-auto h-3 w-0.5 bg-white"/></div>)}</div>}

export default function StudentSceneLive(){
  const {user}=useAuth(); const [,navigate]=useLocation();
  const [code,setCode]=useState(codeFromHash()); const [live,setLive]=useState<LivePayload|null>(null);
  const [joining,setJoining]=useState(false); const [answering,setAnswering]=useState(false); const [error,setError]=useState("");
  const autoJoined=useRef(false); const home=user?.is_eye_gaze_user?"/eye-gaze-home":"/library";

  const request=async(path:string,options:RequestInit={})=>{const token=getTokenFromCookie();const response=await fetch(`${API_BASE}${path}`,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}),...options.headers},cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Something went wrong.");return data;};

  const join=async(value=code)=>{const clean=String(value||"").trim().toUpperCase();if(!/^[A-Z2-9]{6}$/.test(clean)){setError("Enter the 6-character code from your teacher.");return;}setJoining(true);setError("");try{const data=await request("/api/scenes/live/join",{method:"POST",body:JSON.stringify({code:clean})});setCode(clean);setLive(data);const nextHash=`#/scene-live?code=${encodeURIComponent(clean)}`;if(window.location.hash!==nextHash)window.history.replaceState(null,"",nextHash);}catch(err){setLive(null);setError(err instanceof Error?err.message:"Could not join that Scene.");}finally{setJoining(false);}};

  useEffect(()=>{if(!user)return;if(user.role!=="student"||user.isAdmin){navigate("/");return;}const initial=codeFromHash();if(initial&&!autoJoined.current){autoJoined.current=true;setCode(initial);void join(initial);}},[user?.id]);
  useEffect(()=>{if(!live?.code||live.status!=="live")return;const refresh=async()=>{try{setLive(await request(`/api/scenes/live/${live.code}`));}catch(err){setError(err instanceof Error?err.message:"Lost connection to the live Scene.");}};const timer=window.setInterval(refresh,900);return()=>window.clearInterval(timer);},[live?.code,live?.status]);

  const submitAnswer=async(choice:string)=>{if(!live?.code||!live.currentQuestion||live.myAnswer)return;setAnswering(true);setError("");try{await request(`/api/scenes/live/${live.code}/answer`,{method:"POST",body:JSON.stringify({choice})});setLive(current=>current?{...current,myAnswer:{choice,submittedAt:new Date().toISOString()}}:current);}catch(err){setError(err instanceof Error?err.message:"Could not send your answer.");}finally{setAnswering(false);}};
  const fullscreen=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();}catch{}};

  if(!user||user.role!=="student"||user.isAdmin)return null;
  if(!live)return <main className="min-h-screen bg-gradient-to-br from-[#0b0b18] via-[#14112c] to-[#081c26] px-4 py-8 text-white"><div className="mx-auto max-w-lg"><button onClick={()=>navigate(home)} className="mb-8 inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 font-bold"><ArrowLeft size={18}/>Back</button><section className="rounded-[28px] border border-cyan-300/20 bg-white/[.06] p-6 shadow-2xl sm:p-8"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400"><MonitorPlay size={30}/></div><div className="mt-5 text-center"><div className="text-xs font-black uppercase tracking-[.24em] text-cyan-300">Live with your teacher</div><h1 className="mt-2 text-3xl font-black">Join Teacher Scene</h1><p className="mt-2 text-sm leading-6 text-slate-300">Your Scene and any live questions will follow your teacher automatically.</p></div><input value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,"").slice(0,6))} onKeyDown={e=>{if(e.key==="Enter")void join();}} placeholder="ABC234" className="mt-7 h-16 w-full rounded-2xl border border-white/15 bg-black/30 px-4 text-center text-3xl font-black tracking-[.28em]"/>{error&&<div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm font-bold text-red-200">{error}</div>}<button disabled={joining||code.length!==6} onClick={()=>void join()} className="mt-5 inline-flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-violet-500 via-fuchsia-500 to-cyan-400 text-lg font-black disabled:opacity-50"><Radio size={20}/>{joining?"Joining...":"Join live Scene"}</button></section></div></main>;

  const question=live.currentQuestion;
  return <main className="fixed inset-0 z-[340] flex flex-col bg-black text-white">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 bg-[#090914] px-4 py-3 sm:px-6"><div className="min-w-0"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.22em] text-emerald-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>{live.status==="live"?"Live Scene":"Session ended"}</div><h1 className="m-0 mt-1 truncate text-lg font-black sm:text-2xl">{live.scene?.bookTitle||"Teacher Scene"}</h1>{live.scene&&<div className="text-xs font-bold text-slate-400">Ch. {live.scene.chapterStart}{live.scene.chapterEnd!==live.scene.chapterStart?`–${live.scene.chapterEnd}`:""} • {live.teacherName}</div>}</div><div className="flex items-center gap-2"><div className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-center"><div className="text-[9px] font-black uppercase text-slate-400">Code</div><div className="font-black tracking-[.16em]">{live.code}</div></div><button onClick={()=>void fullscreen()} className="grid h-11 w-11 place-items-center rounded-xl bg-white/5"><Maximize2 size={18}/></button><button onClick={()=>navigate(home)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white/5 px-3 text-sm font-black"><ArrowLeft size={17}/>Exit</button></div></header>

    <div className={`grid min-h-0 flex-1 ${question?"lg:grid-cols-[minmax(0,1fr)_420px]":""}`}>
      <section className="relative flex min-h-0 items-center justify-center overflow-auto p-2 sm:p-5">{live.scene?.imageUrl?<SceneVisual scene={live.scene}/>:<div className="p-8 text-center text-slate-400"><RefreshCw className="mx-auto mb-3"/>Waiting for your teacher's Scene...</div>}</section>
      {question&&<aside className="overflow-y-auto border-l border-white/10 bg-[#0d0d17] p-5 sm:p-6"><div className="text-[10px] font-black uppercase tracking-[.22em] text-violet-300">Your teacher is asking</div><h2 className="mt-2 text-2xl font-black leading-tight">{question.prompt}</h2><div className="mt-5 grid gap-3">{question.options.map((option,index)=>{const letter=["A","B","C","D"][index];const chosen=live.myAnswer?.choice===letter;return <button key={letter} disabled={!!live.myAnswer||answering} onClick={()=>void submitAnswer(letter)} className={`flex min-h-16 items-center gap-3 rounded-2xl border p-3 text-left transition disabled:cursor-default ${chosen?"border-emerald-300 bg-emerald-400/15":"border-white/10 bg-white/[.05] hover:bg-white/[.1]"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl font-black ${chosen?"bg-emerald-300 text-slate-950":"bg-violet-500"}`}>{letter}</span><span className="font-bold">{option}</span></button>})}</div>{live.myAnswer&&<div className="mt-5 flex items-center gap-3 rounded-2xl border border-emerald-400/30 bg-emerald-500/10 p-4 text-emerald-200"><CheckCircle2/><div><div className="font-black">Answer sent</div><div className="text-xs text-emerald-100/70">Only your teacher can see the class responses.</div></div></div>}{error&&<div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm font-bold text-red-200">{error}</div>}</aside>}
    </div>

    {live.status==="ended"&&<div className="absolute inset-0 z-50 grid place-items-center bg-black/75 p-6 backdrop-blur-sm"><div className="max-w-md rounded-3xl border border-white/10 bg-[#12121d] p-7 text-center"><h2 className="text-2xl font-black">Live Scene finished</h2><p className="mt-2 text-slate-300">Your teacher ended this presentation.</p><button onClick={()=>navigate(home)} className="mt-5 min-h-12 rounded-xl bg-cyan-300 px-5 font-black text-slate-950">Back to A.R.I.S.E.</button></div></div>}
  </main>;
}
