import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "wouter";
import * as THREE from "three";
import { API_BASE } from "@/lib/queryClient";
import { useAuth } from "@/context/AuthContext";
import { ArrowLeft, Bot, ChevronDown, Crown, Flag, RotateCcw, Sparkles, Trophy, Users, Volume2, VolumeX, X, Zap } from "lucide-react";
import "./ultimate-chess.css";

type Move={from:string;to:string;promotion?:"q"|"r"|"b"|"n";capture?:boolean};
type State={board:(string|null)[][];turn:1|2;winner:0|1|2|null;result:string|null;check:boolean;legalMoves:Move[];lastMove:Move|null;moveHistory:string[];captured:string[];computer?:boolean;computerLevel?:number;clocks:[number,number]};
type Match={id:string;status:"waiting"|"active"|"finished"|"cancelled";player1_id:number;player2_id:number|null;state:State;youAre:1|2;statusText?:string;players:Array<{user_id:number;display_name:string}>};
type Rank={userId:number;displayName:string;wins:number;draws:number;losses:number;games:number;points:number;winRate:number;rank:number};
const P:Record<string,string>={wK:"♔",wQ:"♕",wR:"♖",wB:"♗",wN:"♘",wP:"♙",bK:"♚",bQ:"♛",bR:"♜",bB:"♝",bN:"♞",bP:"♟"};
const N:Record<string,string>={K:"King",Q:"Queen",R:"Rook",B:"Bishop",N:"Knight",P:"Pawn"};
const FILES="abcdefgh";
const LEVELS=[["Rookie","Relaxed"],["Challenger","Tactical"],["Master","Plans ahead"],["Titan","Maximum"]];
const TIMES=[[300,"5 min"],[600,"10 min"],[900,"15 min"],[1800,"30 min"]] as const;
function clock(ms:number){const s=Math.max(0,Math.ceil((Number(ms)||0)/1000));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0");}
function sq(r:number,c:number){return FILES[c]+(8-r);}
function winner(match:Match,self:number|undefined){if(match.state.winner===0)return ["Draw!","Evenly matched. Great game."];const won=(match.state.winner===1&&match.player1_id===self)||(match.state.winner===2&&match.player2_id===self);const why=match.state.result==="checkmate"?"Checkmate.":match.state.result==="timeout"?"Time expired.":match.state.result==="resignation"?"Resignation.":"Match complete.";return won?["Victory!",why+" You ruled the board."]:["Good game!",why+" Ready for a rematch?"];}
function atmosphere(el:HTMLDivElement){
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x05040b);scene.fog=new THREE.FogExp2(0x080716,.025);
  const camera=new THREE.PerspectiveCamera(52,1,.1,100);camera.position.set(0,8.5,17);
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;el.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0x9ac8ff,0x1b1026,1.5));
  const gold=new THREE.PointLight(0xfbbf24,18,28,2);gold.position.set(7,7,-3);scene.add(gold);
  const violet=new THREE.PointLight(0x7c3aed,26,34,2);violet.position.set(-8,5,1);scene.add(violet);
  const floor=new THREE.Mesh(new THREE.CircleGeometry(20,80),new THREE.MeshStandardMaterial({color:0x090817,metalness:.5,roughness:.4}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.2;scene.add(floor);
  const dais=new THREE.Mesh(new THREE.CylinderGeometry(7.5,8,.8,64),new THREE.MeshStandardMaterial({color:0x16112a,metalness:.5,roughness:.35}));dais.position.y=-.78;scene.add(dais);
  const ring=new THREE.Mesh(new THREE.TorusGeometry(7.5,.06,10,100),new THREE.MeshStandardMaterial({color:0xf6c453,emissive:0xf6c453,emissiveIntensity:3}));ring.rotation.x=Math.PI/2;ring.position.y=-.35;scene.add(ring);
  const stars=new THREE.BufferGeometry(),a=new Float32Array(420*3);for(let i=0;i<420;i++){a[i*3]=(Math.random()-.5)*45;a[i*3+1]=Math.random()*20;a[i*3+2]=(Math.random()-.5)*35-7;}stars.setAttribute("position",new THREE.BufferAttribute(a,3));const field=new THREE.Points(stars,new THREE.PointsMaterial({color:0xc4b5fd,size:.06}));scene.add(field);
  for(const x of [-9,-7,7,9]){const col=new THREE.Mesh(new THREE.CylinderGeometry(.38,.5,7,24),new THREE.MeshStandardMaterial({color:0x19162b,roughness:.7}));col.position.set(x,2,-7);scene.add(col);}
  const resize=()=>{const w=Math.max(1,el.clientWidth),h=Math.max(1,el.clientHeight);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);camera.position.z=w<700?21:17;};resize();addEventListener("resize",resize);
  let raf=0;const animate=()=>{field.rotation.y+=.00015;ring.rotation.z+=.0007;renderer.render(scene,camera);raf=requestAnimationFrame(animate);};animate();
  return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);renderer.dispose();scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();});if(renderer.domElement.parentNode===el)el.removeChild(renderer.domElement);};
}
export default function UltimateChess(){
  const {token}=useAuth();const [,go]=useLocation();const bg=useRef<HTMLDivElement>(null);const audio=useRef<AudioContext|null>(null);const last=useRef("");
  const [boot,setBoot]=useState<any>(null),[match,setMatch]=useState<Match|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  const [mode,setMode]=useState<"computer"|"multiplayer">("computer"),[level,setLevel]=useState(2),[time,setTime]=useState(600),[selected,setSelected]=useState<string|null>(null);
  const [promo,setPromo]=useState<{from:string;to:string;choices:string[]}|null>(null),[sound,setSound]=useState(true),[message,setMessage]=useState(""),[intro,setIntro]=useState(false);
  const [ranks,setRanks]=useState<Rank[]>([]),[showRanks,setShowRanks]=useState(false),[movesOpen,setMovesOpen]=useState(false);
  const headers=useMemo(()=>({Authorization:"Bearer "+token,"Content-Type":"application/json"}),[token]);
  useEffect(()=>{if(bg.current)return atmosphere(bg.current);},[]);
  useEffect(()=>{if(!token)return;let live=true;(async()=>{try{const r=await fetch(API_BASE+"/api/chess/bootstrap",{headers:{Authorization:"Bearer "+token},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);if(live)setBoot(d);}catch(e:any){if(live)setMessage(e.message||"Could not enter Chess.");}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[token]);
  useEffect(()=>{if(!match||!["waiting","active"].includes(match.status)||!token)return;let live=true;const poll=async()=>{try{const r=await fetch(API_BASE+"/api/chess/matches/"+match.id,{headers:{Authorization:"Bearer "+token},cache:"no-store"});const d=await r.json();if(r.ok&&live)setMatch(d);}catch{}};const id=setInterval(poll,850);return()=>{live=false;clearInterval(id);};},[match?.id,match?.status,token]);
  const beep=(kind:"move"|"hit"|"check"|"start"|"win")=>{if(!sound)return;try{const AC=window.AudioContext||(window as any).webkitAudioContext;let ctx=audio.current;if(!ctx||ctx.state==="closed"){ctx=new AC();audio.current=ctx;}if(ctx.state==="suspended")void ctx.resume();const plan=kind==="move"?[190,145]:kind==="hit"?[120,82]:kind==="check"?[330,440,660]:kind==="win"?[392,523,659,784]:[110,220,330];plan.forEach((f,i)=>{const o=ctx!.createOscillator(),g=ctx!.createGain(),t=ctx!.currentTime+i*.07;o.type=i%2?"triangle":"sine";o.frequency.value=f;g.gain.setValueAtTime(.055,t);g.gain.exponentialRampToValueAtTime(.0001,t+.12);o.connect(g);g.connect(ctx!.destination);o.start(t);o.stop(t+.14);});}catch{}};
  useEffect(()=>{const m=match?.state?.lastMove;if(!m)return;const key=m.from+m.to+(m.promotion||"");if(key===last.current)return;last.current=key;beep(match?.state.check?"check":m.capture?"hit":"move");},[match?.state?.lastMove?.from,match?.state?.lastMove?.to,match?.state?.check]);
  const start=async()=>{if(!boot?.access?.allowed){setMessage(boot?.access?.locked?"Your teacher has locked game play.":"You need another available game play.");return;}try{setBusy(true);setMessage("");beep("start");const r=await fetch(API_BASE+"/api/chess/matches/join",{method:"POST",headers,body:JSON.stringify({computer:mode==="computer",computerLevel:level,timeControlSec:time})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMatch(d);setSelected(null);if(d.status==="active"){setIntro(true);setTimeout(()=>setIntro(false),2300);}}catch(e:any){setMessage(e.message||"Could not start Chess.");}finally{setBusy(false);}};
  useEffect(()=>{if(match?.status==="active"&&!intro&&match.state.moveHistory.length===0&&mode==="multiplayer"){setIntro(true);beep("start");const t=setTimeout(()=>setIntro(false),2300);return()=>clearTimeout(t);}},[match?.status]);
  const play=async(from:string,to:string,promotion?:string)=>{if(!match||busy)return;try{setBusy(true);const r=await fetch(API_BASE+"/api/chess/matches/"+match.id+"/action",{method:"POST",headers,body:JSON.stringify({from,to,promotion})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMatch(d);setSelected(null);setPromo(null);if(d.status==="finished")beep("win");}catch(e:any){setMessage(e.message||"That move is not available.");}finally{setBusy(false);}};
  const resign=async()=>{if(!match)return;const r=await fetch(API_BASE+"/api/chess/matches/"+match.id+"/resign",{method:"POST",headers});const d=await r.json();if(r.ok)setMatch(d);};
  const cancel=async()=>{if(match)try{await fetch(API_BASE+"/api/chess/matches/"+match.id+"/leave",{method:"POST",headers});}catch{}setMatch(null);setSelected(null);};
  const leaderboard=async()=>{setShowRanks(true);try{const r=await fetch(API_BASE+"/api/chess/leaderboard",{headers:{Authorization:"Bearer "+token},cache:"no-store"});const d=await r.json();if(r.ok)setRanks(d);}catch{}};
  const state=match?.state,myTurn=!!match&&match.status==="active"&&state?.winner===null&&state?.turn===match.youAre;
  const legalFrom=useMemo(()=>new Set((state?.legalMoves||[]).map(m=>m.from)),[state?.legalMoves]);
  const targets=useMemo(()=>new Map((state?.legalMoves||[]).filter(m=>m.from===selected).map(m=>[m.to,m])),[state?.legalMoves,selected]);
  const rows=match?.youAre===2?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7],cols=match?.youAre===2?[7,6,5,4,3,2,1,0]:[0,1,2,3,4,5,6,7];
  const onSquare=(r:number,c:number)=>{if(!state||!myTurn||busy)return;const s=sq(r,c),piece=state.board[r][c],choices=state.legalMoves.filter(m=>m.from===selected&&m.to===s);if(selected&&choices.length){const promotions=choices.map(m=>m.promotion).filter(Boolean) as string[];if(promotions.length>1){setPromo({from:selected,to:s,choices:[...new Set(promotions)]});return;}void play(selected,s,promotions[0]);return;}const mine=piece&&(match!.youAre===1?piece[0]==="w":piece[0]==="b");setSelected(mine&&legalFrom.has(s)?s:null);};
  if(loading)return <main className="uc"><div ref={bg} className="uc-bg"/><div className="uc-load"><Crown/><h1>Opening Ultimate Chess…</h1></div></main>;
  return <main className="uc"><div ref={bg} className="uc-bg"/><div className="uc-shade"/>
    <header className="uc-top"><button onClick={()=>go("/worlds")}><ArrowLeft/><span>Worlds</span></button><div className="uc-logo"><b>♛</b><div><small>A.R.I.S.E. ARENA</small><strong>ULTIMATE CHESS</strong></div></div><div><button onClick={()=>setSound(v=>!v)}>{sound?<Volume2/>:<VolumeX/>}</button><button onClick={()=>void leaderboard()}><Trophy/><span>Ranks</span></button></div></header>
    {!match&&<section className="uc-lobby"><div className="uc-card"><div className="uc-kicker"><Sparkles/> THE BOARD IS WAITING</div><h1>Enter the <em>Ultimate Chess</em> competition.</h1><p>Challenge another A.R.I.S.E. reader live or face the computer. Every finished match feeds a chess-only leaderboard.</p>
      <div className="uc-modes"><button className={mode==="computer"?"active":""} onClick={()=>setMode("computer")}><Bot/><b>Play Computer</b><span>Instant match · 4 levels</span></button><button className={mode==="multiplayer"?"active":""} onClick={()=>setMode("multiplayer")}><Users/><b>Live Multiplayer</b><span>Match another reader</span></button></div>
      {mode==="computer"&&<div className="uc-setting"><label>Computer strength <b>{LEVELS[level-1][0]}</b></label><div className="uc-levels">{LEVELS.map((l,i)=><button key={i} className={level===i+1?"active":""} onClick={()=>setLevel(i+1)}><b>{l[0]}</b><span>{l[1]}</span></button>)}</div></div>}
      <div className="uc-setting"><label>Match clock <b>{TIMES.find(t=>t[0]===time)?.[1]} each</b></label><div className="uc-times">{TIMES.map(t=><button key={t[0]} className={time===t[0]?"active":""} onClick={()=>setTime(t[0])}>{t[1]}</button>)}</div></div>
      {!boot?.access?.allowed&&<p className="uc-lock">{boot?.access?.locked?"Your teacher has locked game play.":"You need another available game play."}</p>}{message&&<p className="uc-msg">{message}</p>}
      <button className="uc-enter" disabled={busy||!boot?.access?.allowed} onClick={()=>void start()}><Zap/>{busy?"Opening arena…":mode==="computer"?"ENTER VS COMPUTER":"FIND A CHALLENGER"}</button><button className="uc-ranklink" onClick={()=>void leaderboard()}><Trophy/> View Chess leaderboard</button>
    </div><div className="uc-hero"><span>♚</span><b>CHECKMATE</b><small>Protect the king. Claim the crown.</small></div></section>}
    {match?.status==="waiting"&&<section className="uc-wait"><div className="uc-orbit"><span>♔</span><i/><i/></div><small>LIVE MULTIPLAYER</small><h2>Searching for your challenger…</h2><p>The match begins automatically when another reader joins.</p><button onClick={()=>void cancel()}>Cancel search</button></section>}
    {match&&match.status!=="waiting"&&<section className="uc-game">
      <PlayerBar name={match.youAre===1?match.players[1].display_name:match.players[0].display_name} side={match.youAre===1?"BLACK":"WHITE"} symbol={match.youAre===1?"♚":"♔"} time={state?.clocks[match.youAre===1?1:0]||0} active={state?.turn===(match.youAre===1?2:1)}/>
      <div className="uc-main"><div className="uc-boardwrap"><div className={"uc-turn "+(state?.check?"check":"")}>{match.status==="finished"?match.statusText:state?.check?(myTurn?"⚠ YOUR KING IS IN CHECK":"⚔ CHECK!"):myTurn?"YOUR MOVE":"OPPONENT THINKING…"}</div><div className="uc-board">
        {rows.flatMap((r,ri)=>cols.map((c,ci)=>{const s=sq(r,c),piece=state?.board[r]?.[c],target=targets.get(s),lastMove=state?.lastMove&&(state.lastMove.from===s||state.lastMove.to===s);return <button key={s} aria-label={s+" "+(piece?(piece[0]==="w"?"White ":"Black ")+(N[piece[1]]||"piece"):"empty")} disabled={match.status!=="active"||busy} onClick={()=>onSquare(r,c)} className={"uc-square "+((r+c)%2?"dark":"light")+" "+(selected===s?"sel ":"")+(target?"target ":"")+(target?.capture?"capture ":"")+(lastMove?"last ":"")}>{ci===0&&<small className="rank">{8-r}</small>}{ri===7&&<small className="file">{FILES[c]}</small>}{target&&!target.capture&&<i className="dot"/>}{target?.capture&&<i className="ring"/>}{piece&&<span className={"piece "+(piece[0]==="w"?"white":"black")}>{P[piece]}</span>}</button>;}))}
      </div></div>
      <aside className={movesOpen?"open":""}><div className="uc-asidehead"><div><small>MATCH CONTROL</small><b>{state?.computer?"VS AI · "+LEVELS[(state.computerLevel||2)-1][0]:"LIVE READER MATCH"}</b></div><button onClick={()=>setMovesOpen(v=>!v)}><ChevronDown/></button></div><div className="uc-captured"><p><small>White captured</small>{(state?.captured||[]).filter(p=>p[0]==="b").map((p,i)=><b key={i}>{P[p]}</b>)}</p><p><small>Black captured</small>{(state?.captured||[]).filter(p=>p[0]==="w").map((p,i)=><b key={i}>{P[p]}</b>)}</p></div><div className="uc-history"><label>MOVE HISTORY <b>{state?.moveHistory.length||0}</b></label>{!state?.moveHistory.length?<p>No moves yet.</p>:Array.from({length:Math.ceil(state.moveHistory.length/2)},(_,i)=><div key={i}><span>{i+1}.</span><b>{state.moveHistory[i*2]||""}</b><b>{state.moveHistory[i*2+1]||""}</b></div>)}</div>{match.status==="active"&&<button className="uc-resign" onClick={()=>void resign()}><Flag/> Resign</button>}<button className="uc-side-rank" onClick={()=>void leaderboard()}><Trophy/> Standings</button></aside>
      </div>
      <PlayerBar name={boot?.self?.displayName||"Reader"} side={(match.youAre===1?"WHITE":"BLACK")+" · YOU"} symbol={match.youAre===1?"♔":"♚"} time={state?.clocks[match.youAre-1]||0} active={state?.turn===match.youAre}/>
      {message&&<button className="uc-toast" onClick={()=>setMessage("")}>{message}<X/></button>}</section>}
    {promo&&<div className="uc-modal"><div className="uc-promote"><small>PAWN PROMOTION</small><h2>Choose your new piece</h2><div>{promo.choices.map(x=><button key={x} onClick={()=>void play(promo.from,promo.to,x)}><span>{P[(match?.youAre===1?"w":"b")+x.toUpperCase()]}</span><b>{N[x.toUpperCase()]}</b></button>)}</div><button onClick={()=>setPromo(null)}>Cancel</button></div></div>}
    {match?.status==="finished"&&<div className="uc-modal"><div className="uc-result"><div>♛</div><small>ULTIMATE CHESS</small><h2>{winner(match,boot?.self?.userId)[0]}</h2><p>{winner(match,boot?.self?.userId)[1]}</p><section><span><b>{state?.moveHistory.length||0}</b>moves</span><span><b>{clock(state?.clocks[match.youAre-1]||0)}</b>time left</span><span><b>{state?.computer?LEVELS[(state.computerLevel||2)-1][0]:"Live"}</b>opponent</span></section><footer><button onClick={()=>{setMatch(null);setTimeout(()=>void start(),30);}}><RotateCcw/> Rematch</button><button onClick={()=>setMatch(null)}>Change match</button><button onClick={()=>void leaderboard()}><Trophy/> Rankings</button></footer></div></div>}
    {intro&&<div className="uc-intro"><small>A.R.I.S.E. PRESENTS</small><h2>ULTIMATE <em>CHESS</em></h2><div><strong>{match?.players[0].display_name}</strong><span>VS</span><strong>{match?.players[1].display_name}</strong></div><p>Protect the king. Control the board. Claim the crown.</p></div>}
    {showRanks&&<div className="uc-modal"><section className="uc-leaders"><header><div><small>♛ CHESS-ONLY STANDINGS</small><h2>Ultimate Chess Leaderboard</h2><p>3 points per win · 1 per draw</p></div><button onClick={()=>setShowRanks(false)}><X/></button></header>{ranks.length===0?<div className="uc-empty"><Trophy/><h3>No ranked games yet.</h3><p>Finish the first match and take #1.</p></div>:<div className="uc-list">{ranks.slice(0,50).map(r=><div key={r.userId} className={(r.userId===boot?.self?.userId?"me ":"")+(r.rank<=3?"podium":"")}><b>{r.rank===1?"👑":r.rank===2?"🥈":r.rank===3?"🥉":"#"+r.rank}</b><strong>{r.displayName}</strong><span>{r.wins}W · {r.draws}D · {r.losses}L</span><em>{r.points} pts</em><small>{r.winRate}%</small></div>)}</div>}</section></div>}
  </main>;
}
function PlayerBar({name,side,symbol,time,active}:{name:string;side:string;symbol:string;time:number;active:boolean}){return <div className="uc-player"><div><span>{symbol}</span><section><small>{side}</small><b>{name}</b></section></div><time className={active?"active":""}>{clock(time)}</time></div>;}
