import {useEffect,useRef,useState} from "react";
import {useLocation} from "wouter";
import * as THREE from "three";
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls.js";
import {ArrowLeft,Compass,LockKeyhole} from "lucide-react";
import BoardGameWorld from "./BoardGameWorld";

type World={id:string;title:string;description:string;emoji:string;color:number;path?:string;coming?:boolean};
const WORLDS:World[]=[
{id:"club",title:"Club A.R.I.S.E.",description:"Dance, socialize, and play arcade games together.",emoji:"🪩",color:0xc026d3,path:"/club-arise"},
{id:"cinema",title:"A.R.I.S.E. Cinema",description:"Walk the theater, grab popcorn, sit with friends, and watch together.",emoji:"🎬",color:0xf59e0b,path:"/club-arise/theater"},
{id:"block",title:"The Block",description:"Explore your neighborhood, visit your home, and meet other readers.",emoji:"🏘️",color:0x4ade80,path:"/neighborhood"},
{id:"laser",title:"Laser Royale",description:"Battle-royale-style 3D laser tag with shields, powers, and a closing zone.",emoji:"⚡",color:0x22d3ee,path:"/laser-royale"},
{id:"board",title:"A.R.I.S.E. Board Quest",description:"NEW • Team-based 3D board game. Answer questions, roll dice, earn powers, collect points, and survive three strikes.",emoji:"🎲",color:0x8b5cf6,path:"/worlds?board=1"},
{id:"space",title:"Outer Space",description:"Explore planets and a glowing galaxy. Coming soon.",emoji:"🚀",color:0x9868f4,coming:true},
{id:"beach",title:"The Beach",description:"Palm trees, a seaside boardwalk, and sunny adventures. Coming soon.",emoji:"🏖️",color:0x38bdf8,coming:true},
{id:"race",title:"The Racetrack",description:"Fast lanes and a place to put your cars to the test. Coming soon.",emoji:"🏁",color:0xf87171,coming:true}
];

export default function Worlds(){
 const [location,navigate]=useLocation();
 const params=new URLSearchParams(typeof window!=="undefined"?window.location.search:"");
 if(params.get("board")==="1")return <BoardGameWorld/>;
 const mount=useRef<HTMLDivElement>(null);const [selected,setSelected]=useState(0);const world=WORLDS[selected];
 useEffect(()=>{const host=mount.current;if(!host)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x050817);const camera=new THREE.PerspectiveCamera(48,1,.1,100);camera.position.set(0,5.5,16);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=10;controls.maxDistance=25;scene.add(new THREE.HemisphereLight(0xffffff,0x18204a,2.6));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-8,12,10);scene.add(sun);
 const earth=new THREE.Mesh(new THREE.SphereGeometry(2.6,40,30),new THREE.MeshStandardMaterial({color:0x176a9d,roughness:.65}));scene.add(earth);for(let i=0;i<34;i++){const a=i*2.4,b=Math.asin(Math.sin(i*1.7)*.7);const land=new THREE.Mesh(new THREE.IcosahedronGeometry(.24+(i%4)*.07,0),new THREE.MeshStandardMaterial({color:0x55bb77,roughness:.9}));land.position.set(Math.cos(b)*Math.cos(a)*2.57,Math.sin(b)*2.57,Math.cos(b)*Math.sin(a)*2.57);scene.add(land)}
 const orbit=new THREE.Group();scene.add(orbit);const planets:THREE.Group[]=[];WORLDS.forEach((w,i)=>{const g=new THREE.Group();const a=i*Math.PI*2/WORLDS.length-.5;g.position.set(Math.sin(a)*6.1,(i%2?-.65:.75),Math.cos(a)*6.1);const p=new THREE.Mesh(new THREE.SphereGeometry(1.05,24,18),new THREE.MeshStandardMaterial({color:w.color,roughness:.65,emissive:w.color,emissiveIntensity:.12}));g.add(p);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.22,.035,8,48),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.55}));ring.rotation.x=1.1;g.add(ring);const c=document.createElement("canvas");c.width=256;c.height=128;const x=c.getContext("2d")!;x.font="70px system-ui";x.textAlign="center";x.fillText(w.emoji,128,82);const tex=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true}));s.position.y=1.45;s.scale.set(1.4,.7,1);g.add(s);g.userData.index=i;orbit.add(g);planets.push(g)});
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down:{x:number;y:number}|null=null;const pd=(e:PointerEvent)=>down={x:e.clientX,y:e.clientY};const pu=(e:PointerEvent)=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>8){down=null;return}down=null;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(planets,true)[0];if(hit){let o:THREE.Object3D|null=hit.object;while(o&&o.userData.index===undefined)o=o.parent;if(o)setSelected(o.userData.index)}};renderer.domElement.addEventListener("pointerdown",pd);renderer.domElement.addEventListener("pointerup",pu);
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/Math.max(1,h);camera.position.set(0,w<640?10:5.5,w<640?27:16);camera.updateProjectionMatrix();renderer.setSize(w,h)};resize();window.addEventListener("resize",resize);let raf=0;const clock=new THREE.Clock();const loop=()=>{const dt=Math.min(.05,clock.getDelta());earth.rotation.y+=dt*.08;orbit.rotation.y+=dt*.025;planets.forEach(p=>p.rotation.y+=dt*.1);controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",resize);renderer.domElement.removeEventListener("pointerdown",pd);renderer.domElement.removeEventListener("pointerup",pu);controls.dispose();renderer.dispose();host.replaceChildren()}},[]);
 const go=(delta:number)=>setSelected(v=>(v+delta+WORLDS.length)%WORLDS.length);
 return <main className="relative h-[100dvh] overflow-hidden bg-slate-950 text-white"><div ref={mount} className="absolute inset-0"/><button onClick={()=>navigate("/library")} className="absolute left-3 top-3 z-20 flex items-center gap-2 rounded-xl bg-black/65 px-3 py-2 font-black backdrop-blur"><ArrowLeft className="h-4 w-4"/> Library</button><div className="pointer-events-none absolute inset-x-0 top-3 z-10 text-center"><div className="inline-flex items-center gap-2 rounded-full bg-black/45 px-4 py-2 text-xs font-black uppercase tracking-[.2em] backdrop-blur"><Compass className="h-4 w-4 text-cyan-300"/> A.R.I.S.E. Worlds 2.0</div></div><section className="absolute inset-x-3 bottom-4 z-20 mx-auto max-w-xl rounded-3xl border border-white/15 bg-slate-950/88 p-4 text-center shadow-2xl backdrop-blur-xl sm:bottom-6 sm:p-5"><div className="mb-1 text-4xl">{world.emoji}</div><div className="flex items-center justify-center gap-2"><h1 className="text-xl font-black sm:text-2xl">{world.title}</h1>{world.id==="board"&&<span className="rounded-full bg-cyan-300 px-2 py-1 text-[9px] font-black text-slate-950">NEW</span>}</div><p className="mx-auto mt-1 max-w-md text-xs text-white/70 sm:text-sm">{world.description}</p><div className="mt-4 flex items-center justify-center gap-2"><button onClick={()=>go(-1)} className="min-h-11 rounded-xl bg-white/10 px-4 font-black">‹</button>{world.path&&!world.coming?<button onClick={()=>navigate(world.path!)} className="min-h-11 flex-1 rounded-xl bg-cyan-300 px-5 font-black text-slate-950">ENTER {world.title.toUpperCase()}</button>:<div className="flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-white/10 px-5 font-black text-white/55"><LockKeyhole className="h-4 w-4"/> COMING SOON</div>}<button onClick={()=>go(1)} className="min-h-11 rounded-xl bg-white/10 px-4 font-black">›</button></div><div className="mt-3 flex justify-center gap-1.5">{WORLDS.map((_,i)=><button key={i} aria-label={`World ${i+1}`} onClick={()=>setSelected(i)} className={`h-2 rounded-full transition-all ${i===selected?"w-7 bg-cyan-300":"w-2 bg-white/30"}`}/>)}</div></section></main>
}
