import {BANK,BOARD_LAST_SPACE,EVENTS,HANDS,TIMING,moveLandingAt,rpsWinner,type Level,type Player,type Cue,type Hand,type View,type Q} from '../shared/boardQuest';
export class BoardQuestGame {
 view:View;private question:Q|null=null;private choices=new Map<number,Hand>();private awarded=false;private nextId=1;
 touched=Date.now();private humansSeen=new Map<number,number>();
 constructor(code:string,host:Player,level:Level,private random:()=>number=Math.random){this.view={code,hostId:host.id,level,players:[host],turn:0,phase:'lobby',phaseAt:0,serverNow:0,scores:{blue:0,gold:0},cue:null,question:null,winner:null,rpsReady:[],rpsDeadline:0,openingRolls:{},openingTotals:{blue:0,gold:0},startingTeam:null,revision:0};}
 member(id:number){return this.view.players.some(p=>p.id===id&&!p.bot);}
 touch(id:number,now:number){this.touched=now;this.humansSeen.set(id,now);}
 add(p:Player){if(this.member(p.id))return;if(this.view.phase!=='lobby')throw Error('This game has already started.');if(this.view.players.length>=6)throw Error('This room is full.');p.team=this.view.players.length%2?'gold':'blue';this.view.players.push(p);this.view.revision++;}
 start(id:number,now:number){if(id!==this.view.hostId)throw Error('Only the host can start.');if(!['lobby','finished'].includes(this.view.phase))throw Error('A game is already running.');const humans=this.view.players.filter(p=>!p.bot);const chars=['robin-hood','alice','king-arthur','sherlock-holmes','hercules','musketeer'];const names=['Robin','Alice','Arthur','Sherlock','Hercules','Musketeer'];this.view.players=Array.from({length:6},(_,i)=>({...humans[i]||{id:-i-1,name:names[i]+' CPU',characterId:chars[i],bot:true},team:i%2?'gold':'blue',space:0,strikes:0,shield:0,power:0,out:false} as Player));this.view.scores={blue:0,gold:0};this.view.winner=null;this.view.turn=0;this.view.question=null;this.question=null;this.view.cue=null;this.view.rpsReady=[];this.view.rpsDeadline=0;this.choices.clear();this.awarded=false;let rolls:Record<number,number>={},blue=0,gold=0;do{rolls={};blue=0;gold=0;for(const p of this.view.players){const n=1+Math.floor(this.random()*6);rolls[p.id]=n;if(p.team==='blue')blue+=n;else gold+=n;}}while(blue===gold);this.view.openingRolls=rolls;this.view.openingTotals={blue,gold};this.view.startingTeam=blue>gold?'blue':'gold';this.view.phase='intro';this.view.phaseAt=now;this.view.revision++;}
 private ask(now:number){this.question=BANK[this.view.level][Math.floor(this.random()*BANK[this.view.level].length)];this.view.question={id:this.nextId++,q:this.question.q,a:this.question.a};this.view.phase='question';this.view.phaseAt=now;this.view.cue=null;this.view.rpsReady=[];this.view.rpsDeadline=0;this.choices.clear();this.awarded=false;this.view.revision++;}
 answer(id:number,questionId:number,choice:number,now:number){const p=this.view.players[this.view.turn];if(this.view.phase!=='question'||p.id!==id||questionId!==this.view.question?.id)throw Error('Wait for your current question.');if(!Number.isInteger(choice)||choice<0||choice>3)throw Error('Choose an answer.');const correct=choice===this.question?.correct;this.view.question=null;this.question=null;this.view.phase='cinematic';this.view.phaseAt=now;this.awarded=false;
 if(!correct){const blocked=this.strike(p);this.view.cue={id:this.nextId++,kind:'strike',startAt:now+600,actor:p.id,from:p.space,to:p.space,raw:0,bonus:0,steps:0,event:'safe',blocked,title:blocked?'SHIELD SAVED YOU!':p.out?p.name+' IS OUT':`STRIKE ${p.strikes} OF 3`};}
 else{const raw=1+Math.floor(this.random()*6),bonus=p.power?2:0;p.power=0;const to=Math.min(BOARD_LAST_SPACE,p.space+raw+bonus);this.view.cue={id:this.nextId++,kind:'move',startAt:now+600,actor:p.id,from:p.space,to,raw,bonus,steps:raw+bonus,event:EVENTS[to%EVENTS.length]};}this.view.revision++;}
 private strike(p:Player){if(p.shield){p.shield--;return true;}p.strikes++;p.out=p.strikes>=3;return false;}
 choose(id:number,hand:Hand,cueId:number,now:number){const cue=this.view.cue;if(this.view.phase!=='rps'||!cue||cue.id!==cueId||![cue.actor,cue.rival].includes(id)||!HANDS.includes(hand))throw Error('This battle is not waiting for your choice.');if(this.choices.has(id))return;this.choices.set(id,hand);this.view.rpsReady=Array.from(this.choices.keys());this.view.revision++;if(this.choices.size===2)this.reveal(now);}
 private reveal(now:number){const old=this.view.cue!;const hands:[Hand,Hand]=[this.choices.get(old.actor)!,this.choices.get(old.rival!)!];const winner=rpsWinner(...hands);this.view.cue={...old,id:this.nextId++,kind:'duel',startAt:now+600,hands,duelWinner:winner===null?null:winner===0?old.actor:old.rival};this.view.phase='cinematic';this.awarded=false;this.view.revision++;}
 private reward(now:number){const cue=this.view.cue!,p=this.view.players[this.view.turn];p.space=cue.to;const team=p.team,other=team==='blue'?'gold':'blue';cue.deltas={blue:0,gold:0};
 switch(cue.event){case 'points':case 'bonus':cue.deltas[team]=cue.event==='bonus'?100:50;cue.title=cue.event==='bonus'?'JACKPOT!':'TEAM POINTS!';break;
 case 'steal':{const amount=Math.min(30,this.view.scores[other]);cue.deltas[team]=amount;cue.deltas[other]=-amount;cue.title=amount?`STOLE ${amount} POINTS!`:'NO POINTS TO STEAL';break;}
 case 'shield':p.shield++;cue.title='SHIELD UP!';break;case 'power':p.power++;cue.title='+2 NEXT ROLL!';break;
 case 'rps':{const rivals=this.view.players.filter(x=>x.team!==team&&!x.out);if(rivals.length){cue.rival=rivals[Math.floor(this.random()*rivals.length)].id;this.view.phase='rps';this.view.phaseAt=now;this.view.rpsDeadline=now+12000;this.view.rpsReady=[];this.choices.clear();cue.title='BATTLE! CHOOSE YOUR HAND';}break;}
 default:cue.title='SAFE AND SOUND';}
 this.view.scores.blue+=cue.deltas.blue;this.view.scores.gold+=cue.deltas.gold;this.awarded=true;this.view.revision++;}
 private advance(now:number){const alive=this.view.players.filter(p=>!p.out),p=this.view.players[this.view.turn];const blue=alive.some(x=>x.team==='blue'),gold=alive.some(x=>x.team==='gold');if(!blue||!gold||p.space===BOARD_LAST_SPACE){this.view.winner=!blue?'GOLD TEAM':!gold?'BLUE TEAM':p.team.toUpperCase()+' TEAM';this.view.phase='finished';this.view.phaseAt=now;this.view.revision++;return;}do{this.view.turn=(this.view.turn+1)%this.view.players.length;}while(this.view.players[this.view.turn].out);this.ask(now);}
 tick(now:number){const v=this.view;v.serverNow=now;if(v.phase==='intro'){const blue=v.players.filter(p=>p.team==='blue').length,gold=v.players.filter(p=>p.team==='gold').length,introDuration=TIMING.teamBanner+blue*TIMING.introPlayer+TIMING.introTeamGap+TIMING.teamBanner+gold*TIMING.introPlayer+TIMING.introHold;if(now-v.phaseAt>=introDuration){v.phase='opening-roll';v.phaseAt=now;v.revision++;}return;}if(v.phase==='opening-roll'){const duration=TIMING.openingCountdown+v.players.length*TIMING.openingRollPlayer+TIMING.openingResultHold;if(now-v.phaseAt>=duration){const first=v.players.findIndex(p=>p.team===v.startingTeam);v.turn=first>=0?first:0;this.ask(now);}return;}const p=v.players[v.turn];if(v.phase==='question'&&this.question){const disconnected=!p.bot&&now-(this.humansSeen.get(p.id)||v.phaseAt)>45000;if((p.bot&&now-v.phaseAt>1800)||now-v.phaseAt>60000||disconnected){const correct=this.question.correct;this.answer(p.id,v.question!.id,p.bot&&this.random()<.7?correct:(correct+1)%4,now);}return;}
 if(v.phase==='rps'){const cue=v.cue!;for(const id of [cue.actor,cue.rival!]){const player=v.players.find(p=>p.id===id)!;if(!this.choices.has(id)&&((player.bot&&now-v.phaseAt>1200)||now>=v.rpsDeadline)){this.choose(id,HANDS[Math.floor(this.random()*3)],cue.id,now);if(v.phase!=='rps')break;}}return;}
 if(v.phase!=='cinematic'||!v.cue)return;const cue=v.cue;
 if(cue.kind==='strike'){if(now>cue.startAt+TIMING.reward)this.advance(now);return;}
 if(cue.kind==='duel'){if(now>=cue.startAt+TIMING.countdown&&!this.awarded){if(cue.duelWinner!==null){const loser=v.players.find(p=>p.id===(cue.duelWinner===cue.actor?cue.rival:cue.actor))!;cue.blocked=this.strike(loser);cue.title=cue.blocked?'SHIELD BLOCKED THE STRIKE!':v.players.find(p=>p.id===cue.duelWinner)!.name+' WINS!';}else cue.title='DRAW! NO STRIKES';this.awarded=true;v.revision++;}if(now>=cue.startAt+TIMING.countdown+TIMING.duelResult)this.advance(now);return;}
 const rewardAt=moveLandingAt(cue)+TIMING.landing;if(now>=rewardAt&&!this.awarded)this.reward(now);if(v.phase==='cinematic'&&now>=rewardAt+TIMING.reward)this.advance(now);
 }
 snapshot(now:number):View{this.tick(now);const data=structuredClone(this.view);if(data.cue?.kind==='duel'&&now<data.cue.startAt+TIMING.countdown){delete data.cue.hands;delete data.cue.duelWinner;}return data;}
}
