// Quiz data for all books - 10 MCQs per book
// These are based on well-known classic children's literature in the public domain.

interface QuizQuestion {
  question: string;
  options: [string, string, string, string];
  correct: "A" | "B" | "C" | "D";
}

interface BookQuiz {
  title: string;
  author: string;
  ageGroup: string;
  coverUrl: string | null;
  description: string;
  questions: QuizQuestion[];
}

export const bookQuizzes: BookQuiz[] = [
  {
    title: "The Tale of Peter Rabbit",
    author: "Beatrix Potter",
    ageGroup: "Ages 3-6",
    coverUrl: "https://covers.openlibrary.org/b/id/2557658-L.jpg",
    description: "A mischievous rabbit sneaks into Mr. McGregor's garden despite his mother's warnings.",
    questions: [
      { question: "What kind of animal is Peter Rabbit?", options: ["A cat", "A rabbit", "A squirrel", "A hedgehog"], correct: "B" },
      { question: "Where does Peter go after his mother tells him not to?", options: ["To the woods", "To Mr. McGregor's garden", "To the river", "To the market"], correct: "B" },
      { question: "What did Peter lose in the garden?", options: ["His shoes and blue jacket", "His hat and scarf", "His basket and umbrella", "His gloves and coat"], correct: "A" },
      { question: "Who is Mr. McGregor?", options: ["A farmer", "A baker", "A blacksmith", "A shopkeeper"], correct: "A" },
      { question: "What did Peter's mother give the good little rabbits for supper?", options: ["Bread and milk", "Carrots", "Lettuce", "Berries"], correct: "A" },
      { question: "How many siblings does Peter have?", options: ["One", "Two", "Three", "Four"], correct: "C" },
      { question: "What are the names of Peter's sisters?", options: ["Flopsy, Mopsy, and Cotton-tail", "Lily, Rose, and Daisy", "Pip, Squeak, and Wilbur", "Hazel, Primrose, and Buttercup"], correct: "A" },
      { question: "Where did Peter hide from Mr. McGregor?", options: ["In a watering can", "In a wheelbarrow", "Under a bush", "In a greenhouse"], correct: "A" },
      { question: "What did the sparrow encourage Peter to do?", options: ["Keep running", "Hide in the shed", "Climb a tree", "Jump in the pond"], correct: "A" },
      { question: "What happened to Peter when he got home?", options: ["His mother put him to bed with chamomile tea", "He was sent to his room", "He had to do chores", "He was given extra supper"], correct: "A" },
    ],
  },
  {
    title: "The Great Big Treasury of Beatrix Potter",
    author: "Beatrix Potter",
    ageGroup: "Ages 3-6",
    coverUrl: "https://covers.openlibrary.org/b/id/320538-L.jpg",
    description: "A collection of 22 beloved Beatrix Potter stories featuring animals on adventures.",
    questions: [
      { question: "How many stories are in this collection?", options: ["10", "15", "22", "30"], correct: "C" },
      { question: "Who is the author of this collection?", options: ["Lewis Carroll", "Beatrix Potter", "A.A. Milne", "Kenneth Grahame"], correct: "B" },
      { question: "What kind of animals are the main characters in these stories?", options: ["Dragons and unicorns", "Talking animals", "Dinosaurs", "Fish only"], correct: "B" },
      { question: "Which famous rabbit appears in this collection?", options: ["Peter Rabbit", "Br'er Rabbit", "Bugs Bunny", "Roger Rabbit"], correct: "A" },
      { question: "What is the setting for most of these stories?", options: ["The countryside and gardens", "A big city", "A desert", "A castle"], correct: "A" },
      { question: "Beatrix Potter set many of her stories in which region of England?", options: ["The Lake District", "London", "Cornwall", "Yorkshire"], correct: "A" },
      { question: "What do the animal characters in Potter's stories often wear?", options: ["Tiny clothes", "Armor", "Nothing", "Only hats"], correct: "A" },
      { question: "Which of these is NOT a Beatrix Potter story?", options: ["The Tale of Jemima Puddle-Duck", "The Tale of Squirrel Nutkin", "The Tale of Peter Rabbit", "The Tale of Despereaux"], correct: "D" },
      { question: "What kind of animal is Jemima Puddle-Duck?", options: ["A duck", "A goose", "A chicken", "A swan"], correct: "A" },
      { question: "What lesson do many Beatrix Potter stories teach?", options: ["Listen to your parents", "Always be late", "Never share", "Run away from home"], correct: "A" },
    ],
  },
  {
    title: "The Real Mother Goose",
    author: "Blanche Fisher Wright",
    ageGroup: "Ages 3-6",
    coverUrl: "https://covers.openlibrary.org/b/id/1755890-L.jpg",
    description: "A classic collection of nursery rhymes and poems for young children.",
    questions: [
      { question: "What type of literature is The Real Mother Goose?", options: ["A novel", "Nursery rhymes", "A play", "A textbook"], correct: "B" },
      { question: "Who is Mother Goose?", options: ["A real historical person", "A fictional storyteller character", "A queen", "A farmer's wife"], correct: "B" },
      { question: "Who climbed the candlestick?", options: ["Jack", "Jill", "Tom", "Mary"], correct: "A" },
      { question: "What did Jack break when he fell down?", options: ["His crown", "His leg", "His arm", "His nose"], correct: "A" },
      { question: "What did Mary have that was little?", options: ["A lamb", "A dog", "A cat", "A bird"], correct: "A" },
      { question: "Where did the itsy-bitsy spider climb up?", options: ["The water spout", "The wall", "The tree", "The fence"], correct: "A" },
      { question: "What did Humpty Dumpty sit on?", options: ["A wall", "A chair", "A roof", "A hill"], correct: "A" },
      { question: "Who went up the hill to fetch a pail of water?", options: ["Jack and Jill", "Tom and Jerry", "Hansel and Gretel", "Mary and Bob"], correct: "A" },
      { question: "How many nursery rhymes are typically in Mother Goose collections?", options: ["About 50", "About 100", "Over 300", "Exactly 25"], correct: "C" },
      { question: "What is the purpose of nursery rhymes?", options: ["To teach children through rhyme and rhythm", "To scare children", "To teach math", "To teach cooking"], correct: "A" },
    ],
  },
  {
    title: "The Story of the Three Little Pigs",
    author: "L. Leslie Brooke",
    ageGroup: "Ages 3-6",
    coverUrl: null,
    description: "The classic tale of three pigs who build houses of different materials and face the big bad wolf.",
    questions: [
      { question: "How many pigs are in the story?", options: ["Two", "Three", "Four", "Five"], correct: "B" },
      { question: "What material does the first pig use to build his house?", options: ["Straw", "Sticks", "Bricks", "Stone"], correct: "A" },
      { question: "What material does the second pig use?", options: ["Straw", "Sticks", "Bricks", "Mud"], correct: "B" },
      { question: "What material does the third pig use?", options: ["Straw", "Sticks", "Bricks", "Wood"], correct: "C" },
      { question: "Who tries to blow down the pigs' houses?", options: ["The big bad wolf", "A bear", "A dragon", "A fox"], correct: "A" },
      { question: "Which pig's house could NOT be blown down?", options: ["The first pig's", "The second pig's", "The third pig's", "None of them"], correct: "C" },
      { question: "What does the wolf say before blowing down a house?", options: ["I'll huff and I'll puff", "Open the door", "Let me in", "I'm hungry"], correct: "A" },
      { question: "Where does the wolf try to enter the brick house from?", options: ["The chimney", "The window", "The door", "The roof"], correct: "A" },
      { question: "What happens to the wolf at the end of the story?", options: ["He falls into a pot of boiling water", "He runs away", "He becomes friends with the pigs", "He gets arrested"], correct: "A" },
      { question: "What lesson does this story teach?", options: ["Hard work pays off", "Always run away", "Don't build houses", "Wolves are friendly"], correct: "A" },
    ],
  },
  {
    title: "Twas the Night before Christmas",
    author: "Clement Clarke Moore",
    ageGroup: "Ages 3-6",
    coverUrl: "https://covers.openlibrary.org/b/id/8236410-L.jpg",
    description: "The beloved Christmas poem about Santa Claus's visit on Christmas Eve.",
    questions: [
      { question: "What holiday does this poem describe?", options: ["Thanksgiving", "Christmas", "Halloween", "Easter"], correct: "B" },
      { question: "Who is the narrator of the poem?", options: ["A father", "A child", "Santa Claus", "A reindeer"], correct: "A" },
      { question: "What is the narrator doing when he hears a noise?", options: ["Sleeping", "Reading", "Eating", "Working"], correct: "A" },
      { question: "What does the narrator see out the window?", options: ["Santa's sleigh", "A Christmas tree", "Snow falling", "Reindeer in the yard"], correct: "A" },
      { question: "How many reindeer pull Santa's sleigh?", options: ["Six", "Eight", "Ten", "Twelve"], correct: "B" },
      { question: "Who is the lead reindeer?", options: ["Rudolph", "Dasher", "Donder", "Vixen"], correct: "C" },
      { question: "How does Santa enter the house?", options: ["Through the chimney", "Through the door", "Through a window", "Through the roof"], correct: "A" },
      { question: "What does Santa carry on his back?", options: ["A sack of toys", "A Christmas tree", "A bag of coal", "A bundle of sticks"], correct: "A" },
      { question: "What does Santa say as he flies away?", options: ["Merry Christmas to all", "Happy New Year", "Ho ho ho", "Good night"], correct: "A" },
      { question: "How does Santa describe himself?", options: ["A jolly old elf", "A magical man", "Father Christmas", "A winter wizard"], correct: "A" },
    ],
  },
  {
    title: "The Wonderful Wizard of Oz",
    author: "L. Frank Baum",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/552443-L.jpg",
    description: "Dorothy is swept away by a tornado to the magical Land of Oz and journeys to find her way home.",
    questions: [
      { question: "What carries Dorothy to the Land of Oz?", options: ["A tornado", "A balloon", "A train", "A magic spell"], correct: "A" },
      { question: "What is the name of Dorothy's dog?", options: ["Toto", "Rex", "Spot", "Buddy"], correct: "A" },
      { question: "Where does Dorothy live?", options: ["Kansas", "Texas", "Nebraska", "Oklahoma"], correct: "A" },
      { question: "What does Dorothy's house land on when it arrives in Oz?", options: ["The Wicked Witch of the East", "A yellow brick road", "A cornfield", "A mountain"], correct: "A" },
      { question: "What does Dorothy get from the Good Witch of the North?", options: ["Silver shoes", "A magic wand", "A flying broom", "A golden key"], correct: "A" },
      { question: "What road does Dorothy follow to reach the Emerald City?", options: ["The Yellow Brick Road", "The Golden Path", "The Emerald Trail", "The Ruby Road"], correct: "A" },
      { question: "What does the Scarecrow want from the Wizard?", options: ["A brain", "A heart", "Courage", "A home"], correct: "A" },
      { question: "What does the Tin Woodman want?", options: ["A heart", "A brain", "Courage", "A friend"], correct: "A" },
      { question: "What does the Cowardly Lion want?", options: ["Courage", "A heart", "A brain", "Wings"], correct: "A" },
      { question: "Who is the ruler Dorothy asks for help?", options: ["The Wizard of Oz", "The Good Witch", "The King of Oz", "The Mayor"], correct: "A" },
    ],
  },
  {
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/10527843-L.jpg",
    description: "A girl named Alice falls down a rabbit hole into a fantasy world populated by peculiar creatures.",
    questions: [
      { question: "How does Alice enter Wonderland?", options: ["She falls down a rabbit hole", "She walks through a door", "She swims across a river", "She flies on a bird"], correct: "A" },
      { question: "What animal does Alice follow down the hole?", options: ["A white rabbit", "A cat", "A fox", "A butterfly"], correct: "A" },
      { question: "What is the white rabbit wearing?", options: ["A waistcoat", "A hat", "A scarf", "A crown"], correct: "A" },
      { question: "What does Alice drink that makes her shrink?", options: ["A potion from a bottle", "Tea", "Milk", "Water from a pond"], correct: "A" },
      { question: "What does Alice eat that makes her grow?", options: ["A cake", "A mushroom", "An apple", "A cookie"], correct: "A" },
      { question: "Who is hosting the tea party?", options: ["The Mad Hatter", "The Cheshire Cat", "The Queen of Hearts", "The White Rabbit"], correct: "A" },
      { question: "What game does the Queen of Hearts play?", options: ["Croquet", "Chess", "Cards", "Tennis"], correct: "A" },
      { question: "What is the Queen of Hearts famous for saying?", options: ["Off with their heads!", "Off to the dungeon!", "Banish them!", "Throw them out!"], correct: "A" },
      { question: "What animal grins and disappears?", options: ["The Cheshire Cat", "The Caterpillar", "The Mock Turtle", "The Dodo"], correct: "A" },
      { question: "How does Alice leave Wonderland?", options: ["She wakes up from a dream", "She climbs back up the hole", "A bird carries her home", "She walks through a door"], correct: "A" },
    ],
  },
  {
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/13335427-L.jpg",
    description: "The adventures of Mole, Rat, Toad, and Badger along the riverbank and in the Wild Wood.",
    questions: [
      { question: "Who is the first character we meet in the story?", options: ["Mole", "Rat", "Toad", "Badger"], correct: "A" },
      { question: "What causes Mole to leave his underground home?", options: ["Spring cleaning fever", "A flood", "Hunger", "Boredom"], correct: "A" },
      { question: "What is Rat's full name?", options: ["Water Rat", "River Rat", "Ratty", "Mr. Rat"], correct: "A" },
      { question: "What animal is Toad?", options: ["A toad", "A frog", "A newt", "A lizard"], correct: "A" },
      { question: "What obsession gets Toad into trouble?", options: ["Motorcars", "Boats", "Food", "Clothes"], correct: "A" },
      { question: "Where does Toad live?", options: ["Toad Hall", "Toad Manor", "Toad Castle", "Toad House"], correct: "A" },
      { question: "Who lives in the Wild Wood?", options: ["Weasels and stoats", "Foxes and wolves", "Bears", "Snakes"], correct: "A" },
      { question: "What does Toad disguise himself as to escape?", options: ["A washerwoman", "A farmer", "A priest", "A soldier"], correct: "A" },
      { question: "Who helps recapture Toad Hall from the weasels?", options: ["Mole, Rat, Toad, and Badger", "Only Badger", "Only Toad", "The police"], correct: "A" },
      { question: "What river do Mole and Rat live beside?", options: ["The River Bank", "The Thames", "The Avon", "The Severn"], correct: "A" },
    ],
  },
  {
    title: "Winnie-the-Pooh",
    author: "A. A. Milne",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/8610816-L.jpg",
    description: "The beloved stories of a teddy bear named Pooh and his friends in the Hundred Acre Wood.",
    questions: [
      { question: "What kind of animal is Winnie-the-Pooh?", options: ["A bear", "A pig", "A tiger", "A donkey"], correct: "A" },
      { question: "Where does Pooh live?", options: ["The Hundred Acre Wood", "The Enchanted Forest", "The River Bank", "The Meadow"], correct: "A" },
      { question: "What does Pooh love to eat?", options: ["Honey", "Berries", "Nuts", "Fish"], correct: "A" },
      { question: "What kind of animal is Piglet?", options: ["A pig", "A mouse", "A rabbit", "A bear"], correct: "A" },
      { question: "What is Eeyore?", options: ["A donkey", "A horse", "A mule", "A goat"], correct: "A" },
      { question: "What does Eeyore often lose?", options: ["His tail", "His ears", "His hat", "His house"], correct: "A" },
      { question: "Who is the bouncy tiger?", options: ["Tigger", "Roo", "Rabbit", "Owl"], correct: "A" },
      { question: "What does Rabbit grow in his garden?", options: ["Carrots and vegetables", "Flowers", "Trees", "Berries"], correct: "A" },
      { question: "Who is the wise bird who tells long stories?", options: ["Owl", "Robin", "Sparrow", "Crow"], correct: "A" },
      { question: "Who is the human boy in the stories?", options: ["Christopher Robin", "Billy", "Tommy", "Johnny"], correct: "A" },
    ],
  },
  {
    title: "The House at Pooh Corner",
    author: "A. A. Milne",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/8743133-L.jpg",
    description: "More adventures with Pooh and friends, including the introduction of Tigger.",
    questions: [
      { question: "Who is the new character introduced in this book?", options: ["Tigger", "Piglet", "Owl", "Rabbit"], correct: "A" },
      { question: "What is Tigger's favorite thing to do?", options: ["Bounce", "Sleep", "Eat honey", "Swim"], correct: "A" },
      { question: "What game do Pooh and his friends invent?", options: ["Poohsticks", "Hide and seek", "Tag", "Musical chairs"], correct: "A" },
      { question: "Where do they play Poohsticks?", options: ["On a bridge over a stream", "In the woods", "In a field", "In a tree"], correct: "A" },
      { question: "What does Tigger eat for breakfast?", options: ["Extract of malt", "Honey", "Carrots", "Fish"], correct: "A" },
      { question: "Who does Tigger try to live with first?", options: ["Kanga and Roo", "Pooh", "Piglet", "Rabbit"], correct: "A" },
      { question: "What does Eeyore's house keep doing?", options: ["Falling down", "Floating away", "Getting stolen", "Catching fire"], correct: "A" },
      { question: "Who builds Eeyore a new house?", options: ["Piglet and Pooh", "Rabbit", "Owl", "Tigger"], correct: "A" },
      { question: "What happens at the end of the book?", options: ["Christopher Robin leaves", "Pooh moves away", "Tigger leaves", "The wood floods"], correct: "A" },
      { question: "What does Pooh promise Christopher Robin?", options: ["To never forget him", "To find honey", "To build a house", "To be brave"], correct: "A" },
    ],
  },
  {
    title: "Black Beauty",
    author: "Anna Sewell",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/14770679-L.jpg",
    description: "The life story of a horse named Black Beauty, told from the horse's own perspective.",
    questions: [
      { question: "Who narrates the story?", options: ["Black Beauty the horse", "A farmer", "A veterinarian", "A young boy"], correct: "A" },
      { question: "What color is Black Beauty?", options: ["Black", "Brown", "White", "Grey"], correct: "A" },
      { question: "What does Black Beauty's mother teach him?", options: ["To be gentle and good", "To run fast", "To jump fences", "To find food"], correct: "A" },
      { question: "Where does Black Beauty first live?", options: ["On a farm", "In a city", "At a racetrack", "In a stable"], correct: "A" },
      { question: "Who is Black Beauty's first owner?", options: ["Farmer Grey", "Squire Gordon", "Jerry Barker", "Joe Green"], correct: "A" },
      { question: "What is the name of the stable where Beauty works in London?", options: ["Birtwick Park", "Earlshall", "The cab stand", "The orchard"], correct: "A" },
      { question: "What job does Black Beauty do in London?", options: ["Pulls a cab", "Races", "Plows fields", "Carries mail"], correct: "A" },
      { question: "Who is Beauty's kind cab driver owner?", options: ["Jerry Barker", "Squire Gordon", "Farmer Grey", "James Howard"], correct: "A" },
      { question: "What happens to Beauty at the end of the story?", options: ["He finds a happy home", "He dies", "He escapes", "He goes to war"], correct: "A" },
      { question: "What is the main message of the book?", options: ["Treat animals with kindness", "Horses are fast", "City life is hard", "Farms are better"], correct: "A" },
    ],
  },
  {
    title: "Five Children and It",
    author: "E. Nesbit",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/28174-L.jpg",
    description: "Five children discover a magical creature that grants wishes, which always go wrong.",
    questions: [
      { question: "How many children are in the story?", options: ["Five", "Three", "Four", "Six"], correct: "A" },
      { question: "What is the magical creature called?", options: ["The Psammead", "The Sand Fairy", "The Wish Gnome", "The Magic Toad"], correct: "A" },
      { question: "Where do the children find the creature?", options: ["In a gravel pit", "In a cave", "In a forest", "In a garden"], correct: "A" },
      { question: "What does the creature look like?", options: ["It is furry and has eyes on stalks", "It looks like a fairy", "It looks like a dragon", "It is invisible"], correct: "A" },
      { question: "How many wishes does each child get per day?", options: ["One", "Three", "Five", "Unlimited"], correct: "A" },
      { question: "When do the wishes expire?", options: ["At sunset", "At midnight", "After one hour", "The next morning"], correct: "A" },
      { question: "What do the children wish for that turns them into angels?", options: ["Wings", "Halo", "Harps", "To fly"], correct: "A" },
      { question: "What goes wrong when they wish for wings?", options: ["They get stuck on a church roof", "They crash into trees", "They can't come down", "They turn into birds"], correct: "A" },
      { question: "What do the children wish for that causes trouble with money?", options: ["Gold and riches", "A castle", "A pony", "A party"], correct: "A" },
      { question: "What lesson do the children learn?", options: ["Be careful what you wish for", "Never make wishes", "Magic is dangerous", "Always share"], correct: "A" },
    ],
  },
  {
    title: "The Railway Children",
    author: "E. Nesbit",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/13241123-L.jpg",
    description: "Three children move to the countryside near a railway and have adventures while their father is away.",
    questions: [
      { question: "How many children are in the story?", options: ["Three", "Two", "Four", "Five"], correct: "A" },
      { question: "What are the children's names?", options: ["Bobbie, Peter, and Phyllis", "Jane, Michael, and John", "Meg, Jo, and Beth", "Cyril, Anthea, and Robert"], correct: "A" },
      { question: "Why do the children move to the countryside?", options: ["Their father is taken away", "Their house burned down", "They lost their money", "They wanted to"], correct: "A" },
      { question: "What is near their new house?", options: ["A railway", "A forest", "A river", "A castle"], correct: "A" },
      { question: "What do the children wave to the train?", options: ["Flags and handkerchiefs", "Hats", "Branches", "Blankets"], correct: "A" },
      { question: "Who is the kind old gentleman on the train?", options: ["An old man who helps them", "Their grandfather", "A stranger", "The station master"], correct: "A" },
      { question: "What do the children do when a landslide covers the tracks?", options: ["They flag down the train with red petticoats", "They call for help", "They run away", "They try to move the rocks"], correct: "A" },
      { question: "Who does Bobbie rescue from a tunnel?", options: ["A boy in a school uniform", "A dog", "An old man", "A baby"], correct: "A" },
      { question: "Who is the boy they rescue?", options: ["Jim, the old gentleman's grandson", "A stranger", "A prince", "A beggar"], correct: "A" },
      { question: "What happens at the end of the story?", options: ["Their father returns", "They move back to the city", "They go to boarding school", "They find treasure"], correct: "A" },
    ],
  },
  {
    title: "The Enchanted Castle",
    author: "E. Nesbit",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/6644514-L.jpg",
    description: "Three children discover a magical ring that grants wishes in an enchanted castle garden.",
    questions: [
      { question: "How many children are the main characters?", options: ["Three", "Two", "Four", "Five"], correct: "A" },
      { question: "What do the children find in the castle garden?", options: ["A sleeping princess", "A dragon", "A treasure chest", "A magic wand"], correct: "A" },
      { question: "What does the princess give the children?", options: ["A magic ring", "A magic wand", "A golden key", "A book of spells"], correct: "A" },
      { question: "What can the ring do?", options: ["Grant wishes", "Make the wearer invisible", "Teleport", "Talk to animals"], correct: "A" },
      { question: "Who is the princess really?", options: ["A magical statue come to life", "A real princess", "A ghost", "An actress"], correct: "A" },
      { question: "What do the children wish for that causes chaos?", options: ["To be rich and beautiful", "To fly", "To be grown up", "To have magic powers"], correct: "A" },
      { question: "What happens when the children misuse the ring's power?", options: ["Strange and frightening things occur", "Nothing happens", "The ring breaks", "They fall asleep"], correct: "A" },
      { question: "Where is the enchanted castle located?", options: ["In a hidden valley", "On a hill", "In a forest", "By the sea"], correct: "A" },
      { question: "What must the children do to undo the magic?", options: ["Return the ring and set things right", "Find a wizard", "Say a spell", "Wait for midnight"], correct: "A" },
      { question: "What is the main theme of the story?", options: ["Magic comes with responsibility", "Castles are dangerous", "Wishes are useless", "Never explore"], correct: "A" },
    ],
  },
  {
    title: "The Story of Doctor Dolittle",
    author: "Hugh Lofting",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/5262289-L.jpg",
    description: "A doctor who can talk to animals leaves his human practice to help animals in need.",
    questions: [
      { question: "What special ability does Doctor Dolittle have?", options: ["He can talk to animals", "He can fly", "He can turn invisible", "He can heal any wound"], correct: "A" },
      { question: "Who teaches Doctor Dolittle to speak animal languages?", options: ["His parrot Polynesia", "A cat", "A dog", "A horse"], correct: "A" },
      { question: "What kind of animal is Polynesia?", options: ["A parrot", "A cat", "A monkey", "A dog"], correct: "A" },
      { question: "Why does Doctor Dolittle stop treating human patients?", options: ["His animal patients take up all his time", "He loses his license", "He gets sick", "He moves away"], correct: "A" },
      { question: "Who is Doctor Dolittle's devoted dog assistant?", options: ["Jip", "Rex", "Spot", "Fido"], correct: "A" },
      { question: "What kind of animal is Gub-Gub?", options: ["A pig", "A goat", "A monkey", "A donkey"], correct: "A" },
      { question: "Where does Doctor Dolittle travel to help monkeys?", options: ["Africa", "India", "South America", "China"], correct: "A" },
      { question: "What do the monkeys build for Doctor Dolittle?", options: ["A bridge", "A house", "A boat", "A hospital"], correct: "A" },
      { question: "Who is the monkey that becomes Doctor Dolittle's assistant?", options: ["Chee-Chee", "Coco", "Bobo", "Kiki"], correct: "A" },
      { question: "What does Doctor Dolittle use to travel?", options: ["A ship with a crew of animals", "A train", "A balloon", "A horse"], correct: "A" },
    ],
  },
  {
    title: "Heidi",
    author: "Johanna Spyri",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/2668686-L.jpg",
    description: "A young Swiss girl brings joy to her grandfather in the Alps and heals those around her.",
    questions: [
      { question: "Where does Heidi live with her grandfather?", options: ["In the Swiss Alps", "In a city", "In a forest", "By the sea"], correct: "A" },
      { question: "What is Heidi's grandfather called?", options: ["The Alm-Uncle", "Grandpa Alm", "Old Father", "The Hermit"], correct: "A" },
      { question: "Who brings Heidi to live with her grandfather?", options: ["Her aunt Dete", "Her mother", "A neighbor", "A priest"], correct: "A" },
      { question: "Who is Heidi's friend who tends the goats?", options: ["Peter", "Hans", "Fritz", "Karl"], correct: "A" },
      { question: "What is the name of the grandfather's goat boy's grandmother?", options: ["Granny", "Old Mother", "Grandma", "Mother Anna"], correct: "A" },
      { question: "Where is Heidi taken to live for a while?", options: ["Frankfurt", "Berlin", "Vienna", "Munich"], correct: "A" },
      { question: "Who is the girl Heidi befriends in the city?", options: ["Clara", "Anna", "Marie", "Lotte"], correct: "A" },
      { question: "What is wrong with Clara?", options: ["She cannot walk", "She is blind", "She is deaf", "She is very sick"], correct: "A" },
      { question: "What happens to Clara when she visits Heidi in the mountains?", options: ["She learns to walk", "She gets homesick", "She breaks her leg", "She meets Peter"], correct: "A" },
      { question: "What does Heidi bring to her grandfather?", options: ["Joy and happiness", "Money", "Food", "Clothes"], correct: "A" },
    ],
  },
  {
    title: "The Water-Babies",
    author: "Charles Kingsley",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/6062095-L.jpg",
    description: "A young chimney sweep transforms into a water baby and goes on underwater adventures.",
    questions: [
      { question: "What is the main character's name?", options: ["Tom", "Tim", "Jim", "Ben"], correct: "A" },
      { question: "What is Tom's job?", options: ["Chimney sweep", "Cobbler", "Baker", "Farm hand"], correct: "A" },
      { question: "Who is Tom's cruel master?", options: ["Mr. Grimes", "Mr. Smith", "Mr. Brown", "Mr. Blake"], correct: "A" },
      { question: "What happens to Tom when he falls into the river?", options: ["He turns into a water baby", "He drowns", "He is rescued", "He swims away"], correct: "A" },
      { question: "Where do the water babies live?", options: ["Underwater", "In trees", "In caves", "In the clouds"], correct: "A" },
      { question: "Who is the kind fairy who helps Tom?", options: ["Mrs. Bedonebyasyoudid", "The Fairy of the Stream", "Mother Carey", "The Water Queen"], correct: "A" },
      { question: "What must Tom do to become a real boy again?", options: ["Do good deeds", "Find a magic spell", "Defeat a dragon", "Find his parents"], correct: "A" },
      { question: "Where does Tom travel to in his adventure?", options: ["To the end of the world", "To the bottom of the sea", "To the stars", "To a volcano"], correct: "A" },
      { question: "What is the moral lesson of the story?", options: ["Actions have consequences", "Water is dangerous", "Magic is real", "Always be clean"], correct: "A" },
      { question: "Who does Tom help on his journey?", options: ["Other creatures in need", "His old master", "A princess", "A dragon"], correct: "A" },
    ],
  },
  {
    title: "The Princess and Curdie",
    author: "George MacDonald",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/14357835-L.jpg",
    description: "A miner boy named Curdie helps Princess Irene defeat goblins beneath the mountain.",
    questions: [
      { question: "Who is the main character?", options: ["Curdie", "Peter", "Hans", "Fritz"], correct: "A" },
      { question: "What is Curdie's job?", options: ["Miner", "Shepherd", "Baker", "Soldier"], correct: "A" },
      { question: "Who is the princess?", options: ["Princess Irene", "Princess Elsa", "Princess Anna", "Princess Rose"], correct: "A" },
      { question: "Who is Irene's magical grandmother?", options: ["Grandmother Irene", "Old Mother", "The Queen", "Mother Wise"], correct: "A" },
      { question: "Where do the goblins live?", options: ["Under the mountain", "In the forest", "In the castle", "By the river"], correct: "A" },
      { question: "What instrument does Curdie play?", options: ["A harp", "A flute", "A drum", "A violin"], correct: "A" },
      { question: "What do the goblins fear?", options: ["Sunlight and singing", "Water and fire", "Iron and salt", "Loud noises"], correct: "A" },
      { question: "What special gift does Curdie receive from the grandmother?", options: ["The ability to see true hearts", "A magic sword", "Invisibility", "The power to fly"], correct: "A" },
      { question: "Who must Curdie save?", options: ["The king and the princess", "The miners", "The kingdom", "The queen"], correct: "A" },
      { question: "What is the main theme of the story?", options: ["Goodness and courage triumph", "Goblins are real", "Mining is dangerous", "Princesses need saving"], correct: "A" },
    ],
  },
  {
    title: "Understood Betsy",
    author: "Dorothy Canfield Fisher",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/5596279-L.jpg",
    description: "A timid city girl is sent to live with country relatives and grows into a confident, capable child.",
    questions: [
      { question: "What is the main character's real name?", options: ["Elizabeth Ann", "Betsy", "Eliza", "Beth"], correct: "A" },
      { question: "Why is she called 'Understood Betsy'?", options: ["Her aunt Frances misunderstands her, but her new family understands her", "She is very smart", "She understands everything", "Her name is hard to say"], correct: "A" },
      { question: "Where does Elizabeth Ann live at the beginning?", options: ["In a city", "On a farm", "In a small town", "By the sea"], correct: "A" },
      { question: "Who raises Elizabeth Ann at first?", options: ["Her aunt Frances", "Her grandmother", "Her uncle", "Her mother"], correct: "A" },
      { question: "Why is Elizabeth Ann sent to live with new relatives?", options: ["Her aunt gets sick", "Her family moves", "She misbehaves", "She wants to go"], correct: "A" },
      { question: "Where do her new relatives live?", options: ["On a farm in Vermont", "In a big city", "In a forest", "By the ocean"], correct: "A" },
      { question: "What are her new relatives' names?", options: ["The Putneys", "The Smiths", "The Browns", "The Johnsons"], correct: "A" },
      { question: "How does Elizabeth Ann change in the country?", options: ["She becomes confident and capable", "She becomes afraid", "She becomes lazy", "She becomes rude"], correct: "A" },
      { question: "What does Betsy learn to do at school?", options: ["Think for herself", "Cook", "Sew", "Play sports"], correct: "A" },
      { question: "What lesson does the story teach?", options: ["Children grow when given responsibility", "City life is bad", "Farms are better than cities", "Aunts are strict"], correct: "A" },
    ],
  },
  {
    title: "The Magic City",
    author: "E. Nesbit",
    ageGroup: "Ages 6-9",
    coverUrl: "https://covers.openlibrary.org/b/id/1673063-L.jpg",
    description: "A lonely boy builds a magical city from household objects that comes to life.",
    questions: [
      { question: "What is the main character's name?", options: ["Philip", "Arthur", "Oliver", "Edward"], correct: "A" },
      { question: "What does Philip build?", options: ["A magical city", "A castle", "A boat", "A machine"], correct: "A" },
      { question: "What does Philip use to build his city?", options: ["Household objects and building toys", "Wood and stone", "Cards", "Clay"], correct: "A" },
      { question: "What happens to Philip's city?", options: ["It comes to life", "It is destroyed", "It is stolen", "It disappears"], correct: "A" },
      { question: "Who does Philip meet in the magic city?", options: ["A princess named Pretia", "A dragon", "A wizard", "A giant"], correct: "A" },
      { question: "What must Philip do in the magic city?", options: ["Complete quests and trials", "Fight a war", "Find treasure", "Build a castle"], correct: "A" },
      { question: "What does Philip learn from his adventure?", options: ["Courage and kindness", "Magic is dangerous", "Building is hard", "Cities are fun"], correct: "A" },
      { question: "Who is the girl Philip befriends?", options: ["Lucy", "Pretia", "Jane", "Anthea"], correct: "A" },
      { question: "Why is Philip lonely at the beginning?", options: ["His sister is getting married and he feels left out", "He has no friends", "He is an orphan", "He moved to a new town"], correct: "A" },
      { question: "What is the main theme of the story?", options: ["Imagination can create real adventures", "Cities are magical", "Loneliness is bad", "Building is fun"], correct: "A" },
    ],
  },
  {
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/12622062-L.jpg",
    description: "A spoiled girl discovers a hidden garden and brings it back to life, healing herself and others.",
    questions: [
      { question: "What is the main character's name?", options: ["Mary Lennox", "Sara Crewe", "Anne Shirley", "Jane Eyre"], correct: "A" },
      { question: "Where does Mary live at the beginning of the story?", options: ["India", "England", "France", "America"], correct: "A" },
      { question: "Why does Mary go to live with her uncle?", options: ["Her parents die in a cholera epidemic", "Her parents divorce", "She is kidnapped", "She is sent to school"], correct: "A" },
      { question: "Where does her uncle live?", options: ["Misselthwaite Manor in Yorkshire", "In London", "In Scotland", "In Ireland"], correct: "A" },
      { question: "What does Mary discover hidden behind a wall?", options: ["A secret garden", "A treasure", "A ghost", "A passage"], correct: "A" },
      { question: "Who helps Mary find the garden?", options: ["A robin bird", "A dog", "A cat", "A rabbit"], correct: "A" },
      { question: "Who is the boy Mary befriends?", options: ["Dickon", "Colin", "Martha", "Ben"], correct: "A" },
      { question: "What is Dickon's special gift?", options: ["He can talk to animals", "He is very strong", "He can read minds", "He is a great cook"], correct: "A" },
      { question: "Who is the sickly boy hidden in the manor?", options: ["Colin Craven", "Dickon Sowerby", "Archibald Craven", "Ben Weatherstaff"], correct: "A" },
      { question: "What does the garden do for the children?", options: ["It heals them physically and emotionally", "It gives them magical powers", "It makes them rich", "It hides them from the world"], correct: "A" },
    ],
  },
  {
    title: "A Little Princess",
    author: "Frances Hodgson Burnett",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/2328315-L.jpg",
    description: "A wealthy girl becomes a servant at her boarding school but keeps her kindness and imagination.",
    questions: [
      { question: "What is the main character's name?", options: ["Sara Crewe", "Mary Lennox", "Anne Shirley", "Cecilia Grant"], correct: "A" },
      { question: "Where does Sara's father send her to school?", options: ["A boarding school in London", "A school in Paris", "A school in India", "A school in America"], correct: "A" },
      { question: "Who is the strict headmistress?", options: ["Miss Minchin", "Miss Ingram", "Miss Havisham", "Miss Murdstone"], correct: "A" },
      { question: "Why does Sara become a servant?", options: ["Her father dies and she is left penniless", "She misbehaves", "She loses a bet", "She is punished"], correct: "A" },
      { question: "What does Sara use to cope with her hardship?", options: ["Her imagination and kindness", "Anger and revenge", "Running away", "Stealing"], correct: "A" },
      { question: "Who is Sara's friend and neighbor?", options: ["Ermengarde", "Becky", "Lottie", "Lavinia"], correct: "A" },
      { question: "Who is the other servant girl Sara befriends?", options: ["Becky", "Molly", "Peggy", "Jane"], correct: "A" },
      { question: "What does Sara pretend to be when she is hungry?", options: ["A soldier on a battlefield", "A queen in disguise", "A princess in hiding", "A bird in a cage"], correct: "A" },
      { question: "Who turns out to be Sara's father's business partner?", options: ["Mr. Carrisford", "Mr. Carmichael", "Mr. Barrow", "Mr. French"], correct: "A" },
      { question: "What happens to Sara at the end?", options: ["She is taken in by Mr. Carrisford and restored to wealth", "She stays at the school", "She goes back to India", "She becomes a teacher"], correct: "A" },
    ],
  },
  {
    title: "Anne of Green Gables",
    author: "L. M. Montgomery",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/14641084-L.jpg",
    description: "An imaginative orphan girl is adopted by an elderly brother and sister on Prince Edward Island.",
    questions: [
      { question: "What is the main character's full name?", options: ["Anne Shirley", "Anna Green", "Annie Stewart", "Anne Blythe"], correct: "A" },
      { question: "Where does Anne live?", options: ["Prince Edward Island", "Nova Scotia", "Ontario", "New Brunswick"], correct: "A" },
      { question: "Who adopts Anne?", options: ["Matthew and Marilla Cuthbert", "John and Mary", "Thomas and Margaret", "Robert and Rachel"], correct: "A" },
      { question: "What mistake was made when Anne arrived?", options: ["They asked for a boy, not a girl", "They got the wrong name", "She arrived a day late", "She was sent to the wrong house"], correct: "A" },
      { question: "What is the name of the Cuthberts' farm?", options: ["Green Gables", "Avonlea", "Sunnybrook", "Ingleside"], correct: "A" },
      { question: "What does Anne do to her red hair that causes trouble?", options: ["She tries to dye it and it turns green", "She cuts it all off", "She braids it wrong", "She burns it"], correct: "A" },
      { question: "Who is Anne's best friend?", options: ["Diana Barry", "Ruby Gillis", "Jane Andrews", "Josie Pye"], correct: "A" },
      { question: "Who is Anne's rival at school?", options: ["Gilbert Blythe", "Charlie Sloane", "Fred Wright", "Jerry Buote"], correct: "A" },
      { question: "What does Gilbert do that makes Anne angry?", options: ["He calls her 'Carrots' and pulls her hair", "He copies her homework", "He breaks her slate", "He laughs at her"], correct: "A" },
      { question: "What happens at the end of the story?", options: ["Matthew dies and Anne gives up a scholarship to stay with Marilla", "Anne goes to college far away", "Anne marries Gilbert", "Anne moves back to the orphanage"], correct: "A" },
    ],
  },
  {
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/13859660-L.jpg",
    description: "A young boy finds a treasure map and joins a dangerous voyage to find pirate gold.",
    questions: [
      { question: "What is the main character's name?", options: ["Jim Hawkins", "Jack Hawkins", "John Silver", "Jim Silver"], correct: "A" },
      { question: "Where does Jim work at the beginning of the story?", options: ["His family's inn", "A tavern", "A ship", "A market"], correct: "A" },
      { question: "Who is the old sailor who comes to stay at the inn?", options: ["Billy Bones", "Captain Flint", "Long John Silver", "Ben Gunn"], correct: "A" },
      { question: "What does the old sailor always watch for?", options: ["A one-legged man", "A black dog", "A ship", "A treasure map"], correct: "A" },
      { question: "What does Jim find in Billy Bones's chest?", options: ["A treasure map", "Gold coins", "A pistol", "A journal"], correct: "A" },
      { question: "Who is the one-legged cook on the ship?", options: ["Long John Silver", "Captain Smollett", "Dr. Livesey", "Squire Trelawney"], correct: "A" },
      { question: "What is the name of the ship?", options: ["The Hispaniola", "The Adventure", "The Endeavour", "The Discovery"], correct: "A" },
      { question: "Where is the treasure buried?", options: ["Treasure Island", "Skeleton Island", "Dead Man's Chest", "Spyglass Hill"], correct: "A" },
      { question: "Who is the man marooned on the island?", options: ["Ben Gunn", "Tom Morgan", "Dick Johnson", "Pew"], correct: "A" },
      { question: "What does Ben Gunn have with him?", options: ["A share of the treasure", "A boat", "A map", "A weapon"], correct: "A" },
    ],
  },
  {
    title: "Little Women",
    author: "Louisa May Alcott",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/8775559-L.jpg",
    description: "Four sisters grow up during the Civil War, each with her own dreams and challenges.",
    questions: [
      { question: "How many sisters are in the March family?", options: ["Four", "Three", "Five", "Two"], correct: "A" },
      { question: "What are the sisters' names?", options: ["Meg, Jo, Beth, and Amy", "Jane, Mary, Beth, and Amy", "Meg, Jo, Helen, and Amy", "Meg, Jo, Beth, and Anna"], correct: "A" },
      { question: "Which sister is a tomboy who loves writing?", options: ["Jo", "Meg", "Beth", "Amy"], correct: "A" },
      { question: "Which sister is the eldest?", options: ["Meg", "Jo", "Beth", "Amy"], correct: "A" },
      { question: "Which sister is shy and loves music?", options: ["Beth", "Meg", "Jo", "Amy"], correct: "A" },
      { question: "Which sister is artistic and loves pretty things?", options: ["Amy", "Meg", "Jo", "Beth"], correct: "A" },
      { question: "What is the name of the boy next door?", options: ["Laurie", "Theodore", "John", "Frederick"], correct: "A" },
      { question: "What is Laurie's real first name?", options: ["Theodore", "Edward", "Thomas", "Timothy"], correct: "A" },
      { question: "What happens to Beth?", options: ["She dies of scarlet fever complications", "She runs away", "She marries Laurie", "She moves to Europe"], correct: "A" },
      { question: "Who does Jo eventually marry?", options: ["Professor Bhaer", "Laurie", "John Brooke", "Mr. March"], correct: "A" },
    ],
  },
  {
    title: "The Jungle Book",
    author: "Rudyard Kipling",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/3344204-L.jpg",
    description: "A boy raised by wolves in the Indian jungle learns the laws of the wild.",
    questions: [
      { question: "What is the main character's name?", options: ["Mowgli", "Bagheera", "Shere Khan", "Baloo"], correct: "A" },
      { question: "Where is Mowgli raised?", options: ["In the jungle by wolves", "In a village", "In a palace", "In a temple"], correct: "A" },
      { question: "Who is the black panther?", options: ["Bagheera", "Baloo", "Shere Khan", "Kaa"], correct: "A" },
      { question: "Who is the bear who teaches Mowgli?", options: ["Baloo", "Bagheera", "Akela", "Raksha"], correct: "A" },
      { question: "Who is the tiger that wants to kill Mowgli?", options: ["Shere Khan", "Bagheera", "Akela", "Kaa"], correct: "A" },
      { question: "Who is the python?", options: ["Kaa", "Baloo", "Bagheera", "Shere Khan"], correct: "A" },
      { question: "What is the Law of the Jungle primarily about?", options: ["The strength of the pack is the wolf", "Survival of the fittest", "Never trust humans", "Always hunt alone"], correct: "A" },
      { question: "Who is the wolf pack leader?", options: ["Akela", "Raksha", "Rama", "Father Wolf"], correct: "A" },
      { question: "What is the name of the monkey people?", options: ["The Bandar-log", "The Tree Folk", "The Jungle People", "The Leaf People"], correct: "A" },
      { question: "What does Mowgli use to defeat Shere Khan?", options: ["Fire", "A knife", "A pack of wolves", "A trap"], correct: "A" },
    ],
  },
  {
    title: "Just So Stories",
    author: "Rudyard Kipling",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/36215-L.jpg",
    description: "Fantastical origin stories explaining how animals got their distinctive features.",
    questions: [
      { question: "What kind of stories are these?", options: ["Origin stories about animals", "Adventure stories", "Ghost stories", "Love stories"], correct: "A" },
      { question: "How did the elephant get its trunk?", options: ["A crocodile pulled its nose", "It evolved over time", "A wizard gave it", "It stretched it on purpose"], correct: "A" },
      { question: "How did the leopard get its spots?", options: ["An Ethiopian painted them on", "They were born with them", "A spell cast them", "The sun burned them"], correct: "A" },
      { question: "How did the camel get its hump?", options: ["A djinn punished it for being lazy", "It stored water", "It ate too much", "It was born with it"], correct: "A" },
      { question: "How did the rhinoceros get its skin?", options: ["It stole a cake and the skin wrinkled", "It was born with it", "A wizard cursed it", "It rolled in mud"], correct: "A" },
      { question: "Who wrote Just So Stories?", options: ["Rudyard Kipling", "Lewis Carroll", "Kenneth Grahame", "J.M. Barrie"], correct: "A" },
      { question: "What is the tone of these stories?", options: ["Playful and humorous", "Dark and serious", "Sad and tragic", "Scary and spooky"], correct: "A" },
      { question: "Who is the 'O Best Beloved' addressed in the stories?", options: ["The reader, especially children", "The author's daughter", "A king", "An animal"], correct: "A" },
      { question: "How did the whale get its throat?", options: ["A sailor stuck a grating in its mouth", "It swallowed a ship", "It was born small", "A spell shrank it"], correct: "A" },
      { question: "What lesson do these stories teach?", options: ["How things came to be (in a fun way)", "Animals are dangerous", "Magic is real", "Always be kind"], correct: "A" },
    ],
  },
  {
    title: "Peter Pan",
    author: "J. M. Barrie",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/8237052-L.jpg",
    description: "A boy who never grows up takes three children to Neverland for magical adventures.",
    questions: [
      { question: "Who is the boy who never grows up?", options: ["Peter Pan", "Wendy Darling", "Captain Hook", "Michael Darling"], correct: "A" },
      { question: "Where does Peter take the children?", options: ["Neverland", "Wonderland", "Narnia", "Oz"], correct: "A" },
      { question: "What are the Darling children's names?", options: ["Wendy, John, and Michael", "Wendy, Peter, and Michael", "Jane, John, and Michael", "Wendy, George, and Mary"], correct: "A" },
      { question: "What helps the children fly?", options: ["Fairy dust and happy thoughts", "Magic wings", "A potion", "A spell"], correct: "A" },
      { question: "Who is Peter Pan's fairy companion?", options: ["Tinker Bell", "Tinkerbell", "Bluebell", "Silvermist"], correct: "A" },
      { question: "Who is the villain?", options: ["Captain Hook", "Mr. Smee", "The Crocodile", "Blackbeard"], correct: "A" },
      { question: "What is Captain Hook afraid of?", options: ["The crocodile that ate his hand", "Peter Pan", "The dark", "Mermaids"], correct: "A" },
      { question: "What animal is Captain Hook's enemy?", options: ["A crocodile", "A shark", "A whale", "An octopus"], correct: "A" },
      { question: "Who is Captain Hook's bumbling assistant?", options: ["Mr. Smee", "Mr. Starkey", "Mr. Jukes", "Mr. Cookson"], correct: "A" },
      { question: "What does Peter ask Wendy to do for him and the Lost Boys?", options: ["Be their mother and tell stories", "Cook for them", "Clean their house", "Teach them to read"], correct: "A" },
    ],
  },
  {
    title: "The Prince and the Pauper",
    author: "Mark Twain",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/8221267-L.jpg",
    description: "A prince and a poor boy switch places and experience each other's very different lives.",
    questions: [
      { question: "Who are the two main characters?", options: ["Prince Edward and Tom Canty", "Prince Henry and Tom Thumb", "Prince Arthur and Tom Brown", "Prince William and Tom Sawyer"], correct: "A" },
      { question: "Where does the story take place?", options: ["London, England", "Paris, France", "Rome, Italy", "Madrid, Spain"], correct: "A" },
      { question: "When does the story take place?", options: ["16th century Tudor England", "14th century medieval England", "18th century Georgian England", "12th century Norman England"], correct: "A" },
      { question: "Why do the boys switch places?", options: ["They look alike and want to experience each other's lives", "They are forced to", "It is an accident", "They are kidnapped"], correct: "A" },
      { question: "Who is the prince?", options: ["Edward, son of King Henry VIII", "Henry, son of King Edward", "Arthur, son of King Henry", "William, son of King Richard"], correct: "A" },
      { question: "What does Tom Canty experience as prince?", options: ["The strict rules and loneliness of royal life", "Freedom and fun", "Great wealth and happiness", "Danger and adventure"], correct: "A" },
      { question: "What does Prince Edward experience as a pauper?", options: ["Poverty and injustice", "Freedom and happiness", "Adventure and excitement", "Boredom and sadness"], correct: "A" },
      { question: "Who helps Prince Edward when he is in trouble?", options: ["Miles Hendon", "Tom Canty", "John Canty", "Father Andrew"], correct: "A" },
      { question: "What happens at the end?", options: ["Edward reclaims his throne and Tom returns to his life", "They both stay as princes", "They switch permanently", "They both become paupers"], correct: "A" },
      { question: "What lesson does the story teach?", options: ["Walk a mile in another's shoes", "Rich is better than poor", "Kings are cruel", "Poverty is noble"], correct: "A" },
    ],
  },
  {
    title: "Pollyanna",
    author: "Eleanor H. Porter",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/902113-L.jpg",
    description: "An orphan girl plays a 'glad game' that transforms a whole town with her optimism.",
    questions: [
      { question: "What is the main character's name?", options: ["Pollyanna", "Polly", "Anna", "Mary"], correct: "A" },
      { question: "Who does Pollyanna go to live with?", options: ["Her aunt Polly", "Her grandmother", "Her uncle", "A neighbor"], correct: "A" },
      { question: "What is the 'glad game'?", options: ["Finding something to be glad about in any situation", "A game with balls", "A guessing game", "A card game"], correct: "A" },
      { question: "Who taught Pollyanna the glad game?", options: ["Her father", "Her mother", "Aunt Polly", "A friend"], correct: "A" },
      { question: "Why does Pollyanna play the glad game?", options: ["To stay positive and find joy in everything", "To win prizes", "To make friends", "To annoy her aunt"], correct: "A" },
      { question: "How does the town change because of Pollyanna?", options: ["People become more positive and kind", "People become jealous", "People become angry", "People become sad"], correct: "A" },
      { question: "What happens to Pollyanna that tests her optimism?", options: ["She is hit by a car and loses the use of her legs", "She loses her aunt", "She is sent away", "She loses a friend"], correct: "A" },
      { question: "How do the townspeople respond when Pollyanna is hurt?", options: ["They play the glad game to cheer her up", "They ignore her", "They feel sorry for her", "They visit her once"], correct: "A" },
      { question: "Who is the man Pollyanna befriends who lives alone?", options: ["Mr. Pendleton", "Mr. Smith", "Mr. Brown", "Mr. Jones"], correct: "A" },
      { question: "What does Pollyanna eventually learn?", options: ["That she can walk again", "That her aunt loves her", "That games are fun", "That money doesn't matter"], correct: "A" },
    ],
  },
  {
    title: "The Swiss Family Robinson",
    author: "Johann David Wyss",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/8240402-L.jpg",
    description: "A family is shipwrecked on a deserted island and uses their skills to build a new life.",
    questions: [
      { question: "What happens to the Robinson family?", options: ["They are shipwrecked on an island", "They move to the wilderness", "They are kidnapped", "They get lost at sea"], correct: "A" },
      { question: "How many children are in the Robinson family?", options: ["Four", "Three", "Five", "Six"], correct: "A" },
      { question: "What are the sons' names?", options: ["Fritz, Ernest, Jack, and Franz", "Hans, Peter, Karl, and Willi", "John, James, William, and Thomas", "Carl, Otto, Paul, and Hans"], correct: "A" },
      { question: "What do they build first on the island?", options: ["A shelter in the trees", "A house on the beach", "A boat", "A fort"], correct: "A" },
      { question: "What do they name their treehouse?", options: ["Falcon's Nest", "Eagle's Roost", "Bird's Nest", "Tree Haven"], correct: "A" },
      { question: "What animals do they tame?", options: ["A monkey, dogs, and livestock", "Lions and tigers", "Elephants", "Wolves"], correct: "A" },
      { question: "What do they discover on the island?", options: ["A cave with a natural spring", "A treasure", "A tribe", "A wrecked ship"], correct: "A" },
      { question: "What do they name the cave?", options: ["Rockburg", "Stonehall", "Cavestone", "Rockhaven"], correct: "A" },
      { question: "What danger do they face on the island?", options: ["A boa constrictor and pirates", "A volcano and earthquakes", "Wild animals and floods", "A storm and starvation"], correct: "A" },
      { question: "How does the story end?", options: ["Some stay on the island and some return to Europe", "They all return home", "They all stay on the island", "They are rescued by a ship"], correct: "A" },
    ],
  },
  {
    title: "The Story of the Treasure Seekers",
    author: "E. Nesbit",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/13241364-L.jpg",
    description: "Six children try to restore their family fortune through a series of humorous schemes.",
    questions: [
      { question: "How many children are in the Bastable family?", options: ["Six", "Four", "Five", "Three"], correct: "A" },
      { question: "What is the children's goal?", options: ["To restore their family's lost fortune", "To find their mother", "To run away", "To find treasure"], correct: "A" },
      { question: "Who is the narrator?", options: ["Oswald Bastable", "Dora Bastable", "Dicky Bastable", "Alice Bastable"], correct: "A" },
      { question: "What is unusual about the narrator?", options: ["He refers to himself in the third person", "He is very young", "He is a girl", "He never speaks"], correct: "A" },
      { question: "What are some of the schemes they try?", options: ["Digging for treasure, kidnapping a rich child, and selling poetry", "Robbing a bank, selling lemonade, and working", "Finding gold, begging, and gambling", "Mining, farming, and trading"], correct: "A" },
      { question: "Who is the eldest child?", options: ["Dora", "Oswald", "Dicky", "Alice"], correct: "A" },
      { question: "What happens to their schemes?", options: ["They almost always fail humorously", "They succeed quickly", "They get in trouble", "They find treasure"], correct: "A" },
      { question: "Who do they befriend?", options: ["An Indian uncle who visits", "A rich neighbor", "A princess", "A policeman"], correct: "A" },
      { question: "What does the Indian uncle do?", options: ["He turns out to be rich and restores the family fortune", "He takes them to India", "He gives them a ship", "He adopts them"], correct: "A" },
      { question: "What is the tone of the story?", options: ["Humorous and heartwarming", "Dark and serious", "Scary and suspenseful", "Sad and tragic"], correct: "A" },
    ],
  },
  {
    title: "Childhood's Favorites and Fairy Stories",
    author: "Various (ed. Mabie)",
    ageGroup: "Ages 9-12",
    coverUrl: "https://covers.openlibrary.org/b/id/7884139-L.jpg",
    description: "A collection of beloved fairy tales and stories from various authors.",
    questions: [
      { question: "What type of book is this?", options: ["A collection of fairy tales", "A novel", "A textbook", "A play"], correct: "A" },
      { question: "Who edited this collection?", options: ["Hamilton Wright Mabie", "Andrew Lang", "Jacob Grimm", "Hans Christian Andersen"], correct: "A" },
      { question: "Which fairy tale character falls asleep for 100 years?", options: ["Sleeping Beauty", "Snow White", "Cinderella", "Rapunzel"], correct: "A" },
      { question: "Who wrote 'The Ugly Duckling'?", options: ["Hans Christian Andersen", "The Brothers Grimm", "Charles Perrault", "Hamilton Mabie"], correct: "A" },
      { question: "What happens to the Ugly Duckling?", options: ["He grows up to be a beautiful swan", "He stays ugly", "He becomes a goose", "He turns into a prince"], correct: "A" },
      { question: "In 'Cinderella,' what does she lose?", options: ["A glass slipper", "A ring", "A crown", "A necklace"], correct: "A" },
      { question: "Who collected many of the German fairy tales?", options: ["The Brothers Grimm", "Hans Christian Andersen", "Charles Perrault", "Hamilton Mabie"], correct: "A" },
      { question: "What is the moral of many fairy tales?", options: ["Goodness and kindness are rewarded", "Magic is dangerous", "Always be rich", "Never trust anyone"], correct: "A" },
      { question: "Who wrote 'Little Red Riding Hood'?", options: ["Charles Perrault", "The Brothers Grimm", "Hans Christian Andersen", "Hamilton Mabie"], correct: "A" },
      { question: "What is the purpose of fairy tales?", options: ["To teach moral lessons through wonder", "To scare children", "To teach history", "To entertain adults"], correct: "A" },
    ],
  },
];
