// Generated by script/build_reads.py. Do not edit by hand.
// Public-domain books that can be read right on Arise (files in client/public/reads/<bookId or key>/).
// Books with a key get their library book id at runtime (server/readsSync.ts) through setReadsKeyIds().

export type ReadableBook = { bookId: number; key: string | null; title: string; author: string; chapters: number; words: number; pictures: number };

export const READABLE_BOOKS: ReadableBook[] = [
  {
    "bookId": 1,
    "key": null,
    "title": "The Tale of Peter Rabbit",
    "author": "Beatrix Potter",
    "chapters": 1,
    "words": 955,
    "pictures": 28
  },
  {
    "bookId": 2,
    "key": null,
    "title": "The Great Big Treasury of Beatrix Potter",
    "author": "Beatrix Potter",
    "chapters": 19,
    "words": 28071,
    "pictures": 0
  },
  {
    "bookId": 4,
    "key": null,
    "title": "The Story of the Three Little Pigs",
    "author": "L. Leslie Brooke",
    "chapters": 1,
    "words": 974,
    "pictures": 28
  },
  {
    "bookId": 6,
    "key": null,
    "title": "The Wonderful Wizard of Oz",
    "author": "L. Frank Baum",
    "chapters": 25,
    "words": 39440,
    "pictures": 0
  },
  {
    "bookId": 7,
    "key": null,
    "title": "Alice's Adventures in Wonderland",
    "author": "Lewis Carroll",
    "chapters": 13,
    "words": 26700,
    "pictures": 0
  },
  {
    "bookId": 8,
    "key": null,
    "title": "The Wind in the Willows",
    "author": "Kenneth Grahame",
    "chapters": 12,
    "words": 58413,
    "pictures": 0
  },
  {
    "bookId": 9,
    "key": null,
    "title": "Winnie-the-Pooh",
    "author": "A. A. Milne",
    "chapters": 11,
    "words": 22804,
    "pictures": 0
  },
  {
    "bookId": 10,
    "key": null,
    "title": "The House at Pooh Corner",
    "author": "A. A. Milne",
    "chapters": 11,
    "words": 26113,
    "pictures": 0
  },
  {
    "bookId": 11,
    "key": null,
    "title": "Black Beauty",
    "author": "Anna Sewell",
    "chapters": 49,
    "words": 59658,
    "pictures": 0
  },
  {
    "bookId": 12,
    "key": null,
    "title": "Five Children and It",
    "author": "E. Nesbit",
    "chapters": 11,
    "words": 52601,
    "pictures": 0
  },
  {
    "bookId": 13,
    "key": null,
    "title": "The Railway Children",
    "author": "E. Nesbit",
    "chapters": 14,
    "words": 59362,
    "pictures": 0
  },
  {
    "bookId": 14,
    "key": null,
    "title": "The Enchanted Castle",
    "author": "E. Nesbit",
    "chapters": 13,
    "words": 67832,
    "pictures": 0
  },
  {
    "bookId": 15,
    "key": null,
    "title": "The Story of Doctor Dolittle",
    "author": "Hugh Lofting",
    "chapters": 21,
    "words": 24834,
    "pictures": 0
  },
  {
    "bookId": 16,
    "key": null,
    "title": "Heidi",
    "author": "Johanna Spyri",
    "chapters": 23,
    "words": 91215,
    "pictures": 0
  },
  {
    "bookId": 17,
    "key": null,
    "title": "The Water-Babies",
    "author": "Charles Kingsley",
    "chapters": 9,
    "words": 68191,
    "pictures": 0
  },
  {
    "bookId": 18,
    "key": null,
    "title": "The Princess and Curdie",
    "author": "George MacDonald",
    "chapters": 35,
    "words": 55788,
    "pictures": 0
  },
  {
    "bookId": 19,
    "key": null,
    "title": "Understood Betsy",
    "author": "Dorothy Canfield Fisher",
    "chapters": 11,
    "words": 47064,
    "pictures": 0
  },
  {
    "bookId": 20,
    "key": null,
    "title": "The Magic City",
    "author": "E. Nesbit",
    "chapters": 12,
    "words": 58760,
    "pictures": 0
  },
  {
    "bookId": 21,
    "key": null,
    "title": "The Secret Garden",
    "author": "Frances Hodgson Burnett",
    "chapters": 27,
    "words": 80501,
    "pictures": 0
  },
  {
    "bookId": 22,
    "key": null,
    "title": "A Little Princess",
    "author": "Frances Hodgson Burnett",
    "chapters": 20,
    "words": 66813,
    "pictures": 0
  },
  {
    "bookId": 23,
    "key": null,
    "title": "Anne of Green Gables",
    "author": "L. M. Montgomery",
    "chapters": 38,
    "words": 102329,
    "pictures": 0
  },
  {
    "bookId": 24,
    "key": null,
    "title": "Treasure Island",
    "author": "Robert Louis Stevenson",
    "chapters": 35,
    "words": 67998,
    "pictures": 0
  },
  {
    "bookId": 25,
    "key": null,
    "title": "Little Women",
    "author": "Louisa May Alcott",
    "chapters": 48,
    "words": 186265,
    "pictures": 0
  },
  {
    "bookId": 26,
    "key": null,
    "title": "The Jungle Book",
    "author": "Rudyard Kipling",
    "chapters": 7,
    "words": 50757,
    "pictures": 0
  },
  {
    "bookId": 27,
    "key": null,
    "title": "Just So Stories",
    "author": "Rudyard Kipling",
    "chapters": 12,
    "words": 33466,
    "pictures": 0
  },
  {
    "bookId": 28,
    "key": null,
    "title": "Peter Pan",
    "author": "J. M. Barrie",
    "chapters": 17,
    "words": 47102,
    "pictures": 0
  },
  {
    "bookId": 29,
    "key": null,
    "title": "The Prince and the Pauper",
    "author": "Mark Twain",
    "chapters": 36,
    "words": 66885,
    "pictures": 0
  },
  {
    "bookId": 30,
    "key": null,
    "title": "Pollyanna",
    "author": "Eleanor H. Porter",
    "chapters": 32,
    "words": 55650,
    "pictures": 0
  },
  {
    "bookId": 31,
    "key": null,
    "title": "The Swiss Family Robinson",
    "author": "Johann David Wyss",
    "chapters": 18,
    "words": 125740,
    "pictures": 0
  },
  {
    "bookId": 32,
    "key": null,
    "title": "The Story of the Treasure Seekers",
    "author": "E. Nesbit",
    "chapters": 16,
    "words": 52505,
    "pictures": 0
  },
  {
    "bookId": 116,
    "key": null,
    "title": "The Princess and the Goblin",
    "author": "George MacDonald",
    "chapters": 32,
    "words": 50779,
    "pictures": 0
  },
  {
    "bookId": 291,
    "key": null,
    "title": "Pinocchio",
    "author": "Carlo Collodi",
    "chapters": 36,
    "words": 41512,
    "pictures": 0
  },
  {
    "bookId": 293,
    "key": null,
    "title": "At the Back of the North Wind",
    "author": "George MacDonald",
    "chapters": 38,
    "words": 88482,
    "pictures": 0
  },
  {
    "bookId": 284,
    "key": null,
    "title": "My Father's Dragon",
    "author": "Ruth Stiles Gannett",
    "chapters": 10,
    "words": 7548,
    "pictures": 44
  },
  {
    "bookId": 0,
    "key": "sleepy-hollow",
    "title": "The Legend of Sleepy Hollow",
    "author": "Washington Irving",
    "chapters": 4,
    "words": 12197,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "canterville-ghost",
    "title": "The Canterville Ghost",
    "author": "Oscar Wilde",
    "chapters": 7,
    "words": 11436,
    "pictures": 17
  },
  {
    "bookId": 0,
    "key": "velveteen-rabbit",
    "title": "The Velveteen Rabbit",
    "author": "Margery Williams",
    "chapters": 1,
    "words": 3896,
    "pictures": 8
  },
  {
    "bookId": 0,
    "key": "hound-baskervilles",
    "title": "The Hound of the Baskervilles",
    "author": "Arthur Conan Doyle",
    "chapters": 15,
    "words": 59152,
    "pictures": 0
  }
];

let keyIds: Record<string, number> = {};
/** Fills in library book ids for keyed books (from /api/reads/books). */
export function setReadsKeyIds(map: Record<string, number>) { keyIds = { ...map }; for (const b of READABLE_BOOKS) if (b.key && map[b.key]) b.bookId = Number(map[b.key]); }
/** Where a book's files live: its key, or its book id. */
export const readsDir = (b: ReadableBook) => b.key ?? String(b.bookId);
export const readableBook = (bookId: number | string | null | undefined) => READABLE_BOOKS.find((b) => (b.bookId > 0 && b.bookId === Number(bookId)) || (b.key !== null && b.key === bookId) || (b.key !== null && keyIds[b.key] === Number(bookId))) ?? null;
/** Minutes to read at about 200 words a minute. */
export const readMinutes = (words: number) => Math.max(1, Math.round(words / 200));
