// Generated by script/build_reads.py. Do not edit by hand.
// Public-domain books that can be read right on Arise (files in client/public/reads/<bookId or key>/).
// Books with a key get their library book id at runtime (server/readsSync.ts) through setReadsKeyIds().

export type ReadableBook = { bookId: number; key: string | null; title: string; author: string; chapters: number; words: number; pictures: number };

export const READABLE_BOOKS: ReadableBook[] = [
  {
    "bookId": 1,
    "key": null,
    "title": "The Tale of Peter Rabbit",
    "author": "Beatrix Potter",
    "chapters": 1,
    "words": 955,
    "pictures": 28
  },
  {
    "bookId": 2,
    "key": null,
    "title": "The Great Big Treasury of Beatrix Potter",
    "author": "Beatrix Potter",
    "chapters": 19,
    "words": 28071,
    "pictures": 0
  },
  {
    "bookId": 4,
    "key": null,
    "title": "The Story of the Three Little Pigs",
    "author": "L. Leslie Brooke",
    "chapters": 1,
    "words": 974,
    "pictures": 28
  },
  {
    "bookId": 6,
    "key": null,
    "title": "The Wonderful Wizard of Oz",
    "author": "L. Frank Baum",
    "chapters": 25,
    "words": 39440,
    "pictures": 0
  },
  {
    "bookId": 7,
    "key": null,
    "title": "Alice's Adventures in Wonderland",
    "author": "Lewis Carroll",
    "chapters": 13,
    "words": 26700,
    "pictures": 0
  },
  {
    "bookId": 8,
    "key": null,
    "title": "The Wind in the Willows",
    "author": "Kenneth Grahame",
    "chapters": 12,
    "words": 58413,
    "pictures": 0
  },
  {
    "bookId": 9,
    "key": null,
    "title": "Winnie-the-Pooh",
    "author": "A. A. Milne",
    "chapters": 11,
    "words": 22804,
    "pictures": 0
  },
  {
    "bookId": 10,
    "key": null,
    "title": "The House at Pooh Corner",
    "author": "A. A. Milne",
    "chapters": 11,
    "words": 26113,
    "pictures": 0
  },
  {
    "bookId": 11,
    "key": null,
    "title": "Black Beauty",
    "author": "Anna Sewell",
    "chapters": 49,
    "words": 59658,
    "pictures": 0
  },
  {
    "bookId": 12,
    "key": null,
    "title": "Five Children and It",
    "author": "E. Nesbit",
    "chapters": 11,
    "words": 52601,
    "pictures": 0
  },
  {
    "bookId": 13,
    "key": null,
    "title": "The Railway Children",
    "author": "E. Nesbit",
    "chapters": 14,
    "words": 59362,
    "pictures": 0
  },
  {
    "bookId": 14,
    "key": null,
    "title": "The Enchanted Castle",
    "author": "E. Nesbit",
    "chapters": 13,
    "words": 67832,
    "pictures": 0
  },
  {
    "bookId": 15,
    "key": null,
    "title": "The Story of Doctor Dolittle",
    "author": "Hugh Lofting",
    "chapters": 21,
    "words": 24834,
    "pictures": 0
  },
  {
    "bookId": 16,
    "key": null,
    "title": "Heidi",
    "author": "Johanna Spyri",
    "chapters": 23,
    "words": 91215,
    "pictures": 0
  },
  {
    "bookId": 17,
    "key": null,
    "title": "The Water-Babies",
    "author": "Charles Kingsley",
    "chapters": 9,
    "words": 68191,
    "pictures": 0
  },
  {
    "bookId": 18,
    "key": null,
    "title": "The Princess and Curdie",
    "author": "George MacDonald",
    "chapters": 35,
    "words": 55788,
    "pictures": 0
  },
  {
    "bookId": 19,
    "key": null,
    "title": "Understood Betsy",
    "author": "Dorothy Canfield Fisher",
    "chapters": 11,
    "words": 47064,
    "pictures": 0
  },
  {
    "bookId": 20,
    "key": null,
    "title": "The Magic City",
    "author": "E. Nesbit",
    "chapters": 12,
    "words": 58760,
    "pictures": 0
  },
  {
    "bookId": 21,
    "key": null,
    "title": "The Secret Garden",
    "author": "Frances Hodgson Burnett",
    "chapters": 27,
    "words": 80501,
    "pictures": 0
  },
  {
    "bookId": 22,
    "key": null,
    "title": "A Little Princess",
    "author": "Frances Hodgson Burnett",
    "chapters": 20,
    "words": 66813,
    "pictures": 0
  },
  {
    "bookId": 23,
    "key": null,
    "title": "Anne of Green Gables",
    "author": "L. M. Montgomery",
    "chapters": 38,
    "words": 102329,
    "pictures": 0
  },
  {
    "bookId": 24,
    "key": null,
    "title": "Treasure Island",
    "author": "Robert Louis Stevenson",
    "chapters": 35,
    "words": 67998,
    "pictures": 0
  },
  {
    "bookId": 25,
    "key": null,
    "title": "Little Women",
    "author": "Louisa May Alcott",
    "chapters": 48,
    "words": 186265,
    "pictures": 0
  },
  {
    "bookId": 26,
    "key": null,
    "title": "The Jungle Book",
    "author": "Rudyard Kipling",
    "chapters": 7,
    "words": 50757,
    "pictures": 0
  },
  {
    "bookId": 27,
    "key": null,
    "title": "Just So Stories",
    "author": "Rudyard Kipling",
    "chapters": 12,
    "words": 33466,
    "pictures": 0
  },
  {
    "bookId": 28,
    "key": null,
    "title": "Peter Pan",
    "author": "J. M. Barrie",
    "chapters": 17,
    "words": 47102,
    "pictures": 0
  },
  {
    "bookId": 29,
    "key": null,
    "title": "The Prince and the Pauper",
    "author": "Mark Twain",
    "chapters": 36,
    "words": 66885,
    "pictures": 0
  },
  {
    "bookId": 30,
    "key": null,
    "title": "Pollyanna",
    "author": "Eleanor H. Porter",
    "chapters": 32,
    "words": 55650,
    "pictures": 0
  },
  {
    "bookId": 31,
    "key": null,
    "title": "The Swiss Family Robinson",
    "author": "Johann David Wyss",
    "chapters": 18,
    "words": 125740,
    "pictures": 0
  },
  {
    "bookId": 32,
    "key": null,
    "title": "The Story of the Treasure Seekers",
    "author": "E. Nesbit",
    "chapters": 16,
    "words": 52505,
    "pictures": 0
  },
  {
    "bookId": 116,
    "key": null,
    "title": "The Princess and the Goblin",
    "author": "George MacDonald",
    "chapters": 32,
    "words": 50779,
    "pictures": 0
  },
  {
    "bookId": 291,
    "key": null,
    "title": "Pinocchio",
    "author": "Carlo Collodi",
    "chapters": 36,
    "words": 41512,
    "pictures": 0
  },
  {
    "bookId": 293,
    "key": null,
    "title": "At the Back of the North Wind",
    "author": "George MacDonald",
    "chapters": 38,
    "words": 88482,
    "pictures": 0
  },
  {
    "bookId": 284,
    "key": null,
    "title": "My Father's Dragon",
    "author": "Ruth Stiles Gannett",
    "chapters": 10,
    "words": 7548,
    "pictures": 44
  },
  {
    "bookId": 0,
    "key": "sleepy-hollow",
    "title": "The Legend of Sleepy Hollow",
    "author": "Washington Irving",
    "chapters": 4,
    "words": 12197,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "canterville-ghost",
    "title": "The Canterville Ghost",
    "author": "Oscar Wilde",
    "chapters": 7,
    "words": 11436,
    "pictures": 17
  },
  {
    "bookId": 0,
    "key": "velveteen-rabbit",
    "title": "The Velveteen Rabbit",
    "author": "Margery Williams",
    "chapters": 1,
    "words": 3896,
    "pictures": 8
  },
  {
    "bookId": 0,
    "key": "hound-baskervilles",
    "title": "The Hound of the Baskervilles",
    "author": "Arthur Conan Doyle",
    "chapters": 15,
    "words": 59152,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "tower-treasure",
    "title": "The Tower Treasure",
    "author": "Franklin W. Dixon",
    "chapters": 24,
    "words": 41176,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "secret-of-the-old-mill",
    "title": "The Secret of the Old Mill",
    "author": "Franklin W. Dixon",
    "chapters": 25,
    "words": 40714,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "missing-chums",
    "title": "The Missing Chums",
    "author": "Franklin W. Dixon",
    "chapters": 23,
    "words": 42210,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "shore-road-mystery",
    "title": "The Shore Road Mystery",
    "author": "Franklin W. Dixon",
    "chapters": 23,
    "words": 39463,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "secret-of-the-caves",
    "title": "The Secret of the Caves",
    "author": "Franklin W. Dixon",
    "chapters": 25,
    "words": 39944,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "mystery-of-cabin-island",
    "title": "The Mystery of Cabin Island",
    "author": "Franklin W. Dixon",
    "chapters": 25,
    "words": 40430,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "great-airport-mystery",
    "title": "The Great Airport Mystery",
    "author": "Franklin W. Dixon",
    "chapters": 24,
    "words": 39627,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "bungalow-mystery",
    "title": "The Bungalow Mystery",
    "author": "Carolyn Keene",
    "chapters": 25,
    "words": 37970,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "macdonald-fairy-tales",
    "title": "The Light Princess and Other Fairy Tales",
    "author": "George MacDonald",
    "chapters": 20,
    "words": 121121,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "windfairies",
    "title": "The Windfairies",
    "author": "Mary De Morgan",
    "chapters": 9,
    "words": 45213,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "princess-fiorimonde",
    "title": "The Necklace of Princess Fiorimonde",
    "author": "Mary De Morgan",
    "chapters": 7,
    "words": 34073,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "on-a-pincushion",
    "title": "On a Pincushion",
    "author": "Mary De Morgan",
    "chapters": 8,
    "words": 43757,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "swallows-and-amazons",
    "title": "Swallows and Amazons",
    "author": "Arthur Ransome",
    "chapters": 31,
    "words": 99390,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "marvelous-land-of-oz",
    "title": "The Marvelous Land of Oz",
    "author": "L. Frank Baum",
    "chapters": 25,
    "words": 41491,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "ozma-of-oz",
    "title": "Ozma of Oz",
    "author": "L. Frank Baum",
    "chapters": 22,
    "words": 38387,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "dorothy-and-the-wizard",
    "title": "Dorothy and the Wizard in Oz",
    "author": "L. Frank Baum",
    "chapters": 21,
    "words": 41865,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "road-to-oz",
    "title": "The Road to Oz",
    "author": "L. Frank Baum",
    "chapters": 25,
    "words": 39161,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "patchwork-girl-of-oz",
    "title": "The Patchwork Girl of Oz",
    "author": "L. Frank Baum",
    "chapters": 28,
    "words": 56701,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "scarecrow-of-oz",
    "title": "The Scarecrow of Oz",
    "author": "L. Frank Baum",
    "chapters": 23,
    "words": 45187,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "emerald-city-of-oz",
    "title": "The Emerald City of Oz",
    "author": "L. Frank Baum",
    "chapters": 30,
    "words": 53246,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "magic-of-oz",
    "title": "The Magic of Oz",
    "author": "L. Frank Baum",
    "chapters": 23,
    "words": 39002,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "lost-princess-of-oz",
    "title": "The Lost Princess of Oz",
    "author": "L. Frank Baum",
    "chapters": 26,
    "words": 46600,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "cornelli",
    "title": "Cornelli",
    "author": "Johanna Spyri",
    "chapters": 10,
    "words": 49588,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "emily-of-new-moon",
    "title": "Emily of New Moon",
    "author": "L. M. Montgomery",
    "chapters": 31,
    "words": 113173,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "bambi",
    "title": "Bambi",
    "author": "Felix Salten",
    "chapters": 25,
    "words": 40738,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "the-blue-bird",
    "title": "The Blue Bird",
    "author": "Maurice Maeterlinck",
    "chapters": 10,
    "words": 32769,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "old-indian-legends",
    "title": "Old Indian Legends",
    "author": "Zitkala-Ša",
    "chapters": 15,
    "words": 18365,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "smoky-the-cowhorse",
    "title": "Smoky the Cowhorse",
    "author": "Will James",
    "chapters": 15,
    "words": 80485,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "grimms-household-tales",
    "title": "Grimms' Household Tales",
    "author": "Jacob and Wilhelm Grimm",
    "chapters": 199,
    "words": 278808,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "wet-magic",
    "title": "Wet Magic",
    "author": "E. Nesbit",
    "chapters": 12,
    "words": 48995,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "story-of-the-amulet",
    "title": "The Story of the Amulet",
    "author": "E. Nesbit",
    "chapters": 14,
    "words": 68610,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "house-of-arden",
    "title": "The House of Arden",
    "author": "E. Nesbit",
    "chapters": 14,
    "words": 72161,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "indian-fairy-tales",
    "title": "Indian Fairy Tales",
    "author": "Joseph Jacobs",
    "chapters": 31,
    "words": 70884,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "wilde-childrens-stories",
    "title": "The Happy Prince and Other Stories",
    "author": "Oscar Wilde",
    "chapters": 8,
    "words": 35327,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "green-forest-stories",
    "title": "Green Forest Stories",
    "author": "Thornton W. Burgess",
    "chapters": 16,
    "words": 84363,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "green-meadow-stories",
    "title": "Green Meadow Stories",
    "author": "Thornton W. Burgess",
    "chapters": 16,
    "words": 88274,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "little-lord-fauntleroy",
    "title": "Little Lord Fauntleroy",
    "author": "Frances Hodgson Burnett",
    "chapters": 15,
    "words": 58308,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "kidnapped",
    "title": "Kidnapped",
    "author": "Robert Louis Stevenson",
    "chapters": 32,
    "words": 80518,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "through-the-looking-glass",
    "title": "Through the Looking-Glass",
    "author": "Lewis Carroll",
    "chapters": 13,
    "words": 29650,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "adventures-of-nils",
    "title": "The Wonderful Adventures of Nils",
    "author": "Selma Lagerlöf",
    "chapters": 44,
    "words": 154148,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "freckles",
    "title": "Freckles",
    "author": "Gene Stratton-Porter",
    "chapters": 20,
    "words": 81597,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "christmas-carol",
    "title": "A Christmas Carol",
    "author": "Charles Dickens",
    "chapters": 5,
    "words": 28549,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "jekyll-and-hyde",
    "title": "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "author": "Robert Louis Stevenson",
    "chapters": 10,
    "words": 25605,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "frankenstein",
    "title": "Frankenstein",
    "author": "Mary Shelley",
    "chapters": 30,
    "words": 77790,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "war-of-the-worlds",
    "title": "The War of the Worlds",
    "author": "H. G. Wells",
    "chapters": 27,
    "words": 59930,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "first-men-in-the-moon",
    "title": "The First Men in the Moon",
    "author": "H. G. Wells",
    "chapters": 26,
    "words": 68327,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "adventures-of-sherlock-holmes",
    "title": "The Adventures of Sherlock Holmes",
    "author": "Arthur Conan Doyle",
    "chapters": 12,
    "words": 104690,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "memoirs-of-sherlock-holmes",
    "title": "The Memoirs of Sherlock Holmes",
    "author": "Arthur Conan Doyle",
    "chapters": 12,
    "words": 95817,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "return-of-sherlock-holmes",
    "title": "The Return of Sherlock Holmes",
    "author": "Arthur Conan Doyle",
    "chapters": 13,
    "words": 112134,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "valley-of-fear",
    "title": "The Valley of Fear",
    "author": "Arthur Conan Doyle",
    "chapters": 15,
    "words": 57532,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "prisoner-of-zenda",
    "title": "The Prisoner of Zenda",
    "author": "Anthony Hope",
    "chapters": 22,
    "words": 53598,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "black-arrow",
    "title": "The Black Arrow",
    "author": "Robert Louis Stevenson",
    "chapters": 33,
    "words": 79144,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "aesops-fables",
    "title": "Aesop's Fables",
    "author": "Aesop",
    "chapters": 9,
    "words": 39496,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "phantom-of-the-opera",
    "title": "The Phantom of the Opera",
    "author": "Gaston Leroux",
    "chapters": 28,
    "words": 83137,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "ragged-dick",
    "title": "Ragged Dick",
    "author": "Horatio Alger Jr.",
    "chapters": 28,
    "words": 48059,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "anne-of-avonlea",
    "title": "Anne of Avonlea",
    "author": "L. M. Montgomery",
    "chapters": 30,
    "words": 89564,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "anne-of-the-island",
    "title": "Anne of the Island",
    "author": "L. M. Montgomery",
    "chapters": 41,
    "words": 76451,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "secret-adversary",
    "title": "The Secret Adversary",
    "author": "Agatha Christie",
    "chapters": 29,
    "words": 75279,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "murder-on-the-links",
    "title": "The Murder on the Links",
    "author": "Agatha Christie",
    "chapters": 28,
    "words": 64774,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "red-house-mystery",
    "title": "The Red House Mystery",
    "author": "A. A. Milne",
    "chapters": 23,
    "words": 60276,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "king-of-elflands-daughter",
    "title": "The King of Elfland's Daughter",
    "author": "Lord Dunsany",
    "chapters": 35,
    "words": 69425,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "the-gold-bat",
    "title": "The Gold Bat",
    "author": "P. G. Wodehouse",
    "chapters": 24,
    "words": 42877,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "hindu-tales",
    "title": "Hindu Tales from the Sanskrit",
    "author": "S. M. Mitra",
    "chapters": 10,
    "words": 39646,
    "pictures": 0
  },
  {
    "bookId": 0,
    "key": "sylvie-and-bruno",
    "title": "Sylvie and Bruno",
    "author": "Lewis Carroll",
    "chapters": 53,
    "words": 134810,
    "pictures": 0
  }
];

let keyIds: Record<string, number> = {};
/** Fills in library book ids for keyed books (from /api/reads/books). */
export function setReadsKeyIds(map: Record<string, number>) { keyIds = { ...map }; for (const b of READABLE_BOOKS) if (b.key && map[b.key]) b.bookId = Number(map[b.key]); }
/** Where a book's files live: its key, or its book id. */
export const readsDir = (b: ReadableBook) => b.key ?? String(b.bookId);
export const readableBook = (bookId: number | string | null | undefined) => READABLE_BOOKS.find((b) => (b.bookId > 0 && b.bookId === Number(bookId)) || (b.key !== null && b.key === bookId) || (b.key !== null && keyIds[b.key] === Number(bookId))) ?? null;
/** Minutes to read at about 200 words a minute. */
export const readMinutes = (words: number) => Math.max(1, Math.round(words / 200));
