// Generated by script/build_reads.py. Do not edit by hand.
// Public-domain books that can be read right on Arise (files in client/public/reads/<bookId>/).

export type ReadableBook = { bookId: number; title: string; author: string; chapters: number; words: number; pictures: number };

export const READABLE_BOOKS: ReadableBook[] = [
  {
    "bookId": 1,
    "title": "The Tale of Peter Rabbit",
    "author": "Beatrix Potter",
    "chapters": 1,
    "words": 955,
    "pictures": 28
  },
  {
    "bookId": 2,
    "title": "The Great Big Treasury of Beatrix Potter",
    "author": "Beatrix Potter",
    "chapters": 19,
    "words": 28071,
    "pictures": 0
  },
  {
    "bookId": 4,
    "title": "The Story of the Three Little Pigs",
    "author": "L. Leslie Brooke",
    "chapters": 1,
    "words": 974,
    "pictures": 28
  },
  {
    "bookId": 6,
    "title": "The Wonderful Wizard of Oz",
    "author": "L. Frank Baum",
    "chapters": 25,
    "words": 39440,
    "pictures": 0
  },
  {
    "bookId": 7,
    "title": "Alice's Adventures in Wonderland",
    "author": "Lewis Carroll",
    "chapters": 13,
    "words": 26700,
    "pictures": 0
  },
  {
    "bookId": 8,
    "title": "The Wind in the Willows",
    "author": "Kenneth Grahame",
    "chapters": 12,
    "words": 58413,
    "pictures": 0
  },
  {
    "bookId": 9,
    "title": "Winnie-the-Pooh",
    "author": "A. A. Milne",
    "chapters": 11,
    "words": 22804,
    "pictures": 0
  },
  {
    "bookId": 10,
    "title": "The House at Pooh Corner",
    "author": "A. A. Milne",
    "chapters": 11,
    "words": 26113,
    "pictures": 0
  },
  {
    "bookId": 11,
    "title": "Black Beauty",
    "author": "Anna Sewell",
    "chapters": 49,
    "words": 59658,
    "pictures": 0
  },
  {
    "bookId": 12,
    "title": "Five Children and It",
    "author": "E. Nesbit",
    "chapters": 11,
    "words": 52601,
    "pictures": 0
  },
  {
    "bookId": 13,
    "title": "The Railway Children",
    "author": "E. Nesbit",
    "chapters": 14,
    "words": 59362,
    "pictures": 0
  },
  {
    "bookId": 14,
    "title": "The Enchanted Castle",
    "author": "E. Nesbit",
    "chapters": 13,
    "words": 67832,
    "pictures": 0
  },
  {
    "bookId": 15,
    "title": "The Story of Doctor Dolittle",
    "author": "Hugh Lofting",
    "chapters": 21,
    "words": 24834,
    "pictures": 0
  },
  {
    "bookId": 16,
    "title": "Heidi",
    "author": "Johanna Spyri",
    "chapters": 23,
    "words": 91215,
    "pictures": 0
  },
  {
    "bookId": 17,
    "title": "The Water-Babies",
    "author": "Charles Kingsley",
    "chapters": 9,
    "words": 68191,
    "pictures": 0
  },
  {
    "bookId": 18,
    "title": "The Princess and Curdie",
    "author": "George MacDonald",
    "chapters": 35,
    "words": 55788,
    "pictures": 0
  },
  {
    "bookId": 19,
    "title": "Understood Betsy",
    "author": "Dorothy Canfield Fisher",
    "chapters": 11,
    "words": 47064,
    "pictures": 0
  },
  {
    "bookId": 20,
    "title": "The Magic City",
    "author": "E. Nesbit",
    "chapters": 12,
    "words": 58760,
    "pictures": 0
  },
  {
    "bookId": 21,
    "title": "The Secret Garden",
    "author": "Frances Hodgson Burnett",
    "chapters": 27,
    "words": 80501,
    "pictures": 0
  },
  {
    "bookId": 22,
    "title": "A Little Princess",
    "author": "Frances Hodgson Burnett",
    "chapters": 20,
    "words": 66813,
    "pictures": 0
  },
  {
    "bookId": 23,
    "title": "Anne of Green Gables",
    "author": "L. M. Montgomery",
    "chapters": 38,
    "words": 102329,
    "pictures": 0
  },
  {
    "bookId": 24,
    "title": "Treasure Island",
    "author": "Robert Louis Stevenson",
    "chapters": 35,
    "words": 67998,
    "pictures": 0
  },
  {
    "bookId": 25,
    "title": "Little Women",
    "author": "Louisa May Alcott",
    "chapters": 48,
    "words": 186265,
    "pictures": 0
  },
  {
    "bookId": 26,
    "title": "The Jungle Book",
    "author": "Rudyard Kipling",
    "chapters": 7,
    "words": 50757,
    "pictures": 0
  },
  {
    "bookId": 27,
    "title": "Just So Stories",
    "author": "Rudyard Kipling",
    "chapters": 12,
    "words": 33466,
    "pictures": 0
  },
  {
    "bookId": 28,
    "title": "Peter Pan",
    "author": "J. M. Barrie",
    "chapters": 17,
    "words": 47102,
    "pictures": 0
  },
  {
    "bookId": 29,
    "title": "The Prince and the Pauper",
    "author": "Mark Twain",
    "chapters": 36,
    "words": 66885,
    "pictures": 0
  },
  {
    "bookId": 30,
    "title": "Pollyanna",
    "author": "Eleanor H. Porter",
    "chapters": 32,
    "words": 55650,
    "pictures": 0
  },
  {
    "bookId": 31,
    "title": "The Swiss Family Robinson",
    "author": "Johann David Wyss",
    "chapters": 18,
    "words": 125740,
    "pictures": 0
  },
  {
    "bookId": 32,
    "title": "The Story of the Treasure Seekers",
    "author": "E. Nesbit",
    "chapters": 16,
    "words": 52505,
    "pictures": 0
  }
];

export const readableBook = (bookId: number | null | undefined) => READABLE_BOOKS.find((b) => b.bookId === Number(bookId)) ?? null;
/** Minutes to read at about 200 words a minute. */
export const readMinutes = (words: number) => Math.max(1, Math.round(words / 200));
