import type { TheaterMovie } from "./clubTheater";
const originalMovies=[
    { id:"cinema-1", title:"Cinema Pick 1", subtitle:"Selected for A.R.I.S.E. Cinema", kind:"video" as const, youtubeId:"vq9TWtT6Uwg", youtubePlaylistId:"", duration:7200, license:"YouTube embed", attribution:"User-selected YouTube video", age:"Featured", category:"Featured" },
    { id:"cinema-2", title:"Cinema Pick 2", subtitle:"Selected for A.R.I.S.E. Cinema", kind:"video" as const, youtubeId:"ixbkzsNCgV8", youtubePlaylistId:"", duration:7200, license:"YouTube embed", attribution:"User-selected YouTube video", age:"Featured", category:"Featured" },
    { id:"cinema-3", title:"Cinema Pick 3", subtitle:"Selected for A.R.I.S.E. Cinema", kind:"video" as const, youtubeId:"VAfGav-5X70", youtubePlaylistId:"", duration:7200, license:"YouTube embed", attribution:"User-selected YouTube video", age:"Featured", category:"Featured" },
    { id:"cinema-4", title:"Cinema Pick 4", subtitle:"Selected for A.R.I.S.E. Cinema", kind:"video" as const, youtubeId:"O1MSGBhXDOA", youtubePlaylistId:"", duration:7200, license:"YouTube embed", attribution:"User-selected YouTube video", age:"Featured", category:"Featured" },
    { id:"cinema-series-1", title:"YouTube Series · Season 1", subtitle:"Series selection from the supplied YouTube Show link", kind:"channel" as const, youtubeId:"", youtubePlaylistId:"UU_l_vAU56D8Sa4WCEZtWIi1w", duration:21600, license:"YouTube embed", attribution:"YouTube show/channel selection", age:"Series", category:"Series & Shows" },
    { id:"cinema-6", title:"Cinema Pick 6", subtitle:"Selected for A.R.I.S.E. Cinema", kind:"video" as const, youtubeId:"qvNsNOIE4CQ", youtubePlaylistId:"", duration:7200, license:"YouTube embed", attribution:"User-selected YouTube video", age:"Featured", category:"Featured" },
    { id:"cinema-7", title:"Cinema Pick 7", subtitle:"Selected for A.R.I.S.E. Cinema", kind:"video" as const, youtubeId:"s1Ylmj87gXY", youtubePlaylistId:"", duration:7200, license:"YouTube embed", attribution:"User-selected YouTube video", age:"Featured", category:"Featured" },
    { id:"cinema-8", title:"Cinema Pick 8", subtitle:"Selected for A.R.I.S.E. Cinema", kind:"video" as const, youtubeId:"tHNXAgZLZwk", youtubePlaylistId:"", duration:7200, license:"YouTube embed", attribution:"User-selected YouTube video", age:"Featured", category:"Featured" },
    { id:"cinema-live-1", title:"Live Cinema Channel 1", subtitle:"Live YouTube selection", kind:"video" as const, youtubeId:"_HviSyC7zSU", youtubePlaylistId:"", duration:21600, license:"YouTube live embed", attribution:"User-selected YouTube live stream", age:"Live", category:"Live" },
    { id:"cinema-live-2", title:"Live Cinema Channel 2", subtitle:"Live YouTube selection", kind:"video" as const, youtubeId:"yzKTO-6KWHU", youtubePlaylistId:"", duration:21600, license:"YouTube live embed", attribution:"User-selected YouTube live stream", age:"Live", category:"Live" }
  ] as const;
export const DEFAULT_THEATER_MOVIES: TheaterMovie[] = originalMovies.map(movie => ({...movie, provider: "youtube", enabled: true, videoUrl: "", sourceUrl: movie.youtubePlaylistId ? "https://www.youtube.com/playlist?list=" + movie.youtubePlaylistId : "https://www.youtube.com/watch?v=" + movie.youtubeId}));
