import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {getAvatarCharacter} from '@/lib/avatarCharacters';
import {boardPosition,cueStage,moveLandingAt,SPACE_LABELS,EVENTS,TIMING,type View,type Hand} from '@shared/boardQuest';
const COLORS=[0xf3c84b,0x58b86b,0x8b5cf6,0x38bdf8,0xef5b4d,0x3157d5,0xf6b90b];
const ease=(t:number)=>{t=THREE.MathUtils.clamp(t,0,1);return t*t*(3-2*t)};
const at=(space:number)=>{const p=boardPosition(space),tier=Math.floor(space/7);return new THREE.Vector3(p.x,2.4+tier*2.9,p.z)};
export const DIE_VALUES=[1,6,2,5,3,4];
export const DIE_NORMALS=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
export function dieOrientation(value:number){return new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(...DIE_NORMALS[DIE_VALUES.indexOf(value)]),new THREE.Vector3(0,.4,1).normalize());}
function label(text:string,color='#12213d',width=512,height=128){const c=document.createElement('canvas');c.width=width;c.height=height;const x=c.getContext('2d')!;x.fillStyle=color;x.beginPath();x.roundRect(8,8,width-16,height-16,24);x.fill();x.fillStyle='white';x.font='900 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,width/2,height/2,width-24);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map,transparent:true,depthTest:false}));sprite.scale.set(4,1,1);return sprite;}
function tileMark(text:string,color='#ffffff'){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d')!;x.clearRect(0,0,512,256);x.fillStyle='rgba(8,25,58,.22)';x.beginPath();x.roundRect(24,38,464,180,42);x.fill();x.strokeStyle='rgba(255,226,137,.75)';x.lineWidth=8;x.stroke();x.fillStyle=color;x.font='900 66px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,128,420);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(3.1,1.55),new THREE.MeshBasicMaterial({map,transparent:true,depthWrite:false,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;return mesh;}
function fallbackCharacter(color:number){const g=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color,roughness:.62}),skin=new THREE.MeshStandardMaterial({color:0xf1b98b,roughness:.75}),dark=new THREE.MeshStandardMaterial({color:0x172033,roughness:.72});const head=new THREE.Mesh(new THREE.SphereGeometry(.38,18,14),skin);head.position.y=2.55;const body=new THREE.Mesh(new THREE.BoxGeometry(.85,1.1,.5),cloth);body.position.y=1.65;const hips=new THREE.Mesh(new THREE.BoxGeometry(.68,.38,.42),dark);hips.position.y=.95;g.add(head,body,hips);for(const side of [-1,1]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.65,3,8),cloth);arm.position.set(side*.58,1.7,0);arm.rotation.z=side*.2;const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.15,.72,3,8),dark);leg.position.set(side*.22,.35,0);g.add(arm,leg);}g.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});return g;}
function diceMaterial(value:number){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d')!;x.fillStyle='#f8fafc';x.fillRect(0,0,256,256);x.strokeStyle='#bfdbfe';x.lineWidth=12;x.strokeRect(6,6,244,244);x.fillStyle='#10203d';const sets:Record<number,number[][]>={1:[[0,0]],2:[[-1,-1],[1,1]],3:[[-1,-1],[0,0],[1,1]],4:[[-1,-1],[-1,1],[1,-1],[1,1]],5:[[-1,-1],[-1,1],[1,-1],[1,1],[0,0]],6:[[-1,-1],[-1,0],[-1,1],[1,-1],[1,0],[1,1]]};for(const [a,b]of sets[value]){x.beginPath();x.arc(128+a*66,128+b*66,20,0,Math.PI*2);x.fill();}const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({map,roughness:.27,metalness:.15});}
function handMesh(hand:Hand,color:number){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,roughness:.4,metalness:.12});const palm=new THREE.Mesh(new THREE.BoxGeometry(1.45,1.5,.7),mat);palm.position.y=.15;g.add(palm);const sphere=new THREE.SphereGeometry(.25,12,10);const finger=(x:number,length:number,angle=0)=>{const f=new THREE.Mesh(new THREE.CapsuleGeometry(.23,length,4,10),mat);f.position.set(x,1+length/2,0);f.rotation.z=angle;g.add(f);};if(hand==='rock'){for(let i=0;i<4;i++){const m=new THREE.Mesh(sphere,mat);m.position.set((i-1.5)*.37,.98,.1);g.add(m);}}else{for(let i=0;i<4;i++)finger((i-1.5)*.36,hand==='paper'?1.1+(i===1||i===2?.15:0):i<2?1.65:.05,hand==='scissors'&&i<2?(i===0?.17:-.17):0);}const thumb=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.6,4,10),mat);thumb.rotation.z=-.7;thumb.position.set(.85,.05,.2);g.add(thumb);g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});return g;}
export class BoardScene{
 private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(50,1,.1,240);private renderer:THREE.WebGLRenderer;private controls:OrbitControls;private roots=new Map<number,THREE.Group>();private tiles:THREE.Mesh<THREE.BufferGeometry,THREE.MeshStandardMaterial>[]=[];private mixers:THREE.AnimationMixer[]=[];private die:THREE.Mesh;private ring:THREE.Mesh;private particles:THREE.Mesh[]=[];private coins:THREE.Mesh[]=[];private aura:THREE.Mesh;private hands=new THREE.Group();private rewardLabel:THREE.Sprite|null=null;private labelKey='';private handKey='';private raf=0;private disposed=false;private lastTime=0;private lastCue=-1;private view:View;private offset=0;private reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;private resizeObserver:ResizeObserver;private home=new THREE.Vector3();private homeTarget=new THREE.Vector3(0,6,3);
 constructor(private host:HTMLDivElement,view:View,offset:number,private onReady?:()=>void,private onProgress?:(loaded:number,total:number)=>void){this.view=view;this.offset=offset;this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.92;this.renderer.domElement.setAttribute('aria-label','3D Board Quest world — shared cinematic dice and landings');host.appendChild(this.renderer.domElement);this.scene.background=new THREE.Color(0x78bce6);this.scene.fog=new THREE.Fog(0xa9d8f2,115,220);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.minDistance=8;this.controls.maxDistance=52;this.controls.maxPolarAngle=Math.PI*.48;this.controls.target.copy(this.homeTarget);
 this.scene.add(new THREE.HemisphereLight(0xeef8ff,0x39495c,2.65));const sun=new THREE.DirectionalLight(0xffe7b0,4.25);sun.position.set(-30,42,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-52,right:52,top:52,bottom:-52});this.scene.add(sun);const rim=new THREE.DirectionalLight(0x8ad5ff,1.35);rim.position.set(28,20,-24);this.scene.add(rim);
 const marble=new THREE.MeshStandardMaterial({color:0xe9e2d2,roughness:.38,metalness:.07}),marbleBright=new THREE.MeshStandardMaterial({color:0xfffbef,roughness:.3,metalness:.06}),gold=new THREE.MeshStandardMaterial({color:0xd2a536,roughness:.25,metalness:.68}),darkRock=new THREE.MeshStandardMaterial({color:0x4b5360,roughness:.92}),rock2=new THREE.MeshStandardMaterial({color:0x66717d,roughness:.88}),blue=new THREE.MeshStandardMaterial({color:0x315899,roughness:.34,metalness:.28}),cloudMat=new THREE.MeshBasicMaterial({color:0xf8fdff,transparent:true,opacity:.84,depthWrite:false}),waterfallMat=new THREE.MeshBasicMaterial({color:0xbbeeff,transparent:true,opacity:.72,side:THREE.DoubleSide,depthWrite:false});
 const addCloud=(x:number,y:number,z:number,s=1)=>{const g=new THREE.Group();for(let j=0;j<6;j++){const puff=new THREE.Mesh(new THREE.SphereGeometry(1.7+(j%3)*.28,14,10),cloudMat);puff.position.set((j-2.5)*1.35,(j%2)*.35,(j%3-1)*.55);g.add(puff);}g.position.set(x,y,z);g.scale.setScalar(s);this.scene.add(g);};
 for(let i=0;i<30;i++){const ang=i/30*Math.PI*2,r=25+(i%6)*7;addCloud(Math.cos(ang)*r,-5-(i%3)*1.1,Math.sin(ang)*r+4,.72+(i%4)*.14);}
 const addIsland=(space:number,radius:number,temple=false)=>{const p=at(space),lower=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius*.28,7.6,14),darkRock);lower.position.set(p.x,p.y-4.05,p.z);lower.rotation.y=space*.19;lower.castShadow=true;lower.receiveShadow=true;this.scene.add(lower);const shelf=new THREE.Mesh(new THREE.CylinderGeometry(radius+.2,radius*.93,1.25,18),rock2);shelf.position.set(p.x,p.y-.95,p.z);shelf.castShadow=true;shelf.receiveShadow=true;this.scene.add(shelf);const plaza=new THREE.Mesh(new THREE.CylinderGeometry(radius*.82,radius*.86,.48,28),marble);plaza.position.set(p.x,p.y-.12,p.z);plaza.castShadow=true;plaza.receiveShadow=true;this.scene.add(plaza);const trim=new THREE.Mesh(new THREE.TorusGeometry(radius*.72,.13,9,48),gold);trim.rotation.x=Math.PI/2;trim.position.set(p.x,p.y+.15,p.z);this.scene.add(trim);if(temple){for(let j=0;j<6;j++){const ang=j/6*Math.PI*2,col=new THREE.Mesh(new THREE.CylinderGeometry(.22,.3,3.5,12),marbleBright);col.position.set(p.x+Math.cos(ang)*(radius*.62),p.y+1.65,p.z+Math.sin(ang)*(radius*.62));col.castShadow=true;this.scene.add(col);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.16,12),gold);cap.position.set(col.position.x,p.y+3.45,col.position.z);this.scene.add(cap);}}return p;};
 const islandSpecs:[[number,number,boolean],[number,number,boolean],[number,number,boolean],[number,number,boolean],[number,number,boolean],[number,number,boolean]]=[[1,7.2,true],[7,6.6,false],[13,7.1,true],[19,6.7,false],[24,6.8,true],[27,8.7,true]];for(const spec of islandSpecs)addIsland(...spec);
 const farIslands=[[-31,8,18,4.2],[-27,13,-9,3.6],[27,10,-7,4.1],[32,14,18,3.5],[-18,18,34,3.4]];for(const [x,y,z,r] of farIslands){const island=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.18,6.2,12),darkRock);island.position.set(x,y-4,z);island.rotation.y=x*.1;this.scene.add(island);const cap=new THREE.Mesh(new THREE.CylinderGeometry(r*.78,r*.84,.42,20),marble);cap.position.set(x,y-.75,z);this.scene.add(cap);}
 for(let i=0;i<27;i++){const p1=at(i),p2=at(i+1),dir=p2.clone().sub(p1),len=dir.length(),mid=p1.clone().add(p2).multiplyScalar(.5),bridge=new THREE.Mesh(new THREE.BoxGeometry(2.35,.32,len),marbleBright);bridge.position.copy(mid).add(new THREE.Vector3(0,-.48,0));bridge.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),dir.clone().normalize());bridge.castShadow=true;bridge.receiveShadow=true;this.scene.add(bridge);const side=new THREE.Vector3(-dir.z,0,dir.x).normalize().multiplyScalar(1.12);for(const s of [-1,1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.12,.16,len),gold);rail.position.copy(mid).add(side.clone().multiplyScalar(s)).add(new THREE.Vector3(0,.12,0));rail.quaternion.copy(bridge.quaternion);this.scene.add(rail);}if(i%4===1){const jewel=new THREE.Mesh(new THREE.OctahedronGeometry(.28),new THREE.MeshStandardMaterial({color:0x75c7ff,emissive:0x3ba5e8,emissiveIntensity:.75,metalness:.25,roughness:.2}));jewel.position.copy(mid).add(new THREE.Vector3(0,.22,0));this.scene.add(jewel);}}
 const tileWords:Record<string,string>={points:'+50',safe:'SAFE',steal:'STEAL',shield:'SHIELD',power:'+2',rps:'RPS',bonus:'100'};
 for(let i=0;i<28;i++){const p=at(i),event=EVENTS[i%7],color=COLORS[i%7],major=event==='rps'||event==='bonus',sides=event==='points'?6:event==='steal'||event==='shield'||event==='power'?8:32,rad=event==='rps'?(i===12?4.25:3.35):event==='bonus'?3.35:2.22,base=new THREE.Mesh(new THREE.CylinderGeometry(rad+.24,rad+.31,.68,sides),event==='rps'?blue:marble),tile=new THREE.Mesh(new THREE.CylinderGeometry(rad,rad,.32,sides),new THREE.MeshStandardMaterial({color,roughness:.23,metalness:.2,emissive:color,emissiveIntensity:.08}));base.position.set(p.x,p.y-.49,p.z);tile.position.set(p.x,p.y-.03,p.z);base.castShadow=true;base.receiveShadow=true;tile.castShadow=true;tile.receiveShadow=true;this.scene.add(base,tile);this.tiles.push(tile);const ring=new THREE.Mesh(new THREE.TorusGeometry(rad-.14,.11,8,44),gold);ring.rotation.x=Math.PI/2;ring.position.set(p.x,p.y+.15,p.z);this.scene.add(ring);const mark=tileMark(tileWords[event],event==='bonus'?'#fff2a8':'#ffffff');mark.scale.setScalar(major?1.2:.9);mark.position.set(p.x,p.y+.17,p.z);this.scene.add(mark);if(event==='rps'){const outer=new THREE.Mesh(new THREE.TorusGeometry(rad+.32,.14,10,54),new THREE.MeshStandardMaterial({color:0x7dc7ff,emissive:0x3274c8,emissiveIntensity:.8,metalness:.45,roughness:.22}));outer.rotation.x=Math.PI/2;outer.position.set(p.x,p.y+.05,p.z);this.scene.add(outer);}}
 const addGateway=(space:number,scale=1)=>{const p=at(space),w=3.1*scale;for(const s of [-1,1]){const col=new THREE.Mesh(new THREE.CylinderGeometry(.26*scale,.34*scale,4.2*scale,14),marbleBright);col.position.set(p.x+s*w,p.y+1.85*scale,p.z);col.castShadow=true;this.scene.add(col);const crown=new THREE.Mesh(new THREE.BoxGeometry(.75*scale,.22*scale,.75*scale),gold);crown.position.set(col.position.x,p.y+4*scale,p.z);this.scene.add(crown);}const beam=new THREE.Mesh(new THREE.BoxGeometry(w*2+.8*scale,.36*scale,.55*scale),gold);beam.position.set(p.x,p.y+4*scale,p.z);this.scene.add(beam);};
 for(const idx of [1,13,24])addGateway(idx,.82);
 const bannerMat=new THREE.MeshStandardMaterial({color:0x234c9a,roughness:.42});for(const idx of [1,7,13,19,24,27]){const p=at(idx);for(const s of [-1,1]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.07,.09,3.4,10),gold);pole.position.set(p.x+s*3.4,p.y+1.45,p.z);const banner=new THREE.Mesh(new THREE.PlaneGeometry(1.05,1.65),bannerMat);banner.position.set(p.x+s*3.4,p.y+2.05,p.z+.05);this.scene.add(pole,banner);}}
 for(const idx of [7,13,19,24,27]){const p=at(idx);for(const s of [-1,1]){const fall=new THREE.Mesh(new THREE.PlaneGeometry(1.45,9),waterfallMat);fall.position.set(p.x+s*4.75,p.y-4.5,p.z);fall.rotation.y=Math.PI/2;this.scene.add(fall);}}
 const startP=at(0),startBase=new THREE.Mesh(new THREE.CylinderGeometry(4.1,4.45,.86,36),blue);startBase.position.set(startP.x,startP.y-.56,startP.z);startBase.castShadow=true;this.scene.add(startBase);const startTrim=new THREE.Mesh(new THREE.TorusGeometry(3.55,.18,10,48),gold);startTrim.rotation.x=Math.PI/2;startTrim.position.set(startP.x,startP.y+.02,startP.z);this.scene.add(startTrim);const startLabel=label('START','#173f72');startLabel.scale.set(4.8,.95,1);startLabel.position.copy(startP).add(new THREE.Vector3(0,2.3,-1));this.scene.add(startLabel);
 const goal=at(27),goalBase=new THREE.Mesh(new THREE.CylinderGeometry(6.2,6.55,1.05,42),marbleBright);goalBase.position.set(goal.x,goal.y-.62,goal.z);goalBase.castShadow=true;goalBase.receiveShadow=true;this.scene.add(goalBase);for(let k=0;k<8;k++){const ang=k/8*Math.PI*2,col=new THREE.Mesh(new THREE.CylinderGeometry(.3,.38,5.1,16),marbleBright);col.position.set(goal.x+Math.cos(ang)*4.8,goal.y+2.2,goal.z+Math.sin(ang)*4.8);col.castShadow=true;this.scene.add(col);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.48,.48,.2,16),gold);cap.position.set(col.position.x,goal.y+4.78,col.position.z);this.scene.add(cap);}const templeBeam1=new THREE.Mesh(new THREE.BoxGeometry(10.2,.42,.7),gold);templeBeam1.position.set(goal.x,goal.y+4.8,goal.z);this.scene.add(templeBeam1);const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(1.35),new THREE.MeshStandardMaterial({color:0xe9f7ff,emissive:0x6ec8ff,emissiveIntensity:1.35,metalness:.2,roughness:.08}));crystal.position.copy(goal).add(new THREE.Vector3(0,6.35,0));crystal.scale.y=1.55;this.scene.add(crystal);const finish=label('GOAL','#8b6b12');finish.scale.set(5.8,1.2,1);finish.position.copy(goal).add(new THREE.Vector3(0,3.25,-1.3));this.scene.add(finish);
 this.die=new THREE.Mesh(new THREE.BoxGeometry(2.6,2.6,2.6),DIE_VALUES.map(diceMaterial));this.die.castShadow=true;this.die.visible=false;this.scene.add(this.die);
 this.ring=new THREE.Mesh(new THREE.RingGeometry(1.5,1.7,64),new THREE.MeshBasicMaterial({color:0xffdf6b,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));this.ring.rotation.x=-Math.PI/2;this.scene.add(this.ring,this.hands);
 this.aura=new THREE.Mesh(new THREE.SphereGeometry(2.4,24,16),new THREE.MeshBasicMaterial({color:0x38bdf8,transparent:true,opacity:.2,wireframe:true,depthWrite:false}));this.aura.visible=false;this.scene.add(this.aura);
 const coinGeo=new THREE.CylinderGeometry(.3,.3,.09,16);for(let i=0;i<20;i++){const coin=new THREE.Mesh(coinGeo,new THREE.MeshStandardMaterial({color:0xffd348,emissive:0xf59e0b,emissiveIntensity:.5,metalness:.8,roughness:.2,transparent:true}));coin.visible=false;this.coins.push(coin);this.scene.add(coin);}

 const geo=new THREE.OctahedronGeometry(.16);for(let i=0;i<64;i++){const particle=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:[0xffdc53,0x34d399,0x67e8f9,0xf472b6][i%4],transparent:true}));particle.visible=false;this.particles.push(particle);this.scene.add(particle);}
 const loader=new GLTFLoader();let loaded=0,total=Math.max(1,view.players.length);const done=()=>{loaded++;this.onProgress?.(Math.min(loaded,total),total);if(loaded>=total)requestAnimationFrame(()=>this.onReady?.());};if(view.players.length===0)requestAnimationFrame(()=>this.onReady?.());view.players.forEach((p,i)=>{const root=new THREE.Group();root.position.copy(this.restPosition(p.space,i));root.visible=false;const badge=label(p.name,p.team==='blue'?'#0369a1':'#a16207');badge.position.y=3.65;badge.scale.set(2.8,.7,1);root.add(badge);this.roots.set(p.id,root);this.scene.add(root);loader.load(getAvatarCharacter(p.characterId).modelPath,g=>{if(this.disposed){this.disposeObject(g.scene);return;}const model=g.scene,b=new THREE.Box3().setFromObject(model),size=b.getSize(new THREE.Vector3());model.scale.setScalar(2.85/Math.max(.01,size.y));model.updateMatrixWorld();model.position.y=-new THREE.Box3().setFromObject(model).min.y;model.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});root.add(model);root.visible=true;if(g.animations.length){const m=new THREE.AnimationMixer(model);this.mixers.push(m);root.userData.mixer=m;root.userData.clips=g.animations;this.action(root,'idle');}done();},undefined,()=>{if(this.disposed)return;root.add(fallbackCharacter(p.team==='blue'?0x38bdf8:0xfbbf24));root.visible=true;done();});});
 this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.camera.position.copy(this.home);this.animate(performance.now());
 }
 update(view:View,offset:number){this.view=view;this.offset=offset;}
 private restPosition(space:number,index:number){return at(space).add(new THREE.Vector3((index%3-1)*.8,0,(Math.floor(index/3)-.5)*1));}
 private action(root:THREE.Group,name:string){if(root.userData.mode===name||!root.userData.mixer)return;const clips=root.userData.clips as THREE.AnimationClip[];const clip=clips.find(c=>new RegExp(name,'i').test(c.name))||clips.find(c=>/idle/i.test(c.name))||clips[0];root.userData.action?.fadeOut(.15);root.userData.action=root.userData.mixer.clipAction(clip).reset().fadeIn(.15).play();root.userData.mode=name;}
 private resize(){const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.camera.aspect=w/h;this.camera.fov=w<h?60:45;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);this.home.set(w<h?1:0,w<h?35:27,w<h?39:34);}
 private setHands(a:Hand,b:Hand,key:string){if(this.handKey===key)return;this.handKey=key;for(const c of [...this.hands.children]){this.hands.remove(c);this.disposeObject(c);}const actor=this.view.players.find(p=>p.id===this.view.cue?.actor),left=handMesh(a,actor?.team==='blue'?0x38bdf8:0xfbbf24),right=handMesh(b,actor?.team==='blue'?0xfbbf24:0x38bdf8);left.position.x=-2;right.position.x=2;this.hands.add(left,right);}
 private animate=(stamp:number)=>{if(this.disposed)return;const dt=Math.min(.05,(stamp-this.lastTime)/1000||.016);this.lastTime=stamp;const now=Date.now()+this.offset,v=this.view,c=v.cue,stage=cueStage(c,now);const cinematic=!!c;const focus=new THREE.Vector3(0,0,0),eye=this.home.clone();this.controls.enabled=!cinematic;this.die.visible=!!c&&c.kind==='move'&&(stage==='roll'||stage==='reveal');this.hands.visible=!!c&&(v.phase==='rps'||c.kind==='duel');
 this.tiles.forEach((tile,i)=>{tile.material.emissiveIntensity=c&&i===c.to&&['landing','reward','countdown','duel-result'].includes(stage)?.62+Math.sin(stamp*.008)*.16:.08;});
 v.players.forEach((p,i)=>{const root=this.roots.get(p.id);if(!root)return;root.visible=!p.out||(c?.actor===p.id||c?.rival===p.id);let target=this.restPosition(p.space,i),mode='idle';if(c&&c.actor===p.id&&c.kind==='move'){
 if(stage==='roll'||stage==='reveal')target=this.restPosition(c.from,i);
 else if(stage==='move'){const elapsed=Math.max(0,now-c.startAt-TIMING.roll-TIMING.reveal),step=Math.min(c.to-c.from-1,Math.floor(elapsed/TIMING.step)),t=elapsed%TIMING.step/TIMING.step;target=this.restPosition(c.from+step,i).lerp(this.restPosition(c.from+step+1,i),ease(t));target.y+=Math.sin(t*Math.PI)*(this.reduced?.15:step===c.to-c.from-1?3:1);mode='walk|run';}
 else target=this.restPosition(c.to,i);
 }if(c&&(v.phase==='rps'||c.kind==='duel')&&(c.actor===p.id||c.rival===p.id)){target=at(c.to).add(new THREE.Vector3(c.actor===p.id?-2:2,0,0));root.rotation.y=c.actor===p.id?Math.PI/2:-Math.PI/2;if(stage==='duel-result'&&c.duelWinner===p.id){mode='jump|dance|wave';target.y+=this.reduced?0:Math.abs(Math.sin((now-c.startAt)*.006))*.65;}}
 else if(c?.actor===p.id&&stage==='move'){const ahead=at(Math.min(c.to,c.from+Math.floor((now-c.startAt-TIMING.roll-TIMING.reveal)/TIMING.step)+1));root.rotation.y=Math.atan2(ahead.x-root.position.x,ahead.z-root.position.z);}
 root.position.copy(target);this.action(root,mode);
 });this.mixers.forEach(m=>m.update(dt));
 if(c){const tile=at(c.to),actor=this.roots.get(c.actor);focus.copy(tile).add(new THREE.Vector3(0,1,0));eye.copy(focus).add(new THREE.Vector3(8,10,13));const portrait=this.camera.aspect<1;
 if(stage==='roll'||stage==='reveal'){const origin=at(c.from);const t=Math.max(0,now-c.startAt)/TIMING.roll;this.die.position.copy(origin).add(new THREE.Vector3(0,5,1));if(t<1){const bounce=this.reduced?0:Math.abs(Math.sin(t*Math.PI*3))*3*(1-t);this.die.position.y+=bounce;this.die.rotation.set(t*Math.PI*8,t*Math.PI*6,t*Math.PI*4);if(t>.7)this.die.quaternion.slerp(dieOrientation(c.raw),ease((t-.7)/.3));}else this.die.quaternion.copy(dieOrientation(c.raw));focus.copy(origin).add(new THREE.Vector3(0,5,1));eye.copy(focus).add(new THREE.Vector3(0,4,portrait?15:11));}
 else if(stage==='move'&&actor){focus.copy(actor.position).add(new THREE.Vector3(0,1,0));eye.copy(focus).add(new THREE.Vector3(8,10,portrait?17:13));}
 else if(this.hands.visible){focus.copy(tile).add(new THREE.Vector3(0,3,0));eye.copy(focus).add(new THREE.Vector3(0,4,portrait?20:15));this.hands.position.copy(tile).add(new THREE.Vector3(0,4,0));const show=c.kind==='duel'&&stage==='duel-result'&&c.hands;this.setHands(show?c.hands![0]:'rock',show?c.hands![1]:'rock',`${c.id}-${show?'reveal':'ready'}`);this.hands.children.forEach((h,i)=>{h.rotation.z=(i===0?-1:1)*(show?.08:Math.sin(stamp*.009)*.2);h.position.y=show?0:Math.abs(Math.sin(stamp*.009))*.5;});}
 else if(portrait)eye.copy(focus).add(new THREE.Vector3(9,12,19));
 const landing=moveLandingAt(c),impact=c.kind==='move'?(now-landing)/1000:-1;const ringMat=this.ring.material as THREE.MeshBasicMaterial;this.ring.position.copy(tile).setY(tile.y+.2);this.ring.visible=impact>=0&&impact<2;this.ring.scale.setScalar(1+Math.max(0,impact)*3);ringMat.opacity=Math.max(0,1-impact/2);
 const rewardTime=c.kind==='duel'?c.startAt+TIMING.countdown:c.kind==='strike'?c.startAt:landing+TIMING.landing;const age=(now-rewardTime)/1000;const showReward=age>=0&&age<3&&v.phase!=='rps';const positive=c.deltas&&(c.deltas.blue>0||c.deltas.gold>0);const amount=c.deltas?Math.max(c.deltas.blue,c.deltas.gold):0;const text=positive?`+${amount} ${v.players.find(p=>p.id===c.actor)?.team.toUpperCase()} POINTS`:c.kind==='duel'||c.kind==='strike'?c.title||'RESULT':'';const key=`${c.id}-${text}`;
 if(key!==this.labelKey){this.labelKey=key;if(this.rewardLabel){this.scene.remove(this.rewardLabel);this.disposeObject(this.rewardLabel);}this.rewardLabel=label(text,positive?'#166534':'#6d28d9');this.rewardLabel.scale.set(7,1.75,1);this.scene.add(this.rewardLabel);}if(this.rewardLabel){this.rewardLabel.visible=showReward&&!!text;this.rewardLabel.position.copy(tile).add(new THREE.Vector3(0,5+Math.max(0,age)*.8,0));(this.rewardLabel.material as THREE.SpriteMaterial).opacity=Math.min(1,Math.max(0,3-age));}
 this.aura.visible=showReward&&(c.event==='shield'||c.event==='power'||!!c.blocked);this.aura.position.copy(tile).add(new THREE.Vector3(0,1.5,0));this.aura.rotation.y=stamp*.001;this.aura.scale.setScalar(1+Math.sin(stamp*.007)*.07);(this.aura.material as THREE.MeshBasicMaterial).color.set(c.event==='power'?0xc084fc:0x38bdf8);
 this.coins.forEach((coin,i)=>{const t=Math.max(0,age-i*.04);coin.visible=showReward&&!!positive&&t>0&&!this.reduced;coin.position.copy(tile).add(new THREE.Vector3(Math.cos(i*2.4)*(1+t)*1.4,2+t*5,Math.sin(i*2.4)*(1+t)*1.4));coin.rotation.set(Math.PI/2,t*5+i,t*2);(coin.material as THREE.MeshStandardMaterial).opacity=Math.max(0,1-t/2.7);});
 this.particles.forEach((p,i)=>{p.visible=showReward&&!this.reduced&&c.kind!=='strike';if(!p.visible)return;const a=i*2.39996,speed=2+(i%7)*.6;p.position.copy(tile).add(new THREE.Vector3(Math.cos(a)*age*speed,3+age*(4+i%3)-age*age*2,Math.sin(a)*age*speed));p.rotation.set(age*4,i+age*3,age*5);(p.material as THREE.MeshBasicMaterial).opacity=Math.max(0,1-age/3);});
 }else{this.ring.visible=false;this.aura.visible=false;this.coins.forEach(p=>p.visible=false);this.particles.forEach(p=>p.visible=false);if(this.rewardLabel)this.rewardLabel.visible=false;}
 if(cinematic){const speed=this.reduced?1:1-Math.exp(-dt*4);this.camera.position.lerp(eye,speed);this.controls.target.lerp(focus,speed);this.lastCue=c!.id;}
 else if(this.lastCue!==-1){this.camera.position.lerp(this.home,1-Math.exp(-dt*3));this.controls.target.lerp(this.homeTarget,1-Math.exp(-dt*3));if(this.camera.position.distanceTo(this.home)<.2)this.lastCue=-1;}
 this.controls.update();this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(this.animate);
 }
 private disposeObject(obj:THREE.Object3D){obj.traverse(o=>{const mesh=o as THREE.Mesh;mesh.geometry?.dispose();const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const m of materials){if(!m)continue;Object.values(m).forEach(v=>{if(v instanceof THREE.Texture)v.dispose()});m.dispose();}});}
 dispose(){this.disposed=true;cancelAnimationFrame(this.raf);this.resizeObserver.disconnect();this.controls.dispose();this.mixers.forEach(m=>m.stopAllAction());this.disposeObject(this.scene);this.renderer.dispose();this.host.replaceChildren();}
}
