import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {getAvatarCharacter} from '@/lib/avatarCharacters';
import {BOARD_LAST_SPACE,boardPosition,cueStage,moveLandingAt,SPACE_LABELS,EVENTS,TIMING,type View,type Hand} from '@shared/boardQuest';
const COLORS=[0xf3c84b,0x58b86b,0x8b5cf6,0x38bdf8,0xef5b4d,0x3157d5,0xf6b90b];
const ease=(t:number)=>{t=THREE.MathUtils.clamp(t,0,1);return t*t*(3-2*t)};
const at=(space:number)=>{const p=boardPosition(space),i=Math.max(0,Math.min(BOARD_LAST_SPACE,space)),rise=i/BOARD_LAST_SPACE;return new THREE.Vector3(p.x,3.2+rise*10.8+Math.sin(i*.46)*1.25,p.z)};
export const DIE_VALUES=[1,6,2,5,3,4];
export const DIE_NORMALS=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
export function dieOrientation(value:number){return new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(...DIE_NORMALS[DIE_VALUES.indexOf(value)]),new THREE.Vector3(0,.4,1).normalize());}
function label(text:string,color='#12213d',width=512,height=128){const c=document.createElement('canvas');c.width=width;c.height=height;const x=c.getContext('2d')!;x.fillStyle=color;x.beginPath();x.roundRect(8,8,width-16,height-16,24);x.fill();x.fillStyle='white';x.font='900 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,width/2,height/2,width-24);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map,transparent:true,depthTest:false}));sprite.scale.set(4,1,1);return sprite;}
function tileMark(text:string,color='#ffffff'){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d')!;x.clearRect(0,0,512,256);x.fillStyle='rgba(8,25,58,.22)';x.beginPath();x.roundRect(24,38,464,180,42);x.fill();x.strokeStyle='rgba(255,226,137,.75)';x.lineWidth=8;x.stroke();x.fillStyle=color;x.font='900 66px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,128,420);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(3.1,1.55),new THREE.MeshBasicMaterial({map,transparent:true,depthWrite:false,side:THREE.DoubleSide}));mesh.rotation.x=-Math.PI/2;return mesh;}
function softCloudTexture(){const c=document.createElement('canvas');c.width=768;c.height=384;const x=c.getContext('2d')!;x.clearRect(0,0,c.width,c.height);const blobs=[[140,205,120],[255,170,150],[390,205,165],[525,160,135],[635,215,105],[330,125,110]];for(const [cx,cy,r] of blobs){const g=x.createRadialGradient(cx,cy,r*.08,cx,cy,r);g.addColorStop(0,'rgba(255,255,255,.98)');g.addColorStop(.42,'rgba(250,253,255,.88)');g.addColorStop(.78,'rgba(239,249,255,.48)');g.addColorStop(1,'rgba(235,248,255,0)');x.fillStyle=g;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.fill();}const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;return map;}
function softGlowTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d')!;const g=x.createRadialGradient(128,128,4,128,128,122);g.addColorStop(0,'rgba(255,244,178,.95)');g.addColorStop(.25,'rgba(255,220,105,.45)');g.addColorStop(1,'rgba(255,210,80,0)');x.fillStyle=g;x.fillRect(0,0,256,256);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;return map;}
function fallbackCharacter(color:number){const g=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color,roughness:.62}),skin=new THREE.MeshStandardMaterial({color:0xf1b98b,roughness:.75}),dark=new THREE.MeshStandardMaterial({color:0x172033,roughness:.72});const head=new THREE.Mesh(new THREE.SphereGeometry(.38,18,14),skin);head.position.y=2.55;const body=new THREE.Mesh(new THREE.BoxGeometry(.85,1.1,.5),cloth);body.position.y=1.65;const hips=new THREE.Mesh(new THREE.BoxGeometry(.68,.38,.42),dark);hips.position.y=.95;g.add(head,body,hips);for(const side of [-1,1]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.65,3,8),cloth);arm.position.set(side*.58,1.7,0);arm.rotation.z=side*.2;const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.15,.72,3,8),dark);leg.position.set(side*.22,.35,0);g.add(arm,leg);}g.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});return g;}
function diceMaterial(value:number){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d')!;x.fillStyle='#f8fafc';x.fillRect(0,0,256,256);x.strokeStyle='#bfdbfe';x.lineWidth=12;x.strokeRect(6,6,244,244);x.fillStyle='#10203d';const sets:Record<number,number[][]>={1:[[0,0]],2:[[-1,-1],[1,1]],3:[[-1,-1],[0,0],[1,1]],4:[[-1,-1],[-1,1],[1,-1],[1,1]],5:[[-1,-1],[-1,1],[1,-1],[1,1],[0,0]],6:[[-1,-1],[-1,0],[-1,1],[1,-1],[1,0],[1,1]]};for(const [a,b]of sets[value]){x.beginPath();x.arc(128+a*66,128+b*66,20,0,Math.PI*2);x.fill();}const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({map,roughness:.27,metalness:.15});}
function handMesh(hand:Hand,color:number){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,roughness:.4,metalness:.12});const palm=new THREE.Mesh(new THREE.BoxGeometry(1.45,1.5,.7),mat);palm.position.y=.15;g.add(palm);const sphere=new THREE.SphereGeometry(.25,12,10);const finger=(x:number,length:number,angle=0)=>{const f=new THREE.Mesh(new THREE.CapsuleGeometry(.23,length,4,10),mat);f.position.set(x,1+length/2,0);f.rotation.z=angle;g.add(f);};if(hand==='rock'){for(let i=0;i<4;i++){const m=new THREE.Mesh(sphere,mat);m.position.set((i-1.5)*.37,.98,.1);g.add(m);}}else{for(let i=0;i<4;i++)finger((i-1.5)*.36,hand==='paper'?1.1+(i===1||i===2?.15:0):i<2?1.65:.05,hand==='scissors'&&i<2?(i===0?.17:-.17):0);}const thumb=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.6,4,10),mat);thumb.rotation.z=-.7;thumb.position.set(.85,.05,.2);g.add(thumb);g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});return g;}
export class BoardScene{
 private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(50,1,.1,260);private renderer:THREE.WebGLRenderer;private controls:OrbitControls;private roots=new Map<number,THREE.Group>();private tiles:THREE.Mesh<THREE.BufferGeometry,THREE.MeshStandardMaterial>[]=[];private ledRings:THREE.Mesh[]=[];private birds:THREE.Group[]=[];private lightningBolts:THREE.Line[]=[];private lightningLights:THREE.PointLight[]=[];private mixers:THREE.AnimationMixer[]=[];private die:THREE.Mesh;private ring:THREE.Mesh;private particles:THREE.Mesh[]=[];private coins:THREE.Mesh[]=[];private aura:THREE.Mesh;private hands=new THREE.Group();private rewardLabel:THREE.Sprite|null=null;private labelKey='';private handKey='';private raf=0;private disposed=false;private lastTime=0;private lastCue=-1;private view:View;private offset=0;private reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;private resizeObserver:ResizeObserver;private home=new THREE.Vector3();private homeTarget=new THREE.Vector3(0,7,1);
 constructor(private host:HTMLDivElement,view:View,offset:number,private onReady?:()=>void,private onProgress?:(loaded:number,total:number)=>void){this.view=view;this.offset=offset;this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.78;this.renderer.domElement.setAttribute('aria-label','3D Board Quest world — shared cinematic dice and landings');host.appendChild(this.renderer.domElement);this.scene.background=new THREE.Color(0x315f87);this.scene.fog=new THREE.Fog(0x6c91ab,118,245);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.minDistance=8;this.controls.maxDistance=72;this.controls.maxPolarAngle=Math.PI*.48;this.controls.target.copy(this.homeTarget);
 this.scene.add(new THREE.HemisphereLight(0xdcefff,0x26394d,2.05));const sun=new THREE.DirectionalLight(0xffe0a3,3.15);sun.position.set(-30,46,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-60,right:60,top:60,bottom:-60});this.scene.add(sun);const rim=new THREE.DirectionalLight(0x6fc8ff,1.05);rim.position.set(32,18,-28);this.scene.add(rim);
 const marble=new THREE.MeshStandardMaterial({color:0xeee8dc,roughness:.34,metalness:.06}),marbleBright=new THREE.MeshStandardMaterial({color:0xfffbef,roughness:.27,metalness:.05}),gold=new THREE.MeshStandardMaterial({color:0xd5aa3b,roughness:.22,metalness:.72}),darkRock=new THREE.MeshStandardMaterial({color:0x4b5563,roughness:.92}),rock2=new THREE.MeshStandardMaterial({color:0x697482,roughness:.87}),blue=new THREE.MeshStandardMaterial({color:0x315b9f,roughness:.3,metalness:.3}),green=new THREE.MeshStandardMaterial({color:0x3f7d45,roughness:.72}),trunkMat=new THREE.MeshStandardMaterial({color:0x76543b,roughness:.86});
 const cloudTex=softCloudTexture(),cloudMat=new THREE.SpriteMaterial({map:cloudTex,color:0xffffff,transparent:true,opacity:.92,depthWrite:false,fog:true}),glowTex=softGlowTexture();
 const addCloudBank=(x:number,y:number,z:number,s=1)=>{for(let j=0;j<3;j++){const cloud=new THREE.Sprite(cloudMat.clone());cloud.position.set(x+(j-1)*3.1*s,y+(j%2)*.55*s,z+(j-1)*.7*s);cloud.scale.set(14*s*(1+j*.08),7*s*(1+(j%2)*.12),1);cloud.material.opacity=.72+j*.08;this.scene.add(cloud);}};
 for(let i=0;i<110;i++){const ang=i/110*Math.PI*2,r=36+(i%11)*6.5,y=-9+(i%7)*1.15,s=1.0+(i%6)*.18;addCloudBank(Math.cos(ang)*r,y,Math.sin(ang)*r+2,s);}for(let i=0;i<52;i++){const ang=i/52*Math.PI*2,r=15+(i%8)*5;addCloudBank(Math.cos(ang)*r,-1.5+(i%5)*.72,Math.sin(ang)*r,.7+(i%5)*.12);}
 const major=new Map<number,{r:number;label:string;color:number;temple?:boolean}>([[0,{r:7.6,label:'START',color:0x315b9f,temple:true}],[10,{r:6.2,label:'SHIELD',color:0x35a853}],[18,{r:6.4,label:'POWER',color:0xef594d,temple:true}],[26,{r:9.2,label:'RPS BATTLE',color:0x315b9f,temple:true}],[37,{r:6.4,label:'STEAL',color:0x8b5cf6}],[41,{r:6.8,label:'JACKPOT',color:0xe7b631,temple:true}],[50,{r:6.5,label:'SAFE',color:0x57b96a}],[55,{r:10.2,label:'GOAL',color:0xd9ad3d,temple:true}]]);
 const addTree=(x:number,y:number,z:number,s=1)=>{const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12*s,.17*s,1.25*s,8),trunkMat);trunk.position.set(x,y+.62*s,z);const crown=new THREE.Mesh(new THREE.DodecahedronGeometry(.62*s,0),green);crown.position.set(x,y+1.48*s,z);crown.scale.set(1,1.35,1);trunk.castShadow=true;crown.castShadow=true;this.scene.add(trunk,crown);};
 const addIsland=(space:number,radius:number,temple=false)=>{const p=at(space),lower=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius*.24,8.4,16),darkRock);lower.position.set(p.x,p.y-4.45,p.z);lower.rotation.y=space*.21;lower.castShadow=true;lower.receiveShadow=true;this.scene.add(lower);const ledge=new THREE.Mesh(new THREE.CylinderGeometry(radius+.2,radius*.88,1.25,20),rock2);ledge.position.set(p.x,p.y-.98,p.z);ledge.castShadow=true;ledge.receiveShadow=true;this.scene.add(ledge);const lawn=new THREE.Mesh(new THREE.CylinderGeometry(radius*.88,radius*.91,.34,28),new THREE.MeshStandardMaterial({color:0x8da56f,roughness:.78}));lawn.position.set(p.x,p.y-.42,p.z);lawn.receiveShadow=true;this.scene.add(lawn);const plaza=new THREE.Mesh(new THREE.CylinderGeometry(radius*.77,radius*.8,.48,32),marble);plaza.position.set(p.x,p.y-.12,p.z);plaza.castShadow=true;plaza.receiveShadow=true;this.scene.add(plaza);const trim=new THREE.Mesh(new THREE.TorusGeometry(radius*.69,.13,10,54),gold);trim.rotation.x=Math.PI/2;trim.position.set(p.x,p.y+.15,p.z);this.scene.add(trim);for(let j=0;j<4;j++){const ang=j/4*Math.PI*2+.35,rr=radius*.79;addTree(p.x+Math.cos(ang)*rr,p.y-.15,p.z+Math.sin(ang)*rr,.78+(j%2)*.18);}if(temple&&space!==BOARD_LAST_SPACE){for(const s of [-1,1]){const col=new THREE.Mesh(new THREE.CylinderGeometry(.2,.27,3.2,12),marbleBright);col.position.set(p.x+s*radius*.52,p.y+1.35,p.z-radius*.42);col.castShadow=true;this.scene.add(col);const cap=new THREE.Mesh(new THREE.BoxGeometry(.65,.2,.65),gold);cap.position.set(col.position.x,p.y+2.98,col.position.z);this.scene.add(cap);}const beam=new THREE.Mesh(new THREE.BoxGeometry(radius*1.3,.3,.48),gold);beam.position.set(p.x,p.y+3,p.z-radius*.42);this.scene.add(beam);}return p;};
 for(const [idx,spec] of major)addIsland(idx,spec.r,!!spec.temple);
 const farSpecs=[[-34,12,-19,4.2],[-27,17,-31,3.8],[-9,20,-36,4.4],[29,15,-32,4.1],[36,11,20,4.3],[-4,12,37,3.9]] as [number,number,number,number][];
 for(const [x,y,z,r] of farSpecs){const lower=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.18,6.8,12),darkRock);lower.position.set(x,y-4,z);this.scene.add(lower);const cap=new THREE.Mesh(new THREE.CylinderGeometry(r*.82,r*.86,.4,18),marble);cap.position.set(x,y-.55,z);this.scene.add(cap);for(const s of [-1,1]){const col=new THREE.Mesh(new THREE.CylinderGeometry(.16,.22,2.8,10),marbleBright);col.position.set(x+s*r*.38,y+.95,z);this.scene.add(col);}const beam=new THREE.Mesh(new THREE.BoxGeometry(r*.95,.24,.4),gold);beam.position.set(x,y+2.35,z);this.scene.add(beam);}
 for(let i=0;i<BOARD_LAST_SPACE;i++){const p1=at(i),p2=at(i+1),dir=p2.clone().sub(p1),len=dir.length(),mid=p1.clone().add(p2).multiplyScalar(.5),bridge=new THREE.Mesh(new THREE.BoxGeometry(2.1,.3,len),marbleBright);bridge.position.copy(mid).add(new THREE.Vector3(0,-.46,0));bridge.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),dir.clone().normalize());bridge.castShadow=true;bridge.receiveShadow=true;this.scene.add(bridge);const side=new THREE.Vector3(-dir.z,0,dir.x).normalize().multiplyScalar(.98);for(const s of [-1,1]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.1,.13,len),gold);rail.position.copy(mid).add(side.clone().multiplyScalar(s)).add(new THREE.Vector3(0,.04,0));rail.quaternion.copy(bridge.quaternion);this.scene.add(rail);}}
 const tileWords:Record<string,string>={points:'+50',safe:'SAFE',steal:'STEAL',shield:'SHIELD',power:'+2',rps:'RPS',bonus:'100'};
 const ledColor=(color:number)=>new THREE.Color(color).lerp(new THREE.Color(0xffffff),.18);
 const addLedRing=(p:THREE.Vector3,rad:number,color:number,strong=false,space=-1)=>{const core=new THREE.Mesh(new THREE.TorusGeometry(rad,.07,strong?12:10,strong?80:64),new THREE.MeshBasicMaterial({color:ledColor(color),transparent:true,opacity:strong ? .92 : .82,depthWrite:false,toneMapped:false}));core.rotation.x=Math.PI/2;core.position.set(p.x,p.y+.18,p.z);core.userData={space,kind:'core'};this.scene.add(core);this.ledRings.push(core);const halo=new THREE.Mesh(new THREE.TorusGeometry(rad,.16,strong?12:10,strong?80:64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:strong ? .075 : .045,depthWrite:false,toneMapped:false,blending:THREE.AdditiveBlending}));halo.rotation.x=Math.PI/2;halo.position.copy(core.position);halo.userData={space,kind:'halo'};this.scene.add(halo);this.ledRings.push(halo);};
 for(let i=0;i<=BOARD_LAST_SPACE;i++){const p=at(i),event=EVENTS[i%7],color=COLORS[i%7],spec=major.get(i);if(spec){const rad=i===26?5.4:i===55?6.1:i===0?4.7:3.9,base=new THREE.Mesh(new THREE.CylinderGeometry(rad+.28,rad+.34,.72,48),i===26?blue:marbleBright),tile=new THREE.Mesh(new THREE.CylinderGeometry(rad,rad,.33,48),new THREE.MeshStandardMaterial({color:spec.color,roughness:.3,metalness:.16,emissive:0x000000,emissiveIntensity:0}));base.position.set(p.x,p.y-.5,p.z);tile.position.set(p.x,p.y-.02,p.z);base.castShadow=true;base.receiveShadow=true;tile.castShadow=true;tile.receiveShadow=true;this.scene.add(base,tile);this.tiles.push(tile);const trim=new THREE.Mesh(new THREE.TorusGeometry(rad+.09,.08,10,64),gold);trim.rotation.x=Math.PI/2;trim.position.set(p.x,p.y+.12,p.z);this.scene.add(trim);addLedRing(p,rad-.18,spec.color,true,i);if(i===26){for(const [dx,dz,t,col] of [[-2,0,'ROCK',0x7e8da0],[0,0,'PAPER',0xe8e2d6],[2,0,'SCISSORS',0x7e8da0]] as [number,number,string,number][]) {const pad=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.05,.16,28),new THREE.MeshStandardMaterial({color:col,roughness:.32}));pad.position.set(p.x+dx,p.y+.22,p.z+dz);this.scene.add(pad);const mark=tileMark(t);mark.scale.set(.52,.52,.52);mark.position.set(p.x+dx,p.y+.32,p.z+dz);this.scene.add(mark);}}const plaque=label(spec.label,i===55?'#9a7314':i===0?'#173f72':i===26?'#173f72':'#26364f');plaque.scale.set(i===26||i===55?5.2:4.1,i===26||i===55?1.02:.82,1);plaque.position.set(p.x,p.y+2.05,p.z-rad*.72);this.scene.add(plaque);}else{const rad=1.44,base=new THREE.Mesh(new THREE.CylinderGeometry(rad+.24,rad+.24,.38,36),marbleBright),tile=new THREE.Mesh(new THREE.CylinderGeometry(rad,rad,.25,36),new THREE.MeshStandardMaterial({color,roughness:.34,metalness:.12,emissive:0x000000,emissiveIntensity:0}));base.position.set(p.x,p.y-.4,p.z);tile.position.set(p.x,p.y-.08,p.z);base.castShadow=true;base.receiveShadow=true;tile.castShadow=true;tile.receiveShadow=true;this.scene.add(base,tile);this.tiles.push(tile);const goldTrim=new THREE.Mesh(new THREE.TorusGeometry(rad+.08,.065,8,48),gold);goldTrim.rotation.x=Math.PI/2;goldTrim.position.set(p.x,p.y+.06,p.z);this.scene.add(goldTrim);addLedRing(p,rad-.14,color,false,i);const mark=tileMark(tileWords[event]);mark.scale.set(.48,.48,.48);mark.position.set(p.x,p.y+.2,p.z);this.scene.add(mark);}}
 const waterfallMat=new THREE.MeshBasicMaterial({color:0xbdefff,transparent:true,opacity:.68,side:THREE.DoubleSide,depthWrite:false});for(const [idx,ang] of [[10,.2],[18,2.5],[26,.4],[37,2.7],[41,.2],[50,2.6],[55,.8]] as [number,number][]) {const p=at(idx),rad=major.get(idx)!.r;for(const offset of [-.65,.65]){const x=p.x+Math.cos(ang)*rad+Math.cos(ang+Math.PI/2)*offset*2,z=p.z+Math.sin(ang)*rad+Math.sin(ang+Math.PI/2)*offset*2,fall=new THREE.Mesh(new THREE.PlaneGeometry(1.6,9.5),waterfallMat);fall.position.set(x,p.y-4.6,z);fall.rotation.y=-ang+Math.PI/2;this.scene.add(fall);}addCloudBank(p.x+Math.cos(ang)*rad,p.y-9.2,p.z+Math.sin(ang)*rad,.5);}
 const addPathMist=(space:number,s=1)=>{const p=at(space);for(let j=0;j<4;j++){const mist=new THREE.Sprite(cloudMat.clone());mist.position.set(p.x+(j-1.5)*2.1*s,p.y+.75+(j%2)*.35,p.z+(j%3-1)*1.1*s);mist.scale.set(10.5*s,5.2*s,1);mist.material.opacity=.18+(j%2)*.08;mist.material.depthWrite=false;this.scene.add(mist);}};
 for(let space=1;space<BOARD_LAST_SPACE;space+=2){if(!major.has(space))addPathMist(space,.66+(space%6)*.045);}for(const space of [6,14,22,30,35,44,48,53])if(!major.has(space))addPathMist(space,.98);
 const bannerMat=new THREE.MeshStandardMaterial({color:0x234d9b,roughness:.4});for(const idx of [0,18,26,37,55]){const p=at(idx),r=major.get(idx)!.r;for(const s of [-1,1]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.07,.09,3.7,10),gold);pole.position.set(p.x+s*r*.62,p.y+1.6,p.z-r*.38);const banner=new THREE.Mesh(new THREE.PlaneGeometry(1.15,1.8),bannerMat);banner.position.set(pole.position.x,p.y+2.25,pole.position.z+.02);this.scene.add(pole,banner);}}
 const goal=at(55),goalR=major.get(55)!.r;for(let k=0;k<8;k++){const ang=k/8*Math.PI*2,col=new THREE.Mesh(new THREE.CylinderGeometry(.3,.4,5.6,16),marbleBright);col.position.set(goal.x+Math.cos(ang)*goalR*.62,goal.y+2.4,goal.z+Math.sin(ang)*goalR*.62);col.castShadow=true;this.scene.add(col);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.5,.5,.2,16),gold);cap.position.set(col.position.x,goal.y+5.25,col.position.z);this.scene.add(cap);}const beamA=new THREE.Mesh(new THREE.BoxGeometry(goalR*1.35,.45,.7),gold),beamB=beamA.clone();beamA.position.set(goal.x,goal.y+5.3,goal.z-goalR*.53);beamB.position.set(goal.x,goal.y+5.3,goal.z+goalR*.53);this.scene.add(beamA,beamB);const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(1.45),new THREE.MeshStandardMaterial({color:0xeaf8ff,emissive:0x79d4ff,emissiveIntensity:1.8,metalness:.28,roughness:.08}));crystal.position.copy(goal).add(new THREE.Vector3(0,7.0,0));crystal.scale.y=1.65;this.scene.add(crystal);const goalLight=new THREE.PointLight(0xffdc83,3.2,30);goalLight.position.copy(goal).add(new THREE.Vector3(0,6,0));this.scene.add(goalLight);const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex,color:0xffdf82,transparent:true,opacity:.72,depthWrite:false}));halo.position.copy(goal).add(new THREE.Vector3(0,6.5,0));halo.scale.set(11,11,1);this.scene.add(halo);
 const birdMat=new THREE.MeshStandardMaterial({color:0x26364b,roughness:.75,side:THREE.DoubleSide});for(let i=0;i<42;i++){const bird=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.07,.38,2,6),birdMat),left=new THREE.Mesh(new THREE.PlaneGeometry(.72,.22),birdMat),right=new THREE.Mesh(new THREE.PlaneGeometry(.72,.22),birdMat);body.rotation.z=Math.PI/2;left.position.x=-.38;right.position.x=.38;left.rotation.y=.22;right.rotation.y=-.22;bird.add(body,left,right);bird.userData={angle:i/42*Math.PI*2,radius:30+(i%9)*6,speed:.000045+(i%3)*.000012,height:17+(i%5)*2.1,phase:i*.8};this.birds.push(bird);this.scene.add(bird);}
 const boltMat=()=>new THREE.LineBasicMaterial({color:0xdff7ff,transparent:true,opacity:0,depthWrite:false,toneMapped:false,blending:THREE.AdditiveBlending});const boltDefs=[[[-50,35,-35],[-47,31,-34],[-49,27,-33],[-45,23,-31],[-47,18,-29]],[[50,38,-28],[46,33,-27],[49,29,-25],[44,24,-23],[46,19,-21]],[[10,42,46],[7,37,43],[11,32,41],[7,27,38],[10,22,35]],[[-30,40,40],[-27,35,37],[-31,31,34],[-26,27,31],[-29,22,28]],[[34,36,32],[31,31,30],[35,27,27],[30,23,24],[33,19,21]],[[-58,32,5],[-54,29,7],[-57,25,9],[-52,21,11],[-55,17,13]],[[56,34,12],[52,30,10],[55,26,8],[50,22,6],[53,18,4]]] as number[][][];for(let i=0;i<boltDefs.length;i++){const geo=new THREE.BufferGeometry().setFromPoints(boltDefs[i].map(v=>new THREE.Vector3(v[0],v[1],v[2]))),bolt=new THREE.Line(geo,boltMat()),light=new THREE.PointLight(0xc9efff,0,55);light.position.copy(new THREE.Vector3(boltDefs[i][2][0],boltDefs[i][2][1],boltDefs[i][2][2]));this.lightningBolts.push(bolt);this.lightningLights.push(light);this.scene.add(bolt,light);}
 const sparklePos:number[]=[];const majors=[0,10,18,26,37,41,50,55];for(let i=0;i<180;i++){const p=at(majors[i%majors.length]),ang=i*2.39996,rr=2.8+(i%9)*.47;sparklePos.push(p.x+Math.cos(ang)*rr,p.y+.7+(i%13)*.36,p.z+Math.sin(ang)*rr);}const sparkleGeo=new THREE.BufferGeometry();sparkleGeo.setAttribute('position',new THREE.Float32BufferAttribute(sparklePos,3));const sparkles=new THREE.Points(sparkleGeo,new THREE.PointsMaterial({color:0xffec9a,size:.12,transparent:true,opacity:.82,depthWrite:false}));this.scene.add(sparkles);
 this.die=new THREE.Mesh(new THREE.BoxGeometry(2.6,2.6,2.6),DIE_VALUES.map(diceMaterial));this.die.castShadow=true;this.die.visible=false;this.scene.add(this.die);
 this.ring=new THREE.Mesh(new THREE.RingGeometry(1.5,1.7,64),new THREE.MeshBasicMaterial({color:0xffdf6b,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));this.ring.rotation.x=-Math.PI/2;this.scene.add(this.ring,this.hands);
 this.aura=new THREE.Mesh(new THREE.SphereGeometry(2.4,24,16),new THREE.MeshBasicMaterial({color:0x38bdf8,transparent:true,opacity:.2,wireframe:true,depthWrite:false}));this.aura.visible=false;this.scene.add(this.aura);
 const coinGeo=new THREE.CylinderGeometry(.3,.3,.09,16);for(let i=0;i<20;i++){const coin=new THREE.Mesh(coinGeo,new THREE.MeshStandardMaterial({color:0xffd348,emissive:0xf59e0b,emissiveIntensity:.5,metalness:.8,roughness:.2,transparent:true}));coin.visible=false;this.coins.push(coin);this.scene.add(coin);}

 const geo=new THREE.OctahedronGeometry(.16);for(let i=0;i<64;i++){const particle=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:[0xffdc53,0x34d399,0x67e8f9,0xf472b6][i%4],transparent:true}));particle.visible=false;this.particles.push(particle);this.scene.add(particle);}
 const loader=new GLTFLoader();let loaded=0,total=Math.max(1,view.players.length);const done=()=>{loaded++;this.onProgress?.(Math.min(loaded,total),total);if(loaded>=total)requestAnimationFrame(()=>this.onReady?.());};if(view.players.length===0)requestAnimationFrame(()=>this.onReady?.());view.players.forEach((p,i)=>{const root=new THREE.Group();root.position.copy(this.restPosition(p.space,i));root.visible=false;const badge=label(p.name,p.team==='blue'?'#0369a1':'#a16207');badge.position.y=3.65;badge.scale.set(2.8,.7,1);root.add(badge);this.roots.set(p.id,root);this.scene.add(root);loader.load(getAvatarCharacter(p.characterId).modelPath,g=>{if(this.disposed){this.disposeObject(g.scene);return;}const model=g.scene,b=new THREE.Box3().setFromObject(model),size=b.getSize(new THREE.Vector3());model.scale.setScalar(2.85/Math.max(.01,size.y));model.updateMatrixWorld();model.position.y=-new THREE.Box3().setFromObject(model).min.y;model.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;}});root.add(model);root.visible=true;if(g.animations.length){const m=new THREE.AnimationMixer(model);this.mixers.push(m);root.userData.mixer=m;root.userData.clips=g.animations;this.action(root,'idle');}done();},undefined,()=>{if(this.disposed)return;root.add(fallbackCharacter(p.team==='blue'?0x38bdf8:0xfbbf24));root.visible=true;done();});});
 this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.camera.position.copy(this.home);this.animate(performance.now());
 }
 update(view:View,offset:number){this.view=view;this.offset=offset;}
 private restPosition(space:number,index:number){return at(space).add(new THREE.Vector3((index%3-1)*.8,0,(Math.floor(index/3)-.5)*1));}
 private action(root:THREE.Group,name:string){if(root.userData.mode===name||!root.userData.mixer)return;const clips=root.userData.clips as THREE.AnimationClip[];const clip=clips.find(c=>new RegExp(name,'i').test(c.name))||clips.find(c=>/idle/i.test(c.name))||clips[0];root.userData.action?.fadeOut(.15);root.userData.action=root.userData.mixer.clipAction(clip).reset().fadeIn(.15).play();root.userData.mode=name;}
 private resize(){const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.camera.aspect=w/h;this.camera.fov=w<h?61:46;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);this.home.set(w<h?0:3,w<h?58:46,w<h?78:76);}
 private setHands(a:Hand,b:Hand,key:string){if(this.handKey===key)return;this.handKey=key;for(const c of [...this.hands.children]){this.hands.remove(c);this.disposeObject(c);}const actor=this.view.players.find(p=>p.id===this.view.cue?.actor),left=handMesh(a,actor?.team==='blue'?0x38bdf8:0xfbbf24),right=handMesh(b,actor?.team==='blue'?0xfbbf24:0x38bdf8);left.position.x=-2;right.position.x=2;this.hands.add(left,right);}
 private animate=(stamp:number)=>{if(this.disposed)return;const dt=Math.min(.05,(stamp-this.lastTime)/1000||.016);this.lastTime=stamp;const now=Date.now()+this.offset,v=this.view,c=v.cue,stage=cueStage(c,now),blueTeam=v.players.filter(p=>p.team==='blue'),goldTeam=v.players.filter(p=>p.team==='gold'),introOrder=[...blueTeam,...goldTeam],introElapsed=Math.max(0,now-v.phaseAt),blueStart=TIMING.teamBanner,blueEnd=blueStart+blueTeam.length*TIMING.introPlayer,goldBannerStart=blueEnd+TIMING.introTeamGap,goldStart=goldBannerStart+TIMING.teamBanner,goldEnd=goldStart+goldTeam.length*TIMING.introPlayer;let introIndex=-1;if(v.phase==='intro'){if(introElapsed>=blueStart&&introElapsed<blueEnd)introIndex=Math.floor((introElapsed-blueStart)/TIMING.introPlayer);else if(introElapsed>=goldStart&&introElapsed<goldEnd)introIndex=blueTeam.length+Math.floor((introElapsed-goldStart)/TIMING.introPlayer);}const openingElapsed=v.phase==='opening-roll'?Math.max(0,now-v.phaseAt):0,openingRollIndex=v.phase==='opening-roll'&&openingElapsed>=TIMING.openingCountdown?Math.floor((openingElapsed-TIMING.openingCountdown)/TIMING.openingRollPlayer):-1,openingPlayer=openingRollIndex>=0&&openingRollIndex<v.players.length?v.players[openingRollIndex]:null,cinematic=!!c||v.phase==='intro'||v.phase==='opening-roll';const focus=new THREE.Vector3(0,0,0),eye=this.home.clone();this.controls.enabled=!cinematic;this.die.visible=(!!c&&c.kind==='move'&&(stage==='roll'||stage==='reveal'))||!!openingPlayer;this.hands.visible=!!c&&(v.phase==='rps'||c.kind==='duel');
 this.tiles.forEach(tile=>{tile.material.emissiveIntensity=0;});
 v.players.forEach((p,i)=>{const root=this.roots.get(p.id);if(!root)return;const orderIndex=introOrder.findIndex(x=>x.id===p.id);root.visible=v.phase==='intro'?(orderIndex>=0&&orderIndex<=introIndex):(!p.out||(c?.actor===p.id||c?.rival===p.id)||v.phase==='opening-roll');let target=this.restPosition(p.space,i),mode='idle';if(v.phase==='intro'){const landing=this.restPosition(0,i);if(orderIndex<introIndex&&orderIndex>=0){target=landing;mode='idle';}else if(orderIndex===introIndex){const base=orderIndex<blueTeam.length?blueStart+orderIndex*TIMING.introPlayer:goldStart+(orderIndex-blueTeam.length)*TIMING.introPlayer,elapsed=Math.max(0,now-v.phaseAt-base),t=THREE.MathUtils.clamp(elapsed/TIMING.introPlayer,0,1),e=1-Math.pow(1-t,3),side=p.team==='blue'?-1:1;target=new THREE.Vector3(landing.x+side*(38-38*e),landing.y+24*(1-e)+Math.sin(Math.min(1,t)*Math.PI)*7.5,landing.z-30*(1-e));if(t<.62){root.rotation.y=side<0?Math.PI/2:-Math.PI/2;mode='run|fly';}else if(t<.78){root.rotation.y+=dt*9*(side<0?-1:1);target.y+=Math.sin((t-.62)/.16*Math.PI)*2.4;mode=orderIndex%3===0?'jump|dance':orderIndex%3===1?'wave|dance':'dance|jump';}else{root.rotation.y=Math.sin((t-.78)*Math.PI*4)*.18;mode=orderIndex%3===0?'dance|wave':orderIndex%3===1?'wave|idle':'jump|idle';}}else root.visible=false;}if(c&&c.actor===p.id&&c.kind==='move'){
 if(stage==='roll'||stage==='reveal')target=this.restPosition(c.from,i);
 else if(stage==='move'){const elapsed=Math.max(0,now-c.startAt-TIMING.roll-TIMING.reveal),step=Math.min(c.to-c.from-1,Math.floor(elapsed/TIMING.step)),t=elapsed%TIMING.step/TIMING.step;target=this.restPosition(c.from+step,i).lerp(this.restPosition(c.from+step+1,i),ease(t));target.y+=Math.sin(t*Math.PI)*(this.reduced?.15:step===c.to-c.from-1?3:1);mode='walk|run';}
 else target=this.restPosition(c.to,i);
 }if(c&&(v.phase==='rps'||c.kind==='duel')&&(c.actor===p.id||c.rival===p.id)){target=at(c.to).add(new THREE.Vector3(c.actor===p.id?-2:2,0,0));root.rotation.y=c.actor===p.id?Math.PI/2:-Math.PI/2;if(stage==='duel-result'&&c.duelWinner===p.id){mode='jump|dance|wave';target.y+=this.reduced?0:Math.abs(Math.sin((now-c.startAt)*.006))*.65;}}
 else if(c?.actor===p.id&&stage==='move'){const ahead=at(Math.min(c.to,c.from+Math.floor((now-c.startAt-TIMING.roll-TIMING.reveal)/TIMING.step)+1));root.rotation.y=Math.atan2(ahead.x-root.position.x,ahead.z-root.position.z);}
 root.position.copy(target);this.action(root,mode);
 });this.mixers.forEach(m=>m.update(dt));
 if(v.phase==='intro'){this.ring.visible=false;this.aura.visible=false;this.coins.forEach(p=>p.visible=false);this.particles.forEach(p=>p.visible=false);if(this.rewardLabel)this.rewardLabel.visible=false;const introPlayer=introIndex>=0?introOrder[introIndex]:null,introRoot=introPlayer?this.roots.get(introPlayer.id):null;if(introRoot){focus.copy(introRoot.position).add(new THREE.Vector3(0,2.5,0));const zoomPhase=introPlayer.team==='blue'?-1:1;eye.copy(focus).add(new THREE.Vector3(zoomPhase*6.5,4.2,10.5));}else{focus.copy(at(0)).add(new THREE.Vector3(0,2,0));eye.copy(focus).add(new THREE.Vector3(0,16,24));}}
 else if(v.phase==='opening-roll'){this.ring.visible=false;this.aura.visible=false;this.coins.forEach(p=>p.visible=false);this.particles.forEach(p=>p.visible=false);if(this.rewardLabel)this.rewardLabel.visible=false;const start=at(0);if(openingPlayer){const idx=v.players.findIndex(p=>p.id===openingPlayer.id),root=this.roots.get(openingPlayer.id),local=THREE.MathUtils.clamp((openingElapsed-TIMING.openingCountdown-openingRollIndex*TIMING.openingRollPlayer)/TIMING.openingRollPlayer,0,1),value=v.openingRolls[openingPlayer.id]||1;this.die.position.copy(start).add(new THREE.Vector3(idx%2===0?-2.2:2.2,5.3,idx%3-1));const spin=Math.min(1,local/.68);this.die.rotation.set(spin*Math.PI*10,spin*Math.PI*8,spin*Math.PI*6);if(local>.62)this.die.quaternion.slerp(dieOrientation(value),ease((local-.62)/.38));if(root){focus.copy(root.position).add(new THREE.Vector3(0,2,0));eye.copy(focus).add(new THREE.Vector3(idx%2===0?7:-7,5.5,12));}}else{this.die.visible=false;focus.copy(start).add(new THREE.Vector3(0,2.5,0));eye.copy(focus).add(new THREE.Vector3(0,15,24));}}
 else if(c){const tile=at(c.to),actor=this.roots.get(c.actor);focus.copy(tile).add(new THREE.Vector3(0,1,0));eye.copy(focus).add(new THREE.Vector3(8,10,13));const portrait=this.camera.aspect<1;
 if(stage==='roll'||stage==='reveal'){const origin=at(c.from);const t=Math.max(0,now-c.startAt)/TIMING.roll;this.die.position.copy(origin).add(new THREE.Vector3(0,5,1));if(t<1){const bounce=this.reduced?0:Math.abs(Math.sin(t*Math.PI*3))*3*(1-t);this.die.position.y+=bounce;this.die.rotation.set(t*Math.PI*8,t*Math.PI*6,t*Math.PI*4);if(t>.7)this.die.quaternion.slerp(dieOrientation(c.raw),ease((t-.7)/.3));}else this.die.quaternion.copy(dieOrientation(c.raw));focus.copy(origin).add(new THREE.Vector3(0,5,1));eye.copy(focus).add(new THREE.Vector3(0,4,portrait?15:11));}
 else if(stage==='move'&&actor){focus.copy(actor.position).add(new THREE.Vector3(0,1,0));eye.copy(focus).add(new THREE.Vector3(8,10,portrait?17:13));}
 else if(this.hands.visible){focus.copy(tile).add(new THREE.Vector3(0,3,0));eye.copy(focus).add(new THREE.Vector3(0,4,portrait?20:15));this.hands.position.copy(tile).add(new THREE.Vector3(0,4,0));const show=c.kind==='duel'&&stage==='duel-result'&&c.hands;this.setHands(show?c.hands![0]:'rock',show?c.hands![1]:'rock',`${c.id}-${show?'reveal':'ready'}`);this.hands.children.forEach((h,i)=>{h.rotation.z=(i===0?-1:1)*(show?.08:Math.sin(stamp*.009)*.2);h.position.y=show?0:Math.abs(Math.sin(stamp*.009))*.5;});}
 else if(portrait)eye.copy(focus).add(new THREE.Vector3(9,12,19));
 const landing=moveLandingAt(c),impact=c.kind==='move'?(now-landing)/1000:-1;this.ring.visible=false;
 const rewardTime=c.kind==='duel'?c.startAt+TIMING.countdown:c.kind==='strike'?c.startAt:landing+TIMING.landing;const age=(now-rewardTime)/1000;const showReward=age>=0&&age<3&&v.phase!=='rps';const positive=c.deltas&&(c.deltas.blue>0||c.deltas.gold>0);const amount=c.deltas?Math.max(c.deltas.blue,c.deltas.gold):0;const text=positive?`+${amount} ${v.players.find(p=>p.id===c.actor)?.team.toUpperCase()} POINTS`:c.kind==='duel'||c.kind==='strike'?c.title||'RESULT':'';const key=`${c.id}-${text}`;
 if(key!==this.labelKey){this.labelKey=key;if(this.rewardLabel){this.scene.remove(this.rewardLabel);this.disposeObject(this.rewardLabel);}this.rewardLabel=label(text,positive?'#166534':'#6d28d9');this.rewardLabel.scale.set(7,1.75,1);this.scene.add(this.rewardLabel);}if(this.rewardLabel){this.rewardLabel.visible=showReward&&!!text;this.rewardLabel.position.copy(tile).add(new THREE.Vector3(0,5+Math.max(0,age)*.8,0));(this.rewardLabel.material as THREE.SpriteMaterial).opacity=Math.min(1,Math.max(0,3-age));}
 this.aura.visible=showReward&&(c.event==='shield'||c.event==='power'||!!c.blocked);this.aura.position.copy(tile).add(new THREE.Vector3(0,1.5,0));this.aura.rotation.y=stamp*.001;this.aura.scale.setScalar(1+Math.sin(stamp*.007)*.07);(this.aura.material as THREE.MeshBasicMaterial).color.set(c.event==='power'?0xc084fc:0x38bdf8);
 this.coins.forEach((coin,i)=>{const t=Math.max(0,age-i*.04);coin.visible=showReward&&!!positive&&t>0&&!this.reduced;coin.position.copy(tile).add(new THREE.Vector3(Math.cos(i*2.4)*(1+t)*1.4,2+t*5,Math.sin(i*2.4)*(1+t)*1.4));coin.rotation.set(Math.PI/2,t*5+i,t*2);(coin.material as THREE.MeshStandardMaterial).opacity=Math.max(0,1-t/2.7);});
 this.particles.forEach((p,i)=>{p.visible=showReward&&!this.reduced&&c.kind!=='strike';if(!p.visible)return;const a=i*2.39996,speed=2+(i%7)*.6;p.position.copy(tile).add(new THREE.Vector3(Math.cos(a)*age*speed,3+age*(4+i%3)-age*age*2,Math.sin(a)*age*speed));p.rotation.set(age*4,i+age*3,age*5);(p.material as THREE.MeshBasicMaterial).opacity=Math.max(0,1-age/3);});
 }else{this.ring.visible=false;this.aura.visible=false;this.coins.forEach(p=>p.visible=false);this.particles.forEach(p=>p.visible=false);if(this.rewardLabel)this.rewardLabel.visible=false;}
 if(cinematic){const speed=this.reduced?1:1-Math.exp(-dt*4);this.camera.position.lerp(eye,speed);this.controls.target.lerp(focus,speed);this.lastCue=c?.id??-2;}
 else if(this.lastCue!==-1){this.camera.position.lerp(this.home,1-Math.exp(-dt*3));this.controls.target.lerp(this.homeTarget,1-Math.exp(-dt*3));if(this.camera.position.distanceTo(this.home)<.2)this.lastCue=-1;}
 if(!this.reduced){this.ledRings.forEach((ring,i)=>{const m=ring.material as THREE.MeshBasicMaterial,activeSpace=c?.to??-1,isActive=ring.userData.space===activeSpace;m.opacity=ring.userData.kind==='core'?(isActive ? .98 : .78):(isActive ? .12 : .045);});this.birds.forEach((bird,i)=>{const d=bird.userData,ang=d.angle+stamp*d.speed;bird.position.set(Math.cos(ang)*d.radius,d.height+Math.sin(stamp*.0008+d.phase)*1.4,Math.sin(ang)*d.radius+2);bird.rotation.y=-ang+Math.PI/2;const flap=Math.sin(stamp*.012+d.phase)*.42;(bird.children[1] as THREE.Mesh).rotation.z=flap;(bird.children[2] as THREE.Mesh).rotation.z=-flap;});this.lightningBolts.forEach((bolt,i)=>{const cycle=(now+i*1350)%(5200+i*390),flash=cycle<125||(cycle>210&&cycle<300);(bolt.material as THREE.LineBasicMaterial).opacity=flash ? (cycle<95 ? .9 : .5) : 0;this.lightningLights[i].intensity=flash ? (cycle<95 ? 2.3 : 1.1) : 0;});}else{this.lightningBolts.forEach(b=>((b.material as THREE.LineBasicMaterial).opacity=0));this.lightningLights.forEach(l=>l.intensity=0);}
 this.controls.update();this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(this.animate);
 }
 private disposeObject(obj:THREE.Object3D){obj.traverse(o=>{const mesh=o as THREE.Mesh;mesh.geometry?.dispose();const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const m of materials){if(!m)continue;Object.values(m).forEach(v=>{if(v instanceof THREE.Texture)v.dispose()});m.dispose();}});}
 dispose(){this.disposed=true;cancelAnimationFrame(this.raf);this.resizeObserver.disconnect();this.controls.dispose();this.mixers.forEach(m=>m.stopAllAction());this.disposeObject(this.scene);this.renderer.dispose();this.host.replaceChildren();}
}
