import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {getAvatarCharacter} from '@/lib/avatarCharacters';
import {boardPosition,cueStage,moveLandingAt,SPACE_LABELS,EVENTS,TIMING,type View,type Hand} from '@shared/boardQuest';
const COLORS=[0x22c55e,0x64748b,0xef4444,0x3b82f6,0xa855f7,0xf97316,0xfacc15];
const ease=(t:number)=>{t=THREE.MathUtils.clamp(t,0,1);return t*t*(3-2*t)};
const at=(space:number)=>{const p=boardPosition(space);return new THREE.Vector3(p.x,1.38,p.z)};
export const DIE_VALUES=[1,6,2,5,3,4];
export const DIE_NORMALS=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
export function dieOrientation(value:number){return new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(...DIE_NORMALS[DIE_VALUES.indexOf(value)]),new THREE.Vector3(0,.4,1).normalize());}
function label(text:string,color='#12213d',width=512,height=128){const c=document.createElement('canvas');c.width=width;c.height=height;const x=c.getContext('2d')!;x.fillStyle=color;x.beginPath();x.roundRect(8,8,width-16,height-16,24);x.fill();x.fillStyle='white';x.font='900 38px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(text,width/2,height/2,width-24);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map,transparent:true,depthTest:false}));sprite.scale.set(4,1,1);return sprite;}
function diceMaterial(value:number){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d')!;x.fillStyle='#f8fafc';x.fillRect(0,0,256,256);x.strokeStyle='#bfdbfe';x.lineWidth=12;x.strokeRect(6,6,244,244);x.fillStyle='#10203d';const sets:Record<number,number[][]>={1:[[0,0]],2:[[-1,-1],[1,1]],3:[[-1,-1],[0,0],[1,1]],4:[[-1,-1],[-1,1],[1,-1],[1,1]],5:[[-1,-1],[-1,1],[1,-1],[1,1],[0,0]],6:[[-1,-1],[-1,0],[-1,1],[1,-1],[1,0],[1,1]]};for(const [a,b]of sets[value]){x.beginPath();x.arc(128+a*66,128+b*66,20,0,Math.PI*2);x.fill();}const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshStandardMaterial({map,roughness:.27,metalness:.15});}
function handMesh(hand:Hand,color:number){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,roughness:.4,metalness:.12});const palm=new THREE.Mesh(new THREE.BoxGeometry(1.45,1.5,.7),mat);palm.position.y=.15;g.add(palm);const sphere=new THREE.SphereGeometry(.25,12,10);const finger=(x:number,length:number,angle=0)=>{const f=new THREE.Mesh(new THREE.CapsuleGeometry(.23,length,4,10),mat);f.position.set(x,1+length/2,0);f.rotation.z=angle;g.add(f);};if(hand==='rock'){for(let i=0;i<4;i++){const m=new THREE.Mesh(sphere,mat);m.position.set((i-1.5)*.37,.98,.1);g.add(m);}}else{for(let i=0;i<4;i++)finger((i-1.5)*.36,hand==='paper'?1.1+(i===1||i===2?.15:0):i<2?1.65:.05,hand==='scissors'&&i<2?(i===0?.17:-.17):0);}const thumb=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.6,4,10),mat);thumb.rotation.z=-.7;thumb.position.set(.85,.05,.2);g.add(thumb);g.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});return g;}
export class BoardScene{
 private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(50,1,.1,180);private renderer:THREE.WebGLRenderer;private controls:OrbitControls;private roots=new Map<number,THREE.Group>();private tiles:THREE.Mesh<THREE.BoxGeometry,THREE.MeshStandardMaterial>[]=[];private mixers:THREE.AnimationMixer[]=[];private die:THREE.Mesh;private ring:THREE.Mesh;private particles:THREE.Mesh[]=[];private coins:THREE.Mesh[]=[];private aura:THREE.Mesh;private hands=new THREE.Group();private rewardLabel:THREE.Sprite|null=null;private labelKey='';private handKey='';private raf=0;private disposed=false;private lastTime=0;private lastCue=-1;private view:View;private offset=0;private reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;private resizeObserver:ResizeObserver;private home=new THREE.Vector3();
 constructor(private host:HTMLDivElement,view:View,offset:number){this.view=view;this.offset=offset;this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.domElement.setAttribute('aria-label','3D Board Quest world — shared cinematic dice and landings');host.appendChild(this.renderer.domElement);this.scene.background=new THREE.Color(0x07172c);this.scene.fog=new THREE.Fog(0x07172c,65,130);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.minDistance=9;this.controls.maxDistance=65;this.controls.maxPolarAngle=Math.PI*.47;
 this.scene.add(new THREE.HemisphereLight(0xd7f4ff,0x244b2c,2.7));const sun=new THREE.DirectionalLight(0xffedc8,3.5);sun.position.set(-15,35,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35});this.scene.add(sun);
 const island=new THREE.Mesh(new THREE.CylinderGeometry(28,30,3,64),new THREE.MeshStandardMaterial({color:0x196546,roughness:.9}));island.position.y=-1.7;island.receiveShadow=true;this.scene.add(island);const water=new THREE.Mesh(new THREE.CircleGeometry(85,64),new THREE.MeshStandardMaterial({color:0x08759b,metalness:.35,roughness:.28}));water.rotation.x=-Math.PI/2;water.position.y=-3.4;this.scene.add(water);
 for(let i=0;i<28;i++){const p=at(i),color=COLORS[i%7],tile=new THREE.Mesh(new THREE.BoxGeometry(4.35,.7,5.1),new THREE.MeshStandardMaterial({color,roughness:.45,metalness:.12,emissive:color,emissiveIntensity:.13}));tile.position.set(p.x,1,p.z);tile.receiveShadow=true;tile.castShadow=true;this.tiles.push(tile);this.scene.add(tile);const text=label(`${i+1} · ${SPACE_LABELS[EVENTS[i%7]]}`);text.scale.set(4,.65,1);text.position.set(p.x,1.65,p.z-1.7);this.scene.add(text);}
 for(let i=0;i<18;i++){const angle=i/18*Math.PI*2,g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.25,.4,2.5,8),new THREE.MeshStandardMaterial({color:0x825333}));const crown=new THREE.Mesh(new THREE.ConeGeometry(1.6,3.8,8),new THREE.MeshStandardMaterial({color:0x268a52}));crown.position.y=2.3;g.add(trunk,crown);g.position.set(Math.cos(angle)*26,.2,Math.sin(angle)*26);this.scene.add(g);}
 const finish=label('FINISH','#7c3aed');finish.position.copy(at(27)).add(new THREE.Vector3(0,4,0));this.scene.add(finish);
 this.die=new THREE.Mesh(new THREE.BoxGeometry(2.6,2.6,2.6),DIE_VALUES.map(diceMaterial));this.die.castShadow=true;this.die.visible=false;this.scene.add(this.die);
 this.ring=new THREE.Mesh(new THREE.RingGeometry(1.5,1.7,64),new THREE.MeshBasicMaterial({color:0xffdf6b,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));this.ring.rotation.x=-Math.PI/2;this.scene.add(this.ring,this.hands);
 this.aura=new THREE.Mesh(new THREE.SphereGeometry(2.4,24,16),new THREE.MeshBasicMaterial({color:0x38bdf8,transparent:true,opacity:.2,wireframe:true,depthWrite:false}));this.aura.visible=false;this.scene.add(this.aura);
 const coinGeo=new THREE.CylinderGeometry(.3,.3,.09,16);for(let i=0;i<20;i++){const coin=new THREE.Mesh(coinGeo,new THREE.MeshStandardMaterial({color:0xffd348,emissive:0xf59e0b,emissiveIntensity:.5,metalness:.8,roughness:.2,transparent:true}));coin.visible=false;this.coins.push(coin);this.scene.add(coin);}

 const geo=new THREE.OctahedronGeometry(.16);for(let i=0;i<64;i++){const particle=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:[0xffdc53,0x34d399,0x67e8f9,0xf472b6][i%4],transparent:true}));particle.visible=false;this.particles.push(particle);this.scene.add(particle);}
 const loader=new GLTFLoader();view.players.forEach((p,i)=>{const root=new THREE.Group();root.position.copy(this.restPosition(p.space,i));const badge=label(p.name,p.team==='blue'?'#0369a1':'#a16207');badge.position.y=3.5;badge.scale.set(2.8,.7,1);root.add(badge);const fallback=new THREE.Mesh(new THREE.CapsuleGeometry(.4,1.4,4,12),new THREE.MeshStandardMaterial({color:p.team==='blue'?0x38bdf8:0xfbbf24}));fallback.position.y=1.2;root.add(fallback);this.roots.set(p.id,root);this.scene.add(root);loader.load(getAvatarCharacter(p.characterId).modelPath,g=>{if(this.disposed){this.disposeObject(g.scene);return;}root.remove(fallback);this.disposeObject(fallback);const model=g.scene,b=new THREE.Box3().setFromObject(model),size=b.getSize(new THREE.Vector3());model.scale.setScalar(2.7/Math.max(.01,size.y));model.updateMatrixWorld();model.position.y=-new THREE.Box3().setFromObject(model).min.y;model.traverse(o=>{if(o instanceof THREE.Mesh)o.castShadow=true});root.add(model);if(g.animations.length){const m=new THREE.AnimationMixer(model);this.mixers.push(m);root.userData.mixer=m;root.userData.clips=g.animations;this.action(root,'idle');}},undefined,()=>{/* The colored 3D piece remains playable if a model is unavailable. */});});
 this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.camera.position.copy(this.home);this.animate(performance.now());
 }
 update(view:View,offset:number){this.view=view;this.offset=offset;}
 private restPosition(space:number,index:number){return at(space).add(new THREE.Vector3((index%3-1)*.8,0,(Math.floor(index/3)-.5)*1));}
 private action(root:THREE.Group,name:string){if(root.userData.mode===name||!root.userData.mixer)return;const clips=root.userData.clips as THREE.AnimationClip[];const clip=clips.find(c=>new RegExp(name,'i').test(c.name))||clips.find(c=>/idle/i.test(c.name))||clips[0];root.userData.action?.fadeOut(.15);root.userData.action=root.userData.mixer.clipAction(clip).reset().fadeIn(.15).play();root.userData.mode=name;}
 private resize(){const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.camera.aspect=w/h;this.camera.fov=w<h?65:50;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);this.home.set(0,w<h?44:32,w<h?48:38);}
 private setHands(a:Hand,b:Hand,key:string){if(this.handKey===key)return;this.handKey=key;for(const c of [...this.hands.children]){this.hands.remove(c);this.disposeObject(c);}const actor=this.view.players.find(p=>p.id===this.view.cue?.actor),left=handMesh(a,actor?.team==='blue'?0x38bdf8:0xfbbf24),right=handMesh(b,actor?.team==='blue'?0xfbbf24:0x38bdf8);left.position.x=-2;right.position.x=2;this.hands.add(left,right);}
 private animate=(stamp:number)=>{if(this.disposed)return;const dt=Math.min(.05,(stamp-this.lastTime)/1000||.016);this.lastTime=stamp;const now=Date.now()+this.offset,v=this.view,c=v.cue,stage=cueStage(c,now);const cinematic=!!c;const focus=new THREE.Vector3(0,0,0),eye=this.home.clone();this.controls.enabled=!cinematic;this.die.visible=!!c&&c.kind==='move'&&(stage==='roll'||stage==='reveal');this.hands.visible=!!c&&(v.phase==='rps'||c.kind==='duel');
 this.tiles.forEach((tile,i)=>{tile.material.emissiveIntensity=c&&i===c.to&&['landing','reward','countdown','duel-result'].includes(stage)?.6+Math.sin(stamp*.008)*.15:.13;});
 v.players.forEach((p,i)=>{const root=this.roots.get(p.id);if(!root)return;root.visible=!p.out||(c?.actor===p.id||c?.rival===p.id);let target=this.restPosition(p.space,i),mode='idle';if(c&&c.actor===p.id&&c.kind==='move'){
 if(stage==='roll'||stage==='reveal')target=this.restPosition(c.from,i);
 else if(stage==='move'){const elapsed=Math.max(0,now-c.startAt-TIMING.roll-TIMING.reveal),step=Math.min(c.to-c.from-1,Math.floor(elapsed/TIMING.step)),t=elapsed%TIMING.step/TIMING.step;target=this.restPosition(c.from+step,i).lerp(this.restPosition(c.from+step+1,i),ease(t));target.y+=Math.sin(t*Math.PI)*(this.reduced?.15:step===c.to-c.from-1?3:1);mode='walk|run';}
 else target=this.restPosition(c.to,i);
 }if(c&&(v.phase==='rps'||c.kind==='duel')&&(c.actor===p.id||c.rival===p.id)){target=at(c.to).add(new THREE.Vector3(c.actor===p.id?-2:2,0,0));root.rotation.y=c.actor===p.id?Math.PI/2:-Math.PI/2;if(stage==='duel-result'&&c.duelWinner===p.id){mode='jump|dance|wave';target.y+=this.reduced?0:Math.abs(Math.sin((now-c.startAt)*.006))*.65;}}
 else if(c?.actor===p.id&&stage==='move'){const ahead=at(Math.min(c.to,c.from+Math.floor((now-c.startAt-TIMING.roll-TIMING.reveal)/TIMING.step)+1));root.rotation.y=Math.atan2(ahead.x-root.position.x,ahead.z-root.position.z);}
 root.position.copy(target);this.action(root,mode);
 });this.mixers.forEach(m=>m.update(dt));
 if(c){const tile=at(c.to),actor=this.roots.get(c.actor);focus.copy(tile).add(new THREE.Vector3(0,1,0));eye.copy(focus).add(new THREE.Vector3(8,10,13));const portrait=this.camera.aspect<1;
 if(stage==='roll'||stage==='reveal'){const origin=at(c.from);const t=Math.max(0,now-c.startAt)/TIMING.roll;this.die.position.copy(origin).add(new THREE.Vector3(0,5,1));if(t<1){const bounce=this.reduced?0:Math.abs(Math.sin(t*Math.PI*3))*3*(1-t);this.die.position.y+=bounce;this.die.rotation.set(t*Math.PI*8,t*Math.PI*6,t*Math.PI*4);if(t>.7)this.die.quaternion.slerp(dieOrientation(c.raw),ease((t-.7)/.3));}else this.die.quaternion.copy(dieOrientation(c.raw));focus.copy(origin).add(new THREE.Vector3(0,5,1));eye.copy(focus).add(new THREE.Vector3(0,4,portrait?15:11));}
 else if(stage==='move'&&actor){focus.copy(actor.position).add(new THREE.Vector3(0,1,0));eye.copy(focus).add(new THREE.Vector3(8,10,portrait?17:13));}
 else if(this.hands.visible){focus.copy(tile).add(new THREE.Vector3(0,3,0));eye.copy(focus).add(new THREE.Vector3(0,4,portrait?20:15));this.hands.position.copy(tile).add(new THREE.Vector3(0,4,0));const show=c.kind==='duel'&&stage==='duel-result'&&c.hands;this.setHands(show?c.hands![0]:'rock',show?c.hands![1]:'rock',`${c.id}-${show?'reveal':'ready'}`);this.hands.children.forEach((h,i)=>{h.rotation.z=(i===0?-1:1)*(show?.08:Math.sin(stamp*.009)*.2);h.position.y=show?0:Math.abs(Math.sin(stamp*.009))*.5;});}
 else if(portrait)eye.copy(focus).add(new THREE.Vector3(9,12,19));
 const landing=moveLandingAt(c),impact=c.kind==='move'?(now-landing)/1000:-1;const ringMat=this.ring.material as THREE.MeshBasicMaterial;this.ring.position.copy(tile).setY(1.44);this.ring.visible=impact>=0&&impact<2;this.ring.scale.setScalar(1+Math.max(0,impact)*3);ringMat.opacity=Math.max(0,1-impact/2);
 const rewardTime=c.kind==='duel'?c.startAt+TIMING.countdown:c.kind==='strike'?c.startAt:landing+TIMING.landing;const age=(now-rewardTime)/1000;const showReward=age>=0&&age<3&&v.phase!=='rps';const positive=c.deltas&&(c.deltas.blue>0||c.deltas.gold>0);const amount=c.deltas?Math.max(c.deltas.blue,c.deltas.gold):0;const text=positive?`+${amount} ${v.players.find(p=>p.id===c.actor)?.team.toUpperCase()} POINTS`:c.title||SPACE_LABELS[c.event];const key=`${c.id}-${text}`;
 if(key!==this.labelKey){this.labelKey=key;if(this.rewardLabel){this.scene.remove(this.rewardLabel);this.disposeObject(this.rewardLabel);}this.rewardLabel=label(text,positive?'#166534':'#6d28d9');this.rewardLabel.scale.set(7,1.75,1);this.scene.add(this.rewardLabel);}if(this.rewardLabel){this.rewardLabel.visible=showReward;this.rewardLabel.position.copy(tile).add(new THREE.Vector3(0,5+Math.max(0,age)*.8,0));(this.rewardLabel.material as THREE.SpriteMaterial).opacity=Math.min(1,Math.max(0,3-age));}
 this.aura.visible=showReward&&(c.event==='shield'||c.event==='power'||!!c.blocked);this.aura.position.copy(tile).add(new THREE.Vector3(0,1.5,0));this.aura.rotation.y=stamp*.001;this.aura.scale.setScalar(1+Math.sin(stamp*.007)*.07);(this.aura.material as THREE.MeshBasicMaterial).color.set(c.event==='power'?0xc084fc:0x38bdf8);
 this.coins.forEach((coin,i)=>{const t=Math.max(0,age-i*.04);coin.visible=showReward&&!!positive&&t>0&&!this.reduced;coin.position.copy(tile).add(new THREE.Vector3(Math.cos(i*2.4)*(1+t)*1.4,2+t*5,Math.sin(i*2.4)*(1+t)*1.4));coin.rotation.set(Math.PI/2,t*5+i,t*2);(coin.material as THREE.MeshStandardMaterial).opacity=Math.max(0,1-t/2.7);});
 this.particles.forEach((p,i)=>{p.visible=showReward&&!this.reduced&&c.kind!=='strike';if(!p.visible)return;const a=i*2.39996,speed=2+(i%7)*.6;p.position.copy(tile).add(new THREE.Vector3(Math.cos(a)*age*speed,3+age*(4+i%3)-age*age*2,Math.sin(a)*age*speed));p.rotation.set(age*4,i+age*3,age*5);(p.material as THREE.MeshBasicMaterial).opacity=Math.max(0,1-age/3);});
 }else{this.ring.visible=false;this.aura.visible=false;this.coins.forEach(p=>p.visible=false);this.particles.forEach(p=>p.visible=false);if(this.rewardLabel)this.rewardLabel.visible=false;}
 if(cinematic){const speed=this.reduced?1:1-Math.exp(-dt*4);this.camera.position.lerp(eye,speed);this.controls.target.lerp(focus,speed);this.lastCue=c!.id;}
 else if(this.lastCue!==-1){this.camera.position.lerp(this.home,1-Math.exp(-dt*3));this.controls.target.lerp(new THREE.Vector3(),1-Math.exp(-dt*3));if(this.camera.position.distanceTo(this.home)<.2)this.lastCue=-1;}
 this.controls.update();this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(this.animate);
 }
 private disposeObject(obj:THREE.Object3D){obj.traverse(o=>{const mesh=o as THREE.Mesh;mesh.geometry?.dispose();const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const m of materials){if(!m)continue;Object.values(m).forEach(v=>{if(v instanceof THREE.Texture)v.dispose()});m.dispose();}});}
 dispose(){this.disposed=true;cancelAnimationFrame(this.raf);this.resizeObserver.disconnect();this.controls.dispose();this.mixers.forEach(m=>m.stopAllAction());this.disposeObject(this.scene);this.renderer.dispose();this.host.replaceChildren();}
}
